Class Global.Models.RETRO Extends %RegisteredObject
{

Property NUMCPT As %Integer;

Property QTETOT As %Decimal;

Property VALOTOT As %Decimal;

Property MAGSRC As %String;

Property MAGDEST As %String;

Property NUMRETRO As %String;

Property USERRETRO As %String;

Property DATESYSRAW As %String;

Property HEURESYS As %String;

Property REMARQUE As %String;

Property NUMCMD As %String;

Property LIBRE As %String;

}
