ROUTINE GetTKAVOIRS
GetTKAVOIRS
 s FIC="c:\pos\transfert\G224TKAVOIRS.txt" s CPT=0 s filedest=##class(%File).%New(FIC) d filedest.Open("WSN") s NODE1=$O(^TKAVOIRS("")) WHILE NODE1'="" {  if $L(NODE1)=12 { s CPT=CPT+1 s NODE2=$O(^TKAVOIRS(NODE1,"")) if NODE2="" { s COMP=$G(^tmpFBLTK(NODE1)) if $L(COMP)=12 {d filedest.WriteLine(NODE1_"$1$"_COMP)}} WHILE NODE2'="" { s STRINFO=^TKAVOIRS(NODE1,NODE2) if +NODE2=1 { s COMP=$G(^tmpFBLTK(NODE1)) if $L(COMP)=12 {s STRINFO=COMP}  else {s ^tmpErrAv(NODE1)=STRINFO} d filedest.WriteLine(NODE1_"$"_NODE2_"$"_STRINFO)} s NODE2=$O(^TKAVOIRS(NODE1,NODE2)) } } s NODE1=$O(^TKAVOIRS(NODE1)) } d filedest.%Close() s filefin=##class(%File).%New("C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\Fini.txt") d filefin.Open("WSN") d filefin.WriteLine("OK") d filefin.%Close() K ^tmpFBLTK Q
 
 
 