ROUTINE KILLMENUINV
KILLMENUINV 
 //^MENU(2,6)="1\nevgetdirect\SF6:neerl\SF6: Réception des livraisons\SF6:ALL\SF6:ANG"
 K ^MENU(2,6)
 //^MENU(2,7)="1\fenRECMercerie\SF7:neerl\SF7: Validation livraisons mercerie\SF7:ALL\SF7:ANG"
 K ^MENU(2,7)
 // ^GUMENU(1,1)= "Création Transfert\fenCMDRetro\img11"
 K ^GUMENU(1,1)
 //^GUMENU(1,2)="Réception Transfert\fenCMDRetroRec\img13"
 K ^GUMENU(1,2)
 q
 
 
 
 
 
 
 
 
 