ROUTINE OPEBLANC201412
OPEBLANC201412 
 s ^TKFINSERIE(7230)="Opé blanc 20%"
 s ^TKFINSERIE(3767)="Opé blanc 20%"
 s ^TKFINSERIE(1500)="Opé blanc 20%"
 s ^TKFINSERIE(3142)="Opé blanc 20%"
 s ^TKFINSERIE(3144)="Opé blanc 20%"
 s ^TKFINSERIE(3152)="Opé blanc 20%"
 s ^TKFINSERIE(3155)="Opé blanc 20%"
 s ^TKFINSERIE(3158)="Opé blanc 20%"
 s ^TKFINSERIE(3159)="Opé blanc 20%"
 s ^TKFINSERIE(3160)="Opé blanc 20%"
 s ^TKFINSERIE(8680)="Opé blanc 20%"
 s ^TKFINSERIE(40926)="Opé blanc 20%"
 s ^TKFINSERIE(54265)="Opé blanc 20%"
 s ^TKFINSERIE(54266)="Opé blanc 20%"
 s ^TKFINSERIE(74796)="Opé blanc 20%"
 s ^TKFINSERIE(74797)="Opé blanc 20%"
 s ^TKFINSERIE(110496)="Opé blanc 20%"
 s ^TKFINSERIE(110497)="Opé blanc 20%"
 s ^TKFINSERIE(110498)="Opé blanc 20%"
 s ^TKFINSERIE(110499)="Opé blanc 20%"
 s ^TKFINSERIE(110500)="Opé blanc 20%"
 s ^TKFINSERIE(111449)="Opé blanc 20%"
 s ^TKFINSERIE(111450)="Opé blanc 20%"
 s ^TKFINSERIE(111451)="Opé blanc 20%"
 s ^TKFINSERIE(111452)="Opé blanc 20%"
 s ^TKFINSERIE(111662)="Opé blanc 20%"
 s ^TKFINSERIE(111663)="Opé blanc 20%"
 s ^TKFINSERIE(111664)="Opé blanc 20%"
 s ^TKFINSERIE(111665)="Opé blanc 20%"
 s ^TKFINSERIE(111666)="Opé blanc 20%"
 s ^TKFINSERIE(111667)="Opé blanc 20%"
 s ^TKFINSERIE(111691)="Opé blanc 20%"
 s ^TKFINSERIE(111692)="Opé blanc 20%"
 s ^TKFINSERIE(111693)="Opé blanc 20%"
 s ^TKFINSERIE(111694)="Opé blanc 20%"
 s ^TKFINSERIE(111792)="Opé blanc 20%"
 s ^TKFINSERIE(1412)="Opé blanc 20%"
 s ^TKFINSERIE(1413)="Opé blanc 20%"
 s ^TKFINSERIE(1497)="Opé blanc 20%"
 s ^TKFINSERIE(7210)="Opé blanc 20%"
 s ^TKFINSERIE(35489)="Opé blanc 20%"
 s ^TKFINSERIE(50614)="Opé blanc 20%"
 s ^TKFINSERIE(54394)="Opé blanc 20%"
 s ^TKFINSERIE(54395)="Opé blanc 20%"
 s ^TKFINSERIE(59319)="Opé blanc 20%"
 s ^TKFINSERIE(63636)="Opé blanc 20%"
 s ^TKFINSERIE(63637)="Opé blanc 20%"
 s ^TKFINSERIE(80296)="Opé blanc 20%"
 s ^TKFINSERIE(113957)="Opé blanc 20%"
 s ^TKFINSERIE(113958)="Opé blanc 20%"
 s ^TKFINSERIE(113959)="Opé blanc 20%"
 s ^TKFINSERIE(113960)="Opé blanc 20%"
 s ^TKFINSERIE(113961)="Opé blanc 20%"
 s ^TKFINSERIE(113962)="Opé blanc 20%"
 s ^TKFINSERIE(113963)="Opé blanc 20%"
 s ^TKFINSERIE(113964)="Opé blanc 20%"
 s ^TKFINSERIE(113965)="Opé blanc 20%"
 s ^TKFINSERIE(114016)="Opé blanc 20%"
 s ^TKFINSERIE(1493)="Opé blanc 20%"
 s ^TKFINSERIE(1504)="Opé blanc 20%"
 s ^TKFINSERIE(80000)="Opé blanc 20%"
 s ^TKFINSERIE(110506)="Opé blanc 20%"
 s ^TKFINSERIE(110507)="Opé blanc 20%"
 s ^TKFINSERIE(111334)="Opé blanc 20%"
 s ^TKFINSERIE(111333)="Opé blanc 20%"
 s ^TKFINSERIE(111332)="Opé blanc 20%"
 s ^TKFINSERIE(79901)="Opé blanc 20%"
 s ^TKFINSERIE(79905)="Opé blanc 20%"
 s ^TKFINSERIE(6127)="Opé blanc 20%"
 s ^TKFINSERIE(6128)="Opé blanc 20%"
 s ^TKFINSERIE(110504)="Opé blanc 20%"
 s ^TKFINSERIE(110505)="Opé blanc 20%"
 s ^TKFINSERIE(110508)="Opé blanc 20%"
 s ^TKFINSERIE(111215)="Opé blanc 20%"
 s ^TKFINSERIE(111214)="Opé blanc 20%"
 s ^TKFINSERIE(103645)="Opé blanc 20%"
 s ^TKFINSERIE(79899)="Opé blanc 20%"
 s ^TKFINSERIE(63527)="Opé blanc 20%"
 s ^TKFINSERIE(63528)="Opé blanc 20%"
 s ^TKFINSERIE(69740)="Opé blanc 20%"
 s ^TKFINSERIE(81047)="Opé blanc 20%"
 s ^TKFINSERIE(81092)="Opé blanc 20%"
 s ^TKFINSERIE(82201)="Opé blanc 20%"
 s ^TKFINSERIE(82269)="Opé blanc 20%"
 s ^TKFINSERIE(82270)="Opé blanc 20%"
 s ^TKFINSERIE(82271)="Opé blanc 20%"
 s ^TKFINSERIE(83070)="Opé blanc 20%"
 s ^TKFINSERIE(83071)="Opé blanc 20%"
 s ^TKFINSERIE(83073)="Opé blanc 20%"
 s ^TKFINSERIE(83094)="Opé blanc 20%"
 s ^TKFINSERIE(83814)="Opé blanc 20%"
 s ^TKFINSERIE(83816)="Opé blanc 20%"
 s ^TKFINSERIE(83819)="Opé blanc 20%"
 s ^TKFINSERIE(104163)="Opé blanc 20%"
 s ^TKFINSERIE(104165)="Opé blanc 20%"
 s ^TKFINSERIE(104169)="Opé blanc 20%"
 s ^TKFINSERIE(104170)="Opé blanc 20%"
 s ^TKFINSERIE(104171)="Opé blanc 20%"
 s ^TKFINSERIE(104172)="Opé blanc 20%"
 s ^TKFINSERIE(104173)="Opé blanc 20%"
 s ^TKFINSERIE(104174)="Opé blanc 20%"
 s ^TKFINSERIE(104175)="Opé blanc 20%"
 s ^TKFINSERIE(104176)="Opé blanc 20%"
 s ^TKFINSERIE(104177)="Opé blanc 20%"
 s ^TKFINSERIE(104178)="Opé blanc 20%"
 s ^TKFINSERIE(105468)="Opé blanc 20%"
 s ^TKFINSERIE(105469)="Opé blanc 20%"
 s ^TKFINSERIE(105493)="Opé blanc 20%"
 s ^TKFINSERIE(105499)="Opé blanc 20%"
 s ^TKFINSERIE(114015)="Opé blanc 20%"
 s ^TKFINSERIE(114014)="Opé blanc 20%"
 s ^TKFINSERIE(114011)="Opé blanc 20%"
 s ^TKFINSERIE(114012)="Opé blanc 20%"
 s ^TKFINSERIE(114009)="Opé blanc 20%"
 s ^TKFINSERIE(114010)="Opé blanc 20%"
 s ^TKFINSERIE(114006)="Opé blanc 20%"
 s ^TKFINSERIE(114013)="Opé blanc 20%"
 s ^TKFINSERIE(114008)="Opé blanc 20%"
 s ^TKFINSERIE(114007)="Opé blanc 20%"
 s ^TKFINSERIE(112154)="Opé blanc 20%"
 s ^TKFINSERIE(112155)="Opé blanc 20%"
 s ^TKFINSERIE(81932)="Opé blanc 20%"
 s ^TKFINSERIE(81295)="Opé blanc 20%"
 s ^TKFINSERIE(75313)="Opé blanc 20%"
 s ^TKFINSERIE(81296)="Opé blanc 20%"
 s ^TKFINSERIE(78311)="Opé blanc 20%"
 s ^TKFINSERIE(81298)="Opé blanc 20%"
 s ^TKFINSERIE(75316)="Opé blanc 20%"
 s ^TKFINSERIE(81299)="Opé blanc 20%"
 s ^TKFINSERIE(75317)="Opé blanc 20%"
 s ^TKFINSERIE(75318)="Opé blanc 20%"
 s ^TKFINSERIE(81302)="Opé blanc 20%"
 s ^TKFINSERIE(75321)="Opé blanc 20%"
 s ^TKFINSERIE(81304)="Opé blanc 20%"
 s ^TKFINSERIE(84419)="Opé blanc 20%"
 s ^TKFINSERIE(84407)="Opé blanc 20%"
 s ^TKFINSERIE(84415)="Opé blanc 20%"
 s ^TKFINSERIE(84412)="Opé blanc 20%"
 s ^TKFINSERIE(84413)="Opé blanc 20%"
 s ^TKFINSERIE(84408)="Opé blanc 20%"
 s ^TKFINSERIE(84417)="Opé blanc 20%"
 s ^TKFINSERIE(84416)="Opé blanc 20%"
 s ^TKFINSERIE(84423)="Opé blanc 20%"
 s ^TKFINSERIE(84411)="Opé blanc 20%"
 s ^TKFINSERIE(84410)="Opé blanc 20%"
 s ^TKFINSERIE(84420)="Opé blanc 20%"
 s ^TKFINSERIE(84409)="Opé blanc 20%"
 s ^TKFINSERIE(84414)="Opé blanc 20%"
 s ^TKFINSERIE(5383)="Opé blanc 20%"
 s ^TKFINSERIE(5394)="Opé blanc 20%"
 s ^TKFINSERIE(104473)="Opé blanc 20%"
 s ^TKFINSERIE(104475)="Opé blanc 20%"
 s ^TKFINSERIE(104474)="Opé blanc 20%"
 s ^TKFINSERIE(114005)="Opé blanc 20%"
 s ^TKFINSERIE(114004)="Opé blanc 20%"
 s ^TKFINSERIE(114001)="Opé blanc 20%"
 s ^TKFINSERIE(114002)="Opé blanc 20%"
 s ^TKFINSERIE(113999)="Opé blanc 20%"
 s ^TKFINSERIE(114000)="Opé blanc 20%"
 s ^TKFINSERIE(113996)="Opé blanc 20%"
 s ^TKFINSERIE(114003)="Opé blanc 20%"
 s ^TKFINSERIE(113998)="Opé blanc 20%"
 s ^TKFINSERIE(113997)="Opé blanc 20%"
 s ^TKFINSERIE(111784)="Opé blanc 20%"
 s ^TKFINSERIE(111785)="Opé blanc 20%"
 s ^TKFINSERIE(81936)="Opé blanc 20%"
 s ^TKFINSERIE(75300)="Opé blanc 20%"
 s ^TKFINSERIE(81307)="Opé blanc 20%"
 s ^TKFINSERIE(75301)="Opé blanc 20%"
 s ^TKFINSERIE(78307)="Opé blanc 20%"
 s ^TKFINSERIE(81310)="Opé blanc 20%"
 s ^TKFINSERIE(75305)="Opé blanc 20%"
 s ^TKFINSERIE(81312)="Opé blanc 20%"
 s ^TKFINSERIE(75309)="Opé blanc 20%"
 s ^TKFINSERIE(81317)="Opé blanc 20%"
 s ^TKFINSERIE(84403)="Opé blanc 20%"
 s ^TKFINSERIE(84390)="Opé blanc 20%"
 s ^TKFINSERIE(84398)="Opé blanc 20%"
 s ^TKFINSERIE(84395)="Opé blanc 20%"
 s ^TKFINSERIE(84396)="Opé blanc 20%"
 s ^TKFINSERIE(84391)="Opé blanc 20%"
 s ^TKFINSERIE(84399)="Opé blanc 20%"
 s ^TKFINSERIE(84404)="Opé blanc 20%"
 s ^TKFINSERIE(84405)="Opé blanc 20%"
 s ^TKFINSERIE(84394)="Opé blanc 20%"
 s ^TKFINSERIE(84393)="Opé blanc 20%"
 s ^TKFINSERIE(84392)="Opé blanc 20%"
 s ^TKFINSERIE(84397)="Opé blanc 20%"
 s ^TKFINSERIE(5399)="Opé blanc 20%"
 s ^TKFINSERIE(47822)="Opé blanc 20%"
 s ^TKFINSERIE(104470)="Opé blanc 20%"
 s ^TKFINSERIE(104472)="Opé blanc 20%"
 s ^TKFINSERIE(104471)="Opé blanc 20%"
 s ^TKFINSERIE(111713)="Opé blanc 20%"
 s ^TKFINSERIE(111719)="Opé blanc 20%"
 s ^TKFINSERIE(111716)="Opé blanc 20%"
 s ^TKFINSERIE(104486)="Opé blanc 20%"
 s ^TKFINSERIE(104487)="Opé blanc 20%"
 s ^TKFINSERIE(104488)="Opé blanc 20%"
 s ^TKFINSERIE(113975)="Opé blanc 20%"
 s ^TKFINSERIE(113974)="Opé blanc 20%"
 s ^TKFINSERIE(113971)="Opé blanc 20%"
 s ^TKFINSERIE(113972)="Opé blanc 20%"
 s ^TKFINSERIE(113969)="Opé blanc 20%"
 s ^TKFINSERIE(113970)="Opé blanc 20%"
 s ^TKFINSERIE(113966)="Opé blanc 20%"
 s ^TKFINSERIE(113973)="Opé blanc 20%"
 s ^TKFINSERIE(113968)="Opé blanc 20%"
 s ^TKFINSERIE(113967)="Opé blanc 20%"
 s ^TKFINSERIE(111778)="Opé blanc 20%"
 s ^TKFINSERIE(111779)="Opé blanc 20%"
 s ^TKFINSERIE(81282)="Opé blanc 20%"
 s ^TKFINSERIE(81928)="Opé blanc 20%"
 s ^TKFINSERIE(81288)="Opé blanc 20%"
 s ^TKFINSERIE(84344)="Opé blanc 20%"
 s ^TKFINSERIE(84329)="Opé blanc 20%"
 s ^TKFINSERIE(84337)="Opé blanc 20%"
 s ^TKFINSERIE(84334)="Opé blanc 20%"
 s ^TKFINSERIE(84335)="Opé blanc 20%"
 s ^TKFINSERIE(84330)="Opé blanc 20%"
 s ^TKFINSERIE(84341)="Opé blanc 20%"
 s ^TKFINSERIE(84340)="Opé blanc 20%"
 s ^TKFINSERIE(84345)="Opé blanc 20%"
 s ^TKFINSERIE(84346)="Opé blanc 20%"
 s ^TKFINSERIE(84333)="Opé blanc 20%"
 s ^TKFINSERIE(84332)="Opé blanc 20%"
 s ^TKFINSERIE(84331)="Opé blanc 20%"
 s ^TKFINSERIE(84339)="Opé blanc 20%"
 s ^TKFINSERIE(64069)="Opé blanc 20%"
 s ^TKFINSERIE(111710)="Opé blanc 20%"
 s ^TKFINSERIE(111717)="Opé blanc 20%"
 s ^TKFINSERIE(111714)="Opé blanc 20%"
 s ^TKFINSERIE(104489)="Opé blanc 20%"
 s ^TKFINSERIE(104490)="Opé blanc 20%"
 s ^TKFINSERIE(104491)="Opé blanc 20%"
 s ^TKFINSERIE(113995)="Opé blanc 20%"
 s ^TKFINSERIE(113994)="Opé blanc 20%"
 s ^TKFINSERIE(113991)="Opé blanc 20%"
 s ^TKFINSERIE(113992)="Opé blanc 20%"
 s ^TKFINSERIE(113989)="Opé blanc 20%"
 s ^TKFINSERIE(113990)="Opé blanc 20%"
 s ^TKFINSERIE(113986)="Opé blanc 20%"
 s ^TKFINSERIE(113993)="Opé blanc 20%"
 s ^TKFINSERIE(113988)="Opé blanc 20%"
 s ^TKFINSERIE(113987)="Opé blanc 20%"
 s ^TKFINSERIE(111781)="Opé blanc 20%"
 s ^TKFINSERIE(111782)="Opé blanc 20%"
 s ^TKFINSERIE(112157)="Opé blanc 20%"
 s ^TKFINSERIE(112156)="Opé blanc 20%"
 s ^TKFINSERIE(81318)="Opé blanc 20%"
 s ^TKFINSERIE(81940)="Opé blanc 20%"
 s ^TKFINSERIE(75283)="Opé blanc 20%"
 s ^TKFINSERIE(75285)="Opé blanc 20%"
 s ^TKFINSERIE(75287)="Opé blanc 20%"
 s ^TKFINSERIE(78308)="Opé blanc 20%"
 s ^TKFINSERIE(81322)="Opé blanc 20%"
 s ^TKFINSERIE(75291)="Opé blanc 20%"
 s ^TKFINSERIE(81323)="Opé blanc 20%"
 s ^TKFINSERIE(75293)="Opé blanc 20%"
 s ^TKFINSERIE(81324)="Opé blanc 20%"
 s ^TKFINSERIE(75294)="Opé blanc 20%"
 s ^TKFINSERIE(81325)="Opé blanc 20%"
 s ^TKFINSERIE(75295)="Opé blanc 20%"
 s ^TKFINSERIE(81943)="Opé blanc 20%"
 s ^TKFINSERIE(75296)="Opé blanc 20%"
 s ^TKFINSERIE(75297)="Opé blanc 20%"
 s ^TKFINSERIE(81328)="Opé blanc 20%"
 s ^TKFINSERIE(75281)="Opé blanc 20%"
 s ^TKFINSERIE(81329)="Opé blanc 20%"
 s ^TKFINSERIE(84377)="Opé blanc 20%"
 s ^TKFINSERIE(84364)="Opé blanc 20%"
 s ^TKFINSERIE(84372)="Opé blanc 20%"
 s ^TKFINSERIE(84369)="Opé blanc 20%"
 s ^TKFINSERIE(84370)="Opé blanc 20%"
 s ^TKFINSERIE(84365)="Opé blanc 20%"
 s ^TKFINSERIE(84373)="Opé blanc 20%"
 s ^TKFINSERIE(84379)="Opé blanc 20%"
 s ^TKFINSERIE(84368)="Opé blanc 20%"
 s ^TKFINSERIE(84367)="Opé blanc 20%"
 s ^TKFINSERIE(84366)="Opé blanc 20%"
 s ^TKFINSERIE(84371)="Opé blanc 20%"
 s ^TKFINSERIE(5431)="Opé blanc 20%"
 s ^TKFINSERIE(5442)="Opé blanc 20%"
 s ^TKFINSERIE(47811)="Opé blanc 20%"
 s ^TKFINSERIE(104467)="Opé blanc 20%"
 s ^TKFINSERIE(104469)="Opé blanc 20%"
 s ^TKFINSERIE(104468)="Opé blanc 20%"
 s ^TKFINSERIE(111712)="Opé blanc 20%"
 s ^TKFINSERIE(111718)="Opé blanc 20%"
 s ^TKFINSERIE(111715)="Opé blanc 20%"
 s ^TKFINSERIE(104483)="Opé blanc 20%"
 s ^TKFINSERIE(104484)="Opé blanc 20%"
 s ^TKFINSERIE(104485)="Opé blanc 20%"
 s ^TKFINSERIE(113985)="Opé blanc 20%"
 s ^TKFINSERIE(113984)="Opé blanc 20%"
 s ^TKFINSERIE(113981)="Opé blanc 20%"
 s ^TKFINSERIE(113982)="Opé blanc 20%"
 s ^TKFINSERIE(113979)="Opé blanc 20%"
 s ^TKFINSERIE(113980)="Opé blanc 20%"
 s ^TKFINSERIE(113976)="Opé blanc 20%"
 s ^TKFINSERIE(113983)="Opé blanc 20%"
 s ^TKFINSERIE(113978)="Opé blanc 20%"
 s ^TKFINSERIE(113977)="Opé blanc 20%"
 s ^TKFINSERIE(112158)="Opé blanc 20%"
 s ^TKFINSERIE(112159)="Opé blanc 20%"
 s ^TKFINSERIE(81330)="Opé blanc 20%"
 s ^TKFINSERIE(81331)="Opé blanc 20%"
 s ^TKFINSERIE(78309)="Opé blanc 20%"
 s ^TKFINSERIE(81334)="Opé blanc 20%"
 s ^TKFINSERIE(75275)="Opé blanc 20%"
 s ^TKFINSERIE(81335)="Opé blanc 20%"
 s ^TKFINSERIE(81336)="Opé blanc 20%"
 s ^TKFINSERIE(81339)="Opé blanc 20%"
 s ^TKFINSERIE(84361)="Opé blanc 20%"
 s ^TKFINSERIE(84348)="Opé blanc 20%"
 s ^TKFINSERIE(84356)="Opé blanc 20%"
 s ^TKFINSERIE(84353)="Opé blanc 20%"
 s ^TKFINSERIE(84360)="Opé blanc 20%"
 s ^TKFINSERIE(84354)="Opé blanc 20%"
 s ^TKFINSERIE(84349)="Opé blanc 20%"
 s ^TKFINSERIE(84358)="Opé blanc 20%"
 s ^TKFINSERIE(84357)="Opé blanc 20%"
 s ^TKFINSERIE(84362)="Opé blanc 20%"
 s ^TKFINSERIE(84363)="Opé blanc 20%"
 s ^TKFINSERIE(84352)="Opé blanc 20%"
 s ^TKFINSERIE(84351)="Opé blanc 20%"
 s ^TKFINSERIE(84359)="Opé blanc 20%"
 s ^TKFINSERIE(84350)="Opé blanc 20%"
 s ^TKFINSERIE(84355)="Opé blanc 20%"
 s ^TKFINSERIE(47786)="Opé blanc 20%"
 s ^TKFINSERIE(110631)="Opé blanc 20%"
 s ^TKFINSERIE(110637)="Opé blanc 20%"
 s ^TKFINSERIE(110643)="Opé blanc 20%"
 s ^TKFINSERIE(110632)="Opé blanc 20%"
 s ^TKFINSERIE(110638)="Opé blanc 20%"
 s ^TKFINSERIE(110644)="Opé blanc 20%"
 s ^TKFINSERIE(110633)="Opé blanc 20%"
 s ^TKFINSERIE(110639)="Opé blanc 20%"
 s ^TKFINSERIE(110645)="Opé blanc 20%"
 s ^TKFINSERIE(110634)="Opé blanc 20%"
 s ^TKFINSERIE(110640)="Opé blanc 20%"
 s ^TKFINSERIE(110646)="Opé blanc 20%"
 s ^TKFINSERIE(110635)="Opé blanc 20%"
 s ^TKFINSERIE(110641)="Opé blanc 20%"
 s ^TKFINSERIE(110647)="Opé blanc 20%"
 s ^TKFINSERIE(110636)="Opé blanc 20%"
 s ^TKFINSERIE(110642)="Opé blanc 20%"
 s ^TKFINSERIE(110648)="Opé blanc 20%"
 s ^TKFINSERIE(83542)="Opé blanc 20%"
 s ^TKFINSERIE(103120)="Opé blanc 20%"
 s ^TKFINSERIE(103121)="Opé blanc 20%"
 s ^TKFINSERIE(103118)="Opé blanc 20%"
 s ^TKFINSERIE(103115)="Opé blanc 20%"
 s ^TKFINSERIE(103114)="Opé blanc 20%"
 s ^TKFINSERIE(103116)="Opé blanc 20%"
 s ^TKFINSERIE(103117)="Opé blanc 20%"
 s ^TKFINSERIE(103119)="Opé blanc 20%"
 s ^TKFINSERIE(103125)="Opé blanc 20%"
 s ^TKFINSERIE(103124)="Opé blanc 20%"
 s ^TKFINSERIE(103126)="Opé blanc 20%"
 s ^TKFINSERIE(103127)="Opé blanc 20%"
 s ^TKFINSERIE(103123)="Opé blanc 20%"
 s ^TKFINSERIE(103128)="Opé blanc 20%"
 s ^TKFINSERIE(103129)="Opé blanc 20%"
 s ^TKFINSERIE(103130)="Opé blanc 20%"
 s ^TKFINSERIE(103136)="Opé blanc 20%"
 s ^TKFINSERIE(103134)="Opé blanc 20%"
 s ^TKFINSERIE(103133)="Opé blanc 20%"
 s ^TKFINSERIE(103135)="Opé blanc 20%"
 s ^TKFINSERIE(103132)="Opé blanc 20%"
 s ^TKFINSERIE(103137)="Opé blanc 20%"
 s ^TKFINSERIE(103138)="Opé blanc 20%"
 s ^TKFINSERIE(103139)="Opé blanc 20%"
 s ^TKFINSERIE(83547)="Opé blanc 20%"
 s ^TKFINSERIE(74577)="Opé blanc 20%"
 s ^TKFINSERIE(83546)="Opé blanc 20%"
 s ^TKFINSERIE(83543)="Opé blanc 20%"
 s ^TKFINSERIE(86186)="Opé blanc 20%"
 s ^TKFINSERIE(83545)="Opé blanc 20%"
 s ^TKFINSERIE(74578)="Opé blanc 20%"
 s ^TKFINSERIE(110649)="Opé blanc 20%"
 s ^TKFINSERIE(110650)="Opé blanc 20%"
 s ^TKFINSERIE(110651)="Opé blanc 20%"
 s ^TKFINSERIE(110652)="Opé blanc 20%"
 s ^TKFINSERIE(110653)="Opé blanc 20%"
 s ^TKFINSERIE(110654)="Opé blanc 20%"
 s ^TKFINSERIE(110655)="Opé blanc 20%"
 s ^TKFINSERIE(110661)="Opé blanc 20%"
 s ^TKFINSERIE(110667)="Opé blanc 20%"
 s ^TKFINSERIE(110656)="Opé blanc 20%"
 s ^TKFINSERIE(110662)="Opé blanc 20%"
 s ^TKFINSERIE(110668)="Opé blanc 20%"
 s ^TKFINSERIE(110657)="Opé blanc 20%"
 s ^TKFINSERIE(110663)="Opé blanc 20%"
 s ^TKFINSERIE(110669)="Opé blanc 20%"
 s ^TKFINSERIE(110658)="Opé blanc 20%"
 s ^TKFINSERIE(110664)="Opé blanc 20%"
 s ^TKFINSERIE(110670)="Opé blanc 20%"
 s ^TKFINSERIE(110659)="Opé blanc 20%"
 s ^TKFINSERIE(110665)="Opé blanc 20%"
 s ^TKFINSERIE(110671)="Opé blanc 20%"
 s ^TKFINSERIE(110660)="Opé blanc 20%"
 s ^TKFINSERIE(110666)="Opé blanc 20%"
 s ^TKFINSERIE(110672)="Opé blanc 20%"
 s ^TKFINSERIE(107546)="Opé blanc 20%"
 s ^TKFINSERIE(107547)="Opé blanc 20%"
 s ^TKFINSERIE(111700)="Opé blanc 20%"
 s ^TKFINSERIE(111699)="Opé blanc 20%"
 s ^TKFINSERIE(107552)="Opé blanc 20%"
 s ^TKFINSERIE(107553)="Opé blanc 20%"
 s ^TKFINSERIE(111729)="Opé blanc 20%"
 s ^TKFINSERIE(111728)="Opé blanc 20%"
 s ^TKFINSERIE(111730)="Opé blanc 20%"
 s ^TKFINSERIE(107554)="Opé blanc 20%"
 s ^TKFINSERIE(107555)="Opé blanc 20%"
 s ^TKFINSERIE(110919)="Opé blanc 20%"
 s ^TKFINSERIE(110920)="Opé blanc 20%"
 s ^TKFINSERIE(112802)="Opé blanc 20%"
 s ^TKFINSERIE(112803)="Opé blanc 20%"
 s ^TKFINSERIE(111727)="Opé blanc 20%"
 s ^TKFINSERIE(111768)="Opé blanc 20%"
 s ^TKFINSERIE(111769)="Opé blanc 20%"
 s ^TKFINSERIE(107559)="Opé blanc 20%"
 s ^TKFINSERIE(107558)="Opé blanc 20%"
 s ^TKFINSERIE(112804)="Opé blanc 20%"
 s ^TKFINSERIE(112805)="Opé blanc 20%"
 s ^TKFINSERIE(112614)="Opé blanc 20%"
 s ^TKFINSERIE(112615)="Opé blanc 20%"
 s ^TKFINSERIE(111731)="Opé blanc 20%"
 s ^TKFINSERIE(107557)="Opé blanc 20%"
 s ^TKFINSERIE(107556)="Opé blanc 20%"
 s ^TKFINSERIE(111697)="Opé blanc 20%"
 s ^TKFINSERIE(111698)="Opé blanc 20%"
 s ^TKFINSERIE(112749)="Opé blanc 20%"
 s ^TKFINSERIE(107550)="Opé blanc 20%"
 s ^TKFINSERIE(107561)="Opé blanc 20%"
 s ^TKFINSERIE(111732)="Opé blanc 20%"
 s ^TKFINSERIE(111695)="Opé blanc 20%"
 s ^TKFINSERIE(111696)="Opé blanc 20%"
 s ^TKFINSERIE(107560)="Opé blanc 20%"
 s ^TKFINSERIE(107548)="Opé blanc 20%"
 s ^TKFINSERIE(107549)="Opé blanc 20%"
 s ^TKFINSERIE(111726)="Opé blanc 20%"
 s ^TKFINSERIE(110673)="Opé blanc 20%"
 s ^TKFINSERIE(110679)="Opé blanc 20%"
 s ^TKFINSERIE(110674)="Opé blanc 20%"
 s ^TKFINSERIE(110680)="Opé blanc 20%"
 s ^TKFINSERIE(110675)="Opé blanc 20%"
 s ^TKFINSERIE(110681)="Opé blanc 20%"
 s ^TKFINSERIE(110676)="Opé blanc 20%"
 s ^TKFINSERIE(110682)="Opé blanc 20%"
 s ^TKFINSERIE(110677)="Opé blanc 20%"
 s ^TKFINSERIE(110683)="Opé blanc 20%"
 s ^TKFINSERIE(110678)="Opé blanc 20%"
 s ^TKFINSERIE(110684)="Opé blanc 20%"
 s ^TKFINSERIE(110685)="Opé blanc 20%"
 s ^TKFINSERIE(110686)="Opé blanc 20%"
 s ^TKFINSERIE(110687)="Opé blanc 20%"
 s ^TKFINSERIE(110688)="Opé blanc 20%"
 s ^TKFINSERIE(110689)="Opé blanc 20%"
 s ^TKFINSERIE(110690)="Opé blanc 20%"
 s ^TKFINSERIE(110691)="Opé blanc 20%"
 s ^TKFINSERIE(110692)="Opé blanc 20%"
 s ^TKFINSERIE(110693)="Opé blanc 20%"
 s ^TKFINSERIE(110694)="Opé blanc 20%"
 s ^TKFINSERIE(110695)="Opé blanc 20%"
 s ^TKFINSERIE(110696)="Opé blanc 20%"
 s ^TKFINSERIE(103154)="Opé blanc 20%"
 s ^TKFINSERIE(103151)="Opé blanc 20%"
 s ^TKFINSERIE(103150)="Opé blanc 20%"
 s ^TKFINSERIE(103152)="Opé blanc 20%"
 s ^TKFINSERIE(103153)="Opé blanc 20%"
 s ^TKFINSERIE(103155)="Opé blanc 20%"
 s ^TKFINSERIE(103156)="Opé blanc 20%"
 s ^TKFINSERIE(103157)="Opé blanc 20%"
 s ^TKFINSERIE(103162)="Opé blanc 20%"
 s ^TKFINSERIE(103159)="Opé blanc 20%"
 s ^TKFINSERIE(103158)="Opé blanc 20%"
 s ^TKFINSERIE(103160)="Opé blanc 20%"
 s ^TKFINSERIE(103161)="Opé blanc 20%"
 s ^TKFINSERIE(103163)="Opé blanc 20%"
 s ^TKFINSERIE(103164)="Opé blanc 20%"
 s ^TKFINSERIE(103165)="Opé blanc 20%"
 s ^TKFINSERIE(103145)="Opé blanc 20%"
 s ^TKFINSERIE(103142)="Opé blanc 20%"
 s ^TKFINSERIE(103140)="Opé blanc 20%"
 s ^TKFINSERIE(103143)="Opé blanc 20%"
 s ^TKFINSERIE(103144)="Opé blanc 20%"
 s ^TKFINSERIE(103146)="Opé blanc 20%"
 s ^TKFINSERIE(103148)="Opé blanc 20%"
 s ^TKFINSERIE(103149)="Opé blanc 20%"
 s ^TKFINSERIE(87392)="Opé blanc 20%"
 s ^TKFINSERIE(87393)="Opé blanc 20%"
 s ^TKFINSERIE(87396)="Opé blanc 20%"
 s ^TKFINSERIE(87397)="Opé blanc 20%"
 s ^TKFINSERIE(111773)="Opé blanc 20%"
 s ^TKFINSERIE(111775)="Opé blanc 20%"
 s ^TKFINSERIE(113618)="Opé blanc 20%"
 s ^TKFINSERIE(113619)="Opé blanc 20%"
 s ^TKFINSERIE(111808)="Opé blanc 20%"
 s ^TKFINSERIE(105166)="Opé blanc 20%"
 s ^TKFINSERIE(111677)="Opé blanc 20%"
 s ^TKFINSERIE(111679)="Opé blanc 20%"
 s ^TKFINSERIE(111681)="Opé blanc 20%"
 s ^TKFINSERIE(74623)="Opé blanc 20%"
 s ^TKFINSERIE(74621)="Opé blanc 20%"
 s ^TKFINSERIE(87372)="Opé blanc 20%"
 s ^TKFINSERIE(87373)="Opé blanc 20%"
 s ^TKFINSERIE(74540)="Opé blanc 20%"
 s ^TKFINSERIE(74620)="Opé blanc 20%"
 s ^TKFINSERIE(87374)="Opé blanc 20%"
 s ^TKFINSERIE(74537)="Opé blanc 20%"
 s ^TKFINSERIE(74624)="Opé blanc 20%"
 s ^TKFINSERIE(113620)="Opé blanc 20%"
 s ^TKFINSERIE(113621)="Opé blanc 20%"
 s ^TKFINSERIE(111648)="Opé blanc 20%"
 s ^TKFINSERIE(74617)="Opé blanc 20%"
 s ^TKFINSERIE(74536)="Opé blanc 20%"
 s ^TKFINSERIE(74538)="Opé blanc 20%"
 s ^TKFINSERIE(101758)="Opé blanc 20%"
 s ^TKFINSERIE(101759)="Opé blanc 20%"
 s ^TKFINSERIE(101760)="Opé blanc 20%"
 s ^TKFINSERIE(101761)="Opé blanc 20%"
 s ^TKFINSERIE(101762)="Opé blanc 20%"
 s ^TKFINSERIE(101764)="Opé blanc 20%"
 s ^TKFINSERIE(101765)="Opé blanc 20%"
 s ^TKFINSERIE(105412)="Opé blanc 20%"
 s ^TKFINSERIE(105413)="Opé blanc 20%"
 s ^TKFINSERIE(105414)="Opé blanc 20%"
 s ^TKFINSERIE(105415)="Opé blanc 20%"
 s ^TKFINSERIE(102246)="Opé blanc 20%"
 s ^TKFINSERIE(102247)="Opé blanc 20%"
 s ^TKFINSERIE(102248)="Opé blanc 20%"
 s ^TKFINSERIE(102249)="Opé blanc 20%"
 s ^TKFINSERIE(102250)="Opé blanc 20%"
 s ^TKFINSERIE(102231)="Opé blanc 20%"
 s ^TKFINSERIE(102232)="Opé blanc 20%"
 s ^TKFINSERIE(102235)="Opé blanc 20%"
 s ^TKFINSERIE(105504)="Opé blanc 20%"
 s ^TKFINSERIE(110935)="Opé blanc 20%"
 s ^TKFINSERIE(111764)="Opé blanc 20%"
 s ^TKFINSERIE(111771)="Opé blanc 20%"
 s ^TKFINSERIE(102226)="Opé blanc 20%"
 s ^TKFINSERIE(102227)="Opé blanc 20%"
 s ^TKFINSERIE(102228)="Opé blanc 20%"
 s ^TKFINSERIE(102229)="Opé blanc 20%"
 s ^TKFINSERIE(102230)="Opé blanc 20%"
 s ^TKFINSERIE(105506)="Opé blanc 20%"
 s ^TKFINSERIE(107811)="Opé blanc 20%"
 s ^TKFINSERIE(107812)="Opé blanc 20%"
 s ^TKFINSERIE(110934)="Opé blanc 20%"
 s ^TKFINSERIE(111688)="Opé blanc 20%"
 s ^TKFINSERIE(111765)="Opé blanc 20%"
 s ^TKFINSERIE(111772)="Opé blanc 20%"
 s ^TKFINSERIE(112795)="Opé blanc 20%"
 s ^TKFINSERIE(100440)="Opé blanc 20%"
 s ^TKFINSERIE(100443)="Opé blanc 20%"
 s ^TKFINSERIE(100442)="Opé blanc 20%"
 s ^TKFINSERIE(100441)="Opé blanc 20%"
 s ^TKFINSERIE(102241)="Opé blanc 20%"
 s ^TKFINSERIE(102242)="Opé blanc 20%"
 s ^TKFINSERIE(102243)="Opé blanc 20%"
 s ^TKFINSERIE(102244)="Opé blanc 20%"
 s ^TKFINSERIE(102245)="Opé blanc 20%"
 s ^TKFINSERIE(100444)="Opé blanc 20%"
 s ^TKFINSERIE(111770)="Opé blanc 20%"
 s ^TKFINSERIE(111763)="Opé blanc 20%"
 s ^TKFINSERIE(105505)="Opé blanc 20%"
 s ^TKFINSERIE(112800)="Opé blanc 20%"
 s ^TKFINSERIE(112799)="Opé blanc 20%"
 s ^TKFINSERIE(112801)="Opé blanc 20%"
 s ^TKFINSERIE(112794)="Opé blanc 20%"
 s ^TKFINSERIE(89789)="Opé blanc 20%"
 s ^TKFINSERIE(89785)="Opé blanc 20%"
 s ^TKFINSERIE(89786)="Opé blanc 20%"
 s ^TKFINSERIE(89790)="Opé blanc 20%"
 s ^TKFINSERIE(89787)="Opé blanc 20%"
 s ^TKFINSERIE(89791)="Opé blanc 20%"
 s ^TKFINSERIE(89788)="Opé blanc 20%"
 s ^TKFINSERIE(89792)="Opé blanc 20%"
 s ^TKFINSERIE(5808)="Opé blanc 20%"
 s ^TKFINSERIE(66358)="Opé blanc 20%"
 s ^TKFINSERIE(5620)="Opé blanc 20%"
 s ^TKFINSERIE(5809)="Opé blanc 20%"
 s ^TKFINSERIE(5621)="Opé blanc 20%"
 s ^TKFINSERIE(5810)="Opé blanc 20%"
 s ^TKFINSERIE(5622)="Opé blanc 20%"
 s ^TKFINSERIE(5623)="Opé blanc 20%"
 s ^TKFINSERIE(66371)="Opé blanc 20%"
 s ^TKFINSERIE(66372)="Opé blanc 20%"
 s ^TKFINSERIE(66365)="Opé blanc 20%"
 s ^TKFINSERIE(66366)="Opé blanc 20%"
 s ^TKFINSERIE(66367)="Opé blanc 20%"
 s ^TKFINSERIE(66368)="Opé blanc 20%"
 s ^TKFINSERIE(66369)="Opé blanc 20%"
 s ^TKFINSERIE(66370)="Opé blanc 20%"
 s ^TKFINSERIE(105809)="Opé blanc 20%"
 s ^TKFINSERIE(105810)="Opé blanc 20%"
 s ^TKFINSERIE(105811)="Opé blanc 20%"
 s ^TKFINSERIE(105813)="Opé blanc 20%"
 s ^TKFINSERIE(115904)="Opé blanc 20%"
 s ^TKFINSERIE(115905)="Opé blanc 20%"
 s ^TKFINSERIE(89796)="Opé blanc 20%"
 s ^TKFINSERIE(100658)="Opé blanc 20%"
 s ^TKFINSERIE(89795)="Opé blanc 20%"
 s ^TKFINSERIE(89793)="Opé blanc 20%"
 s ^TKFINSERIE(89794)="Opé blanc 20%"
 s ^TKFINSERIE(5616)="Opé blanc 20%"
 s ^TKFINSERIE(66364)="Opé blanc 20%"
 s ^TKFINSERIE(5617)="Opé blanc 20%"
 s ^TKFINSERIE(66363)="Opé blanc 20%"
 s ^TKFINSERIE(5618)="Opé blanc 20%"
 s ^TKFINSERIE(66356)="Opé blanc 20%"
 s ^TKFINSERIE(5619)="Opé blanc 20%"
 s ^TKFINSERIE(5624)="Opé blanc 20%"
 s ^TKFINSERIE(5625)="Opé blanc 20%"
 s ^TKFINSERIE(5626)="Opé blanc 20%"
 s ^TKFINSERIE(105822)="Opé blanc 20%"
 s ^TKFINSERIE(105821)="Opé blanc 20%"
 s ^TKFINSERIE(115907)="Opé blanc 20%"
 s ^TKFINSERIE(115909)="Opé blanc 20%"
 s ^TKFINSERIE(115908)="Opé blanc 20%"
 s ^TKFINSERIE(115906)="Opé blanc 20%"
 s ^TKFINSERIE(8683)="Opé blanc 20%"
 s ^TKFINSERIE(5748)="Opé blanc 20%"
 s ^TKFINSERIE(5749)="Opé blanc 20%"
 s ^TKFINSERIE(5750)="Opé blanc 20%"
 s ^TKFINSERIE(5751)="Opé blanc 20%"
 s ^TKFINSERIE(5752)="Opé blanc 20%"
 s ^TKFINSERIE(5753)="Opé blanc 20%"
 s ^TKFINSERIE(5754)="Opé blanc 20%"
 s ^TKFINSERIE(5755)="Opé blanc 20%"
 s ^TKFINSERIE(5811)="Opé blanc 20%"
 s ^TKFINSERIE(5812)="Opé blanc 20%"
 s ^TKFINSERIE(113513)="Opé blanc 20%"
 s ^TKFINSERIE(113514)="Opé blanc 20%"
 s ^TKFINSERIE(113515)="Opé blanc 20%"
 s ^TKFINSERIE(113516)="Opé blanc 20%"
 s ^TKFINSERIE(113517)="Opé blanc 20%"
 s ^TKFINSERIE(113518)="Opé blanc 20%"
 s ^TKFINSERIE(0)="Opé blanc 20%"
 s ^TKFINSERIE(0)="Opé blanc 20%"
 s ^TKFINSERIE(0)="Opé blanc 20%"
 s ^TKFINSERIE(0)="Opé blanc 20%"
 s ^TKFINSERIE(118767)="Opé blanc 20%"
 s ^TKFINSERIE(118766)="Opé blanc 20%"
 s ^TKFINSERIE(118765)="Opé blanc 20%"
 s ^TKFINSERIE(118764)="Opé blanc 20%"
 s ^TKFINSERIE(118763)="Opé blanc 20%"
 s ^TKFINSERIE(118762)="Opé blanc 20%"
 s ^TKFINSERIE(118761)="Opé blanc 20%"
 s ^TKFINSERIE(118760)="Opé blanc 20%"
 s ^TKFINSERIE(118759)="Opé blanc 20%"
 s ^TKFINSERIE(118758)="Opé blanc 20%"
 s ^TKFINSERIE(118757)="Opé blanc 20%"
 s ^TKFINSERIE(118756)="Opé blanc 20%"
 q
















































































































































































































































































































































































































































































































































































































































































