ROUTINE OPESOLDES50PE13P6
OPESOLDES50PE13P6
 
	s ^TKSOLDES("87686")="\0.5\0"
	s ^TKSOLDES("50500")="\0.5\0"
	s ^TKSOLDES("50532")="\0.5\0"
	s ^TKSOLDES("50531")="\0.5\0"
	s ^TKSOLDES("50499")="\0.5\0"
	s ^TKSOLDES("50547")="\0.5\0"
	s ^TKSOLDES("50498")="\0.5\0"
	s ^TKSOLDES("50497")="\0.5\0"
	s ^TKSOLDES("50496")="\0.5\0"
	s ^TKSOLDES("50533")="\0.5\0"
	s ^TKSOLDES("50548")="\0.5\0"
	s ^TKSOLDES("87358")="\0.5\0"
	s ^TKSOLDES("50553")="\0.5\0"
	s ^TKSOLDES("53490")="\0.5\0"
	s ^TKSOLDES("87354")="\0.5\0"
	s ^TKSOLDES("51583")="\0.5\0"
	s ^TKSOLDES("51572")="\0.5\0"
	s ^TKSOLDES("51571")="\0.5\0"
	s ^TKSOLDES("87355")="\0.5\0"
	s ^TKSOLDES("87356")="\0.5\0"
	s ^TKSOLDES("50554")="\0.5\0"
	s ^TKSOLDES("87357")="\0.5\0"
	s ^TKSOLDES("87359")="\0.5\0"
	s ^TKSOLDES("87685")="\0.5\0"
	s ^TKSOLDES("87360")="\0.5\0"
	s ^TKSOLDES("87676")="\0.5\0"
	s ^TKSOLDES("87677")="\0.5\0"
	s ^TKSOLDES("87678")="\0.5\0"
	s ^TKSOLDES("87679")="\0.5\0"
	s ^TKSOLDES("87680")="\0.5\0"
	s ^TKSOLDES("87682")="\0.5\0"
	s ^TKSOLDES("87683")="\0.5\0"
	s ^TKSOLDES("87684")="\0.5\0"
	s ^TKSOLDES("87675")="\0.5\0"
	s ^TKSOLDES("87674")="\0.5\0"
	s ^TKSOLDES("87667")="\0.5\0"
	s ^TKSOLDES("87361")="\0.5\0"
	s ^TKSOLDES("87362")="\0.5\0"
	s ^TKSOLDES("87666")="\0.5\0"
	s ^TKSOLDES("87668")="\0.5\0"
	s ^TKSOLDES("87673")="\0.5\0"
	s ^TKSOLDES("87669")="\0.5\0"
	s ^TKSOLDES("87670")="\0.5\0"
	s ^TKSOLDES("87671")="\0.5\0"
	s ^TKSOLDES("87672")="\0.5\0"
	s ^TKSOLDES("49928")="\0.5\0"
	s ^TKSOLDES("49926")="\0.5\0"
	s ^TKSOLDES("44244")="\0.5\0"
	s ^TKSOLDES("44343")="\0.5\0"
	s ^TKSOLDES("44345")="\0.5\0"
	s ^TKSOLDES("44344")="\0.5\0"
	s ^TKSOLDES("44342")="\0.5\0"
	s ^TKSOLDES("44347")="\0.5\0"
	s ^TKSOLDES("44337")="\0.5\0"
	s ^TKSOLDES("44336")="\0.5\0"
	s ^TKSOLDES("44332")="\0.5\0"
	s ^TKSOLDES("44346")="\0.5\0"
	s ^TKSOLDES("44348")="\0.5\0"
	s ^TKSOLDES("44359")="\0.5\0"
	s ^TKSOLDES("44349")="\0.5\0"
	s ^TKSOLDES("44357")="\0.5\0"
	s ^TKSOLDES("44356")="\0.5\0"
	s ^TKSOLDES("44355")="\0.5\0"
	s ^TKSOLDES("44354")="\0.5\0"
	s ^TKSOLDES("44353")="\0.5\0"
	s ^TKSOLDES("44352")="\0.5\0"
	s ^TKSOLDES("44351")="\0.5\0"
	s ^TKSOLDES("44350")="\0.5\0"
	s ^TKSOLDES("44331")="\0.5\0"
	s ^TKSOLDES("44330")="\0.5\0"
	s ^TKSOLDES("44329")="\0.5\0"
	s ^TKSOLDES("44253")="\0.5\0"
	s ^TKSOLDES("44252")="\0.5\0"
	s ^TKSOLDES("44251")="\0.5\0"
	s ^TKSOLDES("44250")="\0.5\0"
	s ^TKSOLDES("44248")="\0.5\0"
	s ^TKSOLDES("44247")="\0.5\0"
	s ^TKSOLDES("44246")="\0.5\0"
	s ^TKSOLDES("44245")="\0.5\0"
	s ^TKSOLDES("44306")="\0.5\0"
	s ^TKSOLDES("44307")="\0.5\0"
	s ^TKSOLDES("44320")="\0.5\0"
	s ^TKSOLDES("44325")="\0.5\0"
	s ^TKSOLDES("44323")="\0.5\0"
	s ^TKSOLDES("44321")="\0.5\0"
	s ^TKSOLDES("44319")="\0.5\0"
	s ^TKSOLDES("44314")="\0.5\0"
	s ^TKSOLDES("44318")="\0.5\0"
	s ^TKSOLDES("44317")="\0.5\0"
	s ^TKSOLDES("44316")="\0.5\0"
	s ^TKSOLDES("44315")="\0.5\0"
	s ^TKSOLDES("44358")="\0.5\0"
	s ^TKSOLDES("44360")="\0.5\0"
	s ^TKSOLDES("49925")="\0.5\0"
	s ^TKSOLDES("87706")="\0.5\0"
	s ^TKSOLDES("49912")="\0.5\0"
	s ^TKSOLDES("87705")="\0.5\0"
	s ^TKSOLDES("87707")="\0.5\0"
	s ^TKSOLDES("49914")="\0.5\0"
	s ^TKSOLDES("87709")="\0.5\0"
	s ^TKSOLDES("87710")="\0.5\0"
	s ^TKSOLDES("87711")="\0.5\0"
	s ^TKSOLDES("49913")="\0.5\0"
	s ^TKSOLDES("49915")="\0.5\0"
	s ^TKSOLDES("46773")="\0.5\0"
	s ^TKSOLDES("49916")="\0.5\0"
	s ^TKSOLDES("49924")="\0.5\0"
	s ^TKSOLDES("49923")="\0.5\0"
	s ^TKSOLDES("49922")="\0.5\0"
	s ^TKSOLDES("49921")="\0.5\0"
	s ^TKSOLDES("49920")="\0.5\0"
	s ^TKSOLDES("49919")="\0.5\0"
	s ^TKSOLDES("49918")="\0.5\0"
	s ^TKSOLDES("49917")="\0.5\0"
	s ^TKSOLDES("46787")="\0.5\0"
	s ^TKSOLDES("46727")="\0.5\0"
	s ^TKSOLDES("44361")="\0.5\0"
	s ^TKSOLDES("44413")="\0.5\0"
	s ^TKSOLDES("44381")="\0.5\0"
	s ^TKSOLDES("44379")="\0.5\0"
	s ^TKSOLDES("44371")="\0.5\0"
	s ^TKSOLDES("44366")="\0.5\0"
	s ^TKSOLDES("44365")="\0.5\0"
	s ^TKSOLDES("64875")="\0.5\0"
	s ^TKSOLDES("44363")="\0.5\0"
	s ^TKSOLDES("44362")="\0.5\0"
	s ^TKSOLDES("44384")="\0.5\0"
	s ^TKSOLDES("44386")="\0.5\0"
	s ^TKSOLDES("44405")="\0.5\0"
	s ^TKSOLDES("44409")="\0.5\0"
	s ^TKSOLDES("44407")="\0.5\0"
	s ^TKSOLDES("44406")="\0.5\0"
	s ^TKSOLDES("44404")="\0.5\0"
	s ^TKSOLDES("44387")="\0.5\0"
	s ^TKSOLDES("44403")="\0.5\0"
	s ^TKSOLDES("44402")="\0.5\0"
	s ^TKSOLDES("44389")="\0.5\0"
	s ^TKSOLDES("44388")="\0.5\0"
	s ^TKSOLDES("64689")="\0.5\0"
	s ^TKSOLDES("65102")="\0.5\0"
	s ^TKSOLDES("84589")="\0.5\0"
	s ^TKSOLDES("84591")="\0.5\0"
	s ^TKSOLDES("84592")="\0.5\0"
	s ^TKSOLDES("84593")="\0.5\0"
	s ^TKSOLDES("84594")="\0.5\0"
	s ^TKSOLDES("84595")="\0.5\0"
	s ^TKSOLDES("84596")="\0.5\0"
	s ^TKSOLDES("84590")="\0.5\0"
	s ^TKSOLDES("84588")="\0.5\0"
	s ^TKSOLDES("68688")="\0.5\0"
	s ^TKSOLDES("84582")="\0.5\0"
	s ^TKSOLDES("84580")="\0.5\0"
	s ^TKSOLDES("84581")="\0.5\0"
	s ^TKSOLDES("84583")="\0.5\0"
	s ^TKSOLDES("84587")="\0.5\0"
	s ^TKSOLDES("84584")="\0.5\0"
	s ^TKSOLDES("84585")="\0.5\0"
	s ^TKSOLDES("84586")="\0.5\0"
	s ^TKSOLDES("68689")="\0.5\0"
	s ^TKSOLDES("68687")="\0.5\0"
	s ^TKSOLDES("84578")="\0.5\0"
	s ^TKSOLDES("84603")="\0.5\0"
	s ^TKSOLDES("84601")="\0.5\0"
	s ^TKSOLDES("84602")="\0.5\0"
	s ^TKSOLDES("84604")="\0.5\0"
	s ^TKSOLDES("68686")="\0.5\0"
	s ^TKSOLDES("84605")="\0.5\0"
	s ^TKSOLDES("84606")="\0.5\0"
	s ^TKSOLDES("84607")="\0.5\0"
	s ^TKSOLDES("84600")="\0.5\0"
	s ^TKSOLDES("84599")="\0.5\0"
	s ^TKSOLDES("84598")="\0.5\0"
	s ^TKSOLDES("68685")="\0.5\0"
	s ^TKSOLDES("68683")="\0.5\0"
	s ^TKSOLDES("68682")="\0.5\0"
	s ^TKSOLDES("68681")="\0.5\0"
	s ^TKSOLDES("68680")="\0.5\0"
	s ^TKSOLDES("68570")="\0.5\0"
	s ^TKSOLDES("68567")="\0.5\0"
	s ^TKSOLDES("84597")="\0.5\0"
	s ^TKSOLDES("84579")="\0.5\0"
	s ^TKSOLDES("84576")="\0.5\0"
	s ^TKSOLDES("84609")="\0.5\0"
	s ^TKSOLDES("72668")="\0.5\0"
	s ^TKSOLDES("72670")="\0.5\0"
	s ^TKSOLDES("72669")="\0.5\0"
	s ^TKSOLDES("72666")="\0.5\0"
	s ^TKSOLDES("84575")="\0.5\0"
	s ^TKSOLDES("72660")="\0.5\0"
	s ^TKSOLDES("72659")="\0.5\0"
	s ^TKSOLDES("72653")="\0.5\0"
	s ^TKSOLDES("72671")="\0.5\0"
	s ^TKSOLDES("72672")="\0.5\0"
	s ^TKSOLDES("72674")="\0.5\0"
	s ^TKSOLDES("72682")="\0.5\0"
	s ^TKSOLDES("72681")="\0.5\0"
	s ^TKSOLDES("72680")="\0.5\0"
	s ^TKSOLDES("72679")="\0.5\0"
	s ^TKSOLDES("72678")="\0.5\0"
	s ^TKSOLDES("72677")="\0.5\0"
	s ^TKSOLDES("72676")="\0.5\0"
	s ^TKSOLDES("72675")="\0.5\0"
	s ^TKSOLDES("72650")="\0.5\0"
	s ^TKSOLDES("72649")="\0.5\0"
	s ^TKSOLDES("84570")="\0.5\0"
	s ^TKSOLDES("84568")="\0.5\0"
	s ^TKSOLDES("84569")="\0.5\0"
	s ^TKSOLDES("84571")="\0.5\0"
	s ^TKSOLDES("64891")="\0.5\0"
	s ^TKSOLDES("84572")="\0.5\0"
	s ^TKSOLDES("84573")="\0.5\0"
	s ^TKSOLDES("84574")="\0.5\0"
	s ^TKSOLDES("84567")="\0.5\0"
	s ^TKSOLDES("84565")="\0.5\0"
	s ^TKSOLDES("72648")="\0.5\0"
	s ^TKSOLDES("84564")="\0.5\0"
	s ^TKSOLDES("72647")="\0.5\0"
	s ^TKSOLDES("72646")="\0.5\0"
	s ^TKSOLDES("72643")="\0.5\0"
	s ^TKSOLDES("72642")="\0.5\0"
	s ^TKSOLDES("72638")="\0.5\0"
	s ^TKSOLDES("103554")="\0.5\0"
	s ^TKSOLDES("103553")="\0.5\0"
	s ^TKSOLDES("103551")="\0.5\0"
	s ^TKSOLDES("84608")="\0.5\0"
	s ^TKSOLDES("84610")="\0.5\0"
	s ^TKSOLDES("80412")="\0.5\0"
	s ^TKSOLDES("84872")="\0.5\0"
	s ^TKSOLDES("84870")="\0.5\0"
	s ^TKSOLDES("84871")="\0.5\0"
	s ^TKSOLDES("84873")="\0.5\0"
	s ^TKSOLDES("84611")="\0.5\0"
	s ^TKSOLDES("84874")="\0.5\0"
	s ^TKSOLDES("84875")="\0.5\0"
	s ^TKSOLDES("84878")="\0.5\0"
	s ^TKSOLDES("84867")="\0.5\0"
	s ^TKSOLDES("84866")="\0.5\0"
	s ^TKSOLDES("84864")="\0.5\0"
	s ^TKSOLDES("84856")="\0.5\0"
	s ^TKSOLDES("84857")="\0.5\0"
	s ^TKSOLDES("84858")="\0.5\0"
	s ^TKSOLDES("84859")="\0.5\0"
	s ^TKSOLDES("84860")="\0.5\0"
	s ^TKSOLDES("84861")="\0.5\0"
	s ^TKSOLDES("84862")="\0.5\0"
	s ^TKSOLDES("84863")="\0.5\0"
	s ^TKSOLDES("84879")="\0.5\0"
	s ^TKSOLDES("84880")="\0.5\0"
	s ^TKSOLDES("80418")="\0.5\0"
	s ^TKSOLDES("80420")="\0.5\0"
	s ^TKSOLDES("80419")="\0.5\0"
	s ^TKSOLDES("80417")="\0.5\0"
	s ^TKSOLDES("80422")="\0.5\0"
	s ^TKSOLDES("80416")="\0.5\0"
	s ^TKSOLDES("80415")="\0.5\0"
	s ^TKSOLDES("80414")="\0.5\0"
	s ^TKSOLDES("80421")="\0.5\0"
	s ^TKSOLDES("80423")="\0.5\0"
	s ^TKSOLDES("84881")="\0.5\0"
	s ^TKSOLDES("80424")="\0.5\0"
	s ^TKSOLDES("84884")="\0.5\0"
	s ^TKSOLDES("84885")="\0.5\0"
	s ^TKSOLDES("103548")="\0.5\0"
	s ^TKSOLDES("80431")="\0.5\0"
	s ^TKSOLDES("80429")="\0.5\0"
	s ^TKSOLDES("80427")="\0.5\0"
	s ^TKSOLDES("80426")="\0.5\0"
	s ^TKSOLDES("80425")="\0.5\0"
	s ^TKSOLDES("84855")="\0.5\0"
	s ^TKSOLDES("84854")="\0.5\0"
	s ^TKSOLDES("84625")="\0.5\0"
	s ^TKSOLDES("84623")="\0.5\0"
	s ^TKSOLDES("84624")="\0.5\0"
	s ^TKSOLDES("84626")="\0.5\0"
	s ^TKSOLDES("84631")="\0.5\0"
	s ^TKSOLDES("84627")="\0.5\0"
	s ^TKSOLDES("84628")="\0.5\0"
	s ^TKSOLDES("84629")="\0.5\0"
	s ^TKSOLDES("84622")="\0.5\0"
	s ^TKSOLDES("84621")="\0.5\0"
	s ^TKSOLDES("84620")="\0.5\0"
	s ^TKSOLDES("84612")="\0.5\0"
	s ^TKSOLDES("84613")="\0.5\0"
	s ^TKSOLDES("84614")="\0.5\0"
	s ^TKSOLDES("84615")="\0.5\0"
	s ^TKSOLDES("84616")="\0.5\0"
	s ^TKSOLDES("84617")="\0.5\0"
	s ^TKSOLDES("84618")="\0.5\0"
	s ^TKSOLDES("84619")="\0.5\0"
	s ^TKSOLDES("84630")="\0.5\0"
	s ^TKSOLDES("84632")="\0.5\0"
	s ^TKSOLDES("84853")="\0.5\0"
	s ^TKSOLDES("84848")="\0.5\0"
	s ^TKSOLDES("80432")="\0.5\0"
	s ^TKSOLDES("84847")="\0.5\0"
	s ^TKSOLDES("84849")="\0.5\0"
	s ^TKSOLDES("80434")="\0.5\0"
	s ^TKSOLDES("84850")="\0.5\0"
	s ^TKSOLDES("84851")="\0.5\0"
	s ^TKSOLDES("84852")="\0.5\0"
	s ^TKSOLDES("80433")="\0.5\0"
	s ^TKSOLDES("80435")="\0.5\0"
	s ^TKSOLDES("84633")="\0.5\0"
	s ^TKSOLDES("103549")="\0.5\0"
	s ^TKSOLDES("84634")="\0.5\0"
	s ^TKSOLDES("84635")="\0.5\0"
	s ^TKSOLDES("84636")="\0.5\0"
	s ^TKSOLDES("84637")="\0.5\0"
	s ^TKSOLDES("84638")="\0.5\0"
	s ^TKSOLDES("84639")="\0.5\0"
	s ^TKSOLDES("80436")="\0.5\0"
	s ^TKSOLDES("103550")="\0.5\0"
	s ^TKSOLDES("72683")="\0.5\0"
	s ^TKSOLDES("72684")="\0.5\0"
	s ^TKSOLDES("83012")="\0.5\0"
	s ^TKSOLDES("83010")="\0.5\0"
	s ^TKSOLDES("83011")="\0.5\0"
	s ^TKSOLDES("83013")="\0.5\0"
	s ^TKSOLDES("72687")="\0.5\0"
	s ^TKSOLDES("103567")="\0.5\0"
	s ^TKSOLDES("103566")="\0.5\0"
	s ^TKSOLDES("103564")="\0.5\0"
	s ^TKSOLDES("83009")="\0.5\0"
	s ^TKSOLDES("83007")="\0.5\0"
	s ^TKSOLDES("83006")="\0.5\0"
	s ^TKSOLDES("82997")="\0.5\0"
	s ^TKSOLDES("82998")="\0.5\0"
	s ^TKSOLDES("83000")="\0.5\0"
	s ^TKSOLDES("83001")="\0.5\0"
	s ^TKSOLDES("83002")="\0.5\0"
	s ^TKSOLDES("83003")="\0.5\0"
	s ^TKSOLDES("83004")="\0.5\0"
	s ^TKSOLDES("83005")="\0.5\0"
	s ^TKSOLDES("103563")="\0.5\0"
	s ^TKSOLDES("103562")="\0.5\0"
	s ^TKSOLDES("74295")="\0.5\0"
	s ^TKSOLDES("74297")="\0.5\0"
	s ^TKSOLDES("74296")="\0.5\0"
	s ^TKSOLDES("74294")="\0.5\0"
	s ^TKSOLDES("74299")="\0.5\0"
	s ^TKSOLDES("74293")="\0.5\0"
	s ^TKSOLDES("74292")="\0.5\0"
	s ^TKSOLDES("103561")="\0.5\0"
	s ^TKSOLDES("74298")="\0.5\0"
	s ^TKSOLDES("74300")="\0.5\0"
	s ^TKSOLDES("74312")="\0.5\0"
	s ^TKSOLDES("74301")="\0.5\0"
	s ^TKSOLDES("74311")="\0.5\0"
	s ^TKSOLDES("74310")="\0.5\0"
	s ^TKSOLDES("74308")="\0.5\0"
	s ^TKSOLDES("74307")="\0.5\0"
	s ^TKSOLDES("74306")="\0.5\0"
	s ^TKSOLDES("74305")="\0.5\0"
	s ^TKSOLDES("74304")="\0.5\0"
	s ^TKSOLDES("74302")="\0.5\0"
	s ^TKSOLDES("82996")="\0.5\0"
	s ^TKSOLDES("82995")="\0.5\0"
	s ^TKSOLDES("81374")="\0.5\0"
	s ^TKSOLDES("81372")="\0.5\0"
	s ^TKSOLDES("81373")="\0.5\0"
	s ^TKSOLDES("81375")="\0.5\0"
	s ^TKSOLDES("103620")="\0.5\0"
	s ^TKSOLDES("81376")="\0.5\0"
	s ^TKSOLDES("81377")="\0.5\0"
	s ^TKSOLDES("103628")="\0.5\0"
	s ^TKSOLDES("81371")="\0.5\0"
	s ^TKSOLDES("81370")="\0.5\0"
	s ^TKSOLDES("81369")="\0.5\0"
	s ^TKSOLDES("81360")="\0.5\0"
	s ^TKSOLDES("81361")="\0.5\0"
	s ^TKSOLDES("81362")="\0.5\0"
	s ^TKSOLDES("81363")="\0.5\0"
	s ^TKSOLDES("81364")="\0.5\0"
	s ^TKSOLDES("81365")="\0.5\0"
	s ^TKSOLDES("81366")="\0.5\0"
	s ^TKSOLDES("81367")="\0.5\0"
	s ^TKSOLDES("103623")="\0.5\0"
	s ^TKSOLDES("103619")="\0.5\0"
	s ^TKSOLDES("82991")="\0.5\0"
	s ^TKSOLDES("103574")="\0.5\0"
	s ^TKSOLDES("103576")="\0.5\0"
	s ^TKSOLDES("103575")="\0.5\0"
	s ^TKSOLDES("103573")="\0.5\0"
	s ^TKSOLDES("103583")="\0.5\0"
	s ^TKSOLDES("103572")="\0.5\0"
	s ^TKSOLDES("103571")="\0.5\0"
	s ^TKSOLDES("82990")="\0.5\0"
	s ^TKSOLDES("103582")="\0.5\0"
	s ^TKSOLDES("103584")="\0.5\0"
	s ^TKSOLDES("103614")="\0.5\0"
	s ^TKSOLDES("103592")="\0.5\0"
	s ^TKSOLDES("103613")="\0.5\0"
	s ^TKSOLDES("103606")="\0.5\0"
	s ^TKSOLDES("103605")="\0.5\0"
	s ^TKSOLDES("75089")="\0.5\0"
	s ^TKSOLDES("103603")="\0.5\0"
	s ^TKSOLDES("103602")="\0.5\0"
	s ^TKSOLDES("103601")="\0.5\0"
	s ^TKSOLDES("103596")="\0.5\0"
	s ^TKSOLDES("84135")="\0.5\0"
	s ^TKSOLDES("84136")="\0.5\0"
	s ^TKSOLDES("72741")="\0.5\0"
	s ^TKSOLDES("72743")="\0.5\0"
	s ^TKSOLDES("72742")="\0.5\0"
	s ^TKSOLDES("72740")="\0.5\0"
	s ^TKSOLDES("72776")="\0.5\0"
	s ^TKSOLDES("72734")="\0.5\0"
	s ^TKSOLDES("72732")="\0.5\0"
	s ^TKSOLDES("72731")="\0.5\0"
	s ^TKSOLDES("72744")="\0.5\0"
	s ^TKSOLDES("72745")="\0.5\0"
	s ^TKSOLDES("72747")="\0.5\0"
	s ^TKSOLDES("72771")="\0.5\0"
	s ^TKSOLDES("72770")="\0.5\0"
	s ^TKSOLDES("72768")="\0.5\0"
	s ^TKSOLDES("72765")="\0.5\0"
	s ^TKSOLDES("72762")="\0.5\0"
	s ^TKSOLDES("72757")="\0.5\0"
	s ^TKSOLDES("72756")="\0.5\0"
	s ^TKSOLDES("72755")="\0.5\0"
	s ^TKSOLDES("72728")="\0.5\0"
	s ^TKSOLDES("72727")="\0.5\0"
	s ^TKSOLDES("72702")="\0.5\0"
	s ^TKSOLDES("72705")="\0.5\0"
	s ^TKSOLDES("72704")="\0.5\0"
	s ^TKSOLDES("72693")="\0.5\0"
	s ^TKSOLDES("72709")="\0.5\0"
	s ^TKSOLDES("72690")="\0.5\0"
	s ^TKSOLDES("72689")="\0.5\0"
	s ^TKSOLDES("72688")="\0.5\0"
	s ^TKSOLDES("72707")="\0.5\0"
	s ^TKSOLDES("72711")="\0.5\0"
	s ^TKSOLDES("72726")="\0.5\0"
	s ^TKSOLDES("72712")="\0.5\0"
	s ^TKSOLDES("72723")="\0.5\0"
	s ^TKSOLDES("72721")="\0.5\0"
	s ^TKSOLDES("72718")="\0.5\0"
	s ^TKSOLDES("72717")="\0.5\0"
	s ^TKSOLDES("72716")="\0.5\0"
	s ^TKSOLDES("72715")="\0.5\0"
	s ^TKSOLDES("72714")="\0.5\0"
	s ^TKSOLDES("72713")="\0.5\0"
	s ^TKSOLDES("72772")="\0.5\0"
	s ^TKSOLDES("72783")="\0.5\0"
	s ^TKSOLDES("84137")="\0.5\0"
	s ^TKSOLDES("73341")="\0.5\0"
	s ^TKSOLDES("80843")="\0.5\0"
	s ^TKSOLDES("73344")="\0.5\0"
	s ^TKSOLDES("73340")="\0.5\0"
	s ^TKSOLDES("80840")="\0.5\0"
	s ^TKSOLDES("73337")="\0.5\0"
	s ^TKSOLDES("73335")="\0.5\0"
	s ^TKSOLDES("73249")="\0.5\0"
	s ^TKSOLDES("80844")="\0.5\0"
	s ^TKSOLDES("80846")="\0.5\0"
	s ^TKSOLDES("80847")="\0.5\0"
	s ^TKSOLDES("80856")="\0.5\0"
	s ^TKSOLDES("80855")="\0.5\0"
	s ^TKSOLDES("80853")="\0.5\0"
	s ^TKSOLDES("80852")="\0.5\0"
	s ^TKSOLDES("80851")="\0.5\0"
	s ^TKSOLDES("80850")="\0.5\0"
	s ^TKSOLDES("80849")="\0.5\0"
	s ^TKSOLDES("80848")="\0.5\0"
	s ^TKSOLDES("73248")="\0.5\0"
	s ^TKSOLDES("80839")="\0.5\0"
	s ^TKSOLDES("103555")="\0.5\0"
	s ^TKSOLDES("80827")="\0.5\0"
	s ^TKSOLDES("80829")="\0.5\0"
	s ^TKSOLDES("80828")="\0.5\0"
	s ^TKSOLDES("80826")="\0.5\0"
	s ^TKSOLDES("80831")="\0.5\0"
	s ^TKSOLDES("80825")="\0.5\0"
	s ^TKSOLDES("80824")="\0.5\0"
	s ^TKSOLDES("103560")="\0.5\0"
	s ^TKSOLDES("80830")="\0.5\0"
	s ^TKSOLDES("80832")="\0.5\0"
	s ^TKSOLDES("80838")="\0.5\0"
	s ^TKSOLDES("80833")="\0.5\0"
	s ^TKSOLDES("80837")="\0.5\0"
	s ^TKSOLDES("80836")="\0.5\0"
	s ^TKSOLDES("80835")="\0.5\0"
	s ^TKSOLDES("73015")="\0.5\0"
	s ^TKSOLDES("73013")="\0.5\0"
	s ^TKSOLDES("73012")="\0.5\0"
	s ^TKSOLDES("73011")="\0.5\0"
	s ^TKSOLDES("80834")="\0.5\0"
	s ^TKSOLDES("80413")="\0.5\0"
	s ^TKSOLDES("84566")="\0.5\0"
	s ^TKSOLDES("65079")="\0.5\0"
	s ^TKSOLDES("86087")="\0.5\0"
	s ^TKSOLDES("86088")="\0.5\0"
	s ^TKSOLDES("86089")="\0.5\0"
	s ^TKSOLDES("86090")="\0.5\0"
	s ^TKSOLDES("86091")="\0.5\0"
	s ^TKSOLDES("86092")="\0.5\0"
	s ^TKSOLDES("86086")="\0.5\0"
	s ^TKSOLDES("86085")="\0.5\0"
	s ^TKSOLDES("86075")="\0.5\0"
	s ^TKSOLDES("86073")="\0.5\0"
	s ^TKSOLDES("86074")="\0.5\0"
	s ^TKSOLDES("86079")="\0.5\0"
	s ^TKSOLDES("86084")="\0.5\0"
	s ^TKSOLDES("86080")="\0.5\0"
	s ^TKSOLDES("86081")="\0.5\0"
	s ^TKSOLDES("86082")="\0.5\0"
	s ^TKSOLDES("86093")="\0.5\0"
	s ^TKSOLDES("86094")="\0.5\0"
	s ^TKSOLDES("86107")="\0.5\0"
	s ^TKSOLDES("86110")="\0.5\0"
	s ^TKSOLDES("65072")="\0.5\0"
	s ^TKSOLDES("65074")="\0.5\0"
	s ^TKSOLDES("65848")="\0.5\0"
	s ^TKSOLDES("65076")="\0.5\0"
	s ^TKSOLDES("65077")="\0.5\0"
	s ^TKSOLDES("86108")="\0.5\0"
	s ^TKSOLDES("86106")="\0.5\0"
	s ^TKSOLDES("86095")="\0.5\0"
	s ^TKSOLDES("86099")="\0.5\0"
	s ^TKSOLDES("86096")="\0.5\0"
	s ^TKSOLDES("86097")="\0.5\0"
	s ^TKSOLDES("86100")="\0.5\0"
	s ^TKSOLDES("86104")="\0.5\0"
	s ^TKSOLDES("86101")="\0.5\0"
	s ^TKSOLDES("86102")="\0.5\0"
	s ^TKSOLDES("86103")="\0.5\0"
	s ^TKSOLDES("86072")="\0.5\0"
	s ^TKSOLDES("86071")="\0.5\0"
	s ^TKSOLDES("86048")="\0.5\0"
	s ^TKSOLDES("67601")="\0.5\0"
	s ^TKSOLDES("67600")="\0.5\0"
	s ^TKSOLDES("67599")="\0.5\0"
	s ^TKSOLDES("67598")="\0.5\0"
	s ^TKSOLDES("86045")="\0.5\0"
	s ^TKSOLDES("86046")="\0.5\0"
	s ^TKSOLDES("67635")="\0.5\0"
	s ^TKSOLDES("67636")="\0.5\0"
	s ^TKSOLDES("86044")="\0.5\0"
	s ^TKSOLDES("86042")="\0.5\0"
	s ^TKSOLDES("86043")="\0.5\0"
	s ^TKSOLDES("67641")="\0.5\0"
	s ^TKSOLDES("67637")="\0.5\0"
	s ^TKSOLDES("67640")="\0.5\0"
	s ^TKSOLDES("67639")="\0.5\0"
	s ^TKSOLDES("67638")="\0.5\0"
	s ^TKSOLDES("86047")="\0.5\0"
	s ^TKSOLDES("86049")="\0.5\0"
	s ^TKSOLDES("86070")="\0.5\0"
	s ^TKSOLDES("86060")="\0.5\0"
	s ^TKSOLDES("86062")="\0.5\0"
	s ^TKSOLDES("86063")="\0.5\0"
	s ^TKSOLDES("86065")="\0.5\0"
	s ^TKSOLDES("86067")="\0.5\0"
	s ^TKSOLDES("86068")="\0.5\0"
	s ^TKSOLDES("86069")="\0.5\0"
	s ^TKSOLDES("86061")="\0.5\0"
	s ^TKSOLDES("86059")="\0.5\0"
	s ^TKSOLDES("86050")="\0.5\0"
	s ^TKSOLDES("86053")="\0.5\0"
	s ^TKSOLDES("86051")="\0.5\0"
	s ^TKSOLDES("86052")="\0.5\0"
	s ^TKSOLDES("86054")="\0.5\0"
	s ^TKSOLDES("86058")="\0.5\0"
	s ^TKSOLDES("86055")="\0.5\0"
	s ^TKSOLDES("86056")="\0.5\0"
	s ^TKSOLDES("86057")="\0.5\0"
	s ^TKSOLDES("65078")="\0.5\0"
	s ^TKSOLDES("65082")="\0.5\0"
	s ^TKSOLDES("86040")="\0.5\0"
	s ^TKSOLDES("65096")="\0.5\0"
	s ^TKSOLDES("65109")="\0.5\0"
	s ^TKSOLDES("65110")="\0.5\0"
	s ^TKSOLDES("65111")="\0.5\0"
	s ^TKSOLDES("65112")="\0.5\0"
	s ^TKSOLDES("65113")="\0.5\0"
	s ^TKSOLDES("65114")="\0.5\0"
	s ^TKSOLDES("65108")="\0.5\0"
	s ^TKSOLDES("65107")="\0.5\0"
	s ^TKSOLDES("65101")="\0.5\0"
	s ^TKSOLDES("65098")="\0.5\0"
	s ^TKSOLDES("65099")="\0.5\0"
	s ^TKSOLDES("65103")="\0.5\0"
	s ^TKSOLDES("65239")="\0.5\0"
	s ^TKSOLDES("65104")="\0.5\0"
	s ^TKSOLDES("65105")="\0.5\0"
	s ^TKSOLDES("65106")="\0.5\0"
	s ^TKSOLDES("65115")="\0.5\0"
	s ^TKSOLDES("65116")="\0.5\0"
	s ^TKSOLDES("65127")="\0.5\0"
	s ^TKSOLDES("65238")="\0.5\0"
	s ^TKSOLDES("65237")="\0.5\0"
	s ^TKSOLDES("65236")="\0.5\0"
	s ^TKSOLDES("65235")="\0.5\0"
	s ^TKSOLDES("65233")="\0.5\0"
	s ^TKSOLDES("65129")="\0.5\0"
	s ^TKSOLDES("65128")="\0.5\0"
	s ^TKSOLDES("65126")="\0.5\0"
	s ^TKSOLDES("65117")="\0.5\0"
	s ^TKSOLDES("65120")="\0.5\0"
	s ^TKSOLDES("65118")="\0.5\0"
	s ^TKSOLDES("65119")="\0.5\0"
	s ^TKSOLDES("65121")="\0.5\0"
	s ^TKSOLDES("65125")="\0.5\0"
	s ^TKSOLDES("65122")="\0.5\0"
	s ^TKSOLDES("65123")="\0.5\0"
	s ^TKSOLDES("65124")="\0.5\0"
	s ^TKSOLDES("65097")="\0.5\0"
	s ^TKSOLDES("65095")="\0.5\0"
	s ^TKSOLDES("65083")="\0.5\0"
	s ^TKSOLDES("65267")="\0.5\0"
	s ^TKSOLDES("65838")="\0.5\0"
	s ^TKSOLDES("65837")="\0.5\0"
	s ^TKSOLDES("65091")="\0.5\0"
	s ^TKSOLDES("65794")="\0.5\0"
	s ^TKSOLDES("65270")="\0.5\0"
	s ^TKSOLDES("65269")="\0.5\0"
	s ^TKSOLDES("65839")="\0.5\0"
	s ^TKSOLDES("65840")="\0.5\0"
	s ^TKSOLDES("65088")="\0.5\0"
	s ^TKSOLDES("65084")="\0.5\0"
	s ^TKSOLDES("65086")="\0.5\0"
	s ^TKSOLDES("65089")="\0.5\0"
	s ^TKSOLDES("65841")="\0.5\0"
	s ^TKSOLDES("65090")="\0.5\0"
	s ^TKSOLDES("65843")="\0.5\0"
	s ^TKSOLDES("65842")="\0.5\0"
	s ^TKSOLDES("65268")="\0.5\0"
	s ^TKSOLDES("65266")="\0.5\0"
	s ^TKSOLDES("65094")="\0.5\0"
	s ^TKSOLDES("65245")="\0.5\0"
	s ^TKSOLDES("65243")="\0.5\0"
	s ^TKSOLDES("65242")="\0.5\0"
	s ^TKSOLDES("65241")="\0.5\0"
	s ^TKSOLDES("65240")="\0.5\0"
	s ^TKSOLDES("65092")="\0.5\0"
	s ^TKSOLDES("65093")="\0.5\0"
	s ^TKSOLDES("65244")="\0.5\0"
	s ^TKSOLDES("65246")="\0.5\0"
	s ^TKSOLDES("65265")="\0.5\0"
	s ^TKSOLDES("65252")="\0.5\0"
	s ^TKSOLDES("65264")="\0.5\0"
	s ^TKSOLDES("65263")="\0.5\0"
	s ^TKSOLDES("65251")="\0.5\0"
	s ^TKSOLDES("65247")="\0.5\0"
	s ^TKSOLDES("65250")="\0.5\0"
	s ^TKSOLDES("65249")="\0.5\0"
	s ^TKSOLDES("65248")="\0.5\0"
	s ^TKSOLDES("86041")="\0.5\0"
	s ^TKSOLDES("86066")="\0.5\0"
	s ^TKSOLDES("86039")="\0.5\0"
	s ^TKSOLDES("80361")="\0.5\0"
	s ^TKSOLDES("80357")="\0.5\0"
	s ^TKSOLDES("80358")="\0.5\0"
	s ^TKSOLDES("80359")="\0.5\0"
	s ^TKSOLDES("80360")="\0.5\0"
	s ^TKSOLDES("65053")="\0.5\0"
	s ^TKSOLDES("80349")="\0.5\0"
	s ^TKSOLDES("80362")="\0.5\0"
	s ^TKSOLDES("65052")="\0.5\0"
	s ^TKSOLDES("80363")="\0.5\0"
	s ^TKSOLDES("65051")="\0.5\0"
	s ^TKSOLDES("80364")="\0.5\0"
	s ^TKSOLDES("80408")="\0.5\0"
	s ^TKSOLDES("65054")="\0.5\0"
	s ^TKSOLDES("65067")="\0.5\0"
	s ^TKSOLDES("80410")="\0.5\0"
	s ^TKSOLDES("65034")="\0.5\0"
	s ^TKSOLDES("80409")="\0.5\0"
	s ^TKSOLDES("80350")="\0.5\0"
	s ^TKSOLDES("80351")="\0.5\0"
	s ^TKSOLDES("80352")="\0.5\0"
	s ^TKSOLDES("65069")="\0.5\0"
	s ^TKSOLDES("65035")="\0.5\0"
	s ^TKSOLDES("80353")="\0.5\0"
	s ^TKSOLDES("80354")="\0.5\0"
	s ^TKSOLDES("80355")="\0.5\0"
	s ^TKSOLDES("80356")="\0.5\0"
	s ^TKSOLDES("65050")="\0.5\0"
	s ^TKSOLDES("80365")="\0.5\0"
	s ^TKSOLDES("80401")="\0.5\0"
	s ^TKSOLDES("65038")="\0.5\0"
	s ^TKSOLDES("65039")="\0.5\0"
	s ^TKSOLDES("80393")="\0.5\0"
	s ^TKSOLDES("80400")="\0.5\0"
	s ^TKSOLDES("80402")="\0.5\0"
	s ^TKSOLDES("65036")="\0.5\0"
	s ^TKSOLDES("80403")="\0.5\0"
	s ^TKSOLDES("80404")="\0.5\0"
	s ^TKSOLDES("80405")="\0.5\0"
	s ^TKSOLDES("80406")="\0.5\0"
	s ^TKSOLDES("80407")="\0.5\0"
	s ^TKSOLDES("65037")="\0.5\0"
	s ^TKSOLDES("65040")="\0.5\0"
	s ^TKSOLDES("80366")="\0.5\0"
	s ^TKSOLDES("85666")="\0.5\0"
	s ^TKSOLDES("80367")="\0.5\0"
	s ^TKSOLDES("80368")="\0.5\0"
	s ^TKSOLDES("80369")="\0.5\0"
	s ^TKSOLDES("80371")="\0.5\0"
	s ^TKSOLDES("65049")="\0.5\0"
	s ^TKSOLDES("80378")="\0.5\0"
	s ^TKSOLDES("80382")="\0.5\0"
	s ^TKSOLDES("80383")="\0.5\0"
	s ^TKSOLDES("80384")="\0.5\0"
	s ^TKSOLDES("80385")="\0.5\0"
	s ^TKSOLDES("80390")="\0.5\0"
	s ^TKSOLDES("80391")="\0.5\0"
	s ^TKSOLDES("80411")="\0.5\0"
	s ^TKSOLDES("65068")="\0.5\0"
	s ^TKSOLDES("80348")="\0.5\0"
	s ^TKSOLDES("80334")="\0.5\0"
	s ^TKSOLDES("67959")="\0.5\0"
	s ^TKSOLDES("67960")="\0.5\0"
	s ^TKSOLDES("80340")="\0.5\0"
	s ^TKSOLDES("80333")="\0.5\0"
	s ^TKSOLDES("85661")="\0.5\0"
	s ^TKSOLDES("64892")="\0.5\0"
	s ^TKSOLDES("64893")="\0.5\0"
	s ^TKSOLDES("64899")="\0.5\0"
	s ^TKSOLDES("85653")="\0.5\0"
	s ^TKSOLDES("67958")="\0.5\0"
	s ^TKSOLDES("67957")="\0.5\0"
	s ^TKSOLDES("67956")="\0.5\0"
	s ^TKSOLDES("80337")="\0.5\0"
	s ^TKSOLDES("80335")="\0.5\0"
	s ^TKSOLDES("85652")="\0.5\0"
	s ^TKSOLDES("80338")="\0.5\0"
	s ^TKSOLDES("80339")="\0.5\0"
	s ^TKSOLDES("67951")="\0.5\0"
	s ^TKSOLDES("67952")="\0.5\0"
	s ^TKSOLDES("67953")="\0.5\0"
	s ^TKSOLDES("67954")="\0.5\0"
	s ^TKSOLDES("67955")="\0.5\0"
	s ^TKSOLDES("85660")="\0.5\0"
	s ^TKSOLDES("85651")="\0.5\0"
	s ^TKSOLDES("80347")="\0.5\0"
	s ^TKSOLDES("85630")="\0.5\0"
	s ^TKSOLDES("65028")="\0.5\0"
	s ^TKSOLDES("80341")="\0.5\0"
	s ^TKSOLDES("80342")="\0.5\0"
	s ^TKSOLDES("80343")="\0.5\0"
	s ^TKSOLDES("80344")="\0.5\0"
	s ^TKSOLDES("80345")="\0.5\0"
	s ^TKSOLDES("80346")="\0.5\0"
	s ^TKSOLDES("65029")="\0.5\0"
	s ^TKSOLDES("85665")="\0.5\0"
	s ^TKSOLDES("80336")="\0.5\0"
	s ^TKSOLDES("85664")="\0.5\0"
	s ^TKSOLDES("64903")="\0.5\0"
	s ^TKSOLDES("65019")="\0.5\0"
	s ^TKSOLDES("85662")="\0.5\0"
	s ^TKSOLDES("85663")="\0.5\0"
	s ^TKSOLDES("65020")="\0.5\0"
	s ^TKSOLDES("80332")="\0.5\0"
	s ^TKSOLDES("83663")="\0.5\0"
	s ^TKSOLDES("103087")="\0.5\0"
	s ^TKSOLDES("103086")="\0.5\0"
	s ^TKSOLDES("41309")="\0.5\0"
	s ^TKSOLDES("76167")="\0.5\0"
	s ^TKSOLDES("83665")="\0.5\0"
	s ^TKSOLDES("103085")="\0.5\0"
	s ^TKSOLDES("83609")="\0.5\0"
	s ^TKSOLDES("83590")="\0.5\0"
	s ^TKSOLDES("101195")="\0.5\0"
	s ^TKSOLDES("83567")="\0.5\0"
	s ^TKSOLDES("101191")="\0.5\0"
	s ^TKSOLDES("83568")="\0.5\0"
	s ^TKSOLDES("83569")="\0.5\0"
	s ^TKSOLDES("83591")="\0.5\0"
	s ^TKSOLDES("103084")="\0.5\0"
	s ^TKSOLDES("83592")="\0.5\0"
	s ^TKSOLDES("78934")="\0.5\0"
	s ^TKSOLDES("41310")="\0.5\0"
	s ^TKSOLDES("83593")="\0.5\0"
	s ^TKSOLDES("41085")="\0.5\0"
	s ^TKSOLDES("83610")="\0.5\0"
	s ^TKSOLDES("103088")="\0.5\0"
	s ^TKSOLDES("79162")="\0.5\0"
	s ^TKSOLDES("103089")="\0.5\0"
	s ^TKSOLDES("103090")="\0.5\0"
	s ^TKSOLDES("103228")="\0.5\0"
	s ^TKSOLDES("100470")="\0.5\0"
	s ^TKSOLDES("101200")="\0.5\0"
	s ^TKSOLDES("100465")="\0.5\0"
	s ^TKSOLDES("76174")="\0.5\0"
	s ^TKSOLDES("78936")="\0.5\0"
	s ^TKSOLDES("78937")="\0.5\0"
	s ^TKSOLDES("78938")="\0.5\0"
	s ^TKSOLDES("62509")="\0.5\0"
	s ^TKSOLDES("78940")="\0.5\0"
	s ^TKSOLDES("76187")="\0.5\0"
	s ^TKSOLDES("76185")="\0.5\0"
	s ^TKSOLDES("76183")="\0.5\0"
	s ^TKSOLDES("103198")="\0.5\0"
	s ^TKSOLDES("79159")="\0.5\0"
	s ^TKSOLDES("103096")="\0.5\0"
	s ^TKSOLDES("103091")="\0.5\0"
	s ^TKSOLDES("103092")="\0.5\0"
	s ^TKSOLDES("103093")="\0.5\0"
	s ^TKSOLDES("103094")="\0.5\0"
	s ^TKSOLDES("41082")="\0.5\0"
	s ^TKSOLDES("103095")="\0.5\0"
	s ^TKSOLDES("41081")="\0.5\0"
	s ^TKSOLDES("79161")="\0.5\0"
	s ^TKSOLDES("83666")="\0.5\0"
	s ^TKSOLDES("78935")="\0.5\0"
	s ^TKSOLDES("40961")="\0.5\0"
	s ^TKSOLDES("40967")="\0.5\0"
	s ^TKSOLDES("41078")="\0.5\0"
	s ^TKSOLDES("79163")="\0.5\0"
	s ^TKSOLDES("76173")="\0.5\0"
	s ^TKSOLDES("101196")="\0.5\0"
	s ^TKSOLDES("75993")="\0.5\0"
	s ^TKSOLDES("101207")="\0.5\0"
	s ^TKSOLDES("82461")="\0.5\0"
	s ^TKSOLDES("82292")="\0.5\0"
	s ^TKSOLDES("82293")="\0.5\0"
	s ^TKSOLDES("82294")="\0.5\0"
	s ^TKSOLDES("82297")="\0.5\0"
	s ^TKSOLDES("82299")="\0.5\0"
	s ^TKSOLDES("82300")="\0.5\0"
	s ^TKSOLDES("82290")="\0.5\0"
	s ^TKSOLDES("82289")="\0.5\0"
	s ^TKSOLDES("82457")="\0.5\0"
	s ^TKSOLDES("82459")="\0.5\0"
	s ^TKSOLDES("82458")="\0.5\0"
	s ^TKSOLDES("82266")="\0.5\0"
	s ^TKSOLDES("82288")="\0.5\0"
	s ^TKSOLDES("82267")="\0.5\0"
	s ^TKSOLDES("82268")="\0.5\0"
	s ^TKSOLDES("82287")="\0.5\0"
	s ^TKSOLDES("82456")="\0.5\0"
	s ^TKSOLDES("82453")="\0.5\0"
	s ^TKSOLDES("82314")="\0.5\0"
	s ^TKSOLDES("82307")="\0.5\0"
	s ^TKSOLDES("82308")="\0.5\0"
	s ^TKSOLDES("82309")="\0.5\0"
	s ^TKSOLDES("82310")="\0.5\0"
	s ^TKSOLDES("82312")="\0.5\0"
	s ^TKSOLDES("82311")="\0.5\0"
	s ^TKSOLDES("82313")="\0.5\0"
	s ^TKSOLDES("82306")="\0.5\0"
	s ^TKSOLDES("82448")="\0.5\0"
	s ^TKSOLDES("82302")="\0.5\0"
	s ^TKSOLDES("82438")="\0.5\0"
	s ^TKSOLDES("82301")="\0.5\0"
	s ^TKSOLDES("82303")="\0.5\0"
	s ^TKSOLDES("82315")="\0.5\0"
	s ^TKSOLDES("82304")="\0.5\0"
	s ^TKSOLDES("81045")="\0.5\0"
	s ^TKSOLDES("82305")="\0.5\0"
	s ^TKSOLDES("82460")="\0.5\0"
	s ^TKSOLDES("82510")="\0.5\0"
	s ^TKSOLDES("101208")="\0.5\0"
	s ^TKSOLDES("86511")="\0.5\0"
	s ^TKSOLDES("102294")="\0.5\0"
	s ^TKSOLDES("103293")="\0.5\0"
	s ^TKSOLDES("103294")="\0.5\0"
	s ^TKSOLDES("86517")="\0.5\0"
	s ^TKSOLDES("86515")="\0.5\0"
	s ^TKSOLDES("101459")="\0.5\0"
	s ^TKSOLDES("101455")="\0.5\0"
	s ^TKSOLDES("101448")="\0.5\0"
	s ^TKSOLDES("101209")="\0.5\0"
	s ^TKSOLDES("101447")="\0.5\0"
	s ^TKSOLDES("103083")="\0.5\0"
	s ^TKSOLDES("101454")="\0.5\0"
	s ^TKSOLDES("101451")="\0.5\0"
	s ^TKSOLDES("101452")="\0.5\0"
	s ^TKSOLDES("101453")="\0.5\0"
	s ^TKSOLDES("86512")="\0.5\0"
	s ^TKSOLDES("8415")="\0.5\0"
	s ^TKSOLDES("82511")="\0.5\0"
	s ^TKSOLDES("75998")="\0.5\0"
	s ^TKSOLDES("75988")="\0.5\0"
	s ^TKSOLDES("75978")="\0.5\0"
	s ^TKSOLDES("75968")="\0.5\0"
	s ^TKSOLDES("75952")="\0.5\0"
	s ^TKSOLDES("75946")="\0.5\0"
	s ^TKSOLDES("75755")="\0.5\0"
	s ^TKSOLDES("75994")="\0.5\0"
	s ^TKSOLDES("76000")="\0.5\0"
	s ^TKSOLDES("8439")="\0.5\0"
	s ^TKSOLDES("8653")="\0.5\0"
	s ^TKSOLDES("8441")="\0.5\0"
	s ^TKSOLDES("8650")="\0.5\0"
	s ^TKSOLDES("102292")="\0.5\0"
	s ^TKSOLDES("76005")="\0.5\0"
	s ^TKSOLDES("102289")="\0.5\0"
	s ^TKSOLDES("9271")="\0.5\0"
	s ^TKSOLDES("9272")="\0.5\0"
	s ^TKSOLDES("81046")="\0.5\0"
	s ^TKSOLDES("78806")="\0.5\0"
	s ^TKSOLDES("78540")="\0.5\0"
	s ^TKSOLDES("78547")="\0.5\0"
	s ^TKSOLDES("78543")="\0.5\0"
	s ^TKSOLDES("78542")="\0.5\0"
	s ^TKSOLDES("78541")="\0.5\0"
	s ^TKSOLDES("78539")="\0.5\0"
	s ^TKSOLDES("78549")="\0.5\0"
	s ^TKSOLDES("78538")="\0.5\0"
	s ^TKSOLDES("44302")="\0.5\0"
	s ^TKSOLDES("80065")="\0.5\0"
	s ^TKSOLDES("87165")="\0.5\0"
	s ^TKSOLDES("87164")="\0.5\0"
	s ^TKSOLDES("78548")="\0.5\0"
	s ^TKSOLDES("78550")="\0.5\0"
	s ^TKSOLDES("78732")="\0.5\0"
	s ^TKSOLDES("78552")="\0.5\0"
	s ^TKSOLDES("67418")="\0.5\0"
	s ^TKSOLDES("87848")="\0.5\0"
	s ^TKSOLDES("103082")="\0.5\0"
	s ^TKSOLDES("87317")="\0.5\0"
	s ^TKSOLDES("78421")="\0.5\0"
	s ^TKSOLDES("78586")="\0.5\0"
	s ^TKSOLDES("78585")="\0.5\0"
	s ^TKSOLDES("86166")="\0.5\0"
	s ^TKSOLDES("86167")="\0.5\0"
	s ^TKSOLDES("78429")="\0.5\0"
	s ^TKSOLDES("78430")="\0.5\0"
	s ^TKSOLDES("78432")="\0.5\0"
	s ^TKSOLDES("73124")="\0.5\0"
	s ^TKSOLDES("73125")="\0.5\0"
	s ^TKSOLDES("73127")="\0.5\0"
	s ^TKSOLDES("80078")="\0.5\0"
	s ^TKSOLDES("80079")="\0.5\0"
	s ^TKSOLDES("80080")="\0.5\0"
	s ^TKSOLDES("86998")="\0.5\0"
	s ^TKSOLDES("86997")="\0.5\0"
	s ^TKSOLDES("86996")="\0.5\0"
	s ^TKSOLDES("78718")="\0.5\0"
	s ^TKSOLDES("78720")="\0.5\0"
	s ^TKSOLDES("78721")="\0.5\0"
	s ^TKSOLDES("78722")="\0.5\0"
	s ^TKSOLDES("78728")="\0.5\0"
	s ^TKSOLDES("78730")="\0.5\0"
	s ^TKSOLDES("80077")="\0.5\0"
	s ^TKSOLDES("80066")="\0.5\0"
	s ^TKSOLDES("87155")="\0.5\0"
	s ^TKSOLDES("73128")="\0.5\0"
	s ^TKSOLDES("73129")="\0.5\0"
	s ^TKSOLDES("73130")="\0.5\0"
	s ^TKSOLDES("87157")="\0.5\0"
	s ^TKSOLDES("87156")="\0.5\0"
	s ^TKSOLDES("87153")="\0.5\0"
	s ^TKSOLDES("87141")="\0.5\0"
	s ^TKSOLDES("87151")="\0.5\0"
	s ^TKSOLDES("87150")="\0.5\0"
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 