ROUTINE OPESOLDES50PE13P10
OPESOLDES50PE13P10
 
 s ^TKSOLDES("103352")="\0.5\0"
 s ^TKSOLDES("103353")="\0.5\0"
 s ^TKSOLDES("103354")="\0.5\0"
 s ^TKSOLDES("104320")="\0.5\0"
 s ^TKSOLDES("104321")="\0.5\0"
 s ^TKSOLDES("104322")="\0.5\0"
 s ^TKSOLDES("104323")="\0.5\0"
 s ^TKSOLDES("104326")="\0.5\0"
 s ^TKSOLDES("104327")="\0.5\0"
 s ^TKSOLDES("77763")="\0.5\0"
 s ^TKSOLDES("103336")="\0.5\0"
 s ^TKSOLDES("87647")="\0.5\0"
 s ^TKSOLDES("87650")="\0.5\0"
 s ^TKSOLDES("103366")="\0.5\0"
 s ^TKSOLDES("103367")="\0.5\0"
 s ^TKSOLDES("103368")="\0.5\0"
 s ^TKSOLDES("103369")="\0.5\0"
 s ^TKSOLDES("86290")="\0.5\0"
 s ^TKSOLDES("86292")="\0.5\0"
 s ^TKSOLDES("86294")="\0.5\0"
 s ^TKSOLDES("86295")="\0.5\0"
 s ^TKSOLDES("87763")="\0.5\0"
 s ^TKSOLDES("87764")="\0.5\0"
 s ^TKSOLDES("87765")="\0.5\0"
 s ^TKSOLDES("89919")="\0.5\0"
 s ^TKSOLDES("105401")="\0.5\0"
 s ^TKSOLDES("105402")="\0.5\0"
 s ^TKSOLDES("105403")="\0.5\0"
 s ^TKSOLDES("104365")="\0.5\0"
 s ^TKSOLDES("104366")="\0.5\0"
 s ^TKSOLDES("104557")="\0.5\0"
 s ^TKSOLDES("104558")="\0.5\0"
 s ^TKSOLDES("104559")="\0.5\0"
 s ^TKSOLDES("104560")="\0.5\0"
 s ^TKSOLDES("105066")="\0.5\0"
 s ^TKSOLDES("105067")="\0.5\0"
 s ^TKSOLDES("105070")="\0.5\0"
 s ^TKSOLDES("105104")="\0.5\0"
 s ^TKSOLDES("105105")="\0.5\0"
 s ^TKSOLDES("105607")="\0.5\0"
 s ^TKSOLDES("105608")="\0.5\0"
 s ^TKSOLDES("105609")="\0.5\0"
 s ^TKSOLDES("105610")="\0.5\0"
 s ^TKSOLDES("105078")="\0.5\0"
 s ^TKSOLDES("105079")="\0.5\0"
 s ^TKSOLDES("105080")="\0.5\0"
 s ^TKSOLDES("105086")="\0.5\0"
 s ^TKSOLDES("105595")="\0.5\0"
 s ^TKSOLDES("105596")="\0.5\0"
 s ^TKSOLDES("105598")="\0.5\0"
 s ^TKSOLDES("89916")="\0.5\0"
 s ^TKSOLDES("89920")="\0.5\0"
 s ^TKSOLDES("104324")="\0.5\0"
 s ^TKSOLDES("104325")="\0.5\0"
 s ^TKSOLDES("104370")="\0.5\0"
 s ^TKSOLDES("105087")="\0.5\0"
 s ^TKSOLDES("104328")="\0.5\0"
 s ^TKSOLDES("105097")="\0.5\0"
 s ^TKSOLDES("105101")="\0.5\0"
 s ^TKSOLDES("105606")="\0.5\0"
 s ^TKSOLDES("105611")="\0.5\0"
 s ^TKSOLDES("101940")="\0.5\0"
 s ^TKSOLDES("104341")="\0.5\0"
 s ^TKSOLDES("104342")="\0.5\0"
 s ^TKSOLDES("104343")="\0.5\0"
 s ^TKSOLDES("104344")="\0.5\0"
 s ^TKSOLDES("104345")="\0.5\0"
 s ^TKSOLDES("104346")="\0.5\0"
 s ^TKSOLDES("104554")="\0.5\0"
 s ^TKSOLDES("104555")="\0.5\0"
 s ^TKSOLDES("104556")="\0.5\0"
 s ^TKSOLDES("104361")="\0.5\0"
 s ^TKSOLDES("104362")="\0.5\0"
 s ^TKSOLDES("104363")="\0.5\0"
 s ^TKSOLDES("104377")="\0.5\0"
 s ^TKSOLDES("104405")="\0.5\0"
 s ^TKSOLDES("104409")="\0.5\0"
 s ^TKSOLDES("104387")="\0.5\0"
 s ^TKSOLDES("104388")="\0.5\0"
 s ^TKSOLDES("104389")="\0.5\0"
 s ^TKSOLDES("104390")="\0.5\0"
 s ^TKSOLDES("104383")="\0.5\0"
 s ^TKSOLDES("104384")="\0.5\0"
 s ^TKSOLDES("104385")="\0.5\0"
 s ^TKSOLDES("104386")="\0.5\0"
 s ^TKSOLDES("104398")="\0.5\0"
 s ^TKSOLDES("104432")="\0.5\0"
 s ^TKSOLDES("104433")="\0.5\0"
 s ^TKSOLDES("104434")="\0.5\0"
 s ^TKSOLDES("104478")="\0.5\0"
 s ^TKSOLDES("104479")="\0.5\0"
 s ^TKSOLDES("104480")="\0.5\0"
 s ^TKSOLDES("104482")="\0.5\0"
 s ^TKSOLDES("104477")="\0.5\0"
 s ^TKSOLDES("104189")="\0.5\0"
 s ^TKSOLDES("104393")="\0.5\0"
 s ^TKSOLDES("104561")="\0.5\0"
 s ^TKSOLDES("104568")="\0.5\0"
 s ^TKSOLDES("104575")="\0.5\0"
 s ^TKSOLDES("104396")="\0.5\0"
 s ^TKSOLDES("104397")="\0.5\0"
 s ^TKSOLDES("104421")="\0.5\0"
 s ^TKSOLDES("104422")="\0.5\0"
 s ^TKSOLDES("104420")="\0.5\0"
 s ^TKSOLDES("104348")="\0.5\0"
 s ^TKSOLDES("104350")="\0.5\0"
 s ^TKSOLDES("104364")="\0.5\0"
 s ^TKSOLDES("104410")="\0.5\0"
 s ^TKSOLDES("104411")="\0.5\0"
 s ^TKSOLDES("104476")="\0.5\0"
 s ^TKSOLDES("104429")="\0.5\0"
 s ^TKSOLDES("104430")="\0.5\0"
 s ^TKSOLDES("104431")="\0.5\0"
 s ^TKSOLDES("105075")="\0.5\0"
 s ^TKSOLDES("105076")="\0.5\0"
 s ^TKSOLDES("103348")="\0.5\0"
 s ^TKSOLDES("103349")="\0.5\0"
 s ^TKSOLDES("103350")="\0.5\0"
 s ^TKSOLDES("103351")="\0.5\0"
 s ^TKSOLDES("104349")="\0.5\0"
 s ^TKSOLDES("104354")="\0.5\0"
 s ^TKSOLDES("104357")="\0.5\0"
 s ^TKSOLDES("104358")="\0.5\0"
 s ^TKSOLDES("104367")="\0.5\0"
 s ^TKSOLDES("104372")="\0.5\0"
 s ^TKSOLDES("104458")="\0.5\0"
 s ^TKSOLDES("104459")="\0.5\0"
 s ^TKSOLDES("104460")="\0.5\0"
 s ^TKSOLDES("104403")="\0.5\0"
 s ^TKSOLDES("104404")="\0.5\0"
 s ^TKSOLDES("104412")="\0.5\0"
 s ^TKSOLDES("104414")="\0.5\0"
 s ^TKSOLDES("104415")="\0.5\0"
 s ^TKSOLDES("104569")="\0.5\0"
 s ^TKSOLDES("104572")="\0.5\0"
 s ^TKSOLDES("104573")="\0.5\0"
 s ^TKSOLDES("104574")="\0.5\0"
 s ^TKSOLDES("104582")="\0.5\0"
 s ^TKSOLDES("104584")="\0.5\0"
 s ^TKSOLDES("104438")="\0.5\0"
 s ^TKSOLDES("105601")="\0.5\0"
 s ^TKSOLDES("105602")="\0.5\0"
 s ^TKSOLDES("105617")="\0.5\0"
 s ^TKSOLDES("105618")="\0.5\0"
 s ^TKSOLDES("105619")="\0.5\0"
 s ^TKSOLDES("105620")="\0.5\0"
 s ^TKSOLDES("100087")="\0.5\0"
 s ^TKSOLDES("104391")="\0.5\0"
 s ^TKSOLDES("104392")="\0.5\0"
 s ^TKSOLDES("104360")="\0.5\0"
 s ^TKSOLDES("104424")="\0.5\0"
 s ^TKSOLDES("104427")="\0.5\0"
 s ^TKSOLDES("104428")="\0.5\0"
 s ^TKSOLDES("105444")="\0.5\0"
 s ^TKSOLDES("105446")="\0.5\0"
 s ^TKSOLDES("105447")="\0.5\0"
 s ^TKSOLDES("105449")="\0.5\0"
 s ^TKSOLDES("105151")="\0.5\0"
 s ^TKSOLDES("105152")="\0.5\0"
 s ^TKSOLDES("105150")="\0.5\0"
 s ^TKSOLDES("105467")="\0.5\0"
 s ^TKSOLDES("105468")="\0.5\0"
 s ^TKSOLDES("105469")="\0.5\0"
 s ^TKSOLDES("105466")="\0.5\0"
 s ^TKSOLDES("105465")="\0.5\0"
 s ^TKSOLDES("105156")="\0.5\0"
 s ^TKSOLDES("105157")="\0.5\0"
 s ^TKSOLDES("105153")="\0.5\0"
 s ^TKSOLDES("105474")="\0.5\0"
 s ^TKSOLDES("105473")="\0.5\0"
 s ^TKSOLDES("105475")="\0.5\0"
 s ^TKSOLDES("105160")="\0.5\0"
 s ^TKSOLDES("105161")="\0.5\0"
 s ^TKSOLDES("105149")="\0.5\0"
 s ^TKSOLDES("105481")="\0.5\0"
 s ^TKSOLDES("105472")="\0.5\0"
 s ^TKSOLDES("105470")="\0.5\0"
 s ^TKSOLDES("105471")="\0.5\0"
 s ^TKSOLDES("105483")="\0.5\0"
 s ^TKSOLDES("105482")="\0.5\0"
 s ^TKSOLDES("105485")="\0.5\0"
 s ^TKSOLDES("105484")="\0.5\0"
 s ^TKSOLDES("105480")="\0.5\0"
 s ^TKSOLDES("105479")="\0.5\0"
 s ^TKSOLDES("105476")="\0.5\0"
 s ^TKSOLDES("105478")="\0.5\0"
 s ^TKSOLDES("105477")="\0.5\0"
 s ^TKSOLDES("105155")="\0.5\0"
 s ^TKSOLDES("8475")="\0.5\0"
 s ^TKSOLDES("40953")="\0.5\0"
 s ^TKSOLDES("43881")="\0.5\0"
 s ^TKSOLDES("44012")="\0.5\0"
 s ^TKSOLDES("44303")="\0.5\0"
 s ^TKSOLDES("75947")="\0.5\0"
 s ^TKSOLDES("75951")="\0.5\0"
 s ^TKSOLDES("86990")="\0.5\0"
 s ^TKSOLDES("101188")="\0.5\0"
 s ^TKSOLDES("101189")="\0.5\0"
 s ^TKSOLDES("101190")="\0.5\0"
 s ^TKSOLDES("78799")="\0.5\0"
 s ^TKSOLDES("100463")="\0.5\0"
 s ^TKSOLDES("100467")="\0.5\0"
 s ^TKSOLDES("100469")="\0.5\0"
 s ^TKSOLDES("101456")="\0.5\0"
 s ^TKSOLDES("101457")="\0.5\0"
 s ^TKSOLDES("101458")="\0.5\0"
 s ^TKSOLDES("103079")="\0.5\0"
 s ^TKSOLDES("103097")="\0.5\0"
 s ^TKSOLDES("103199")="\0.5\0"
 s ^TKSOLDES("105259")="\0.5\0"
 s ^TKSOLDES("102401")="\0.5\0"
 s ^TKSOLDES("102402")="\0.5\0"
 s ^TKSOLDES("102403")="\0.5\0"
 s ^TKSOLDES("102405")="\0.5\0"
 s ^TKSOLDES("102550")="\0.5\0"
 s ^TKSOLDES("102551")="\0.5\0"
 s ^TKSOLDES("105136")="\0.5\0"
 s ^TKSOLDES("82580")="\0.5\0"
 s ^TKSOLDES("82010")="\0.5\0"
 s ^TKSOLDES("82632")="\0.5\0"
 s ^TKSOLDES("82576")="\0.5\0"
 s ^TKSOLDES("82588")="\0.5\0"
 s ^TKSOLDES("41645")="\0.5\0"
 s ^TKSOLDES("41646")="\0.5\0"
 s ^TKSOLDES("41809")="\0.5\0"
 s ^TKSOLDES("41810")="\0.5\0"
 s ^TKSOLDES("41811")="\0.5\0"
 s ^TKSOLDES("41812")="\0.5\0"
 s ^TKSOLDES("41813")="\0.5\0"
 s ^TKSOLDES("41814")="\0.5\0"
 s ^TKSOLDES("41815")="\0.5\0"
 s ^TKSOLDES("41816")="\0.5\0"
 s ^TKSOLDES("41817")="\0.5\0"
 s ^TKSOLDES("41818")="\0.5\0"
 s ^TKSOLDES("41819")="\0.5\0"
 s ^TKSOLDES("41820")="\0.5\0"
 s ^TKSOLDES("41821")="\0.5\0"
 s ^TKSOLDES("41822")="\0.5\0"
 s ^TKSOLDES("41823")="\0.5\0"
 s ^TKSOLDES("41824")="\0.5\0"
 s ^TKSOLDES("41825")="\0.5\0"
 s ^TKSOLDES("41826")="\0.5\0"
 s ^TKSOLDES("41827")="\0.5\0"
 s ^TKSOLDES("56110")="\0.5\0"
 s ^TKSOLDES("41828")="\0.5\0"
 s ^TKSOLDES("41829")="\0.5\0"
 s ^TKSOLDES("41830")="\0.5\0"
 s ^TKSOLDES("41831")="\0.5\0"
 s ^TKSOLDES("41832")="\0.5\0"
 s ^TKSOLDES("41833")="\0.5\0"
 s ^TKSOLDES("41834")="\0.5\0"
 s ^TKSOLDES("41835")="\0.5\0"
 s ^TKSOLDES("41836")="\0.5\0"
 s ^TKSOLDES("41837")="\0.5\0"
 s ^TKSOLDES("41838")="\0.5\0"
 s ^TKSOLDES("41839")="\0.5\0"
 s ^TKSOLDES("41840")="\0.5\0"
 s ^TKSOLDES("41841")="\0.5\0"
 s ^TKSOLDES("41842")="\0.5\0"
 s ^TKSOLDES("41843")="\0.5\0"
 s ^TKSOLDES("41844")="\0.5\0"
 s ^TKSOLDES("41845")="\0.5\0"
 s ^TKSOLDES("41846")="\0.5\0"
 s ^TKSOLDES("56111")="\0.5\0"
 s ^TKSOLDES("41858")="\0.5\0"
 s ^TKSOLDES("41859")="\0.5\0"
 s ^TKSOLDES("41860")="\0.5\0"
 s ^TKSOLDES("41861")="\0.5\0"
 s ^TKSOLDES("41862")="\0.5\0"
 s ^TKSOLDES("41863")="\0.5\0"
 s ^TKSOLDES("41864")="\0.5\0"
 s ^TKSOLDES("41865")="\0.5\0"
 s ^TKSOLDES("41866")="\0.5\0"
 s ^TKSOLDES("41867")="\0.5\0"
 s ^TKSOLDES("41868")="\0.5\0"
 s ^TKSOLDES("56112")="\0.5\0"
 s ^TKSOLDES("41920")="\0.5\0"
 s ^TKSOLDES("56114")="\0.5\0"
 s ^TKSOLDES("41803")="\0.5\0"
 s ^TKSOLDES("56115")="\0.5\0"
 s ^TKSOLDES("41804")="\0.5\0"
 s ^TKSOLDES("41805")="\0.5\0"
 s ^TKSOLDES("56116")="\0.5\0"
 s ^TKSOLDES("56117")="\0.5\0"
 s ^TKSOLDES("41806")="\0.5\0"
 s ^TKSOLDES("41807")="\0.5\0"
 s ^TKSOLDES("41808")="\0.5\0"
 s ^TKSOLDES("41847")="\0.5\0"
 s ^TKSOLDES("41848")="\0.5\0"
 s ^TKSOLDES("41849")="\0.5\0"
 s ^TKSOLDES("41850")="\0.5\0"
 s ^TKSOLDES("41851")="\0.5\0"
 s ^TKSOLDES("41852")="\0.5\0"
 s ^TKSOLDES("41853")="\0.5\0"
 s ^TKSOLDES("41854")="\0.5\0"
 s ^TKSOLDES("41855")="\0.5\0"
 s ^TKSOLDES("41856")="\0.5\0"
 s ^TKSOLDES("41857")="\0.5\0"
 s ^TKSOLDES("56118")="\0.5\0"
 s ^TKSOLDES("41869")="\0.5\0"
 s ^TKSOLDES("41870")="\0.5\0"
 s ^TKSOLDES("41871")="\0.5\0"
 s ^TKSOLDES("41872")="\0.5\0"
 s ^TKSOLDES("41873")="\0.5\0"
 s ^TKSOLDES("41874")="\0.5\0"
 s ^TKSOLDES("41875")="\0.5\0"
 s ^TKSOLDES("41876")="\0.5\0"
 s ^TKSOLDES("41877")="\0.5\0"
 s ^TKSOLDES("41878")="\0.5\0"
 s ^TKSOLDES("41879")="\0.5\0"
 s ^TKSOLDES("56119")="\0.5\0"
 s ^TKSOLDES("41916")="\0.5\0"
 s ^TKSOLDES("56120")="\0.5\0"
 s ^TKSOLDES("41915")="\0.5\0"
 s ^TKSOLDES("56121")="\0.5\0"
 s ^TKSOLDES("41913")="\0.5\0"
 s ^TKSOLDES("41914")="\0.5\0"
 s ^TKSOLDES("41902")="\0.5\0"
 s ^TKSOLDES("41903")="\0.5\0"
 s ^TKSOLDES("41904")="\0.5\0"
 s ^TKSOLDES("41905")="\0.5\0"
 s ^TKSOLDES("41906")="\0.5\0"
 s ^TKSOLDES("41907")="\0.5\0"
 s ^TKSOLDES("41908")="\0.5\0"
 s ^TKSOLDES("41909")="\0.5\0"
 s ^TKSOLDES("41910")="\0.5\0"
 s ^TKSOLDES("41911")="\0.5\0"
 s ^TKSOLDES("41912")="\0.5\0"
 s ^TKSOLDES("56122")="\0.5\0"
 s ^TKSOLDES("41890")="\0.5\0"
 s ^TKSOLDES("41891")="\0.5\0"
 s ^TKSOLDES("41892")="\0.5\0"
 s ^TKSOLDES("41893")="\0.5\0"
 s ^TKSOLDES("41894")="\0.5\0"
 s ^TKSOLDES("41895")="\0.5\0"
 s ^TKSOLDES("41896")="\0.5\0"
 s ^TKSOLDES("41897")="\0.5\0"
 s ^TKSOLDES("41898")="\0.5\0"
 s ^TKSOLDES("41899")="\0.5\0"
 s ^TKSOLDES("41900")="\0.5\0"
 s ^TKSOLDES("56123")="\0.5\0"
 s ^TKSOLDES("41901")="\0.5\0"
 s ^TKSOLDES("56124")="\0.5\0"
 s ^TKSOLDES("56125")="\0.5\0"
 s ^TKSOLDES("41759")="\0.5\0"
 s ^TKSOLDES("56126")="\0.5\0"
 s ^TKSOLDES("41760")="\0.5\0"
 s ^TKSOLDES("41761")="\0.5\0"
 s ^TKSOLDES("41762")="\0.5\0"
 s ^TKSOLDES("41763")="\0.5\0"
 s ^TKSOLDES("41764")="\0.5\0"
 s ^TKSOLDES("56127")="\0.5\0"
 s ^TKSOLDES("41765")="\0.5\0"
 s ^TKSOLDES("56128")="\0.5\0"
 s ^TKSOLDES("41766")="\0.5\0"
 s ^TKSOLDES("41767")="\0.5\0"
 s ^TKSOLDES("41768")="\0.5\0"
 s ^TKSOLDES("56129")="\0.5\0"
 s ^TKSOLDES("41769")="\0.5\0"
 s ^TKSOLDES("56130")="\0.5\0"
 s ^TKSOLDES("56131")="\0.5\0"
 s ^TKSOLDES("41770")="\0.5\0"
 s ^TKSOLDES("56132")="\0.5\0"
 s ^TKSOLDES("56133")="\0.5\0"
 s ^TKSOLDES("41771")="\0.5\0"
 s ^TKSOLDES("41772")="\0.5\0"
 s ^TKSOLDES("56134")="\0.5\0"
 s ^TKSOLDES("56135")="\0.5\0"
 s ^TKSOLDES("41773")="\0.5\0"
 s ^TKSOLDES("41774")="\0.5\0"
 s ^TKSOLDES("41775")="\0.5\0"
 s ^TKSOLDES("41776")="\0.5\0"
 s ^TKSOLDES("56136")="\0.5\0"
 s ^TKSOLDES("41777")="\0.5\0"
 s ^TKSOLDES("41778")="\0.5\0"
 s ^TKSOLDES("41779")="\0.5\0"
 s ^TKSOLDES("56137")="\0.5\0"
 s ^TKSOLDES("56138")="\0.5\0"
 s ^TKSOLDES("41780")="\0.5\0"
 s ^TKSOLDES("41781")="\0.5\0"
 s ^TKSOLDES("41782")="\0.5\0"
 s ^TKSOLDES("41783")="\0.5\0"
 s ^TKSOLDES("56139")="\0.5\0"
 s ^TKSOLDES("41784")="\0.5\0"
 s ^TKSOLDES("41785")="\0.5\0"
 s ^TKSOLDES("56140")="\0.5\0"
 s ^TKSOLDES("41786")="\0.5\0"
 s ^TKSOLDES("41787")="\0.5\0"
 s ^TKSOLDES("56141")="\0.5\0"
 s ^TKSOLDES("41788")="\0.5\0"
 s ^TKSOLDES("41789")="\0.5\0"
 s ^TKSOLDES("56142")="\0.5\0"
 s ^TKSOLDES("56143")="\0.5\0"
 s ^TKSOLDES("41790")="\0.5\0"
 s ^TKSOLDES("41791")="\0.5\0"
 s ^TKSOLDES("41792")="\0.5\0"
 s ^TKSOLDES("56144")="\0.5\0"
 s ^TKSOLDES("56145")="\0.5\0"
 s ^TKSOLDES("41793")="\0.5\0"
 s ^TKSOLDES("56146")="\0.5\0"
 s ^TKSOLDES("41794")="\0.5\0"
 s ^TKSOLDES("41795")="\0.5\0"
 s ^TKSOLDES("41796")="\0.5\0"
 s ^TKSOLDES("56147")="\0.5\0"
 s ^TKSOLDES("41797")="\0.5\0"
 s ^TKSOLDES("41798")="\0.5\0"
 s ^TKSOLDES("41799")="\0.5\0"
 s ^TKSOLDES("41800")="\0.5\0"
 s ^TKSOLDES("41801")="\0.5\0"
 s ^TKSOLDES("56148")="\0.5\0"
 s ^TKSOLDES("41802")="\0.5\0"
 s ^TKSOLDES("56149")="\0.5\0"
 s ^TKSOLDES("41885")="\0.5\0"
 s ^TKSOLDES("41886")="\0.5\0"
 s ^TKSOLDES("41887")="\0.5\0"
 s ^TKSOLDES("41888")="\0.5\0"
 s ^TKSOLDES("41889")="\0.5\0"
 s ^TKSOLDES("56151")="\0.5\0"
 s ^TKSOLDES("41880")="\0.5\0"
 s ^TKSOLDES("41881")="\0.5\0"
 s ^TKSOLDES("41882")="\0.5\0"
 s ^TKSOLDES("41883")="\0.5\0"
 s ^TKSOLDES("41884")="\0.5\0"
 s ^TKSOLDES("56152")="\0.5\0"
 s ^TKSOLDES("70815")="\0.5\0"
 s ^TKSOLDES("70816")="\0.5\0"
 s ^TKSOLDES("70817")="\0.5\0"
 s ^TKSOLDES("70818")="\0.5\0"
 s ^TKSOLDES("70819")="\0.5\0"
 s ^TKSOLDES("70820")="\0.5\0"
 s ^TKSOLDES("70821")="\0.5\0"
 s ^TKSOLDES("70822")="\0.5\0"
 s ^TKSOLDES("70823")="\0.5\0"
 s ^TKSOLDES("70824")="\0.5\0"
 s ^TKSOLDES("70825")="\0.5\0"
 s ^TKSOLDES("70826")="\0.5\0"
 s ^TKSOLDES("70827")="\0.5\0"
 s ^TKSOLDES("70828")="\0.5\0"
 s ^TKSOLDES("70829")="\0.5\0"
 s ^TKSOLDES("70830")="\0.5\0"
 s ^TKSOLDES("70831")="\0.5\0"
 s ^TKSOLDES("70832")="\0.5\0"
 s ^TKSOLDES("70833")="\0.5\0"
 s ^TKSOLDES("70834")="\0.5\0"
 s ^TKSOLDES("70835")="\0.5\0"
 s ^TKSOLDES("70836")="\0.5\0"
 s ^TKSOLDES("70837")="\0.5\0"
 s ^TKSOLDES("70838")="\0.5\0"
 s ^TKSOLDES("70839")="\0.5\0"
 s ^TKSOLDES("70840")="\0.5\0"
 s ^TKSOLDES("70805")="\0.5\0"
 s ^TKSOLDES("70806")="\0.5\0"
 s ^TKSOLDES("70807")="\0.5\0"
 s ^TKSOLDES("70808")="\0.5\0"
 s ^TKSOLDES("70809")="\0.5\0"
 s ^TKSOLDES("70810")="\0.5\0"
 s ^TKSOLDES("70811")="\0.5\0"
 s ^TKSOLDES("70812")="\0.5\0"
 s ^TKSOLDES("70813")="\0.5\0"
 s ^TKSOLDES("70814")="\0.5\0"
 s ^TKSOLDES("72914")="\0.5\0"
 s ^TKSOLDES("72912")="\0.5\0"
 s ^TKSOLDES("70841")="\0.5\0"
 s ^TKSOLDES("70842")="\0.5\0"
 s ^TKSOLDES("70843")="\0.5\0"
 s ^TKSOLDES("70844")="\0.5\0"
 s ^TKSOLDES("70845")="\0.5\0"
 s ^TKSOLDES("70846")="\0.5\0"
 s ^TKSOLDES("70847")="\0.5\0"
 s ^TKSOLDES("70848")="\0.5\0"
 s ^TKSOLDES("70849")="\0.5\0"
 s ^TKSOLDES("70850")="\0.5\0"
 s ^TKSOLDES("70851")="\0.5\0"
 s ^TKSOLDES("70852")="\0.5\0"
 s ^TKSOLDES("70853")="\0.5\0"
 s ^TKSOLDES("70854")="\0.5\0"
 s ^TKSOLDES("70855")="\0.5\0"
 s ^TKSOLDES("70856")="\0.5\0"
 s ^TKSOLDES("70857")="\0.5\0"
 s ^TKSOLDES("70858")="\0.5\0"
 s ^TKSOLDES("70859")="\0.5\0"
 s ^TKSOLDES("70860")="\0.5\0"
 s ^TKSOLDES("70861")="\0.5\0"
 s ^TKSOLDES("70862")="\0.5\0"
 s ^TKSOLDES("70863")="\0.5\0"
 s ^TKSOLDES("70864")="\0.5\0"
 s ^TKSOLDES("70865")="\0.5\0"
 s ^TKSOLDES("70866")="\0.5\0"
 s ^TKSOLDES("72913")="\0.5\0"
 s ^TKSOLDES("72915")="\0.5\0"
 s ^TKSOLDES("70781")="\0.5\0"
 s ^TKSOLDES("70782")="\0.5\0"
 s ^TKSOLDES("70783")="\0.5\0"
 s ^TKSOLDES("70784")="\0.5\0"
 s ^TKSOLDES("70785")="\0.5\0"
 s ^TKSOLDES("70786")="\0.5\0"
 s ^TKSOLDES("70787")="\0.5\0"
 s ^TKSOLDES("70788")="\0.5\0"
 s ^TKSOLDES("70789")="\0.5\0"
 s ^TKSOLDES("70790")="\0.5\0"
 s ^TKSOLDES("70791")="\0.5\0"
 s ^TKSOLDES("70792")="\0.5\0"
 s ^TKSOLDES("70793")="\0.5\0"
 s ^TKSOLDES("70794")="\0.5\0"
 s ^TKSOLDES("70795")="\0.5\0"
 s ^TKSOLDES("70796")="\0.5\0"
 s ^TKSOLDES("70797")="\0.5\0"
 s ^TKSOLDES("70798")="\0.5\0"
 s ^TKSOLDES("70799")="\0.5\0"
 s ^TKSOLDES("70800")="\0.5\0"
 s ^TKSOLDES("70801")="\0.5\0"
 s ^TKSOLDES("70802")="\0.5\0"
 s ^TKSOLDES("70803")="\0.5\0"
 s ^TKSOLDES("70804")="\0.5\0"
 s ^TKSOLDES("46274")="\0.5\0"
 s ^TKSOLDES("65131")="\0.5\0"
 s ^TKSOLDES("46275")="\0.5\0"
 s ^TKSOLDES("46276")="\0.5\0"
 s ^TKSOLDES("46277")="\0.5\0"
 s ^TKSOLDES("46278")="\0.5\0"
 s ^TKSOLDES("65133")="\0.5\0"
 s ^TKSOLDES("46279")="\0.5\0"
 s ^TKSOLDES("46281")="\0.5\0"
 s ^TKSOLDES("63033")="\0.5\0"
 s ^TKSOLDES("73048")="\0.5\0"
 s ^TKSOLDES("73047")="\0.5\0"
 s ^TKSOLDES("70246")="\0.5\0"
 s ^TKSOLDES("70247")="\0.5\0"
 s ^TKSOLDES("70248")="\0.5\0"
 s ^TKSOLDES("70249")="\0.5\0"
 s ^TKSOLDES("73065")="\0.5\0"
 s ^TKSOLDES("51280")="\0.5\0"
 s ^TKSOLDES("51281")="\0.5\0"
 s ^TKSOLDES("51282")="\0.5\0"
 s ^TKSOLDES("51283")="\0.5\0"
 s ^TKSOLDES("51284")="\0.5\0"
 s ^TKSOLDES("73066")="\0.5\0"
 s ^TKSOLDES("72266")="\0.5\0"
 s ^TKSOLDES("72267")="\0.5\0"
 s ^TKSOLDES("46268")="\0.5\0"
 s ^TKSOLDES("46270")="\0.5\0"
 s ^TKSOLDES("46272")="\0.5\0"
 s ^TKSOLDES("46273")="\0.5\0"
 s ^TKSOLDES("46228")="\0.5\0"
 s ^TKSOLDES("46229")="\0.5\0"
 s ^TKSOLDES("46230")="\0.5\0"
 s ^TKSOLDES("46231")="\0.5\0"
 s ^TKSOLDES("46232")="\0.5\0"
 s ^TKSOLDES("46233")="\0.5\0"
 s ^TKSOLDES("46234")="\0.5\0"
 s ^TKSOLDES("46235")="\0.5\0"
 s ^TKSOLDES("46236")="\0.5\0"
 s ^TKSOLDES("46237")="\0.5\0"
 s ^TKSOLDES("46238")="\0.5\0"
 s ^TKSOLDES("46239")="\0.5\0"
 s ^TKSOLDES("46240")="\0.5\0"
 s ^TKSOLDES("46241")="\0.5\0"
 s ^TKSOLDES("46242")="\0.5\0"
 s ^TKSOLDES("46243")="\0.5\0"
 s ^TKSOLDES("46244")="\0.5\0"
 s ^TKSOLDES("46245")="\0.5\0"
 s ^TKSOLDES("46246")="\0.5\0"
 s ^TKSOLDES("46247")="\0.5\0"
 s ^TKSOLDES("46248")="\0.5\0"
 s ^TKSOLDES("46249")="\0.5\0"
 s ^TKSOLDES("46250")="\0.5\0"
 s ^TKSOLDES("46251")="\0.5\0"
 s ^TKSOLDES("46252")="\0.5\0"
 s ^TKSOLDES("46253")="\0.5\0"
 s ^TKSOLDES("46254")="\0.5\0"
 s ^TKSOLDES("46255")="\0.5\0"
 s ^TKSOLDES("46256")="\0.5\0"
 s ^TKSOLDES("46257")="\0.5\0"
 s ^TKSOLDES("46258")="\0.5\0"
 s ^TKSOLDES("46259")="\0.5\0"
 s ^TKSOLDES("46260")="\0.5\0"
 s ^TKSOLDES("46261")="\0.5\0"
 s ^TKSOLDES("46262")="\0.5\0"
 s ^TKSOLDES("46263")="\0.5\0"
 s ^TKSOLDES("46264")="\0.5\0"
 s ^TKSOLDES("46265")="\0.5\0"
 s ^TKSOLDES("46266")="\0.5\0"
 s ^TKSOLDES("46267")="\0.5\0"
 s ^TKSOLDES("64704")="\0.5\0"
 s ^TKSOLDES("64705")="\0.5\0"
 s ^TKSOLDES("65205")="\0.5\0"
 s ^TKSOLDES("64706")="\0.5\0"
 s ^TKSOLDES("64229")="\0.5\0"
 s ^TKSOLDES("64230")="\0.5\0"
 s ^TKSOLDES("64231")="\0.5\0"
 s ^TKSOLDES("64211")="\0.5\0"
 s ^TKSOLDES("64212")="\0.5\0"
 s ^TKSOLDES("64232")="\0.5\0"
 s ^TKSOLDES("64203")="\0.5\0"
 s ^TKSOLDES("64204")="\0.5\0"
 s ^TKSOLDES("64233")="\0.5\0"
 s ^TKSOLDES("64205")="\0.5\0"
 s ^TKSOLDES("64213")="\0.5\0"
 s ^TKSOLDES("64234")="\0.5\0"
 s ^TKSOLDES("64214")="\0.5\0"
 s ^TKSOLDES("64215")="\0.5\0"
 s ^TKSOLDES("64216")="\0.5\0"
 s ^TKSOLDES("64217")="\0.5\0"
 s ^TKSOLDES("64224")="\0.5\0"
 s ^TKSOLDES("64235")="\0.5\0"
 s ^TKSOLDES("64206")="\0.5\0"
 s ^TKSOLDES("64218")="\0.5\0"
 s ^TKSOLDES("64219")="\0.5\0"
 s ^TKSOLDES("64207")="\0.5\0"
 s ^TKSOLDES("64236")="\0.5\0"
 s ^TKSOLDES("64237")="\0.5\0"
 s ^TKSOLDES("64220")="\0.5\0"
 s ^TKSOLDES("64225")="\0.5\0"
 s ^TKSOLDES("64238")="\0.5\0"
 s ^TKSOLDES("64221")="\0.5\0"
 s ^TKSOLDES("64239")="\0.5\0"
 s ^TKSOLDES("64222")="\0.5\0"
 s ^TKSOLDES("64208")="\0.5\0"
 s ^TKSOLDES("64223")="\0.5\0"
 s ^TKSOLDES("64209")="\0.5\0"
 s ^TKSOLDES("64226")="\0.5\0"
 s ^TKSOLDES("64227")="\0.5\0"
 s ^TKSOLDES("64210")="\0.5\0"
 s ^TKSOLDES("64228")="\0.5\0"
 s ^TKSOLDES("45856")="\0.5\0"
 s ^TKSOLDES("45946")="\0.5\0"
 s ^TKSOLDES("45947")="\0.5\0"
 s ^TKSOLDES("45948")="\0.5\0"
 s ^TKSOLDES("45949")="\0.5\0"
 s ^TKSOLDES("45950")="\0.5\0"
 s ^TKSOLDES("45955")="\0.5\0"
 s ^TKSOLDES("45956")="\0.5\0"
 s ^TKSOLDES("45957")="\0.5\0"
 s ^TKSOLDES("45958")="\0.5\0"
 s ^TKSOLDES("45959")="\0.5\0"
 s ^TKSOLDES("45960")="\0.5\0"
 s ^TKSOLDES("45963")="\0.5\0"
 s ^TKSOLDES("70331")="\0.5\0"
 s ^TKSOLDES("70332")="\0.5\0"
 s ^TKSOLDES("70333")="\0.5\0"
 s ^TKSOLDES("70334")="\0.5\0"
 s ^TKSOLDES("70335")="\0.5\0"
 s ^TKSOLDES("70336")="\0.5\0"
 s ^TKSOLDES("70337")="\0.5\0"
 s ^TKSOLDES("70353")="\0.5\0"
 s ^TKSOLDES("70354")="\0.5\0"
 s ^TKSOLDES("70355")="\0.5\0"
 s ^TKSOLDES("70356")="\0.5\0"
 s ^TKSOLDES("70357")="\0.5\0"
 s ^TKSOLDES("70358")="\0.5\0"
 s ^TKSOLDES("70359")="\0.5\0"
 s ^TKSOLDES("70360")="\0.5\0"
 s ^TKSOLDES("70361")="\0.5\0"
 s ^TKSOLDES("70362")="\0.5\0"
 s ^TKSOLDES("70363")="\0.5\0"
 s ^TKSOLDES("70364")="\0.5\0"
 s ^TKSOLDES("70365")="\0.5\0"
 s ^TKSOLDES("70366")="\0.5\0"
 s ^TKSOLDES("70367")="\0.5\0"
 s ^TKSOLDES("70368")="\0.5\0"
 s ^TKSOLDES("70369")="\0.5\0"
 s ^TKSOLDES("70370")="\0.5\0"
 s ^TKSOLDES("70371")="\0.5\0"
 s ^TKSOLDES("70372")="\0.5\0"
 s ^TKSOLDES("70373")="\0.5\0"
 s ^TKSOLDES("70374")="\0.5\0"
 s ^TKSOLDES("70375")="\0.5\0"
 s ^TKSOLDES("70376")="\0.5\0"
 s ^TKSOLDES("70377")="\0.5\0"
 s ^TKSOLDES("70378")="\0.5\0"
 s ^TKSOLDES("70379")="\0.5\0"
 s ^TKSOLDES("70380")="\0.5\0"
 s ^TKSOLDES("70452")="\0.5\0"
 s ^TKSOLDES("70381")="\0.5\0"
 s ^TKSOLDES("70382")="\0.5\0"
 s ^TKSOLDES("70383")="\0.5\0"
 s ^TKSOLDES("70384")="\0.5\0"
 s ^TKSOLDES("70385")="\0.5\0"
 s ^TKSOLDES("70386")="\0.5\0"
 s ^TKSOLDES("70387")="\0.5\0"
 s ^TKSOLDES("70388")="\0.5\0"
 s ^TKSOLDES("70389")="\0.5\0"
 s ^TKSOLDES("70390")="\0.5\0"
 s ^TKSOLDES("70391")="\0.5\0"
 s ^TKSOLDES("70392")="\0.5\0"
 s ^TKSOLDES("70393")="\0.5\0"
 s ^TKSOLDES("70394")="\0.5\0"
 s ^TKSOLDES("70395")="\0.5\0"
 s ^TKSOLDES("70396")="\0.5\0"
 s ^TKSOLDES("70397")="\0.5\0"
 s ^TKSOLDES("70398")="\0.5\0"
 s ^TKSOLDES("70399")="\0.5\0"
 s ^TKSOLDES("70400")="\0.5\0"
 s ^TKSOLDES("70401")="\0.5\0"
 s ^TKSOLDES("70402")="\0.5\0"
 s ^TKSOLDES("70403")="\0.5\0"
 s ^TKSOLDES("70404")="\0.5\0"
 s ^TKSOLDES("70405")="\0.5\0"
 s ^TKSOLDES("70406")="\0.5\0"
 s ^TKSOLDES("70407")="\0.5\0"
 s ^TKSOLDES("70408")="\0.5\0"
 s ^TKSOLDES("70409")="\0.5\0"
 s ^TKSOLDES("70410")="\0.5\0"
 s ^TKSOLDES("70411")="\0.5\0"
 s ^TKSOLDES("70421")="\0.5\0"
 s ^TKSOLDES("70422")="\0.5\0"
 s ^TKSOLDES("70423")="\0.5\0"
 s ^TKSOLDES("70424")="\0.5\0"
 s ^TKSOLDES("70425")="\0.5\0"
 s ^TKSOLDES("70426")="\0.5\0"
 s ^TKSOLDES("70412")="\0.5\0"
 s ^TKSOLDES("70413")="\0.5\0"
 s ^TKSOLDES("70414")="\0.5\0"
 s ^TKSOLDES("70415")="\0.5\0"
 s ^TKSOLDES("70416")="\0.5\0"
 s ^TKSOLDES("70417")="\0.5\0"
 s ^TKSOLDES("70418")="\0.5\0"
 s ^TKSOLDES("70419")="\0.5\0"
 s ^TKSOLDES("70420")="\0.5\0"
 s ^TKSOLDES("70451")="\0.5\0"
 s ^TKSOLDES("70427")="\0.5\0"
 s ^TKSOLDES("70428")="\0.5\0"
 s ^TKSOLDES("70429")="\0.5\0"
 s ^TKSOLDES("70430")="\0.5\0"
 s ^TKSOLDES("70431")="\0.5\0"
 s ^TKSOLDES("70432")="\0.5\0"
 s ^TKSOLDES("70433")="\0.5\0"
 s ^TKSOLDES("70434")="\0.5\0"
 s ^TKSOLDES("70435")="\0.5\0"
 s ^TKSOLDES("70436")="\0.5\0"
 s ^TKSOLDES("70437")="\0.5\0"
 s ^TKSOLDES("70438")="\0.5\0"
 s ^TKSOLDES("70439")="\0.5\0"
 s ^TKSOLDES("70440")="\0.5\0"
 s ^TKSOLDES("70441")="\0.5\0"
 s ^TKSOLDES("70442")="\0.5\0"
 s ^TKSOLDES("70443")="\0.5\0"
 s ^TKSOLDES("70444")="\0.5\0"
 s ^TKSOLDES("70445")="\0.5\0"
 s ^TKSOLDES("70446")="\0.5\0"
 s ^TKSOLDES("70447")="\0.5\0"
 s ^TKSOLDES("70448")="\0.5\0"
 s ^TKSOLDES("70449")="\0.5\0"
 s ^TKSOLDES("70450")="\0.5\0"
 s ^TKSOLDES("45964")="\0.5\0"
 s ^TKSOLDES("45965")="\0.5\0"
 s ^TKSOLDES("45966")="\0.5\0"
 s ^TKSOLDES("45967")="\0.5\0"
 s ^TKSOLDES("45968")="\0.5\0"
 s ^TKSOLDES("45969")="\0.5\0"
 s ^TKSOLDES("45970")="\0.5\0"
 s ^TKSOLDES("45971")="\0.5\0"
 s ^TKSOLDES("45972")="\0.5\0"
 s ^TKSOLDES("45974")="\0.5\0"
 s ^TKSOLDES("45975")="\0.5\0"
 s ^TKSOLDES("45976")="\0.5\0"
 s ^TKSOLDES("45977")="\0.5\0"
 s ^TKSOLDES("45978")="\0.5\0"
 s ^TKSOLDES("45980")="\0.5\0"
 s ^TKSOLDES("45981")="\0.5\0"
 s ^TKSOLDES("45982")="\0.5\0"
 s ^TKSOLDES("45983")="\0.5\0"
 s ^TKSOLDES("45984")="\0.5\0"
 s ^TKSOLDES("45985")="\0.5\0"
 s ^TKSOLDES("45986")="\0.5\0"
 s ^TKSOLDES("45987")="\0.5\0"
 s ^TKSOLDES("45988")="\0.5\0"
 s ^TKSOLDES("45989")="\0.5\0"
 s ^TKSOLDES("45991")="\0.5\0"
 s ^TKSOLDES("45992")="\0.5\0"
 s ^TKSOLDES("45994")="\0.5\0"
 s ^TKSOLDES("45996")="\0.5\0"
 s ^TKSOLDES("45997")="\0.5\0"
 s ^TKSOLDES("45998")="\0.5\0"
 s ^TKSOLDES("45999")="\0.5\0"
 s ^TKSOLDES("46000")="\0.5\0"
 s ^TKSOLDES("46001")="\0.5\0"
 s ^TKSOLDES("46002")="\0.5\0"
 s ^TKSOLDES("46004")="\0.5\0"
 s ^TKSOLDES("46005")="\0.5\0"
 s ^TKSOLDES("46007")="\0.5\0"
 s ^TKSOLDES("46008")="\0.5\0"
 s ^TKSOLDES("46009")="\0.5\0"
 s ^TKSOLDES("46010")="\0.5\0"
 s ^TKSOLDES("46011")="\0.5\0"
 s ^TKSOLDES("46012")="\0.5\0"
 s ^TKSOLDES("46013")="\0.5\0"
 s ^TKSOLDES("70346")="\0.5\0"
 s ^TKSOLDES("70347")="\0.5\0"
 s ^TKSOLDES("70348")="\0.5\0"
 s ^TKSOLDES("70349")="\0.5\0"
 s ^TKSOLDES("70350")="\0.5\0"
 s ^TKSOLDES("70351")="\0.5\0"
 s ^TKSOLDES("70352")="\0.5\0"
 s ^TKSOLDES("46022")="\0.5\0"
 s ^TKSOLDES("46023")="\0.5\0"
 s ^TKSOLDES("70338")="\0.5\0"
 s ^TKSOLDES("70339")="\0.5\0"
 s ^TKSOLDES("70340")="\0.5\0"
 s ^TKSOLDES("70341")="\0.5\0"
 s ^TKSOLDES("70342")="\0.5\0"
 s ^TKSOLDES("70343")="\0.5\0"
 s ^TKSOLDES("70344")="\0.5\0"
 s ^TKSOLDES("70345")="\0.5\0"
 s ^TKSOLDES("60599")="\0.5\0"
 s ^TKSOLDES("60591")="\0.5\0"
 s ^TKSOLDES("52398")="\0.5\0"
 s ^TKSOLDES("52396")="\0.5\0"
 s ^TKSOLDES("60592")="\0.5\0"
 s ^TKSOLDES("52397")="\0.5\0"
 s ^TKSOLDES("60593")="\0.5\0"
 s ^TKSOLDES("60594")="\0.5\0"
 s ^TKSOLDES("60596")="\0.5\0"
 s ^TKSOLDES("60597")="\0.5\0"
 s ^TKSOLDES("60598")="\0.5\0"
 s ^TKSOLDES("46348")="\0.5\0"
 s ^TKSOLDES("46349")="\0.5\0"
 s ^TKSOLDES("46350")="\0.5\0"
 s ^TKSOLDES("46351")="\0.5\0"
 s ^TKSOLDES("46352")="\0.5\0"
 s ^TKSOLDES("46353")="\0.5\0"
 s ^TKSOLDES("46354")="\0.5\0"
 s ^TKSOLDES("52376")="\0.5\0"
 s ^TKSOLDES("60573")="\0.5\0"
 s ^TKSOLDES("60574")="\0.5\0"
 s ^TKSOLDES("52389")="\0.5\0"
 s ^TKSOLDES("60575")="\0.5\0"
 s ^TKSOLDES("60576")="\0.5\0"
 s ^TKSOLDES("52377")="\0.5\0"
 s ^TKSOLDES("60577")="\0.5\0"
 s ^TKSOLDES("60578")="\0.5\0"
 s ^TKSOLDES("60579")="\0.5\0"
 s ^TKSOLDES("60580")="\0.5\0"
 s ^TKSOLDES("60581")="\0.5\0"
 s ^TKSOLDES("52393")="\0.5\0"
 s ^TKSOLDES("60582")="\0.5\0"
 s ^TKSOLDES("52384")="\0.5\0"
 s ^TKSOLDES("60583")="\0.5\0"
 s ^TKSOLDES("52385")="\0.5\0"
 s ^TKSOLDES("52378")="\0.5\0"
 s ^TKSOLDES("52379")="\0.5\0"
 s ^TKSOLDES("52386")="\0.5\0"
 s ^TKSOLDES("52392")="\0.5\0"
 s ^TKSOLDES("52380")="\0.5\0"
 s ^TKSOLDES("60584")="\0.5\0"
 s ^TKSOLDES("60585")="\0.5\0"
 s ^TKSOLDES("52391")="\0.5\0"
 s ^TKSOLDES("52395")="\0.5\0"
 s ^TKSOLDES("60586")="\0.5\0"
 s ^TKSOLDES("52387")="\0.5\0"
 s ^TKSOLDES("60587")="\0.5\0"
 s ^TKSOLDES("52381")="\0.5\0"
 s ^TKSOLDES("60588")="\0.5\0"
 s ^TKSOLDES("52390")="\0.5\0"
 s ^TKSOLDES("52382")="\0.5\0"
 s ^TKSOLDES("52383")="\0.5\0"
 s ^TKSOLDES("52388")="\0.5\0"
 s ^TKSOLDES("70171")="\0.5\0"
 s ^TKSOLDES("70172")="\0.5\0"
 s ^TKSOLDES("70173")="\0.5\0"
 s ^TKSOLDES("70174")="\0.5\0"
 s ^TKSOLDES("70175")="\0.5\0"
 s ^TKSOLDES("70176")="\0.5\0"
 s ^TKSOLDES("70177")="\0.5\0"
 s ^TKSOLDES("70178")="\0.5\0"
 s ^TKSOLDES("70179")="\0.5\0"
 s ^TKSOLDES("70180")="\0.5\0"
 s ^TKSOLDES("70181")="\0.5\0"
 s ^TKSOLDES("70182")="\0.5\0"
 s ^TKSOLDES("70183")="\0.5\0"
 s ^TKSOLDES("70184")="\0.5\0"
 s ^TKSOLDES("70185")="\0.5\0"
 s ^TKSOLDES("70186")="\0.5\0"
 s ^TKSOLDES("60589")="\0.5\0"
 s ^TKSOLDES("52394")="\0.5\0"
 s ^TKSOLDES("70187")="\0.5\0"
 s ^TKSOLDES("70188")="\0.5\0"
 s ^TKSOLDES("60590")="\0.5\0"
 s ^TKSOLDES("70189")="\0.5\0"
 s ^TKSOLDES("70190")="\0.5\0"
 s ^TKSOLDES("70191")="\0.5\0"
 s ^TKSOLDES("70192")="\0.5\0"
 s ^TKSOLDES("70193")="\0.5\0"
 s ^TKSOLDES("73045")="\0.5\0"
 s ^TKSOLDES("60554")="\0.5\0"
 s ^TKSOLDES("52401")="\0.5\0"
 s ^TKSOLDES("52402")="\0.5\0"
 s ^TKSOLDES("60557")="\0.5\0"
 s ^TKSOLDES("52404")="\0.5\0"
 s ^TKSOLDES("52405")="\0.5\0"
 s ^TKSOLDES("73049")="\0.5\0"
 s ^TKSOLDES("60558")="\0.5\0"
 s ^TKSOLDES("60559")="\0.5\0"
 s ^TKSOLDES("60560")="\0.5\0"
 s ^TKSOLDES("60562")="\0.5\0"
 s ^TKSOLDES("60563")="\0.5\0"
 s ^TKSOLDES("60564")="\0.5\0"
 s ^TKSOLDES("73046")="\0.5\0"
 s ^TKSOLDES("52407")="\0.5\0"
 s ^TKSOLDES("60565")="\0.5\0"
 s ^TKSOLDES("60566")="\0.5\0"
 s ^TKSOLDES("60572")="\0.5\0"
 s ^TKSOLDES("60569")="\0.5\0"
 s ^TKSOLDES("60571")="\0.5\0"
 
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 