ROUTINE OPESOLDES50PE13P4
OPESOLDES50PE13P4
 
 s ^TKSOLDES("74381")="\0.5\0"
 s ^TKSOLDES("79005")="\0.5\0"
 s ^TKSOLDES("79011")="\0.5\0"
 s ^TKSOLDES("74380")="\0.5\0"
 s ^TKSOLDES("79015")="\0.5\0"
 s ^TKSOLDES("79013")="\0.5\0"
 s ^TKSOLDES("103024")="\0.5\0"
 s ^TKSOLDES("79010")="\0.5\0"
 s ^TKSOLDES("79006")="\0.5\0"
 s ^TKSOLDES("74509")="\0.5\0"
 s ^TKSOLDES("5804")="\0.5\0"
 s ^TKSOLDES("79009")="\0.5\0"
 s ^TKSOLDES("79008")="\0.5\0"
 s ^TKSOLDES("79007")="\0.5\0"
 s ^TKSOLDES("78405")="\0.5\0"
 s ^TKSOLDES("78126")="\0.5\0"
 s ^TKSOLDES("76441")="\0.5\0"
 s ^TKSOLDES("75400")="\0.5\0"
 s ^TKSOLDES("75398")="\0.5\0"
 s ^TKSOLDES("75396")="\0.5\0"
 s ^TKSOLDES("75394")="\0.5\0"
 s ^TKSOLDES("75390")="\0.5\0"
 s ^TKSOLDES("76442")="\0.5\0"
 s ^TKSOLDES("75440")="\0.5\0"
 s ^TKSOLDES("76443")="\0.5\0"
 s ^TKSOLDES("76444")="\0.5\0"
 s ^TKSOLDES("76445")="\0.5\0"
 s ^TKSOLDES("76446")="\0.5\0"
 s ^TKSOLDES("76447")="\0.5\0"
 s ^TKSOLDES("76450")="\0.5\0"
 s ^TKSOLDES("75403")="\0.5\0"
 s ^TKSOLDES("75405")="\0.5\0"
 s ^TKSOLDES("75407")="\0.5\0"
 s ^TKSOLDES("75435")="\0.5\0"
 s ^TKSOLDES("75433")="\0.5\0"
 s ^TKSOLDES("75431")="\0.5\0"
 s ^TKSOLDES("75427")="\0.5\0"
 s ^TKSOLDES("75423")="\0.5\0"
 s ^TKSOLDES("75419")="\0.5\0"
 s ^TKSOLDES("75417")="\0.5\0"
 s ^TKSOLDES("75415")="\0.5\0"
 s ^TKSOLDES("75410")="\0.5\0"
 s ^TKSOLDES("46924")="\0.5\0"
 s ^TKSOLDES("46977")="\0.5\0"
 s ^TKSOLDES("46997")="\0.5\0"
 s ^TKSOLDES("47025")="\0.5\0"
 s ^TKSOLDES("75412")="\0.5\0"
 s ^TKSOLDES("76454")="\0.5\0"
 s ^TKSOLDES("75388")="\0.5\0"
 s ^TKSOLDES("75132")="\0.5\0"
 s ^TKSOLDES("74515")="\0.5\0"
 s ^TKSOLDES("105194")="\0.5\0"
 s ^TKSOLDES("75135")="\0.5\0"
 s ^TKSOLDES("75133")="\0.5\0"
 s ^TKSOLDES("76925")="\0.5\0"
 s ^TKSOLDES("75131")="\0.5\0"
 s ^TKSOLDES("75325")="\0.5\0"
 s ^TKSOLDES("77175")="\0.5\0"
 s ^TKSOLDES("77216")="\0.5\0"
 s ^TKSOLDES("77217")="\0.5\0"
 s ^TKSOLDES("77220")="\0.5\0"
 s ^TKSOLDES("77221")="\0.5\0"
 s ^TKSOLDES("77223")="\0.5\0"
 s ^TKSOLDES("75323")="\0.5\0"
 s ^TKSOLDES("75326")="\0.5\0"
 s ^TKSOLDES("75386")="\0.5\0"
 s ^TKSOLDES("75327")="\0.5\0"
 s ^TKSOLDES("75384")="\0.5\0"
 s ^TKSOLDES("75382")="\0.5\0"
 s ^TKSOLDES("75380")="\0.5\0"
 s ^TKSOLDES("75377")="\0.5\0"
 s ^TKSOLDES("75373")="\0.5\0"
 s ^TKSOLDES("67392")="\0.5\0"
 s ^TKSOLDES("67393")="\0.5\0"
 s ^TKSOLDES("67394")="\0.5\0"
 s ^TKSOLDES("75329")="\0.5\0"
 s ^TKSOLDES("75330")="\0.5\0"
 s ^TKSOLDES("75331")="\0.5\0"
 s ^TKSOLDES("75332")="\0.5\0"
 s ^TKSOLDES("75333")="\0.5\0"
 s ^TKSOLDES("75335")="\0.5\0"
 s ^TKSOLDES("75438")="\0.5\0"
 s ^TKSOLDES("75443")="\0.5\0"
 s ^TKSOLDES("77226")="\0.5\0"
 s ^TKSOLDES("105199")="\0.5\0"
 s ^TKSOLDES("63960")="\0.5\0"
 s ^TKSOLDES("63959")="\0.5\0"
 s ^TKSOLDES("63789")="\0.5\0"
 s ^TKSOLDES("105197")="\0.5\0"
 s ^TKSOLDES("105198")="\0.5\0"
 s ^TKSOLDES("103074")="\0.5\0"
 s ^TKSOLDES("50575")="\0.5\0"
 s ^TKSOLDES("103075")="\0.5\0"
 s ^TKSOLDES("103076")="\0.5\0"
 s ^TKSOLDES("103077")="\0.5\0"
 s ^TKSOLDES("53523")="\0.5\0"
 s ^TKSOLDES("53522")="\0.5\0"
 s ^TKSOLDES("103078")="\0.5\0"
 s ^TKSOLDES("63962")="\0.5\0"
 s ^TKSOLDES("63965")="\0.5\0"
 s ^TKSOLDES("63966")="\0.5\0"
 s ^TKSOLDES("66351")="\0.5\0"
 s ^TKSOLDES("66348")="\0.5\0"
 s ^TKSOLDES("66347")="\0.5\0"
 s ^TKSOLDES("105195")="\0.5\0"
 s ^TKSOLDES("105196")="\0.5\0"
 s ^TKSOLDES("75568")="\0.5\0"
 s ^TKSOLDES("75569")="\0.5\0"
 s ^TKSOLDES("75570")="\0.5\0"
 s ^TKSOLDES("75575")="\0.5\0"
 s ^TKSOLDES("64099")="\0.5\0"
 s ^TKSOLDES("75574")="\0.5\0"
 s ^TKSOLDES("75573")="\0.5\0"
 s ^TKSOLDES("75572")="\0.5\0"
 s ^TKSOLDES("75571")="\0.5\0"
 s ^TKSOLDES("50695")="\0.5\0"
 s ^TKSOLDES("67379")="\0.5\0"
 s ^TKSOLDES("75445")="\0.5\0"
 s ^TKSOLDES("75459")="\0.5\0"
 s ^TKSOLDES("75471")="\0.5\0"
 s ^TKSOLDES("75469")="\0.5\0"
 s ^TKSOLDES("75467")="\0.5\0"
 s ^TKSOLDES("75464")="\0.5\0"
 s ^TKSOLDES("75462")="\0.5\0"
 s ^TKSOLDES("75457")="\0.5\0"
 s ^TKSOLDES("75476")="\0.5\0"
 s ^TKSOLDES("49371")="\0.5\0"
 s ^TKSOLDES("47760")="\0.5\0"
 s ^TKSOLDES("47031")="\0.5\0"
 s ^TKSOLDES("75455")="\0.5\0"
 s ^TKSOLDES("75452")="\0.5\0"
 s ^TKSOLDES("75447")="\0.5\0"
 s ^TKSOLDES("75474")="\0.5\0"
 s ^TKSOLDES("75479")="\0.5\0"
 s ^TKSOLDES("67380")="\0.5\0"
 s ^TKSOLDES("75481")="\0.5\0"
 s ^TKSOLDES("67381")="\0.5\0"
 s ^TKSOLDES("67382")="\0.5\0"
 s ^TKSOLDES("67383")="\0.5\0"
 s ^TKSOLDES("67384")="\0.5\0"
 s ^TKSOLDES("76134")="\0.5\0"
 s ^TKSOLDES("76143")="\0.5\0"
 s ^TKSOLDES("76147")="\0.5\0"
 s ^TKSOLDES("75566")="\0.5\0"
 s ^TKSOLDES("75483")="\0.5\0"
 s ^TKSOLDES("75509")="\0.5\0"
 s ^TKSOLDES("67391")="\0.5\0"
 s ^TKSOLDES("67386")="\0.5\0"
 s ^TKSOLDES("67385")="\0.5\0"
 s ^TKSOLDES("75565")="\0.5\0"
 s ^TKSOLDES("77224")="\0.5\0"
 s ^TKSOLDES("77227")="\0.5\0"
 s ^TKSOLDES("78398")="\0.5\0"
 s ^TKSOLDES("78166")="\0.5\0"
 s ^TKSOLDES("78156")="\0.5\0"
 s ^TKSOLDES("78157")="\0.5\0"
 s ^TKSOLDES("78159")="\0.5\0"
 s ^TKSOLDES("78160")="\0.5\0"
 s ^TKSOLDES("78161")="\0.5\0"
 s ^TKSOLDES("78177")="\0.5\0"
 s ^TKSOLDES("78223")="\0.5\0"
 s ^TKSOLDES("78197")="\0.5\0"
 s ^TKSOLDES("78201")="\0.5\0"
 s ^TKSOLDES("78204")="\0.5\0"
 s ^TKSOLDES("78205")="\0.5\0"
 s ^TKSOLDES("78206")="\0.5\0"
 s ^TKSOLDES("78210")="\0.5\0"
 s ^TKSOLDES("78155")="\0.5\0"
 s ^TKSOLDES("78154")="\0.5\0"
 s ^TKSOLDES("78153")="\0.5\0"
 s ^TKSOLDES("78113")="\0.5\0"
 s ^TKSOLDES("78114")="\0.5\0"
 s ^TKSOLDES("78115")="\0.5\0"
 s ^TKSOLDES("78116")="\0.5\0"
 s ^TKSOLDES("78117")="\0.5\0"
 s ^TKSOLDES("78118")="\0.5\0"
 s ^TKSOLDES("78119")="\0.5\0"
 s ^TKSOLDES("78120")="\0.5\0"
 s ^TKSOLDES("78152")="\0.5\0"
 s ^TKSOLDES("78127")="\0.5\0"
 s ^TKSOLDES("78124")="\0.5\0"
 s ^TKSOLDES("78123")="\0.5\0"
 s ^TKSOLDES("78122")="\0.5\0"
 s ^TKSOLDES("78121")="\0.5\0"
 s ^TKSOLDES("78221")="\0.5\0"
 s ^TKSOLDES("74366")="\0.5\0"
 s ^TKSOLDES("77230")="\0.5\0"
 s ^TKSOLDES("78387")="\0.5\0"
 s ^TKSOLDES("78376")="\0.5\0"
 s ^TKSOLDES("78380")="\0.5\0"
 s ^TKSOLDES("78382")="\0.5\0"
 s ^TKSOLDES("78383")="\0.5\0"
 s ^TKSOLDES("78385")="\0.5\0"
 s ^TKSOLDES("78388")="\0.5\0"
 s ^TKSOLDES("78372")="\0.5\0"
 s ^TKSOLDES("78390")="\0.5\0"
 s ^TKSOLDES("78392")="\0.5\0"
 s ^TKSOLDES("78393")="\0.5\0"
 s ^TKSOLDES("78394")="\0.5\0"
 s ^TKSOLDES("78395")="\0.5\0"
 s ^TKSOLDES("78396")="\0.5\0"
 s ^TKSOLDES("78373")="\0.5\0"
 s ^TKSOLDES("78371")="\0.5\0"
 s ^TKSOLDES("74367")="\0.5\0"
 s ^TKSOLDES("78365")="\0.5\0"
 s ^TKSOLDES("74368")="\0.5\0"
 s ^TKSOLDES("74369")="\0.5\0"
 s ^TKSOLDES("78269")="\0.5\0"
 s ^TKSOLDES("78271")="\0.5\0"
 s ^TKSOLDES("78272")="\0.5\0"
 s ^TKSOLDES("78274")="\0.5\0"
 s ^TKSOLDES("78275")="\0.5\0"
 s ^TKSOLDES("78277")="\0.5\0"
 s ^TKSOLDES("78361")="\0.5\0"
 s ^TKSOLDES("78359")="\0.5\0"
 s ^TKSOLDES("78356")="\0.5\0"
 s ^TKSOLDES("78310")="\0.5\0"
 s ^TKSOLDES("78304")="\0.5\0"
 s ^TKSOLDES("78279")="\0.5\0"
 s ^TKSOLDES("78112")="\0.5\0"
 s ^TKSOLDES("78111")="\0.5\0"
 s ^TKSOLDES("70164")="\0.5\0"
 s ^TKSOLDES("70111")="\0.5\0"
 s ^TKSOLDES("70112")="\0.5\0"
 s ^TKSOLDES("70113")="\0.5\0"
 s ^TKSOLDES("70161")="\0.5\0"
 s ^TKSOLDES("70162")="\0.5\0"
 s ^TKSOLDES("71599")="\0.5\0"
 s ^TKSOLDES("70109")="\0.5\0"
 s ^TKSOLDES("71604")="\0.5\0"
 s ^TKSOLDES("71617")="\0.5\0"
 s ^TKSOLDES("71618")="\0.5\0"
 s ^TKSOLDES("79128")="\0.5\0"
 s ^TKSOLDES("78013")="\0.5\0"
 s ^TKSOLDES("73133")="\0.5\0"
 s ^TKSOLDES("70110")="\0.5\0"
 s ^TKSOLDES("70108")="\0.5\0"
 s ^TKSOLDES("78110")="\0.5\0"
 s ^TKSOLDES("68422")="\0.5\0"
 s ^TKSOLDES("77231")="\0.5\0"
 s ^TKSOLDES("77232")="\0.5\0"
 s ^TKSOLDES("77233")="\0.5\0"
 s ^TKSOLDES("77236")="\0.5\0"
 s ^TKSOLDES("77239")="\0.5\0"
 s ^TKSOLDES("77679")="\0.5\0"
 s ^TKSOLDES("77686")="\0.5\0"
 s ^TKSOLDES("77687")="\0.5\0"
 s ^TKSOLDES("68421")="\0.5\0"
 s ^TKSOLDES("105191")="\0.5\0"
 s ^TKSOLDES("105192")="\0.5\0"
 s ^TKSOLDES("105193")="\0.5\0"
 s ^TKSOLDES("77690")="\0.5\0"
 s ^TKSOLDES("77689")="\0.5\0"
 s ^TKSOLDES("73142")="\0.5\0"
 s ^TKSOLDES("78076")="\0.5\0"
 s ^TKSOLDES("78077")="\0.5\0"
 s ^TKSOLDES("78096")="\0.5\0"
 s ^TKSOLDES("78097")="\0.5\0"
 s ^TKSOLDES("78098")="\0.5\0"
 s ^TKSOLDES("78099")="\0.5\0"
 s ^TKSOLDES("78100")="\0.5\0"
 s ^TKSOLDES("78101")="\0.5\0"
 s ^TKSOLDES("78102")="\0.5\0"
 s ^TKSOLDES("78103")="\0.5\0"
 s ^TKSOLDES("78109")="\0.5\0"
 s ^TKSOLDES("78108")="\0.5\0"
 s ^TKSOLDES("78107")="\0.5\0"
 s ^TKSOLDES("78106")="\0.5\0"
 s ^TKSOLDES("78105")="\0.5\0"
 s ^TKSOLDES("78104")="\0.5\0"
 s ^TKSOLDES("78095")="\0.5\0"
 s ^TKSOLDES("78094")="\0.5\0"
 s ^TKSOLDES("78084")="\0.5\0"
 s ^TKSOLDES("78078")="\0.5\0"
 s ^TKSOLDES("78079")="\0.5\0"
 s ^TKSOLDES("78080")="\0.5\0"
 s ^TKSOLDES("78081")="\0.5\0"
 s ^TKSOLDES("78082")="\0.5\0"
 s ^TKSOLDES("78083")="\0.5\0"
 s ^TKSOLDES("78085")="\0.5\0"
 s ^TKSOLDES("78093")="\0.5\0"
 s ^TKSOLDES("78086")="\0.5\0"
 s ^TKSOLDES("78092")="\0.5\0"
 s ^TKSOLDES("78091")="\0.5\0"
 s ^TKSOLDES("78090")="\0.5\0"
 s ^TKSOLDES("78089")="\0.5\0"
 s ^TKSOLDES("78088")="\0.5\0"
 s ^TKSOLDES("78087")="\0.5\0"
 s ^TKSOLDES("79127")="\0.5\0"
 s ^TKSOLDES("79012")="\0.5\0"
 s ^TKSOLDES("84225")="\0.5\0"
 s ^TKSOLDES("84232")="\0.5\0"
 s ^TKSOLDES("84231")="\0.5\0"
 s ^TKSOLDES("84230")="\0.5\0"
 s ^TKSOLDES("84228")="\0.5\0"
 s ^TKSOLDES("84227")="\0.5\0"
 s ^TKSOLDES("84224")="\0.5\0"
 s ^TKSOLDES("84234")="\0.5\0"
 s ^TKSOLDES("84223")="\0.5\0"
 s ^TKSOLDES("84177")="\0.5\0"
 s ^TKSOLDES("84176")="\0.5\0"
 s ^TKSOLDES("84174")="\0.5\0"
 s ^TKSOLDES("84141")="\0.5\0"
 s ^TKSOLDES("84140")="\0.5\0"
 s ^TKSOLDES("84233")="\0.5\0"
 s ^TKSOLDES("84235")="\0.5\0"
 s ^TKSOLDES("81265")="\0.5\0"
 s ^TKSOLDES("84236")="\0.5\0"
 s ^TKSOLDES("84290")="\0.5\0"
 s ^TKSOLDES("84289")="\0.5\0"
 s ^TKSOLDES("84288")="\0.5\0"
 s ^TKSOLDES("84251")="\0.5\0"
 s ^TKSOLDES("84250")="\0.5\0"
 s ^TKSOLDES("84247")="\0.5\0"
 s ^TKSOLDES("84246")="\0.5\0"
 s ^TKSOLDES("84244")="\0.5\0"
 s ^TKSOLDES("84237")="\0.5\0"
 s ^TKSOLDES("84239")="\0.5\0"
 s ^TKSOLDES("84240")="\0.5\0"
 s ^TKSOLDES("84241")="\0.5\0"
 s ^TKSOLDES("84242")="\0.5\0"
 s ^TKSOLDES("84243")="\0.5\0"
 s ^TKSOLDES("84139")="\0.5\0"
 s ^TKSOLDES("84072")="\0.5\0"
 s ^TKSOLDES("84071")="\0.5\0"
 s ^TKSOLDES("83094")="\0.5\0"
 s ^TKSOLDES("83093")="\0.5\0"
 s ^TKSOLDES("83092")="\0.5\0"
 s ^TKSOLDES("83073")="\0.5\0"
 s ^TKSOLDES("83072")="\0.5\0"
 s ^TKSOLDES("83071")="\0.5\0"
 s ^TKSOLDES("83070")="\0.5\0"
 s ^TKSOLDES("82896")="\0.5\0"
 s ^TKSOLDES("82889")="\0.5\0"
 s ^TKSOLDES("82891")="\0.5\0"
 s ^TKSOLDES("82892")="\0.5\0"
 s ^TKSOLDES("82893")="\0.5\0"
 s ^TKSOLDES("82894")="\0.5\0"
 s ^TKSOLDES("82895")="\0.5\0"
 s ^TKSOLDES("83095")="\0.5\0"
 s ^TKSOLDES("83544")="\0.5\0"
 s ^TKSOLDES("84054")="\0.5\0"
 s ^TKSOLDES("84067")="\0.5\0"
 s ^TKSOLDES("84062")="\0.5\0"
 s ^TKSOLDES("84059")="\0.5\0"
 s ^TKSOLDES("84057")="\0.5\0"
 s ^TKSOLDES("84056")="\0.5\0"
 s ^TKSOLDES("84055")="\0.5\0"
 s ^TKSOLDES("83625")="\0.5\0"
 s ^TKSOLDES("83548")="\0.5\0"
 s ^TKSOLDES("83623")="\0.5\0"
 s ^TKSOLDES("83549")="\0.5\0"
 s ^TKSOLDES("83550")="\0.5\0"
 s ^TKSOLDES("83551")="\0.5\0"
 s ^TKSOLDES("83552")="\0.5\0"
 s ^TKSOLDES("83553")="\0.5\0"
 s ^TKSOLDES("83555")="\0.5\0"
 s ^TKSOLDES("84291")="\0.5\0"
 s ^TKSOLDES("84292")="\0.5\0"
 s ^TKSOLDES("85081")="\0.5\0"
 s ^TKSOLDES("85087")="\0.5\0"
 s ^TKSOLDES("85086")="\0.5\0"
 s ^TKSOLDES("85085")="\0.5\0"
 s ^TKSOLDES("85084")="\0.5\0"
 s ^TKSOLDES("85083")="\0.5\0"
 s ^TKSOLDES("85080")="\0.5\0"
 s ^TKSOLDES("85089")="\0.5\0"
 s ^TKSOLDES("85079")="\0.5\0"
 s ^TKSOLDES("85078")="\0.5\0"
 s ^TKSOLDES("85077")="\0.5\0"
 s ^TKSOLDES("85076")="\0.5\0"
 s ^TKSOLDES("85074")="\0.5\0"
 s ^TKSOLDES("79129")="\0.5\0"
 s ^TKSOLDES("85088")="\0.5\0"
 s ^TKSOLDES("85090")="\0.5\0"
 s ^TKSOLDES("103042")="\0.5\0"
 s ^TKSOLDES("85091")="\0.5\0"
 s ^TKSOLDES("85105")="\0.5\0"
 s ^TKSOLDES("85104")="\0.5\0"
 s ^TKSOLDES("85103")="\0.5\0"
 s ^TKSOLDES("85102")="\0.5\0"
 s ^TKSOLDES("85101")="\0.5\0"
 s ^TKSOLDES("85100")="\0.5\0"
 s ^TKSOLDES("85099")="\0.5\0"
 s ^TKSOLDES("85098")="\0.5\0"
 s ^TKSOLDES("85092")="\0.5\0"
 s ^TKSOLDES("85093")="\0.5\0"
 s ^TKSOLDES("85094")="\0.5\0"
 s ^TKSOLDES("85095")="\0.5\0"
 s ^TKSOLDES("85096")="\0.5\0"
 s ^TKSOLDES("85097")="\0.5\0"
 s ^TKSOLDES("103041")="\0.5\0"
 s ^TKSOLDES("103524")="\0.5\0"
 s ^TKSOLDES("84293")="\0.5\0"
 s ^TKSOLDES("103525")="\0.5\0"
 s ^TKSOLDES("84435")="\0.5\0"
 s ^TKSOLDES("84434")="\0.5\0"
 s ^TKSOLDES("84433")="\0.5\0"
 s ^TKSOLDES("84432")="\0.5\0"
 s ^TKSOLDES("84431")="\0.5\0"
 s ^TKSOLDES("84430")="\0.5\0"
 s ^TKSOLDES("84429")="\0.5\0"
 s ^TKSOLDES("84428")="\0.5\0"
 s ^TKSOLDES("84294")="\0.5\0"
 s ^TKSOLDES("84295")="\0.5\0"
 s ^TKSOLDES("84296")="\0.5\0"
 s ^TKSOLDES("84297")="\0.5\0"
 s ^TKSOLDES("84426")="\0.5\0"
 s ^TKSOLDES("84427")="\0.5\0"
 s ^TKSOLDES("84436")="\0.5\0"
 s ^TKSOLDES("84437")="\0.5\0"
 s ^TKSOLDES("84774")="\0.5\0"
 s ^TKSOLDES("103526")="\0.5\0"
 s ^TKSOLDES("103527")="\0.5\0"
 s ^TKSOLDES("103043")="\0.5\0"
 s ^TKSOLDES("103044")="\0.5\0"
 s ^TKSOLDES("84776")="\0.5\0"
 s ^TKSOLDES("84775")="\0.5\0"
 s ^TKSOLDES("84773")="\0.5\0"
 s ^TKSOLDES("84438")="\0.5\0"
 s ^TKSOLDES("84643")="\0.5\0"
 s ^TKSOLDES("84439")="\0.5\0"
 s ^TKSOLDES("84440")="\0.5\0"
 s ^TKSOLDES("84441")="\0.5\0"
 s ^TKSOLDES("84640")="\0.5\0"
 s ^TKSOLDES("84641")="\0.5\0"
 s ^TKSOLDES("84642")="\0.5\0"
 s ^TKSOLDES("82881")="\0.5\0"
 s ^TKSOLDES("82880")="\0.5\0"
 s ^TKSOLDES("81463")="\0.5\0"
 s ^TKSOLDES("81485")="\0.5\0"
 s ^TKSOLDES("81484")="\0.5\0"
 s ^TKSOLDES("81483")="\0.5\0"
 s ^TKSOLDES("81482")="\0.5\0"
 s ^TKSOLDES("81481")="\0.5\0"
 s ^TKSOLDES("81461")="\0.5\0"
 s ^TKSOLDES("103050")="\0.5\0"
 s ^TKSOLDES("81458")="\0.5\0"
 s ^TKSOLDES("81456")="\0.5\0"
 s ^TKSOLDES("81454")="\0.5\0"
 s ^TKSOLDES("81452")="\0.5\0"
 s ^TKSOLDES("81448")="\0.5\0"
 s ^TKSOLDES("81447")="\0.5\0"
 s ^TKSOLDES("103052")="\0.5\0"
 s ^TKSOLDES("103049")="\0.5\0"
 s ^TKSOLDES("82201")="\0.5\0"
 s ^TKSOLDES("81948")="\0.5\0"
 s ^TKSOLDES("103046")="\0.5\0"
 s ^TKSOLDES("82031")="\0.5\0"
 s ^TKSOLDES("82030")="\0.5\0"
 s ^TKSOLDES("82029")="\0.5\0"
 s ^TKSOLDES("82028")="\0.5\0"
 s ^TKSOLDES("82027")="\0.5\0"
 s ^TKSOLDES("82025")="\0.5\0"
 s ^TKSOLDES("82024")="\0.5\0"
 s ^TKSOLDES("81949")="\0.5\0"
 s ^TKSOLDES("81950")="\0.5\0"
 s ^TKSOLDES("81951")="\0.5\0"
 s ^TKSOLDES("103048")="\0.5\0"
 s ^TKSOLDES("103047")="\0.5\0"
 s ^TKSOLDES("82023")="\0.5\0"
 s ^TKSOLDES("81446")="\0.5\0"
 s ^TKSOLDES("81443")="\0.5\0"
 s ^TKSOLDES("81441")="\0.5\0"
 s ^TKSOLDES("81280")="\0.5\0"
 s ^TKSOLDES("81279")="\0.5\0"
 s ^TKSOLDES("81278")="\0.5\0"
 s ^TKSOLDES("81277")="\0.5\0"
 s ^TKSOLDES("81276")="\0.5\0"
 s ^TKSOLDES("81275")="\0.5\0"
 s ^TKSOLDES("81274")="\0.5\0"
 s ^TKSOLDES("81273")="\0.5\0"
 s ^TKSOLDES("81267")="\0.5\0"
 s ^TKSOLDES("81268")="\0.5\0"
 s ^TKSOLDES("81269")="\0.5\0"
 s ^TKSOLDES("81270")="\0.5\0"
 s ^TKSOLDES("81271")="\0.5\0"
 s ^TKSOLDES("81272")="\0.5\0"
 s ^TKSOLDES("81281")="\0.5\0"
 s ^TKSOLDES("81342")="\0.5\0"
 s ^TKSOLDES("81352")="\0.5\0"
 s ^TKSOLDES("81440")="\0.5\0"
 s ^TKSOLDES("81439")="\0.5\0"
 s ^TKSOLDES("81438")="\0.5\0"
 s ^TKSOLDES("81437")="\0.5\0"
 s ^TKSOLDES("81436")="\0.5\0"
 s ^TKSOLDES("81353")="\0.5\0"
 s ^TKSOLDES("81351")="\0.5\0"
 s ^TKSOLDES("81343")="\0.5\0"
 s ^TKSOLDES("81350")="\0.5\0"
 s ^TKSOLDES("81344")="\0.5\0"
 s ^TKSOLDES("81345")="\0.5\0"
 s ^TKSOLDES("81346")="\0.5\0"
 s ^TKSOLDES("81347")="\0.5\0"
 s ^TKSOLDES("81348")="\0.5\0"
 s ^TKSOLDES("81349")="\0.5\0"
 s ^TKSOLDES("103045")="\0.5\0"
 s ^TKSOLDES("82224")="\0.5\0"
 s ^TKSOLDES("82879")="\0.5\0"
 s ^TKSOLDES("82281")="\0.5\0"
 s ^TKSOLDES("82725")="\0.5\0"
 s ^TKSOLDES("82285")="\0.5\0"
 s ^TKSOLDES("82284")="\0.5\0"
 s ^TKSOLDES("82283")="\0.5\0"
 s ^TKSOLDES("82282")="\0.5\0"
 s ^TKSOLDES("82280")="\0.5\0"
 s ^TKSOLDES("82727")="\0.5\0"
 s ^TKSOLDES("82279")="\0.5\0"
 s ^TKSOLDES("82278")="\0.5\0"
 s ^TKSOLDES("82277")="\0.5\0"
 s ^TKSOLDES("82276")="\0.5\0"
 s ^TKSOLDES("82275")="\0.5\0"
 s ^TKSOLDES("82274")="\0.5\0"
 s ^TKSOLDES("82726")="\0.5\0"
 s ^TKSOLDES("82728")="\0.5\0"
 s ^TKSOLDES("82272")="\0.5\0"
 s ^TKSOLDES("82729")="\0.5\0"
 s ^TKSOLDES("82876")="\0.5\0"
 s ^TKSOLDES("82875")="\0.5\0"
 s ^TKSOLDES("82770")="\0.5\0"
 s ^TKSOLDES("82769")="\0.5\0"
 s ^TKSOLDES("82743")="\0.5\0"
 s ^TKSOLDES("82742")="\0.5\0"
 s ^TKSOLDES("82739")="\0.5\0"
 s ^TKSOLDES("82736")="\0.5\0"
 s ^TKSOLDES("82730")="\0.5\0"
 s ^TKSOLDES("82731")="\0.5\0"
 s ^TKSOLDES("82732")="\0.5\0"
 s ^TKSOLDES("82733")="\0.5\0"
 s ^TKSOLDES("82734")="\0.5\0"
 s ^TKSOLDES("82735")="\0.5\0"
 s ^TKSOLDES("82273")="\0.5\0"
 s ^TKSOLDES("82265")="\0.5\0"
 s ^TKSOLDES("82225")="\0.5\0"
 s ^TKSOLDES("82264")="\0.5\0"
 s ^TKSOLDES("82240")="\0.5\0"
 s ^TKSOLDES("82239")="\0.5\0"
 s ^TKSOLDES("82238")="\0.5\0"
 s ^TKSOLDES("82237")="\0.5\0"
 s ^TKSOLDES("82236")="\0.5\0"
 s ^TKSOLDES("82235")="\0.5\0"
 s ^TKSOLDES("82234")="\0.5\0"
 s ^TKSOLDES("82233")="\0.5\0"
 s ^TKSOLDES("82226")="\0.5\0"
 s ^TKSOLDES("82227")="\0.5\0"
 s ^TKSOLDES("82229")="\0.5\0"
 s ^TKSOLDES("82230")="\0.5\0"
 s ^TKSOLDES("82231")="\0.5\0"
 s ^TKSOLDES("82232")="\0.5\0"
 s ^TKSOLDES("82241")="\0.5\0"
 s ^TKSOLDES("82242")="\0.5\0"
 s ^TKSOLDES("82257")="\0.5\0"
 s ^TKSOLDES("82263")="\0.5\0"
 s ^TKSOLDES("82262")="\0.5\0"
 s ^TKSOLDES("82261")="\0.5\0"
 s ^TKSOLDES("82260")="\0.5\0"
 s ^TKSOLDES("82259")="\0.5\0"
 s ^TKSOLDES("82258")="\0.5\0"
 s ^TKSOLDES("82256")="\0.5\0"
 s ^TKSOLDES("82248")="\0.5\0"
 s ^TKSOLDES("82255")="\0.5\0"
 s ^TKSOLDES("82249")="\0.5\0"
 s ^TKSOLDES("82250")="\0.5\0"
 s ^TKSOLDES("82251")="\0.5\0"
 s ^TKSOLDES("82252")="\0.5\0"
 s ^TKSOLDES("82253")="\0.5\0"
 s ^TKSOLDES("82254")="\0.5\0"
 s ^TKSOLDES("85106")="\0.5\0"
 s ^TKSOLDES("85107")="\0.5\0"
 s ^TKSOLDES("100343")="\0.5\0"
 s ^TKSOLDES("100349")="\0.5\0"
 s ^TKSOLDES("100348")="\0.5\0"
 s ^TKSOLDES("100347")="\0.5\0"
 s ^TKSOLDES("100346")="\0.5\0"
 s ^TKSOLDES("100345")="\0.5\0"
 s ^TKSOLDES("100342")="\0.5\0"
 s ^TKSOLDES("100355")="\0.5\0"
 s ^TKSOLDES("103238")="\0.5\0"
 s ^TKSOLDES("100340")="\0.5\0"
 s ^TKSOLDES("100339")="\0.5\0"
 s ^TKSOLDES("100338")="\0.5\0"
 s ^TKSOLDES("100337")="\0.5\0"
 s ^TKSOLDES("100335")="\0.5\0"
 s ^TKSOLDES("100353")="\0.5\0"
 s ^TKSOLDES("100357")="\0.5\0"
 s ^TKSOLDES("93639")="\0.5\0"
 s ^TKSOLDES("100358")="\0.5\0"
 s ^TKSOLDES("103233")="\0.5\0"
 s ^TKSOLDES("100456")="\0.5\0"
 s ^TKSOLDES("100455")="\0.5\0"
 s ^TKSOLDES("100454")="\0.5\0"
 s ^TKSOLDES("100452")="\0.5\0"
 s ^TKSOLDES("103235")="\0.5\0"
 s ^TKSOLDES("103236")="\0.5\0"
 s ^TKSOLDES("100367")="\0.5\0"
 s ^TKSOLDES("100359")="\0.5\0"
 s ^TKSOLDES("100360")="\0.5\0"
 s ^TKSOLDES("100361")="\0.5\0"
 s ^TKSOLDES("100364")="\0.5\0"
 s ^TKSOLDES("100365")="\0.5\0"
 s ^TKSOLDES("100366")="\0.5\0"
 s ^TKSOLDES("100334")="\0.5\0"
 s ^TKSOLDES("100333")="\0.5\0"
 s ^TKSOLDES("100332")="\0.5\0"
 s ^TKSOLDES("93661")="\0.5\0"
 s ^TKSOLDES("93660")="\0.5\0"
 s ^TKSOLDES("93659")="\0.5\0"
 s ^TKSOLDES("93657")="\0.5\0"
 s ^TKSOLDES("93656")="\0.5\0"
 s ^TKSOLDES("93655")="\0.5\0"
 s ^TKSOLDES("93654")="\0.5\0"
 s ^TKSOLDES("93653")="\0.5\0"
 s ^TKSOLDES("93643")="\0.5\0"
 s ^TKSOLDES("93644")="\0.5\0"
 s ^TKSOLDES("93649")="\0.5\0"
 s ^TKSOLDES("93650")="\0.5\0"
 s ^TKSOLDES("93651")="\0.5\0"
 s ^TKSOLDES("93652")="\0.5\0"
 s ^TKSOLDES("93662")="\0.5\0"
 s ^TKSOLDES("93664")="\0.5\0"
 s ^TKSOLDES("100325")="\0.5\0"
 s ^TKSOLDES("100331")="\0.5\0"
 s ^TKSOLDES("100330")="\0.5\0"
 s ^TKSOLDES("100329")="\0.5\0"
 s ^TKSOLDES("100328")="\0.5\0"
 s ^TKSOLDES("100327")="\0.5\0"
 s ^TKSOLDES("100326")="\0.5\0"
 s ^TKSOLDES("100324")="\0.5\0"
 s ^TKSOLDES("93665")="\0.5\0"
 s ^TKSOLDES("100323")="\0.5\0"
 s ^TKSOLDES("93669")="\0.5\0"
 s ^TKSOLDES("93670")="\0.5\0"
 s ^TKSOLDES("93672")="\0.5\0"
 s ^TKSOLDES("100320")="\0.5\0"
 s ^TKSOLDES("100321")="\0.5\0"
 s ^TKSOLDES("100322")="\0.5\0"
 s ^TKSOLDES("103231")="\0.5\0"
 s ^TKSOLDES("103230")="\0.5\0"
 s ^TKSOLDES("102312")="\0.5\0"
 s ^TKSOLDES("102320")="\0.5\0"
 s ^TKSOLDES("102319")="\0.5\0"
 s ^TKSOLDES("102317")="\0.5\0"
 s ^TKSOLDES("102315")="\0.5\0"
 s ^TKSOLDES("102314")="\0.5\0"
 s ^TKSOLDES("102311")="\0.5\0"
 s ^TKSOLDES("102323")="\0.5\0"
 s ^TKSOLDES("102310")="\0.5\0"
 s ^TKSOLDES("102308")="\0.5\0"
 s ^TKSOLDES("102307")="\0.5\0"
 s ^TKSOLDES("102288")="\0.5\0"
 s ^TKSOLDES("102287")="\0.5\0"
 s ^TKSOLDES("102281")="\0.5\0"
 s ^TKSOLDES("102321")="\0.5\0"
 s ^TKSOLDES("102325")="\0.5\0"
 s ^TKSOLDES("102279")="\0.5\0"
 s ^TKSOLDES("102326")="\0.5\0"
 s ^TKSOLDES("103023")="\0.5\0"
 s ^TKSOLDES("103022")="\0.5\0"
 s ^TKSOLDES("102546")="\0.5\0"
 s ^TKSOLDES("102545")="\0.5\0"
 s ^TKSOLDES("102544")="\0.5\0"
 s ^TKSOLDES("102543")="\0.5\0"
 s ^TKSOLDES("102542")="\0.5\0"
 s ^TKSOLDES("102541")="\0.5\0"
 s ^TKSOLDES("102328")="\0.5\0"
 s ^TKSOLDES("102330")="\0.5\0"
 s ^TKSOLDES("102331")="\0.5\0"
 s ^TKSOLDES("102340")="\0.5\0"
 s ^TKSOLDES("102341")="\0.5\0"
 s ^TKSOLDES("102539")="\0.5\0"
 s ^TKSOLDES("102280")="\0.5\0"
 s ^TKSOLDES("102264")="\0.5\0"
 s ^TKSOLDES("103112")="\0.5\0"
 s ^TKSOLDES("102261")="\0.5\0"
 s ^TKSOLDES("100729")="\0.5\0"
 s ^TKSOLDES("100728")="\0.5\0"
 s ^TKSOLDES("100727")="\0.5\0"
 s ^TKSOLDES("100726")="\0.5\0"
 s ^TKSOLDES("103099")="\0.5\0"
 s ^TKSOLDES("103101")="\0.5\0"
 s ^TKSOLDES("103103")="\0.5\0"
 s ^TKSOLDES("103104")="\0.5\0"
 s ^TKSOLDES("103111")="\0.5\0"
 s ^TKSOLDES("103110")="\0.5\0"
 s ^TKSOLDES("103109")="\0.5\0"
 s ^TKSOLDES("103108")="\0.5\0"
 s ^TKSOLDES("103107")="\0.5\0"
 s ^TKSOLDES("103105")="\0.5\0"
 s ^TKSOLDES("100733")="\0.5\0"
 s ^TKSOLDES("100734")="\0.5\0"
 s ^TKSOLDES("101163")="\0.5\0"
 s ^TKSOLDES("102259")="\0.5\0"
 s ^TKSOLDES("101450")="\0.5\0"
 s ^TKSOLDES("101449")="\0.5\0"
 s ^TKSOLDES("101192")="\0.5\0"
 s ^TKSOLDES("101172")="\0.5\0"
 s ^TKSOLDES("101164")="\0.5\0"
 s ^TKSOLDES("101162")="\0.5\0"
 s ^TKSOLDES("100735")="\0.5\0"
 s ^TKSOLDES("101161")="\0.5\0"
 s ^TKSOLDES("100736")="\0.5\0"
 s ^TKSOLDES("100737")="\0.5\0"
 s ^TKSOLDES("101003")="\0.5\0"
 s ^TKSOLDES("101142")="\0.5\0"
 s ^TKSOLDES("101143")="\0.5\0"
 s ^TKSOLDES("101158")="\0.5\0"
 s ^TKSOLDES("93641")="\0.5\0"
 s ^TKSOLDES("93638")="\0.5\0"
 s ^TKSOLDES("85108")="\0.5\0"
 s ^TKSOLDES("86485")="\0.5\0"
 s ^TKSOLDES("86912")="\0.5\0"
 s ^TKSOLDES("86910")="\0.5\0"
 s ^TKSOLDES("86904")="\0.5\0"
 s ^TKSOLDES("103285")="\0.5\0"
 s ^TKSOLDES("103298")="\0.5\0"
 s ^TKSOLDES("86484")="\0.5\0"
 s ^TKSOLDES("86917")="\0.5\0"
 s ^TKSOLDES("103025")="\0.5\0"
 s ^TKSOLDES("86186")="\0.5\0"
 s ^TKSOLDES("103027")="\0.5\0"
 s ^TKSOLDES("103028")="\0.5\0"
 s ^TKSOLDES("103039")="\0.5\0"
 s ^TKSOLDES("85912")="\0.5\0"
 s ^TKSOLDES("86916")="\0.5\0"
 s ^TKSOLDES("86919")="\0.5\0"
 s ^TKSOLDES("87185")="\0.5\0"
 s ^TKSOLDES("86920")="\0.5\0"
 s ^TKSOLDES("87183")="\0.5\0"
 s ^TKSOLDES("87182")="\0.5\0"
 s ^TKSOLDES("87181")="\0.5\0"
 s ^TKSOLDES("87180")="\0.5\0"
 s ^TKSOLDES("87179")="\0.5\0"
 s ^TKSOLDES("87178")="\0.5\0"
 s ^TKSOLDES("87177")="\0.5\0"
 s ^TKSOLDES("87140")="\0.5\0"
 s ^TKSOLDES("86921")="\0.5\0"
 s ^TKSOLDES("86922")="\0.5\0"
 s ^TKSOLDES("87135")="\0.5\0"
 s ^TKSOLDES("87136")="\0.5\0"
 s ^TKSOLDES("87138")="\0.5\0"
 s ^TKSOLDES("87139")="\0.5\0"
 s ^TKSOLDES("85614")="\0.5\0"
 s ^TKSOLDES("85613")="\0.5\0"
 s ^TKSOLDES("85612")="\0.5\0"
 s ^TKSOLDES("85137")="\0.5\0"
 s ^TKSOLDES("85136")="\0.5\0"
 s ^TKSOLDES("85135")="\0.5\0"
 s ^TKSOLDES("85134")="\0.5\0"
 s ^TKSOLDES("85118")="\0.5\0"
 s ^TKSOLDES("85117")="\0.5\0"
 s ^TKSOLDES("85116")="\0.5\0"
 s ^TKSOLDES("85115")="\0.5\0"
 s ^TKSOLDES("85109")="\0.5\0"
 s ^TKSOLDES("85110")="\0.5\0"
 s ^TKSOLDES("85111")="\0.5\0"
 s ^TKSOLDES("85112")="\0.5\0"
 s ^TKSOLDES("85113")="\0.5\0"
 s ^TKSOLDES("85114")="\0.5\0"
 s ^TKSOLDES("85567")="\0.5\0"
 s ^TKSOLDES("85568")="\0.5\0"
 s ^TKSOLDES("85599")="\0.5\0"
 s ^TKSOLDES("85611")="\0.5\0"
 s ^TKSOLDES("85610")="\0.5\0"
 s ^TKSOLDES("85609")="\0.5\0"
 s ^TKSOLDES("85608")="\0.5\0"
 s ^TKSOLDES("85607")="\0.5\0"
 s ^TKSOLDES("85601")="\0.5\0"
 s ^TKSOLDES("85598")="\0.5\0"
 s ^TKSOLDES("85569")="\0.5\0"
 s ^TKSOLDES("85596")="\0.5\0"
 s ^TKSOLDES("85570")="\0.5\0"
 s ^TKSOLDES("85571")="\0.5\0"
 s ^TKSOLDES("85572")="\0.5\0"
 s ^TKSOLDES("85573")="\0.5\0"
 s ^TKSOLDES("85574")="\0.5\0"
 s ^TKSOLDES("85595")="\0.5\0"
 s ^TKSOLDES("87184")="\0.5\0"
 s ^TKSOLDES("87186")="\0.5\0"
 s ^TKSOLDES("93637")="\0.5\0"
 s ^TKSOLDES("87904")="\0.5\0"
 s ^TKSOLDES("87909")="\0.5\0"
 s ^TKSOLDES("87908")="\0.5\0"
 s ^TKSOLDES("87907")="\0.5\0"
 s ^TKSOLDES("87906")="\0.5\0"
 s ^TKSOLDES("87905")="\0.5\0"
 s ^TKSOLDES("87903")="\0.5\0"
 s ^TKSOLDES("87911")="\0.5\0"
 s ^TKSOLDES("87902")="\0.5\0"
 s ^TKSOLDES("87901")="\0.5\0"
 s ^TKSOLDES("87900")="\0.5\0"
 s ^TKSOLDES("87879")="\0.5\0"
 s ^TKSOLDES("87878")="\0.5\0"
 s ^TKSOLDES("87877")="\0.5\0"
 s ^TKSOLDES("87910")="\0.5\0"
 s ^TKSOLDES("87912")="\0.5\0"
 s ^TKSOLDES("87875")="\0.5\0"
 s ^TKSOLDES("87913")="\0.5\0"
 s ^TKSOLDES("93635")="\0.5\0"
 s ^TKSOLDES("93633")="\0.5\0"
 s ^TKSOLDES("93632")="\0.5\0"
 s ^TKSOLDES("93631")="\0.5\0"
 s ^TKSOLDES("93621")="\0.5\0"
 s ^TKSOLDES("93620")="\0.5\0"
 s ^TKSOLDES("93619")="\0.5\0"
 s ^TKSOLDES("103240")="\0.5\0"
 s ^TKSOLDES("87915")="\0.5\0"
 s ^TKSOLDES("103284")="\0.5\0"
 s ^TKSOLDES("103279")="\0.5\0"
 s ^TKSOLDES("103272")="\0.5\0"
 s ^TKSOLDES("103271")="\0.5\0"
 s ^TKSOLDES("103269")="\0.5\0"
 s ^TKSOLDES("87876")="\0.5\0"
 s ^TKSOLDES("87874")="\0.5\0"
 s ^TKSOLDES("87187")="\0.5\0"
 s ^TKSOLDES("87873")="\0.5\0"
 s ^TKSOLDES("87202")="\0.5\0"
 s ^TKSOLDES("87200")="\0.5\0"
 s ^TKSOLDES("87199")="\0.5\0"
 s ^TKSOLDES("87198")="\0.5\0"
 s ^TKSOLDES("87197")="\0.5\0"
 s ^TKSOLDES("87196")="\0.5\0"
 s ^TKSOLDES("87195")="\0.5\0"
 s ^TKSOLDES("87194")="\0.5\0"
 s ^TKSOLDES("87188")="\0.5\0"
 s ^TKSOLDES("87189")="\0.5\0"
 s ^TKSOLDES("87190")="\0.5\0"
 s ^TKSOLDES("87191")="\0.5\0"
 s ^TKSOLDES("87192")="\0.5\0"
 s ^TKSOLDES("87193")="\0.5\0"
 s ^TKSOLDES("87203")="\0.5\0"
 s ^TKSOLDES("87205")="\0.5\0"
 s ^TKSOLDES("87851")="\0.5\0"
 s ^TKSOLDES("87857")="\0.5\0"
 s ^TKSOLDES("87856")="\0.5\0"
 s ^TKSOLDES("87855")="\0.5\0"
 s ^TKSOLDES("87854")="\0.5\0"
 s ^TKSOLDES("87853")="\0.5\0"
 s ^TKSOLDES("87852")="\0.5\0"
 s ^TKSOLDES("87850")="\0.5\0"
 s ^TKSOLDES("87206")="\0.5\0"
 s ^TKSOLDES("87391")="\0.5\0"
 s ^TKSOLDES("87207")="\0.5\0"
 s ^TKSOLDES("87313")="\0.5\0"
 s ^TKSOLDES("87314")="\0.5\0"
 s ^TKSOLDES("87315")="\0.5\0"
 s ^TKSOLDES("87388")="\0.5\0"
 s ^TKSOLDES("87390")="\0.5\0"
 s ^TKSOLDES("81266")="\0.5\0"
 s ^TKSOLDES("79038")="\0.5\0"
 s ^TKSOLDES("81091")="\0.5\0"
 s ^TKSOLDES("81094")="\0.5\0"
 s ^TKSOLDES("81095")="\0.5\0"
 s ^TKSOLDES("81096")="\0.5\0"
 s ^TKSOLDES("81097")="\0.5\0"
 s ^TKSOLDES("81098")="\0.5\0"
 s ^TKSOLDES("81099")="\0.5\0"
 s ^TKSOLDES("81102")="\0.5\0"
 s ^TKSOLDES("81103")="\0.5\0"
 s ^TKSOLDES("81108")="\0.5\0"
 s ^TKSOLDES("81107")="\0.5\0"
 s ^TKSOLDES("81106")="\0.5\0"
 s ^TKSOLDES("81105")="\0.5\0"
 s ^TKSOLDES("104158")="\0.5\0"
 s ^TKSOLDES("81104")="\0.5\0"
 s ^TKSOLDES("81093")="\0.5\0"
 s ^TKSOLDES("81088")="\0.5\0"
 s ^TKSOLDES("103071")="\0.5\0"
 s ^TKSOLDES("81076")="\0.5\0"
 s ^TKSOLDES("103073")="\0.5\0"
 s ^TKSOLDES("104497")="\0.5\0"
 s ^TKSOLDES("81072")="\0.5\0"
 s ^TKSOLDES("81073")="\0.5\0"
 s ^TKSOLDES("81074")="\0.5\0"
 s ^TKSOLDES("81075")="\0.5\0"
 s ^TKSOLDES("81077")="\0.5\0"
 s ^TKSOLDES("81087")="\0.5\0"
 s ^TKSOLDES("81078")="\0.5\0"
 s ^TKSOLDES("81085")="\0.5\0"
 s ^TKSOLDES("81084")="\0.5\0"
 s ^TKSOLDES("81083")="\0.5\0"
 s ^TKSOLDES("81081")="\0.5\0"
 s ^TKSOLDES("81080")="\0.5\0"
 s ^TKSOLDES("81079")="\0.5\0"
 s ^TKSOLDES("81109")="\0.5\0"
 s ^TKSOLDES("81110")="\0.5\0"
 s ^TKSOLDES("81164")="\0.5\0"
 s ^TKSOLDES("81158")="\0.5\0"
 s ^TKSOLDES("81159")="\0.5\0"
 s ^TKSOLDES("81160")="\0.5\0"
 s ^TKSOLDES("81161")="\0.5\0"
 s ^TKSOLDES("81162")="\0.5\0"
 s ^TKSOLDES("81163")="\0.5\0"
 s ^TKSOLDES("81165")="\0.5\0"
 s ^TKSOLDES("103055")="\0.5\0"
 s ^TKSOLDES("81166")="\0.5\0"
 s ^TKSOLDES("81174")="\0.5\0"
 s ^TKSOLDES("81173")="\0.5\0"
 s ^TKSOLDES("81172")="\0.5\0"
 s ^TKSOLDES("81171")="\0.5\0"
 s ^TKSOLDES("81170")="\0.5\0"
 s ^TKSOLDES("81169")="\0.5\0"
 s ^TKSOLDES("81157")="\0.5\0"
 s ^TKSOLDES("81154")="\0.5\0"
 s ^TKSOLDES("81153")="\0.5\0"
 s ^TKSOLDES("81152")="\0.5\0"
 s ^TKSOLDES("81151")="\0.5\0"
 s ^TKSOLDES("81150")="\0.5\0"
 s ^TKSOLDES("81113")="\0.5\0"
 s ^TKSOLDES("81111")="\0.5\0"
 s ^TKSOLDES("80235")="\0.5\0"
 s ^TKSOLDES("80236")="\0.5\0"
 s ^TKSOLDES("80238")="\0.5\0"
 s ^TKSOLDES("80309")="\0.5\0"
 s ^TKSOLDES("80311")="\0.5\0"
 s ^TKSOLDES("80310")="\0.5\0"
 s ^TKSOLDES("80308")="\0.5\0"
 s ^TKSOLDES("80305")="\0.5\0"
 s ^TKSOLDES("81262")="\0.5\0"
 s ^TKSOLDES("80307")="\0.5\0"
 s ^TKSOLDES("80306")="\0.5\0"
 s ^TKSOLDES("103072")="\0.5\0"
 s ^TKSOLDES("103070")="\0.5\0"
 s ^TKSOLDES("81176")="\0.5\0"
 s ^TKSOLDES("80813")="\0.5\0"
 s ^TKSOLDES("79747")="\0.5\0"
 s ^TKSOLDES("79743")="\0.5\0"
 s ^TKSOLDES("79742")="\0.5\0"
 s ^TKSOLDES("79740")="\0.5\0"
 s ^TKSOLDES("79739")="\0.5\0"
 s ^TKSOLDES("79737")="\0.5\0"
 s ^TKSOLDES("104461")="\0.5\0"
 s ^TKSOLDES("104463")="\0.5\0"
 s ^TKSOLDES("103053")="\0.5\0"
 s ^TKSOLDES("103054")="\0.5\0"
 s ^TKSOLDES("104467")="\0.5\0"
 s ^TKSOLDES("104466")="\0.5\0"
 s ^TKSOLDES("104465")="\0.5\0"
 s ^TKSOLDES("104464")="\0.5\0"
 s ^TKSOLDES("80814")="\0.5\0"
 s ^TKSOLDES("80812")="\0.5\0"
 s ^TKSOLDES("104185")="\0.5\0"
 s ^TKSOLDES("79768")="\0.5\0"
 s ^TKSOLDES("104186")="\0.5\0"
 s ^TKSOLDES("80635")="\0.5\0"
 s ^TKSOLDES("80639")="\0.5\0"
 s ^TKSOLDES("80640")="\0.5\0"
 s ^TKSOLDES("104187")="\0.5\0"
 s ^TKSOLDES("104188")="\0.5\0"
 s ^TKSOLDES("79750")="\0.5\0"
 s ^TKSOLDES("80811")="\0.5\0"
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 