ROUTINE OPESOLDES50PE13P2
OPESOLDES50PE13P2
 
	s ^TKSOLDES("62250")="\0.5\0"
	s ^TKSOLDES("62251")="\0.5\0"
	s ^TKSOLDES("72847")="\0.5\0"
	s ^TKSOLDES("72848")="\0.5\0"
	s ^TKSOLDES("38379")="\0.5\0"
	s ^TKSOLDES("68152")="\0.5\0"
	s ^TKSOLDES("68153")="\0.5\0"
	s ^TKSOLDES("68154")="\0.5\0"
	s ^TKSOLDES("68155")="\0.5\0"
	s ^TKSOLDES("68156")="\0.5\0"
	s ^TKSOLDES("38378")="\0.5\0"
	s ^TKSOLDES("38375")="\0.5\0"
	s ^TKSOLDES("38374")="\0.5\0"
	s ^TKSOLDES("38373")="\0.5\0"
	s ^TKSOLDES("38372")="\0.5\0"
	s ^TKSOLDES("38371")="\0.5\0"
	s ^TKSOLDES("38370")="\0.5\0"
	s ^TKSOLDES("68151")="\0.5\0"
	s ^TKSOLDES("68150")="\0.5\0"
	s ^TKSOLDES("38368")="\0.5\0"
	s ^TKSOLDES("74984")="\0.5\0"
	s ^TKSOLDES("74988")="\0.5\0"
	s ^TKSOLDES("68147")="\0.5\0"
	s ^TKSOLDES("74987")="\0.5\0"
	s ^TKSOLDES("74986")="\0.5\0"
	s ^TKSOLDES("74985")="\0.5\0"
	s ^TKSOLDES("74983")="\0.5\0"
	s ^TKSOLDES("68149")="\0.5\0"
	s ^TKSOLDES("74982")="\0.5\0"
	s ^TKSOLDES("74981")="\0.5\0"
	s ^TKSOLDES("74980")="\0.5\0"
	s ^TKSOLDES("74979")="\0.5\0"
	s ^TKSOLDES("74978")="\0.5\0"
	s ^TKSOLDES("68148")="\0.5\0"
	s ^TKSOLDES("38369")="\0.5\0"
	s ^TKSOLDES("38367")="\0.5\0"
	s ^TKSOLDES("38437")="\0.5\0"
	s ^TKSOLDES("68161")="\0.5\0"
	s ^TKSOLDES("38324")="\0.5\0"
	s ^TKSOLDES("68157")="\0.5\0"
	s ^TKSOLDES("68158")="\0.5\0"
	s ^TKSOLDES("68159")="\0.5\0"
	s ^TKSOLDES("68160")="\0.5\0"
	s ^TKSOLDES("68162")="\0.5\0"
	s ^TKSOLDES("38366")="\0.5\0"
	s ^TKSOLDES("83533")="\0.5\0"
	s ^TKSOLDES("68163")="\0.5\0"
	s ^TKSOLDES("17488")="\0.5\0"
	s ^TKSOLDES("17487")="\0.5\0"
	s ^TKSOLDES("17485")="\0.5\0"
	s ^TKSOLDES("17484")="\0.5\0"
	s ^TKSOLDES("38325")="\0.5\0"
	s ^TKSOLDES("38327")="\0.5\0"
	s ^TKSOLDES("38332")="\0.5\0"
	s ^TKSOLDES("38365")="\0.5\0"
	s ^TKSOLDES("38364")="\0.5\0"
	s ^TKSOLDES("38363")="\0.5\0"
	s ^TKSOLDES("38360")="\0.5\0"
	s ^TKSOLDES("38353")="\0.5\0"
	s ^TKSOLDES("38350")="\0.5\0"
	s ^TKSOLDES("38349")="\0.5\0"
	s ^TKSOLDES("38348")="\0.5\0"
	s ^TKSOLDES("38338")="\0.5\0"
	s ^TKSOLDES("38341")="\0.5\0"
	s ^TKSOLDES("38342")="\0.5\0"
	s ^TKSOLDES("38343")="\0.5\0"
	s ^TKSOLDES("38345")="\0.5\0"
	s ^TKSOLDES("38347")="\0.5\0"
	s ^TKSOLDES("74989")="\0.5\0"
	s ^TKSOLDES("74990")="\0.5\0"
	s ^TKSOLDES("38421")="\0.5\0"
	s ^TKSOLDES("75005")="\0.5\0"
	s ^TKSOLDES("75004")="\0.5\0"
	s ^TKSOLDES("38422")="\0.5\0"
	s ^TKSOLDES("104728")="\0.5\0"
	s ^TKSOLDES("75003")="\0.5\0"
	s ^TKSOLDES("75002")="\0.5\0"
	s ^TKSOLDES("74991")="\0.5\0"
	s ^TKSOLDES("75001")="\0.5\0"
	s ^TKSOLDES("75000")="\0.5\0"
	s ^TKSOLDES("74999")="\0.5\0"
	s ^TKSOLDES("74998")="\0.5\0"
	s ^TKSOLDES("38420")="\0.5\0"
	s ^TKSOLDES("38419")="\0.5\0"
	s ^TKSOLDES("75006")="\0.5\0"
	s ^TKSOLDES("68146")="\0.5\0"
	s ^TKSOLDES("68145")="\0.5\0"
	s ^TKSOLDES("72849")="\0.5\0"
	s ^TKSOLDES("38434")="\0.5\0"
	s ^TKSOLDES("38433")="\0.5\0"
	s ^TKSOLDES("38432")="\0.5\0"
	s ^TKSOLDES("38431")="\0.5\0"
	s ^TKSOLDES("38430")="\0.5\0"
	s ^TKSOLDES("38429")="\0.5\0"
	s ^TKSOLDES("38428")="\0.5\0"
	s ^TKSOLDES("68144")="\0.5\0"
	s ^TKSOLDES("38423")="\0.5\0"
	s ^TKSOLDES("38424")="\0.5\0"
	s ^TKSOLDES("38425")="\0.5\0"
	s ^TKSOLDES("38426")="\0.5\0"
	s ^TKSOLDES("38427")="\0.5\0"
	s ^TKSOLDES("38418")="\0.5\0"
	s ^TKSOLDES("38417")="\0.5\0"
	s ^TKSOLDES("38381")="\0.5\0"
	s ^TKSOLDES("38388")="\0.5\0"
	s ^TKSOLDES("38387")="\0.5\0"
	s ^TKSOLDES("38386")="\0.5\0"
	s ^TKSOLDES("38385")="\0.5\0"
	s ^TKSOLDES("38383")="\0.5\0"
	s ^TKSOLDES("38380")="\0.5\0"
	s ^TKSOLDES("38390")="\0.5\0"
	s ^TKSOLDES("74997")="\0.5\0"
	s ^TKSOLDES("74996")="\0.5\0"
	s ^TKSOLDES("74995")="\0.5\0"
	s ^TKSOLDES("74994")="\0.5\0"
	s ^TKSOLDES("74993")="\0.5\0"
	s ^TKSOLDES("74992")="\0.5\0"
	s ^TKSOLDES("38389")="\0.5\0"
	s ^TKSOLDES("38391")="\0.5\0"
	s ^TKSOLDES("38416")="\0.5\0"
	s ^TKSOLDES("38393")="\0.5\0"
	s ^TKSOLDES("38415")="\0.5\0"
	s ^TKSOLDES("38414")="\0.5\0"
	s ^TKSOLDES("38413")="\0.5\0"
	s ^TKSOLDES("38411")="\0.5\0"
	s ^TKSOLDES("38409")="\0.5\0"
	s ^TKSOLDES("38408")="\0.5\0"
	s ^TKSOLDES("38406")="\0.5\0"
	s ^TKSOLDES("38404")="\0.5\0"
	s ^TKSOLDES("38394")="\0.5\0"
	s ^TKSOLDES("38395")="\0.5\0"
	s ^TKSOLDES("38396")="\0.5\0"
	s ^TKSOLDES("38397")="\0.5\0"
	s ^TKSOLDES("38400")="\0.5\0"
	s ^TKSOLDES("38403")="\0.5\0"
	s ^TKSOLDES("17483")="\0.5\0"
	s ^TKSOLDES("17482")="\0.5\0"
	s ^TKSOLDES("83409")="\0.5\0"
	s ^TKSOLDES("83407")="\0.5\0"
	s ^TKSOLDES("83406")="\0.5\0"
	s ^TKSOLDES("83405")="\0.5\0"
	s ^TKSOLDES("83404")="\0.5\0"
	s ^TKSOLDES("83403")="\0.5\0"
	s ^TKSOLDES("83402")="\0.5\0"
	s ^TKSOLDES("83401")="\0.5\0"
	s ^TKSOLDES("83399")="\0.5\0"
	s ^TKSOLDES("83398")="\0.5\0"
	s ^TKSOLDES("83397")="\0.5\0"
	s ^TKSOLDES("83396")="\0.5\0"
	s ^TKSOLDES("102499")="\0.5\0"
	s ^TKSOLDES("83408")="\0.5\0"
	s ^TKSOLDES("83410")="\0.5\0"
	s ^TKSOLDES("102501")="\0.5\0"
	s ^TKSOLDES("83419")="\0.5\0"
	s ^TKSOLDES("83424")="\0.5\0"
	s ^TKSOLDES("83423")="\0.5\0"
	s ^TKSOLDES("83422")="\0.5\0"
	s ^TKSOLDES("83421")="\0.5\0"
	s ^TKSOLDES("83420")="\0.5\0"
	s ^TKSOLDES("83418")="\0.5\0"
	s ^TKSOLDES("83411")="\0.5\0"
	s ^TKSOLDES("83417")="\0.5\0"
	s ^TKSOLDES("83416")="\0.5\0"
	s ^TKSOLDES("83415")="\0.5\0"
	s ^TKSOLDES("83414")="\0.5\0"
	s ^TKSOLDES("83413")="\0.5\0"
	s ^TKSOLDES("83412")="\0.5\0"
	s ^TKSOLDES("102500")="\0.5\0"
	s ^TKSOLDES("102502")="\0.5\0"
	s ^TKSOLDES("83426")="\0.5\0"
	s ^TKSOLDES("102526")="\0.5\0"
	s ^TKSOLDES("102521")="\0.5\0"
	s ^TKSOLDES("102522")="\0.5\0"
	s ^TKSOLDES("102523")="\0.5\0"
	s ^TKSOLDES("102524")="\0.5\0"
	s ^TKSOLDES("102525")="\0.5\0"
	s ^TKSOLDES("83395")="\0.5\0"
	s ^TKSOLDES("102503")="\0.5\0"
	s ^TKSOLDES("83394")="\0.5\0"
	s ^TKSOLDES("83393")="\0.5\0"
	s ^TKSOLDES("83392")="\0.5\0"
	s ^TKSOLDES("68165")="\0.5\0"
	s ^TKSOLDES("68166")="\0.5\0"
	s ^TKSOLDES("68167")="\0.5\0"
	s ^TKSOLDES("102520")="\0.5\0"
	s ^TKSOLDES("102519")="\0.5\0"
	s ^TKSOLDES("102518")="\0.5\0"
	s ^TKSOLDES("102504")="\0.5\0"
	s ^TKSOLDES("102505")="\0.5\0"
	s ^TKSOLDES("102506")="\0.5\0"
	s ^TKSOLDES("102507")="\0.5\0"
	s ^TKSOLDES("102508")="\0.5\0"
	s ^TKSOLDES("102509")="\0.5\0"
	s ^TKSOLDES("102510")="\0.5\0"
	s ^TKSOLDES("102511")="\0.5\0"
	s ^TKSOLDES("102517")="\0.5\0"
	s ^TKSOLDES("102516")="\0.5\0"
	s ^TKSOLDES("102515")="\0.5\0"
	s ^TKSOLDES("102514")="\0.5\0"
	s ^TKSOLDES("102513")="\0.5\0"
	s ^TKSOLDES("102512")="\0.5\0"
	s ^TKSOLDES("83425")="\0.5\0"
	s ^TKSOLDES("83427")="\0.5\0"
	s ^TKSOLDES("17481")="\0.5\0"
	s ^TKSOLDES("17255")="\0.5\0"
	s ^TKSOLDES("17260")="\0.5\0"
	s ^TKSOLDES("17259")="\0.5\0"
	s ^TKSOLDES("17258")="\0.5\0"
	s ^TKSOLDES("17257")="\0.5\0"
	s ^TKSOLDES("17256")="\0.5\0"
	s ^TKSOLDES("17254")="\0.5\0"
	s ^TKSOLDES("83428")="\0.5\0"
	s ^TKSOLDES("68164")="\0.5\0"
	s ^TKSOLDES("17253")="\0.5\0"
	s ^TKSOLDES("83468")="\0.5\0"
	s ^TKSOLDES("17252")="\0.5\0"
	s ^TKSOLDES("83465")="\0.5\0"
	s ^TKSOLDES("17250")="\0.5\0"
	s ^TKSOLDES("17262")="\0.5\0"
	s ^TKSOLDES("17263")="\0.5\0"
	s ^TKSOLDES("17392")="\0.5\0"
	s ^TKSOLDES("17480")="\0.5\0"
	s ^TKSOLDES("17479")="\0.5\0"
	s ^TKSOLDES("17478")="\0.5\0"
	s ^TKSOLDES("17477")="\0.5\0"
	s ^TKSOLDES("17475")="\0.5\0"
	s ^TKSOLDES("17474")="\0.5\0"
	s ^TKSOLDES("17473")="\0.5\0"
	s ^TKSOLDES("17472")="\0.5\0"
	s ^TKSOLDES("17393")="\0.5\0"
	s ^TKSOLDES("17394")="\0.5\0"
	s ^TKSOLDES("17401")="\0.5\0"
	s ^TKSOLDES("17403")="\0.5\0"
	s ^TKSOLDES("17469")="\0.5\0"
	s ^TKSOLDES("17471")="\0.5\0"
	s ^TKSOLDES("83464")="\0.5\0"
	s ^TKSOLDES("83460")="\0.5\0"
	s ^TKSOLDES("83436")="\0.5\0"
	s ^TKSOLDES("83441")="\0.5\0"
	s ^TKSOLDES("83440")="\0.5\0"
	s ^TKSOLDES("83439")="\0.5\0"
	s ^TKSOLDES("83438")="\0.5\0"
	s ^TKSOLDES("83437")="\0.5\0"
	s ^TKSOLDES("83435")="\0.5\0"
	s ^TKSOLDES("83443")="\0.5\0"
	s ^TKSOLDES("83434")="\0.5\0"
	s ^TKSOLDES("83433")="\0.5\0"
	s ^TKSOLDES("83432")="\0.5\0"
	s ^TKSOLDES("83431")="\0.5\0"
	s ^TKSOLDES("83430")="\0.5\0"
	s ^TKSOLDES("83429")="\0.5\0"
	s ^TKSOLDES("83442")="\0.5\0"
	s ^TKSOLDES("83444")="\0.5\0"
	s ^TKSOLDES("83459")="\0.5\0"
	s ^TKSOLDES("83445")="\0.5\0"
	s ^TKSOLDES("83458")="\0.5\0"
	s ^TKSOLDES("83457")="\0.5\0"
	s ^TKSOLDES("83456")="\0.5\0"
	s ^TKSOLDES("83455")="\0.5\0"
	s ^TKSOLDES("83454")="\0.5\0"
	s ^TKSOLDES("83453")="\0.5\0"
	s ^TKSOLDES("17247")="\0.5\0"
	s ^TKSOLDES("17246")="\0.5\0"
	s ^TKSOLDES("83446")="\0.5\0"
	s ^TKSOLDES("83447")="\0.5\0"
	s ^TKSOLDES("83448")="\0.5\0"
	s ^TKSOLDES("83449")="\0.5\0"
	s ^TKSOLDES("83452")="\0.5\0"
	s ^TKSOLDES("17244")="\0.5\0"
	s ^TKSOLDES("38436")="\0.5\0"
	s ^TKSOLDES("38435")="\0.5\0"
	s ^TKSOLDES("82587")="\0.5\0"
	s ^TKSOLDES("82582")="\0.5\0"
	s ^TKSOLDES("82583")="\0.5\0"
	s ^TKSOLDES("82584")="\0.5\0"
	s ^TKSOLDES("82585")="\0.5\0"
	s ^TKSOLDES("82586")="\0.5\0"
	s ^TKSOLDES("82589")="\0.5\0"
	s ^TKSOLDES("44077")="\0.5\0"
	s ^TKSOLDES("82591")="\0.5\0"
	s ^TKSOLDES("82593")="\0.5\0"
	s ^TKSOLDES("82594")="\0.5\0"
	s ^TKSOLDES("104730")="\0.5\0"
	s ^TKSOLDES("104729")="\0.5\0"
	s ^TKSOLDES("82595")="\0.5\0"
	s ^TKSOLDES("82578")="\0.5\0"
	s ^TKSOLDES("82577")="\0.5\0"
	s ^TKSOLDES("75025")="\0.5\0"
	s ^TKSOLDES("73587")="\0.5\0"
	s ^TKSOLDES("73588")="\0.5\0"
	s ^TKSOLDES("73589")="\0.5\0"
	s ^TKSOLDES("73590")="\0.5\0"
	s ^TKSOLDES("73591")="\0.5\0"
	s ^TKSOLDES("73592")="\0.5\0"
	s ^TKSOLDES("73593")="\0.5\0"
	s ^TKSOLDES("73594")="\0.5\0"
	s ^TKSOLDES("75026")="\0.5\0"
	s ^TKSOLDES("75027")="\0.5\0"
	s ^TKSOLDES("75028")="\0.5\0"
	s ^TKSOLDES("75029")="\0.5\0"
	s ^TKSOLDES("73596")="\0.5\0"
	s ^TKSOLDES("73595")="\0.5\0"
	s ^TKSOLDES("82596")="\0.5\0"
	s ^TKSOLDES("82598")="\0.5\0"
	s ^TKSOLDES("44090")="\0.5\0"
	s ^TKSOLDES("44096")="\0.5\0"
	s ^TKSOLDES("44094")="\0.5\0"
	s ^TKSOLDES("44093")="\0.5\0"
	s ^TKSOLDES("44092")="\0.5\0"
	s ^TKSOLDES("44091")="\0.5\0"
	s ^TKSOLDES("44087")="\0.5\0"
	s ^TKSOLDES("44098")="\0.5\0"
	s ^TKSOLDES("44085")="\0.5\0"
	s ^TKSOLDES("44084")="\0.5\0"
	s ^TKSOLDES("44083")="\0.5\0"
	s ^TKSOLDES("44081")="\0.5\0"
	s ^TKSOLDES("44080")="\0.5\0"
	s ^TKSOLDES("44079")="\0.5\0"
	s ^TKSOLDES("44097")="\0.5\0"
	s ^TKSOLDES("44099")="\0.5\0"
	s ^TKSOLDES("82599")="\0.5\0"
	s ^TKSOLDES("44100")="\0.5\0"
	s ^TKSOLDES("82600")="\0.5\0"
	s ^TKSOLDES("82601")="\0.5\0"
	s ^TKSOLDES("82602")="\0.5\0"
	s ^TKSOLDES("82609")="\0.5\0"
	s ^TKSOLDES("82610")="\0.5\0"
	s ^TKSOLDES("82611")="\0.5\0"
	s ^TKSOLDES("82612")="\0.5\0"
	s ^TKSOLDES("82613")="\0.5\0"
	s ^TKSOLDES("44101")="\0.5\0"
	s ^TKSOLDES("44102")="\0.5\0"
	s ^TKSOLDES("44103")="\0.5\0"
	s ^TKSOLDES("44104")="\0.5\0"
	s ^TKSOLDES("82615")="\0.5\0"
	s ^TKSOLDES("82614")="\0.5\0"
	s ^TKSOLDES("73586")="\0.5\0"
	s ^TKSOLDES("73585")="\0.5\0"
	s ^TKSOLDES("75037")="\0.5\0"
	s ^TKSOLDES("72867")="\0.5\0"
	s ^TKSOLDES("72868")="\0.5\0"
	s ^TKSOLDES("72869")="\0.5\0"
	s ^TKSOLDES("72871")="\0.5\0"
	s ^TKSOLDES("72872")="\0.5\0"
	s ^TKSOLDES("75036")="\0.5\0"
	s ^TKSOLDES("73534")="\0.5\0"
	s ^TKSOLDES("75035")="\0.5\0"
	s ^TKSOLDES("75034")="\0.5\0"
	s ^TKSOLDES("75033")="\0.5\0"
	s ^TKSOLDES("75032")="\0.5\0"
	s ^TKSOLDES("75031")="\0.5\0"
	s ^TKSOLDES("75030")="\0.5\0"
	s ^TKSOLDES("72865")="\0.5\0"
	s ^TKSOLDES("72864")="\0.5\0"
	s ^TKSOLDES("72863")="\0.5\0"
	s ^TKSOLDES("72850")="\0.5\0"
	s ^TKSOLDES("72851")="\0.5\0"
	s ^TKSOLDES("72852")="\0.5\0"
	s ^TKSOLDES("72853")="\0.5\0"
	s ^TKSOLDES("72854")="\0.5\0"
	s ^TKSOLDES("72855")="\0.5\0"
	s ^TKSOLDES("68131")="\0.5\0"
	s ^TKSOLDES("68132")="\0.5\0"
	s ^TKSOLDES("72862")="\0.5\0"
	s ^TKSOLDES("72859")="\0.5\0"
	s ^TKSOLDES("72857")="\0.5\0"
	s ^TKSOLDES("72856")="\0.5\0"
	s ^TKSOLDES("75038")="\0.5\0"
	s ^TKSOLDES("75039")="\0.5\0"
	s ^TKSOLDES("44115")="\0.5\0"
	s ^TKSOLDES("73536")="\0.5\0"
	s ^TKSOLDES("73584")="\0.5\0"
	s ^TKSOLDES("73568")="\0.5\0"
	s ^TKSOLDES("44113")="\0.5\0"
	s ^TKSOLDES("44112")="\0.5\0"
	s ^TKSOLDES("44111")="\0.5\0"
	s ^TKSOLDES("44110")="\0.5\0"
	s ^TKSOLDES("44109")="\0.5\0"
	s ^TKSOLDES("44108")="\0.5\0"
	s ^TKSOLDES("73561")="\0.5\0"
	s ^TKSOLDES("44107")="\0.5\0"
	s ^TKSOLDES("73569")="\0.5\0"
	s ^TKSOLDES("44106")="\0.5\0"
	s ^TKSOLDES("73570")="\0.5\0"
	s ^TKSOLDES("73571")="\0.5\0"
	s ^TKSOLDES("73583")="\0.5\0"
	s ^TKSOLDES("73562")="\0.5\0"
	s ^TKSOLDES("73560")="\0.5\0"
	s ^TKSOLDES("44114")="\0.5\0"
	s ^TKSOLDES("73559")="\0.5\0"
	s ^TKSOLDES("73537")="\0.5\0"
	s ^TKSOLDES("73538")="\0.5\0"
	s ^TKSOLDES("73539")="\0.5\0"
	s ^TKSOLDES("73540")="\0.5\0"
	s ^TKSOLDES("73541")="\0.5\0"
	s ^TKSOLDES("73542")="\0.5\0"
	s ^TKSOLDES("73543")="\0.5\0"
	s ^TKSOLDES("73544")="\0.5\0"
	s ^TKSOLDES("73550")="\0.5\0"
	s ^TKSOLDES("73549")="\0.5\0"
	s ^TKSOLDES("73548")="\0.5\0"
	s ^TKSOLDES("73547")="\0.5\0"
	s ^TKSOLDES("73546")="\0.5\0"
	s ^TKSOLDES("73545")="\0.5\0"
	s ^TKSOLDES("38438")="\0.5\0"
	s ^TKSOLDES("44078")="\0.5\0"
	s ^TKSOLDES("43076")="\0.5\0"
	s ^TKSOLDES("43073")="\0.5\0"
	s ^TKSOLDES("43072")="\0.5\0"
	s ^TKSOLDES("43070")="\0.5\0"
	s ^TKSOLDES("43069")="\0.5\0"
	s ^TKSOLDES("43067")="\0.5\0"
	s ^TKSOLDES("43066")="\0.5\0"
	s ^TKSOLDES("43065")="\0.5\0"
	s ^TKSOLDES("43064")="\0.5\0"
	s ^TKSOLDES("43058")="\0.5\0"
	s ^TKSOLDES("43056")="\0.5\0"
	s ^TKSOLDES("43055")="\0.5\0"
	s ^TKSOLDES("43054")="\0.5\0"
	s ^TKSOLDES("43075")="\0.5\0"
	s ^TKSOLDES("43079")="\0.5\0"
	s ^TKSOLDES("43051")="\0.5\0"
	s ^TKSOLDES("43098")="\0.5\0"
	s ^TKSOLDES("75010")="\0.5\0"
	s ^TKSOLDES("75009")="\0.5\0"
	s ^TKSOLDES("75008")="\0.5\0"
	s ^TKSOLDES("43100")="\0.5\0"
	s ^TKSOLDES("43099")="\0.5\0"
	s ^TKSOLDES("43097")="\0.5\0"
	s ^TKSOLDES("43081")="\0.5\0"
	s ^TKSOLDES("43095")="\0.5\0"
	s ^TKSOLDES("43094")="\0.5\0"
	s ^TKSOLDES("43089")="\0.5\0"
	s ^TKSOLDES("43088")="\0.5\0"
	s ^TKSOLDES("43086")="\0.5\0"
	s ^TKSOLDES("43082")="\0.5\0"
	s ^TKSOLDES("43052")="\0.5\0"
	s ^TKSOLDES("43050")="\0.5\0"
	s ^TKSOLDES("75012")="\0.5\0"
	s ^TKSOLDES("68140")="\0.5\0"
	s ^TKSOLDES("42855")="\0.5\0"
	s ^TKSOLDES("75007")="\0.5\0"
	s ^TKSOLDES("68137")="\0.5\0"
	s ^TKSOLDES("68138")="\0.5\0"
	s ^TKSOLDES("68139")="\0.5\0"
	s ^TKSOLDES("68141")="\0.5\0"
	s ^TKSOLDES("43049")="\0.5\0"
	s ^TKSOLDES("68142")="\0.5\0"
	s ^TKSOLDES("68143")="\0.5\0"
	s ^TKSOLDES("38442")="\0.5\0"
	s ^TKSOLDES("38441")="\0.5\0"
	s ^TKSOLDES("38440")="\0.5\0"
	s ^TKSOLDES("38439")="\0.5\0"
	s ^TKSOLDES("42859")="\0.5\0"
	s ^TKSOLDES("42861")="\0.5\0"
	s ^TKSOLDES("42862")="\0.5\0"
	s ^TKSOLDES("43048")="\0.5\0"
	s ^TKSOLDES("43047")="\0.5\0"
	s ^TKSOLDES("43046")="\0.5\0"
	s ^TKSOLDES("43045")="\0.5\0"
	s ^TKSOLDES("43044")="\0.5\0"
	s ^TKSOLDES("43043")="\0.5\0"
	s ^TKSOLDES("42871")="\0.5\0"
	s ^TKSOLDES("42870")="\0.5\0"
	s ^TKSOLDES("42863")="\0.5\0"
	s ^TKSOLDES("42864")="\0.5\0"
	s ^TKSOLDES("42866")="\0.5\0"
	s ^TKSOLDES("42867")="\0.5\0"
	s ^TKSOLDES("42868")="\0.5\0"
	s ^TKSOLDES("42869")="\0.5\0"
	s ^TKSOLDES("44076")="\0.5\0"
	s ^TKSOLDES("75011")="\0.5\0"
	s ^TKSOLDES("75013")="\0.5\0"
	s ^TKSOLDES("44049")="\0.5\0"
	s ^TKSOLDES("44055")="\0.5\0"
	s ^TKSOLDES("44054")="\0.5\0"
	s ^TKSOLDES("44053")="\0.5\0"
	s ^TKSOLDES("44052")="\0.5\0"
	s ^TKSOLDES("44051")="\0.5\0"
	s ^TKSOLDES("44046")="\0.5\0"
	s ^TKSOLDES("82626")="\0.5\0"
	s ^TKSOLDES("44042")="\0.5\0"
	s ^TKSOLDES("44040")="\0.5\0"
	s ^TKSOLDES("44039")="\0.5\0"
	s ^TKSOLDES("44038")="\0.5\0"
	s ^TKSOLDES("82625")="\0.5\0"
	s ^TKSOLDES("75014")="\0.5\0"
	s ^TKSOLDES("44056")="\0.5\0"
	s ^TKSOLDES("44057")="\0.5\0"
	s ^TKSOLDES("82624")="\0.5\0"
	s ^TKSOLDES("44075")="\0.5\0"
	s ^TKSOLDES("44073")="\0.5\0"
	s ^TKSOLDES("44072")="\0.5\0"
	s ^TKSOLDES("44070")="\0.5\0"
	s ^TKSOLDES("44069")="\0.5\0"
	s ^TKSOLDES("44068")="\0.5\0"
	s ^TKSOLDES("44058")="\0.5\0"
	s ^TKSOLDES("82616")="\0.5\0"
	s ^TKSOLDES("82623")="\0.5\0"
	s ^TKSOLDES("82622")="\0.5\0"
	s ^TKSOLDES("82621")="\0.5\0"
	s ^TKSOLDES("82620")="\0.5\0"
	s ^TKSOLDES("82618")="\0.5\0"
	s ^TKSOLDES("82617")="\0.5\0"
	s ^TKSOLDES("43101")="\0.5\0"
	s ^TKSOLDES("43102")="\0.5\0"
	s ^TKSOLDES("75022")="\0.5\0"
	s ^TKSOLDES("82628")="\0.5\0"
	s ^TKSOLDES("68135")="\0.5\0"
	s ^TKSOLDES("68136")="\0.5\0"
	s ^TKSOLDES("75024")="\0.5\0"
	s ^TKSOLDES("75023")="\0.5\0"
	s ^TKSOLDES("75021")="\0.5\0"
	s ^TKSOLDES("82673")="\0.5\0"
	s ^TKSOLDES("75020")="\0.5\0"
	s ^TKSOLDES("75019")="\0.5\0"
	s ^TKSOLDES("75018")="\0.5\0"
	s ^TKSOLDES("75017")="\0.5\0"
	s ^TKSOLDES("75016")="\0.5\0"
	s ^TKSOLDES("75015")="\0.5\0"
	s ^TKSOLDES("68133")="\0.5\0"
	s ^TKSOLDES("68134")="\0.5\0"
	s ^TKSOLDES("82666")="\0.5\0"
	s ^TKSOLDES("82664")="\0.5\0"
	s ^TKSOLDES("82663")="\0.5\0"
	s ^TKSOLDES("82660")="\0.5\0"
	s ^TKSOLDES("82659")="\0.5\0"
	s ^TKSOLDES("82647")="\0.5\0"
	s ^TKSOLDES("82646")="\0.5\0"
	s ^TKSOLDES("82672")="\0.5\0"
	s ^TKSOLDES("82665")="\0.5\0"
	s ^TKSOLDES("82667")="\0.5\0"
	s ^TKSOLDES("82671")="\0.5\0"
	s ^TKSOLDES("82670")="\0.5\0"
	s ^TKSOLDES("68089")="\0.5\0"
	s ^TKSOLDES("82669")="\0.5\0"
	s ^TKSOLDES("82668")="\0.5\0"
	s ^TKSOLDES("75105")="\0.5\0"
	s ^TKSOLDES("75102")="\0.5\0"
	s ^TKSOLDES("75103")="\0.5\0"
	s ^TKSOLDES("75106")="\0.5\0"
	s ^TKSOLDES("75108")="\0.5\0"
	s ^TKSOLDES("75104")="\0.5\0"
	s ^TKSOLDES("82322")="\0.5\0"
	s ^TKSOLDES("82752")="\0.5\0"
	s ^TKSOLDES("82754")="\0.5\0"
	s ^TKSOLDES("82755")="\0.5\0"
	s ^TKSOLDES("82843")="\0.5\0"
	s ^TKSOLDES("82910")="\0.5\0"
	s ^TKSOLDES("82911")="\0.5\0"
	s ^TKSOLDES("105106")="\0.5\0"
	s ^TKSOLDES("82753")="\0.5\0"
	s ^TKSOLDES("82751")="\0.5\0"
	s ^TKSOLDES("82948")="\0.5\0"
	s ^TKSOLDES("82745")="\0.5\0"
	s ^TKSOLDES("82677")="\0.5\0"
	s ^TKSOLDES("82679")="\0.5\0"
	s ^TKSOLDES("82746")="\0.5\0"
	s ^TKSOLDES("82750")="\0.5\0"
	s ^TKSOLDES("82747")="\0.5\0"
	s ^TKSOLDES("82748")="\0.5\0"
	s ^TKSOLDES("82749")="\0.5\0"
	s ^TKSOLDES("105107")="\0.5\0"
	s ^TKSOLDES("82950")="\0.5\0"
	s ^TKSOLDES("75101")="\0.5\0"
	s ^TKSOLDES("82981")="\0.5\0"
	s ^TKSOLDES("82979")="\0.5\0"
	s ^TKSOLDES("82980")="\0.5\0"
	s ^TKSOLDES("74597")="\0.5\0"
	s ^TKSOLDES("82952")="\0.5\0"
	s ^TKSOLDES("74594")="\0.5\0"
	s ^TKSOLDES("74591")="\0.5\0"
	s ^TKSOLDES("74590")="\0.5\0"
	s ^TKSOLDES("82966")="\0.5\0"
	s ^TKSOLDES("82965")="\0.5\0"
	s ^TKSOLDES("82962")="\0.5\0"
	s ^TKSOLDES("82953")="\0.5\0"
	s ^TKSOLDES("82954")="\0.5\0"
	s ^TKSOLDES("82955")="\0.5\0"
	s ^TKSOLDES("82956")="\0.5\0"
	s ^TKSOLDES("82957")="\0.5\0"
	s ^TKSOLDES("82958")="\0.5\0"
	s ^TKSOLDES("82959")="\0.5\0"
	s ^TKSOLDES("82961")="\0.5\0"
	s ^TKSOLDES("82676")="\0.5\0"
	s ^TKSOLDES("82675")="\0.5\0"
	s ^TKSOLDES("75110")="\0.5\0"
	s ^TKSOLDES("82320")="\0.5\0"
	s ^TKSOLDES("82321")="\0.5\0"
	s ^TKSOLDES("82323")="\0.5\0"
	s ^TKSOLDES("82495")="\0.5\0"
	s ^TKSOLDES("82324")="\0.5\0"
	s ^TKSOLDES("82326")="\0.5\0"
	s ^TKSOLDES("82327")="\0.5\0"
	s ^TKSOLDES("82318")="\0.5\0"
	s ^TKSOLDES("82317")="\0.5\0"
	s ^TKSOLDES("82316")="\0.5\0"
	s ^TKSOLDES("75100")="\0.5\0"
	s ^TKSOLDES("75099")="\0.5\0"
	s ^TKSOLDES("75081")="\0.5\0"
	s ^TKSOLDES("75080")="\0.5\0"
	s ^TKSOLDES("75078")="\0.5\0"
	s ^TKSOLDES("75076")="\0.5\0"
	s ^TKSOLDES("75075")="\0.5\0"
	s ^TKSOLDES("75072")="\0.5\0"
	s ^TKSOLDES("82328")="\0.5\0"
	s ^TKSOLDES("82330")="\0.5\0"
	s ^TKSOLDES("82371")="\0.5\0"
	s ^TKSOLDES("82368")="\0.5\0"
	s ^TKSOLDES("82369")="\0.5\0"
	s ^TKSOLDES("82377")="\0.5\0"
	s ^TKSOLDES("82364")="\0.5\0"
	s ^TKSOLDES("82481")="\0.5\0"
	s ^TKSOLDES("82487")="\0.5\0"
	s ^TKSOLDES("82494")="\0.5\0"
	s ^TKSOLDES("82366")="\0.5\0"
	s ^TKSOLDES("82362")="\0.5\0"
	s ^TKSOLDES("82331")="\0.5\0"
	s ^TKSOLDES("82361")="\0.5\0"
	s ^TKSOLDES("82332")="\0.5\0"
	s ^TKSOLDES("82333")="\0.5\0"
	s ^TKSOLDES("82334")="\0.5\0"
	s ^TKSOLDES("82335")="\0.5\0"
	s ^TKSOLDES("82336")="\0.5\0"
	s ^TKSOLDES("82351")="\0.5\0"
	s ^TKSOLDES("82353")="\0.5\0"
	s ^TKSOLDES("82356")="\0.5\0"
	s ^TKSOLDES("75109")="\0.5\0"
	s ^TKSOLDES("105085")="\0.5\0"
	s ^TKSOLDES("75111")="\0.5\0"
	s ^TKSOLDES("78496")="\0.5\0"
	s ^TKSOLDES("78481")="\0.5\0"
	s ^TKSOLDES("78489")="\0.5\0"
	s ^TKSOLDES("78492")="\0.5\0"
	s ^TKSOLDES("78493")="\0.5\0"
	s ^TKSOLDES("78497")="\0.5\0"
	s ^TKSOLDES("78479")="\0.5\0"
	s ^TKSOLDES("78504")="\0.5\0"
	s ^TKSOLDES("78505")="\0.5\0"
	s ^TKSOLDES("80074")="\0.5\0"
	s ^TKSOLDES("80073")="\0.5\0"
	s ^TKSOLDES("80072")="\0.5\0"
	s ^TKSOLDES("78480")="\0.5\0"
	s ^TKSOLDES("78478")="\0.5\0"
	s ^TKSOLDES("77951")="\0.5\0"
	s ^TKSOLDES("78477")="\0.5\0"
	s ^TKSOLDES("80330")="\0.5\0"
	s ^TKSOLDES("80327")="\0.5\0"
	s ^TKSOLDES("80326")="\0.5\0"
	s ^TKSOLDES("80324")="\0.5\0"
	s ^TKSOLDES("80322")="\0.5\0"
	s ^TKSOLDES("80321")="\0.5\0"
	s ^TKSOLDES("78447")="\0.5\0"
	s ^TKSOLDES("78448")="\0.5\0"
	s ^TKSOLDES("78463")="\0.5\0"
	s ^TKSOLDES("78474")="\0.5\0"
	s ^TKSOLDES("78475")="\0.5\0"
	s ^TKSOLDES("78476")="\0.5\0"
	s ^TKSOLDES("80071")="\0.5\0"
	s ^TKSOLDES("78506")="\0.5\0"
	s ^TKSOLDES("78507")="\0.5\0"
	s ^TKSOLDES("104145")="\0.5\0"
	s ^TKSOLDES("104146")="\0.5\0"
	s ^TKSOLDES("104149")="\0.5\0"
	s ^TKSOLDES("104151")="\0.5\0"
	s ^TKSOLDES("104152")="\0.5\0"
	s ^TKSOLDES("104153")="\0.5\0"
	s ^TKSOLDES("78570")="\0.5\0"
	s ^TKSOLDES("78572")="\0.5\0"
	s ^TKSOLDES("78574")="\0.5\0"
	s ^TKSOLDES("78577")="\0.5\0"
	s ^TKSOLDES("78578")="\0.5\0"
	s ^TKSOLDES("78579")="\0.5\0"
	s ^TKSOLDES("104143")="\0.5\0"
	s ^TKSOLDES("104142")="\0.5\0"
	s ^TKSOLDES("79985")="\0.5\0"
	s ^TKSOLDES("104114")="\0.5\0"
	s ^TKSOLDES("104116")="\0.5\0"
	s ^TKSOLDES("104125")="\0.5\0"
	s ^TKSOLDES("104127")="\0.5\0"
	s ^TKSOLDES("79987")="\0.5\0"
	s ^TKSOLDES("104129")="\0.5\0"
	s ^TKSOLDES("104141")="\0.5\0"
	s ^TKSOLDES("104130")="\0.5\0"
	s ^TKSOLDES("104131")="\0.5\0"
	s ^TKSOLDES("104137")="\0.5\0"
	s ^TKSOLDES("104138")="\0.5\0"
	s ^TKSOLDES("104139")="\0.5\0"
	s ^TKSOLDES("104140")="\0.5\0"
	s ^TKSOLDES("80331")="\0.5\0"
	s ^TKSOLDES("78360")="\0.5\0"
	s ^TKSOLDES("80866")="\0.5\0"
	s ^TKSOLDES("80871")="\0.5\0"
	s ^TKSOLDES("80869")="\0.5\0"
	s ^TKSOLDES("80868")="\0.5\0"
	s ^TKSOLDES("80867")="\0.5\0"
	s ^TKSOLDES("80865")="\0.5\0"
	s ^TKSOLDES("81000")="\0.5\0"
	s ^TKSOLDES("80864")="\0.5\0"
	s ^TKSOLDES("80863")="\0.5\0"
	s ^TKSOLDES("78005")="\0.5\0"
	s ^TKSOLDES("78006")="\0.5\0"
	s ^TKSOLDES("78007")="\0.5\0"
	s ^TKSOLDES("80872")="\0.5\0"
	s ^TKSOLDES("81004")="\0.5\0"
	s ^TKSOLDES("78057")="\0.5\0"
	s ^TKSOLDES("81005")="\0.5\0"
	s ^TKSOLDES("77961")="\0.5\0"
	s ^TKSOLDES("77962")="\0.5\0"
	s ^TKSOLDES("77966")="\0.5\0"
	s ^TKSOLDES("77968")="\0.5\0"
	s ^TKSOLDES("77969")="\0.5\0"
	s ^TKSOLDES("77970")="\0.5\0"
	s ^TKSOLDES("77972")="\0.5\0"
	s ^TKSOLDES("81011")="\0.5\0"
	s ^TKSOLDES("81010")="\0.5\0"
	s ^TKSOLDES("81009")="\0.5\0"
	s ^TKSOLDES("81007")="\0.5\0"
	s ^TKSOLDES("81006")="\0.5\0"
	s ^TKSOLDES("78056")="\0.5\0"
	s ^TKSOLDES("78058")="\0.5\0"
	s ^TKSOLDES("78358")="\0.5\0"
	s ^TKSOLDES("78059")="\0.5\0"
	s ^TKSOLDES("78240")="\0.5\0"
	s ^TKSOLDES("78241")="\0.5\0"
	s ^TKSOLDES("78242")="\0.5\0"
	s ^TKSOLDES("78243")="\0.5\0"
	s ^TKSOLDES("78249")="\0.5\0"
	s ^TKSOLDES("78251")="\0.5\0"
	s ^TKSOLDES("78326")="\0.5\0"
	s ^TKSOLDES("78331")="\0.5\0"
	s ^TKSOLDES("78336")="\0.5\0"
	s ^TKSOLDES("78337")="\0.5\0"
	s ^TKSOLDES("78339")="\0.5\0"
	s ^TKSOLDES("78357")="\0.5\0"
	s ^TKSOLDES("78239")="\0.5\0"
	s ^TKSOLDES("80712")="\0.5\0"
	s ^TKSOLDES("80721")="\0.5\0"
	s ^TKSOLDES("78060")="\0.5\0"
	s ^TKSOLDES("78061")="\0.5\0"
	s ^TKSOLDES("80724")="\0.5\0"
	s ^TKSOLDES("80723")="\0.5\0"
	s ^TKSOLDES("80722")="\0.5\0"
	s ^TKSOLDES("80720")="\0.5\0"
	s ^TKSOLDES("80713")="\0.5\0"
	s ^TKSOLDES("80719")="\0.5\0"
	s ^TKSOLDES("80718")="\0.5\0"
	s ^TKSOLDES("80717")="\0.5\0"
	s ^TKSOLDES("80716")="\0.5\0"
	s ^TKSOLDES("80715")="\0.5\0"
	s ^TKSOLDES("80714")="\0.5\0"
	s ^TKSOLDES("78587")="\0.5\0"
	s ^TKSOLDES("78597")="\0.5\0"
	s ^TKSOLDES("79309")="\0.5\0"
	s ^TKSOLDES("78871")="\0.5\0"
	s ^TKSOLDES("78964")="\0.5\0"
	s ^TKSOLDES("104481")="\0.5\0"
	s ^TKSOLDES("79314")="\0.5\0"
	s ^TKSOLDES("79258")="\0.5\0"
	s ^TKSOLDES("78869")="\0.5\0"
	s ^TKSOLDES("79256")="\0.5\0"
	s ^TKSOLDES("79255")="\0.5\0"
	s ^TKSOLDES("79254")="\0.5\0"
	s ^TKSOLDES("79253")="\0.5\0"
	s ^TKSOLDES("79252")="\0.5\0"
	s ^TKSOLDES("78870")="\0.5\0"
	s ^TKSOLDES("78868")="\0.5\0"
	s ^TKSOLDES("78821")="\0.5\0"
	s ^TKSOLDES("78867")="\0.5\0"
	s ^TKSOLDES("78824")="\0.5\0"
	s ^TKSOLDES("78825")="\0.5\0"
	s ^TKSOLDES("78840")="\0.5\0"
	s ^TKSOLDES("78856")="\0.5\0"
	s ^TKSOLDES("78857")="\0.5\0"
	s ^TKSOLDES("78860")="\0.5\0"
	s ^TKSOLDES("78861")="\0.5\0"
	s ^TKSOLDES("78862")="\0.5\0"
	s ^TKSOLDES("78863")="\0.5\0"
	s ^TKSOLDES("78865")="\0.5\0"
	s ^TKSOLDES("105693")="\0.5\0"
	s ^TKSOLDES("78866")="\0.5\0"
	s ^TKSOLDES("79251")="\0.5\0"
	s ^TKSOLDES("79247")="\0.5\0"
	s ^TKSOLDES("79244")="\0.5\0"
	s ^TKSOLDES("79189")="\0.5\0"
	s ^TKSOLDES("79188")="\0.5\0"
	s ^TKSOLDES("79187")="\0.5\0"
	s ^TKSOLDES("79186")="\0.5\0"
	s ^TKSOLDES("79172")="\0.5\0"
	s ^TKSOLDES("79170")="\0.5\0"
	s ^TKSOLDES("79169")="\0.5\0"
	s ^TKSOLDES("79164")="\0.5\0"
	s ^TKSOLDES("79155")="\0.5\0"
	s ^TKSOLDES("79154")="\0.5\0"
	s ^TKSOLDES("79153")="\0.5\0"
	s ^TKSOLDES("79152")="\0.5\0"
	s ^TKSOLDES("79190")="\0.5\0"
	s ^TKSOLDES("79191")="\0.5\0"
	s ^TKSOLDES("79238")="\0.5\0"
	s ^TKSOLDES("79243")="\0.5\0"
	s ^TKSOLDES("79242")="\0.5\0"
	s ^TKSOLDES("79241")="\0.5\0"
	s ^TKSOLDES("79240")="\0.5\0"
	s ^TKSOLDES("79239")="\0.5\0"
	s ^TKSOLDES("79237")="\0.5\0"
	s ^TKSOLDES("79230")="\0.5\0"
	s ^TKSOLDES("79236")="\0.5\0"
	s ^TKSOLDES("79235")="\0.5\0"
	s ^TKSOLDES("79234")="\0.5\0"
	s ^TKSOLDES("79233")="\0.5\0"
	s ^TKSOLDES("79232")="\0.5\0"
	s ^TKSOLDES("79231")="\0.5\0"
	s ^TKSOLDES("78823")="\0.5\0"
	s ^TKSOLDES("78819")="\0.5\0"
	s ^TKSOLDES("104585")="\0.5\0"
	s ^TKSOLDES("104336")="\0.5\0"
	s ^TKSOLDES("104332")="\0.5\0"
	s ^TKSOLDES("104333")="\0.5\0"
	s ^TKSOLDES("104334")="\0.5\0"
	s ^TKSOLDES("104335")="\0.5\0"
	s ^TKSOLDES("104337")="\0.5\0"
	s ^TKSOLDES("104330")="\0.5\0"
	s ^TKSOLDES("104338")="\0.5\0"
	s ^TKSOLDES("104339")="\0.5\0"
	s ^TKSOLDES("104347")="\0.5\0"
	s ^TKSOLDES("104355")="\0.5\0"
	s ^TKSOLDES("104356")="\0.5\0"
	s ^TKSOLDES("104331")="\0.5\0"
	s ^TKSOLDES("104329")="\0.5\0"
	s ^TKSOLDES("104371")="\0.5\0"
	s ^TKSOLDES("78770")="\0.5\0"
	s ^TKSOLDES("78618")="\0.5\0"
	s ^TKSOLDES("78619")="\0.5\0"
	s ^TKSOLDES("78628")="\0.5\0"
	s ^TKSOLDES("104319")="\0.5\0"
	s ^TKSOLDES("78629")="\0.5\0"
	s ^TKSOLDES("78630")="\0.5\0"
	s ^TKSOLDES("78632")="\0.5\0"
	s ^TKSOLDES("104550")="\0.5\0"
	s ^TKSOLDES("78664")="\0.5\0"
	s ^TKSOLDES("78668")="\0.5\0"
	s ^TKSOLDES("78767")="\0.5\0"
	s ^TKSOLDES("78768")="\0.5\0"
	s ^TKSOLDES("104359")="\0.5\0"
	s ^TKSOLDES("104373")="\0.5\0"
	s ^TKSOLDES("104457")="\0.5\0"
	s ^TKSOLDES("104374")="\0.5\0"
	s ^TKSOLDES("104443")="\0.5\0"
	s ^TKSOLDES("104444")="\0.5\0"
	s ^TKSOLDES("104445")="\0.5\0"
	s ^TKSOLDES("104446")="\0.5\0"
	s ^TKSOLDES("104447")="\0.5\0"
	s ^TKSOLDES("104448")="\0.5\0"
	s ^TKSOLDES("104449")="\0.5\0"
	s ^TKSOLDES("104450")="\0.5\0"
	s ^TKSOLDES("104451")="\0.5\0"
	s ^TKSOLDES("104454")="\0.5\0"
	s ^TKSOLDES("104455")="\0.5\0"
	s ^TKSOLDES("104456")="\0.5\0"
	s ^TKSOLDES("104442")="\0.5\0"
	s ^TKSOLDES("104441")="\0.5\0"
	s ^TKSOLDES("104406")="\0.5\0"
	s ^TKSOLDES("104378")="\0.5\0"
	s ^TKSOLDES("104379")="\0.5\0"
	s ^TKSOLDES("104380")="\0.5\0"
	s ^TKSOLDES("104381")="\0.5\0"
	s ^TKSOLDES("104394")="\0.5\0"
	s ^TKSOLDES("104407")="\0.5\0"
	s ^TKSOLDES("104439")="\0.5\0"
	s ^TKSOLDES("104423")="\0.5\0"
	s ^TKSOLDES("104425")="\0.5\0"
	s ^TKSOLDES("104426")="\0.5\0"
	s ^TKSOLDES("104435")="\0.5\0"
	s ^TKSOLDES("78771")="\0.5\0"
	s ^TKSOLDES("104436")="\0.5\0"
	s ^TKSOLDES("77957")="\0.5\0"
	s ^TKSOLDES("77950")="\0.5\0"
	s ^TKSOLDES("75112")="\0.5\0"
	s ^TKSOLDES("81450")="\0.5\0"
	s ^TKSOLDES("75689")="\0.5\0"
	s ^TKSOLDES("75690")="\0.5\0"
	s ^TKSOLDES("105098")="\0.5\0"
	s ^TKSOLDES("81451")="\0.5\0"
	s ^TKSOLDES("81449")="\0.5\0"
	s ^TKSOLDES("75680")="\0.5\0"
	s ^TKSOLDES("105096")="\0.5\0"
	s ^TKSOLDES("105095")="\0.5\0"
	s ^TKSOLDES("105094")="\0.5\0"
	s ^TKSOLDES("105093")="\0.5\0"
	s ^TKSOLDES("105092")="\0.5\0"
	s ^TKSOLDES("75688")="\0.5\0"
	s ^TKSOLDES("81464")="\0.5\0"
	s ^TKSOLDES("76269")="\0.5\0"
	s ^TKSOLDES("81465")="\0.5\0"
	s ^TKSOLDES("81609")="\0.5\0"
	s ^TKSOLDES("81608")="\0.5\0"
	s ^TKSOLDES("81606")="\0.5\0"
	s ^TKSOLDES("81605")="\0.5\0"
	s ^TKSOLDES("81604")="\0.5\0"
	s ^TKSOLDES("81591")="\0.5\0"
	s ^TKSOLDES("81590")="\0.5\0"
	s ^TKSOLDES("81589")="\0.5\0"
	s ^TKSOLDES("81588")="\0.5\0"
	s ^TKSOLDES("81468")="\0.5\0"
	s ^TKSOLDES("81467")="\0.5\0"
	s ^TKSOLDES("81466")="\0.5\0"
	s ^TKSOLDES("105091")="\0.5\0"
	s ^TKSOLDES("105090")="\0.5\0"
	s ^TKSOLDES("105089")="\0.5\0"
	s ^TKSOLDES("105081")="\0.5\0"
	s ^TKSOLDES("76213")="\0.5\0"
	s ^TKSOLDES("76214")="\0.5\0"
	s ^TKSOLDES("76215")="\0.5\0"
	s ^TKSOLDES("76216")="\0.5\0"
	s ^TKSOLDES("76217")="\0.5\0"
	s ^TKSOLDES("76218")="\0.5\0"
	s ^TKSOLDES("76238")="\0.5\0"
	s ^TKSOLDES("76240")="\0.5\0"
	s ^TKSOLDES("76241")="\0.5\0"
	s ^TKSOLDES("76242")="\0.5\0"
	s ^TKSOLDES("76243")="\0.5\0"
	s ^TKSOLDES("76171")="\0.5\0"
	s ^TKSOLDES("105082")="\0.5\0"
	s ^TKSOLDES("81431")="\0.5\0"
	s ^TKSOLDES("105088")="\0.5\0"
	s ^TKSOLDES("83042")="\0.5\0"
	s ^TKSOLDES("81434")="\0.5\0"
	s ^TKSOLDES("81433")="\0.5\0"
	s ^TKSOLDES("81432")="\0.5\0"
	s ^TKSOLDES("81430")="\0.5\0"
	s ^TKSOLDES("105083")="\0.5\0"
	s ^TKSOLDES("81429")="\0.5\0"
	s ^TKSOLDES("81428")="\0.5\0"
	s ^TKSOLDES("81427")="\0.5\0"
	s ^TKSOLDES("81426")="\0.5\0"
	s ^TKSOLDES("81423")="\0.5\0"
	s ^TKSOLDES("105084")="\0.5\0"
	s ^TKSOLDES("81612")="\0.5\0"
	s ^TKSOLDES("81613")="\0.5\0"
	s ^TKSOLDES("75243")="\0.5\0"
	s ^TKSOLDES("75224")="\0.5\0"
	s ^TKSOLDES("75225")="\0.5\0"
	s ^TKSOLDES("75226")="\0.5\0"
	s ^TKSOLDES("75236")="\0.5\0"
	s ^TKSOLDES("75244")="\0.5\0"
	s ^TKSOLDES("75203")="\0.5\0"
	s ^TKSOLDES("75345")="\0.5\0"
	s ^TKSOLDES("75346")="\0.5\0"
	s ^TKSOLDES("75359")="\0.5\0"
	s ^TKSOLDES("105102")="\0.5\0"
	s ^TKSOLDES("105100")="\0.5\0"
	s ^TKSOLDES("75204")="\0.5\0"
	s ^TKSOLDES("75202")="\0.5\0"
	s ^TKSOLDES("81917")="\0.5\0"
	s ^TKSOLDES("75166")="\0.5\0"
	s ^TKSOLDES("75113")="\0.5\0"
	s ^TKSOLDES("75114")="\0.5\0"
	s ^TKSOLDES("75115")="\0.5\0"
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 