ROUTINE OPESOLDES50PE13P1
OPESOLDES50PE13P1
 
	s ^TKSOLDES("79664")="\0.5\0"
	s ^TKSOLDES("82069")="\0.5\0"
	s ^TKSOLDES("82070")="\0.5\0"
	s ^TKSOLDES("82072")="\0.5\0"
	s ^TKSOLDES("82123")="\0.5\0"
	s ^TKSOLDES("82124")="\0.5\0"
	s ^TKSOLDES("82125")="\0.5\0"
	s ^TKSOLDES("81953")="\0.5\0"
	s ^TKSOLDES("81952")="\0.5\0"
	s ^TKSOLDES("80220")="\0.5\0"
	s ^TKSOLDES("80009")="\0.5\0"
	s ^TKSOLDES("80016")="\0.5\0"
	s ^TKSOLDES("81028")="\0.5\0"
	s ^TKSOLDES("81924")="\0.5\0"
	s ^TKSOLDES("81040")="\0.5\0"
	s ^TKSOLDES("81527")="\0.5\0"
	s ^TKSOLDES("81543")="\0.5\0"
	s ^TKSOLDES("82243")="\0.5\0"
	s ^TKSOLDES("82244")="\0.5\0"
	s ^TKSOLDES("82722")="\0.5\0"
	s ^TKSOLDES("82779")="\0.5\0"
	s ^TKSOLDES("82898")="\0.5\0"
	s ^TKSOLDES("82901")="\0.5\0"
	s ^TKSOLDES("82906")="\0.5\0"
	s ^TKSOLDES("83637")="\0.5\0"
	s ^TKSOLDES("83638")="\0.5\0"
	s ^TKSOLDES("82771")="\0.5\0"
	s ^TKSOLDES("82721")="\0.5\0"
	s ^TKSOLDES("82246")="\0.5\0"
	s ^TKSOLDES("82514")="\0.5\0"
	s ^TKSOLDES("82247")="\0.5\0"
	s ^TKSOLDES("82513")="\0.5\0"
	s ^TKSOLDES("82538")="\0.5\0"
	s ^TKSOLDES("82720")="\0.5\0"
	s ^TKSOLDES("82540")="\0.5\0"
	s ^TKSOLDES("82541")="\0.5\0"
	s ^TKSOLDES("82546")="\0.5\0"
	s ^TKSOLDES("79993")="\0.5\0"
	s ^TKSOLDES("79989")="\0.5\0"
	s ^TKSOLDES("79856")="\0.5\0"
	s ^TKSOLDES("79799")="\0.5\0"
	s ^TKSOLDES("79820")="\0.5\0"
	s ^TKSOLDES("79823")="\0.5\0"
	s ^TKSOLDES("79850")="\0.5\0"
	s ^TKSOLDES("79853")="\0.5\0"
	s ^TKSOLDES("79854")="\0.5\0"
	s ^TKSOLDES("79775")="\0.5\0"
	s ^TKSOLDES("79774")="\0.5\0"
	s ^TKSOLDES("79678")="\0.5\0"
	s ^TKSOLDES("79670")="\0.5\0"
	s ^TKSOLDES("79675")="\0.5\0"
	s ^TKSOLDES("79679")="\0.5\0"
	s ^TKSOLDES("79773")="\0.5\0"
	s ^TKSOLDES("79702")="\0.5\0"
	s ^TKSOLDES("79709")="\0.5\0"
	s ^TKSOLDES("79771")="\0.5\0"
	s ^TKSOLDES("79855")="\0.5\0"
	s ^TKSOLDES("79857")="\0.5\0"
	s ^TKSOLDES("79982")="\0.5\0"
	s ^TKSOLDES("79927")="\0.5\0"
	s ^TKSOLDES("79938")="\0.5\0"
	s ^TKSOLDES("79939")="\0.5\0"
	s ^TKSOLDES("79940")="\0.5\0"
	s ^TKSOLDES("79941")="\0.5\0"
	s ^TKSOLDES("79948")="\0.5\0"
	s ^TKSOLDES("79972")="\0.5\0"
	s ^TKSOLDES("79935")="\0.5\0"
	s ^TKSOLDES("79926")="\0.5\0"
	s ^TKSOLDES("79858")="\0.5\0"
	s ^TKSOLDES("79904")="\0.5\0"
	s ^TKSOLDES("79881")="\0.5\0"
	s ^TKSOLDES("79885")="\0.5\0"
	s ^TKSOLDES("79905")="\0.5\0"
	s ^TKSOLDES("79920")="\0.5\0"
	s ^TKSOLDES("79911")="\0.5\0"
	s ^TKSOLDES("79912")="\0.5\0"
	s ^TKSOLDES("79915")="\0.5\0"
	s ^TKSOLDES("83639")="\0.5\0"
	s ^TKSOLDES("83640")="\0.5\0"
	s ^TKSOLDES("86608")="\0.5\0"
	s ^TKSOLDES("100460")="\0.5\0"
	s ^TKSOLDES("100462")="\0.5\0"
	s ^TKSOLDES("100562")="\0.5\0"
	s ^TKSOLDES("100585")="\0.5\0"
	s ^TKSOLDES("100586")="\0.5\0"
	s ^TKSOLDES("100587")="\0.5\0"
	s ^TKSOLDES("100458")="\0.5\0"
	s ^TKSOLDES("100451")="\0.5\0"
	s ^TKSOLDES("92407")="\0.5\0"
	s ^TKSOLDES("90194")="\0.5\0"
	s ^TKSOLDES("91164")="\0.5\0"
	s ^TKSOLDES("92593")="\0.5\0"
	s ^TKSOLDES("100424")="\0.5\0"
	s ^TKSOLDES("92707")="\0.5\0"
	s ^TKSOLDES("93004")="\0.5\0"
	s ^TKSOLDES("100341")="\0.5\0"
	s ^TKSOLDES("100589")="\0.5\0"
	s ^TKSOLDES("100590")="\0.5\0"
	s ^TKSOLDES("100636")="\0.5\0"
	s ^TKSOLDES("100638")="\0.5\0"
	s ^TKSOLDES("100642")="\0.5\0"
	s ^TKSOLDES("100645")="\0.5\0"
	s ^TKSOLDES("100652")="\0.5\0"
	s ^TKSOLDES("100661")="\0.5\0"
	s ^TKSOLDES("100662")="\0.5\0"
	s ^TKSOLDES("100637")="\0.5\0"
	s ^TKSOLDES("100635")="\0.5\0"
	s ^TKSOLDES("100591")="\0.5\0"
	s ^TKSOLDES("100613")="\0.5\0"
	s ^TKSOLDES("100592")="\0.5\0"
	s ^TKSOLDES("100609")="\0.5\0"
	s ^TKSOLDES("100630")="\0.5\0"
	s ^TKSOLDES("100634")="\0.5\0"
	s ^TKSOLDES("100631")="\0.5\0"
	s ^TKSOLDES("100632")="\0.5\0"
	s ^TKSOLDES("100633")="\0.5\0"
	s ^TKSOLDES("88537")="\0.5\0"
	s ^TKSOLDES("86602")="\0.5\0"
	s ^TKSOLDES("83641")="\0.5\0"
	s ^TKSOLDES("84998")="\0.5\0"
	s ^TKSOLDES("84979")="\0.5\0"
	s ^TKSOLDES("84983")="\0.5\0"
	s ^TKSOLDES("84984")="\0.5\0"
	s ^TKSOLDES("84988")="\0.5\0"
	s ^TKSOLDES("84990")="\0.5\0"
	s ^TKSOLDES("84992")="\0.5\0"
	s ^TKSOLDES("84978")="\0.5\0"
	s ^TKSOLDES("84973")="\0.5\0"
	s ^TKSOLDES("84316")="\0.5\0"
	s ^TKSOLDES("84117")="\0.5\0"
	s ^TKSOLDES("84304")="\0.5\0"
	s ^TKSOLDES("84462")="\0.5\0"
	s ^TKSOLDES("84772")="\0.5\0"
	s ^TKSOLDES("84463")="\0.5\0"
	s ^TKSOLDES("84464")="\0.5\0"
	s ^TKSOLDES("84767")="\0.5\0"
	s ^TKSOLDES("84997")="\0.5\0"
	s ^TKSOLDES("85000")="\0.5\0"
	s ^TKSOLDES("86601")="\0.5\0"
	s ^TKSOLDES("86154")="\0.5\0"
	s ^TKSOLDES("86156")="\0.5\0"
	s ^TKSOLDES("86157")="\0.5\0"
	s ^TKSOLDES("86169")="\0.5\0"
	s ^TKSOLDES("86171")="\0.5\0"
	s ^TKSOLDES("86193")="\0.5\0"
	s ^TKSOLDES("86596")="\0.5\0"
	s ^TKSOLDES("86155")="\0.5\0"
	s ^TKSOLDES("86121")="\0.5\0"
	s ^TKSOLDES("85002")="\0.5\0"
	s ^TKSOLDES("85556")="\0.5\0"
	s ^TKSOLDES("85005")="\0.5\0"
	s ^TKSOLDES("85037")="\0.5\0"
	s ^TKSOLDES("85557")="\0.5\0"
	s ^TKSOLDES("86117")="\0.5\0"
	s ^TKSOLDES("85558")="\0.5\0"
	s ^TKSOLDES("86115")="\0.5\0"
	s ^TKSOLDES("86116")="\0.5\0"
	s ^TKSOLDES("79666")="\0.5\0"
	s ^TKSOLDES("79660")="\0.5\0"
	s ^TKSOLDES("100756")="\0.5\0"
	s ^TKSOLDES("77434")="\0.5\0"
	s ^TKSOLDES("74814")="\0.5\0"
	s ^TKSOLDES("75523")="\0.5\0"
	s ^TKSOLDES("75539")="\0.5\0"
	s ^TKSOLDES("75541")="\0.5\0"
	s ^TKSOLDES("76016")="\0.5\0"
	s ^TKSOLDES("76029")="\0.5\0"
	s ^TKSOLDES("74811")="\0.5\0"
	s ^TKSOLDES("73155")="\0.5\0"
	s ^TKSOLDES("68311")="\0.5\0"
	s ^TKSOLDES("66198")="\0.5\0"
	s ^TKSOLDES("67930")="\0.5\0"
	s ^TKSOLDES("68359")="\0.5\0"
	s ^TKSOLDES("72459")="\0.5\0"
	s ^TKSOLDES("68361")="\0.5\0"
	s ^TKSOLDES("70285")="\0.5\0"
	s ^TKSOLDES("72159")="\0.5\0"
	s ^TKSOLDES("76031")="\0.5\0"
	s ^TKSOLDES("76032")="\0.5\0"
	s ^TKSOLDES("76204")="\0.5\0"
	s ^TKSOLDES("76394")="\0.5\0"
	s ^TKSOLDES("76404")="\0.5\0"
	s ^TKSOLDES("76405")="\0.5\0"
	s ^TKSOLDES("76406")="\0.5\0"
	s ^TKSOLDES("76416")="\0.5\0"
	s ^TKSOLDES("76437")="\0.5\0"
	s ^TKSOLDES("76386")="\0.5\0"
	s ^TKSOLDES("76158")="\0.5\0"
	s ^TKSOLDES("76037")="\0.5\0"
	s ^TKSOLDES("76084")="\0.5\0"
	s ^TKSOLDES("76071")="\0.5\0"
	s ^TKSOLDES("76078")="\0.5\0"
	s ^TKSOLDES("76093")="\0.5\0"
	s ^TKSOLDES("76123")="\0.5\0"
	s ^TKSOLDES("76115")="\0.5\0"
	s ^TKSOLDES("76117")="\0.5\0"
	s ^TKSOLDES("76122")="\0.5\0"
	s ^TKSOLDES("64467")="\0.5\0"
	s ^TKSOLDES("63081")="\0.5\0"
	s ^TKSOLDES("7112")="\0.5\0"
	s ^TKSOLDES("2433")="\0.5\0"
	s ^TKSOLDES("3589")="\0.5\0"
	s ^TKSOLDES("6129")="\0.5\0"
	s ^TKSOLDES("6130")="\0.5\0"
	s ^TKSOLDES("6134")="\0.5\0"
	s ^TKSOLDES("6135")="\0.5\0"
	s ^TKSOLDES("2281")="\0.5\0"
	s ^TKSOLDES("1496")="\0.5\0"
	s ^TKSOLDES("1046")="\0.5\0"
	s ^TKSOLDES("1044")="\0.5\0"
	s ^TKSOLDES("1045")="\0.5\0"
	s ^TKSOLDES("1049")="\0.5\0"
	s ^TKSOLDES("1392")="\0.5\0"
	s ^TKSOLDES("1050")="\0.5\0"
	s ^TKSOLDES("1054")="\0.5\0"
	s ^TKSOLDES("1068")="\0.5\0"
	s ^TKSOLDES("6817")="\0.5\0"
	s ^TKSOLDES("7225")="\0.5\0"
	s ^TKSOLDES("63037")="\0.5\0"
	s ^TKSOLDES("49964")="\0.5\0"
	s ^TKSOLDES("52106")="\0.5\0"
	s ^TKSOLDES("53555")="\0.5\0"
	s ^TKSOLDES("54722")="\0.5\0"
	s ^TKSOLDES("55631")="\0.5\0"
	s ^TKSOLDES("59643")="\0.5\0"
	s ^TKSOLDES("59981")="\0.5\0"
	s ^TKSOLDES("52099")="\0.5\0"
	s ^TKSOLDES("44711")="\0.5\0"
	s ^TKSOLDES("8008")="\0.5\0"
	s ^TKSOLDES("8156")="\0.5\0"
	s ^TKSOLDES("8063")="\0.5\0"
	s ^TKSOLDES("8146")="\0.5\0"
	s ^TKSOLDES("8375")="\0.5\0"
	s ^TKSOLDES("41729")="\0.5\0"
	s ^TKSOLDES("37494")="\0.5\0"
	s ^TKSOLDES("37495")="\0.5\0"
	s ^TKSOLDES("37497")="\0.5\0"
	s ^TKSOLDES("76438")="\0.5\0"
	s ^TKSOLDES("77442")="\0.5\0"
	s ^TKSOLDES("79653")="\0.5\0"
	s ^TKSOLDES("79465")="\0.5\0"
	s ^TKSOLDES("79570")="\0.5\0"
	s ^TKSOLDES("79571")="\0.5\0"
	s ^TKSOLDES("79573")="\0.5\0"
	s ^TKSOLDES("79579")="\0.5\0"
	s ^TKSOLDES("79580")="\0.5\0"
	s ^TKSOLDES("79582")="\0.5\0"
	s ^TKSOLDES("79569")="\0.5\0"
	s ^TKSOLDES("79568")="\0.5\0"
	s ^TKSOLDES("79541")="\0.5\0"
	s ^TKSOLDES("79534")="\0.5\0"
	s ^TKSOLDES("79536")="\0.5\0"
	s ^TKSOLDES("79555")="\0.5\0"
	s ^TKSOLDES("79564")="\0.5\0"
	s ^TKSOLDES("79556")="\0.5\0"
	s ^TKSOLDES("79558")="\0.5\0"
	s ^TKSOLDES("79562")="\0.5\0"
	s ^TKSOLDES("79596")="\0.5\0"
	s ^TKSOLDES("79598")="\0.5\0"
	s ^TKSOLDES("79641")="\0.5\0"
	s ^TKSOLDES("79645")="\0.5\0"
	s ^TKSOLDES("79647")="\0.5\0"
	s ^TKSOLDES("79648")="\0.5\0"
	s ^TKSOLDES("79649")="\0.5\0"
	s ^TKSOLDES("79650")="\0.5\0"
	s ^TKSOLDES("79651")="\0.5\0"
	s ^TKSOLDES("79643")="\0.5\0"
	s ^TKSOLDES("79634")="\0.5\0"
	s ^TKSOLDES("79604")="\0.5\0"
	s ^TKSOLDES("79607")="\0.5\0"
	s ^TKSOLDES("79605")="\0.5\0"
	s ^TKSOLDES("79606")="\0.5\0"
	s ^TKSOLDES("79608")="\0.5\0"
	s ^TKSOLDES("79632")="\0.5\0"
	s ^TKSOLDES("79609")="\0.5\0"
	s ^TKSOLDES("79610")="\0.5\0"
	s ^TKSOLDES("79623")="\0.5\0"
	s ^TKSOLDES("79466")="\0.5\0"
	s ^TKSOLDES("79464")="\0.5\0"
	s ^TKSOLDES("77450")="\0.5\0"
	s ^TKSOLDES("79328")="\0.5\0"
	s ^TKSOLDES("78816")="\0.5\0"
	s ^TKSOLDES("79319")="\0.5\0"
	s ^TKSOLDES("79320")="\0.5\0"
	s ^TKSOLDES("79321")="\0.5\0"
	s ^TKSOLDES("79322")="\0.5\0"
	s ^TKSOLDES("79323")="\0.5\0"
	s ^TKSOLDES("78810")="\0.5\0"
	s ^TKSOLDES("78792")="\0.5\0"
	s ^TKSOLDES("77456")="\0.5\0"
	s ^TKSOLDES("77451")="\0.5\0"
	s ^TKSOLDES("77455")="\0.5\0"
	s ^TKSOLDES("78203")="\0.5\0"
	s ^TKSOLDES("78648")="\0.5\0"
	s ^TKSOLDES("78237")="\0.5\0"
	s ^TKSOLDES("78615")="\0.5\0"
	s ^TKSOLDES("78616")="\0.5\0"
	s ^TKSOLDES("79327")="\0.5\0"
	s ^TKSOLDES("79330")="\0.5\0"
	s ^TKSOLDES("79460")="\0.5\0"
	s ^TKSOLDES("79442")="\0.5\0"
	s ^TKSOLDES("79451")="\0.5\0"
	s ^TKSOLDES("79453")="\0.5\0"
	s ^TKSOLDES("79454")="\0.5\0"
	s ^TKSOLDES("79455")="\0.5\0"
	s ^TKSOLDES("79457")="\0.5\0"
	s ^TKSOLDES("79459")="\0.5\0"
	s ^TKSOLDES("79443")="\0.5\0"
	s ^TKSOLDES("79426")="\0.5\0"
	s ^TKSOLDES("79352")="\0.5\0"
	s ^TKSOLDES("79355")="\0.5\0"
	s ^TKSOLDES("79353")="\0.5\0"
	s ^TKSOLDES("79354")="\0.5\0"
	s ^TKSOLDES("79385")="\0.5\0"
	s ^TKSOLDES("79406")="\0.5\0"
	s ^TKSOLDES("79389")="\0.5\0"
	s ^TKSOLDES("79397")="\0.5\0"
	s ^TKSOLDES("79399")="\0.5\0"
	s ^TKSOLDES("100674")="\0.5\0"
	s ^TKSOLDES("79456")="\0.5\0"
	s ^TKSOLDES("103638")="\0.5\0"
	s ^TKSOLDES("103635")="\0.5\0"
	s ^TKSOLDES("103634")="\0.5\0"
	s ^TKSOLDES("103633")="\0.5\0"
	s ^TKSOLDES("103632")="\0.5\0"
	s ^TKSOLDES("103631")="\0.5\0"
	s ^TKSOLDES("103630")="\0.5\0"
	s ^TKSOLDES("103544")="\0.5\0"
	s ^TKSOLDES("103543")="\0.5\0"
	s ^TKSOLDES("103523")="\0.5\0"
	s ^TKSOLDES("103520")="\0.5\0"
	s ^TKSOLDES("103309")="\0.5\0"
	s ^TKSOLDES("103308")="\0.5\0"
	s ^TKSOLDES("103637")="\0.5\0"
	s ^TKSOLDES("103642")="\0.5\0"
	s ^TKSOLDES("103306")="\0.5\0"
	s ^TKSOLDES("105206")="\0.5\0"
	s ^TKSOLDES("105212")="\0.5\0"
	s ^TKSOLDES("105211")="\0.5\0"
	s ^TKSOLDES("105210")="\0.5\0"
	s ^TKSOLDES("105209")="\0.5\0"
	s ^TKSOLDES("105207")="\0.5\0"
	s ^TKSOLDES("105205")="\0.5\0"
	s ^TKSOLDES("103643")="\0.5\0"
	s ^TKSOLDES("105202")="\0.5\0"
	s ^TKSOLDES("104496")="\0.5\0"
	s ^TKSOLDES("104495")="\0.5\0"
	s ^TKSOLDES("104494")="\0.5\0"
	s ^TKSOLDES("104493")="\0.5\0"
	s ^TKSOLDES("104492")="\0.5\0"
	s ^TKSOLDES("103307")="\0.5\0"
	s ^TKSOLDES("1041")="\0.5\0"
	s ^TKSOLDES("68098")="\0.5\0"
	s ^TKSOLDES("44145")="\0.5\0"
	s ^TKSOLDES("44143")="\0.5\0"
	s ^TKSOLDES("44142")="\0.5\0"
	s ^TKSOLDES("44141")="\0.5\0"
	s ^TKSOLDES("44140")="\0.5\0"
	s ^TKSOLDES("44136")="\0.5\0"
	s ^TKSOLDES("68099")="\0.5\0"
	s ^TKSOLDES("75065")="\0.5\0"
	s ^TKSOLDES("44135")="\0.5\0"
	s ^TKSOLDES("44134")="\0.5\0"
	s ^TKSOLDES("44133")="\0.5\0"
	s ^TKSOLDES("44132")="\0.5\0"
	s ^TKSOLDES("44146")="\0.5\0"
	s ^TKSOLDES("44147")="\0.5\0"
	s ^TKSOLDES("44126")="\0.5\0"
	s ^TKSOLDES("68297")="\0.5\0"
	s ^TKSOLDES("68292")="\0.5\0"
	s ^TKSOLDES("68293")="\0.5\0"
	s ^TKSOLDES("68294")="\0.5\0"
	s ^TKSOLDES("68295")="\0.5\0"
	s ^TKSOLDES("68296")="\0.5\0"
	s ^TKSOLDES("68298")="\0.5\0"
	s ^TKSOLDES("44150")="\0.5\0"
	s ^TKSOLDES("68299")="\0.5\0"
	s ^TKSOLDES("68300")="\0.5\0"
	s ^TKSOLDES("68097")="\0.5\0"
	s ^TKSOLDES("44153")="\0.5\0"
	s ^TKSOLDES("44152")="\0.5\0"
	s ^TKSOLDES("44151")="\0.5\0"
	s ^TKSOLDES("44127")="\0.5\0"
	s ^TKSOLDES("44125")="\0.5\0"
	s ^TKSOLDES("68290")="\0.5\0"
	s ^TKSOLDES("87986")="\0.5\0"
	s ^TKSOLDES("87981")="\0.5\0"
	s ^TKSOLDES("87982")="\0.5\0"
	s ^TKSOLDES("87983")="\0.5\0"
	s ^TKSOLDES("87984")="\0.5\0"
	s ^TKSOLDES("87985")="\0.5\0"
	s ^TKSOLDES("87987")="\0.5\0"
	s ^TKSOLDES("44124")="\0.5\0"
	s ^TKSOLDES("87988")="\0.5\0"
	s ^TKSOLDES("87989")="\0.5\0"
	s ^TKSOLDES("87990")="\0.5\0"
	s ^TKSOLDES("87991")="\0.5\0"
	s ^TKSOLDES("87995")="\0.5\0"
	s ^TKSOLDES("87997")="\0.5\0"
	s ^TKSOLDES("87980")="\0.5\0"
	s ^TKSOLDES("87976")="\0.5\0"
	s ^TKSOLDES("87975")="\0.5\0"
	s ^TKSOLDES("44123")="\0.5\0"
	s ^TKSOLDES("44122")="\0.5\0"
	s ^TKSOLDES("44121")="\0.5\0"
	s ^TKSOLDES("44120")="\0.5\0"
	s ^TKSOLDES("44119")="\0.5\0"
	s ^TKSOLDES("44118")="\0.5\0"
	s ^TKSOLDES("44117")="\0.5\0"
	s ^TKSOLDES("75064")="\0.5\0"
	s ^TKSOLDES("87974")="\0.5\0"
	s ^TKSOLDES("87973")="\0.5\0"
	s ^TKSOLDES("87972")="\0.5\0"
	s ^TKSOLDES("87971")="\0.5\0"
	s ^TKSOLDES("75062")="\0.5\0"
	s ^TKSOLDES("75063")="\0.5\0"
	s ^TKSOLDES("68291")="\0.5\0"
	s ^TKSOLDES("68289")="\0.5\0"
	s ^TKSOLDES("68090")="\0.5\0"
	s ^TKSOLDES("50409")="\0.5\0"
	s ^TKSOLDES("68273")="\0.5\0"
	s ^TKSOLDES("68274")="\0.5\0"
	s ^TKSOLDES("50412")="\0.5\0"
	s ^TKSOLDES("50411")="\0.5\0"
	s ^TKSOLDES("50410")="\0.5\0"
	s ^TKSOLDES("50408")="\0.5\0"
	s ^TKSOLDES("68288")="\0.5\0"
	s ^TKSOLDES("50407")="\0.5\0"
	s ^TKSOLDES("50406")="\0.5\0"
	s ^TKSOLDES("50405")="\0.5\0"
	s ^TKSOLDES("50404")="\0.5\0"
	s ^TKSOLDES("50403")="\0.5\0"
	s ^TKSOLDES("50402")="\0.5\0"
	s ^TKSOLDES("68272")="\0.5\0"
	s ^TKSOLDES("68271")="\0.5\0"
	s ^TKSOLDES("68270")="\0.5\0"
	s ^TKSOLDES("68256")="\0.5\0"
	s ^TKSOLDES("68257")="\0.5\0"
	s ^TKSOLDES("68258")="\0.5\0"
	s ^TKSOLDES("68259")="\0.5\0"
	s ^TKSOLDES("68260")="\0.5\0"
	s ^TKSOLDES("68261")="\0.5\0"
	s ^TKSOLDES("68262")="\0.5\0"
	s ^TKSOLDES("68263")="\0.5\0"
	s ^TKSOLDES("68269")="\0.5\0"
	s ^TKSOLDES("68268")="\0.5\0"
	s ^TKSOLDES("68267")="\0.5\0"
	s ^TKSOLDES("68266")="\0.5\0"
	s ^TKSOLDES("68265")="\0.5\0"
	s ^TKSOLDES("68264")="\0.5\0"
	s ^TKSOLDES("50401")="\0.5\0"
	s ^TKSOLDES("50400")="\0.5\0"
	s ^TKSOLDES("68280")="\0.5\0"
	s ^TKSOLDES("68275")="\0.5\0"
	s ^TKSOLDES("68276")="\0.5\0"
	s ^TKSOLDES("68277")="\0.5\0"
	s ^TKSOLDES("68278")="\0.5\0"
	s ^TKSOLDES("68279")="\0.5\0"
	s ^TKSOLDES("68281")="\0.5\0"
	s ^TKSOLDES("50382")="\0.5\0"
	s ^TKSOLDES("68282")="\0.5\0"
	s ^TKSOLDES("68283")="\0.5\0"
	s ^TKSOLDES("68284")="\0.5\0"
	s ^TKSOLDES("68285")="\0.5\0"
	s ^TKSOLDES("68286")="\0.5\0"
	s ^TKSOLDES("68287")="\0.5\0"
	s ^TKSOLDES("50381")="\0.5\0"
	s ^TKSOLDES("50383")="\0.5\0"
	s ^TKSOLDES("50399")="\0.5\0"
	s ^TKSOLDES("50384")="\0.5\0"
	s ^TKSOLDES("50398")="\0.5\0"
	s ^TKSOLDES("50397")="\0.5\0"
	s ^TKSOLDES("50396")="\0.5\0"
	s ^TKSOLDES("50395")="\0.5\0"
	s ^TKSOLDES("50394")="\0.5\0"
	s ^TKSOLDES("50393")="\0.5\0"
	s ^TKSOLDES("50392")="\0.5\0"
	s ^TKSOLDES("50391")="\0.5\0"
	s ^TKSOLDES("50385")="\0.5\0"
	s ^TKSOLDES("50386")="\0.5\0"
	s ^TKSOLDES("50387")="\0.5\0"
	s ^TKSOLDES("50388")="\0.5\0"
	s ^TKSOLDES("50389")="\0.5\0"
	s ^TKSOLDES("50390")="\0.5\0"
	s ^TKSOLDES("87998")="\0.5\0"
	s ^TKSOLDES("87999")="\0.5\0"
	s ^TKSOLDES("68104")="\0.5\0"
	s ^TKSOLDES("75049")="\0.5\0"
	s ^TKSOLDES("68100")="\0.5\0"
	s ^TKSOLDES("68101")="\0.5\0"
	s ^TKSOLDES("68102")="\0.5\0"
	s ^TKSOLDES("68103")="\0.5\0"
	s ^TKSOLDES("68105")="\0.5\0"
	s ^TKSOLDES("88000")="\0.5\0"
	s ^TKSOLDES("68106")="\0.5\0"
	s ^TKSOLDES("68107")="\0.5\0"
	s ^TKSOLDES("68108")="\0.5\0"
	s ^TKSOLDES("68109")="\0.5\0"
	s ^TKSOLDES("68110")="\0.5\0"
	s ^TKSOLDES("68111")="\0.5\0"
	s ^TKSOLDES("75050")="\0.5\0"
	s ^TKSOLDES("75051")="\0.5\0"
	s ^TKSOLDES("88596")="\0.5\0"
	s ^TKSOLDES("88582")="\0.5\0"
	s ^TKSOLDES("88583")="\0.5\0"
	s ^TKSOLDES("88584")="\0.5\0"
	s ^TKSOLDES("88585")="\0.5\0"
	s ^TKSOLDES("88586")="\0.5\0"
	s ^TKSOLDES("88587")="\0.5\0"
	s ^TKSOLDES("88588")="\0.5\0"
	s ^TKSOLDES("88589")="\0.5\0"
	s ^TKSOLDES("88595")="\0.5\0"
	s ^TKSOLDES("88594")="\0.5\0"
	s ^TKSOLDES("88593")="\0.5\0"
	s ^TKSOLDES("88592")="\0.5\0"
	s ^TKSOLDES("88591")="\0.5\0"
	s ^TKSOLDES("88590")="\0.5\0"
	s ^TKSOLDES("68112")="\0.5\0"
	s ^TKSOLDES("68113")="\0.5\0"
	s ^TKSOLDES("75045")="\0.5\0"
	s ^TKSOLDES("104735")="\0.5\0"
	s ^TKSOLDES("104734")="\0.5\0"
	s ^TKSOLDES("104733")="\0.5\0"
	s ^TKSOLDES("104732")="\0.5\0"
	s ^TKSOLDES("104731")="\0.5\0"
	s ^TKSOLDES("75044")="\0.5\0"
	s ^TKSOLDES("75046")="\0.5\0"
	s ^TKSOLDES("75043")="\0.5\0"
	s ^TKSOLDES("75042")="\0.5\0"
	s ^TKSOLDES("75041")="\0.5\0"
	s ^TKSOLDES("75040")="\0.5\0"
	s ^TKSOLDES("68129")="\0.5\0"
	s ^TKSOLDES("68130")="\0.5\0"
	s ^TKSOLDES("104736")="\0.5\0"
	s ^TKSOLDES("75047")="\0.5\0"
	s ^TKSOLDES("68114")="\0.5\0"
	s ^TKSOLDES("75048")="\0.5\0"
	s ^TKSOLDES("68115")="\0.5\0"
	s ^TKSOLDES("68116")="\0.5\0"
	s ^TKSOLDES("68117")="\0.5\0"
	s ^TKSOLDES("68118")="\0.5\0"
	s ^TKSOLDES("68119")="\0.5\0"
	s ^TKSOLDES("68120")="\0.5\0"
	s ^TKSOLDES("68121")="\0.5\0"
	s ^TKSOLDES("68122")="\0.5\0"
	s ^TKSOLDES("68128")="\0.5\0"
	s ^TKSOLDES("68127")="\0.5\0"
	s ^TKSOLDES("68126")="\0.5\0"
	s ^TKSOLDES("68125")="\0.5\0"
	s ^TKSOLDES("68124")="\0.5\0"
	s ^TKSOLDES("68123")="\0.5\0"
	s ^TKSOLDES("88581")="\0.5\0"
	s ^TKSOLDES("88580")="\0.5\0"
	s ^TKSOLDES("75056")="\0.5\0"
	s ^TKSOLDES("75061")="\0.5\0"
	s ^TKSOLDES("75060")="\0.5\0"
	s ^TKSOLDES("75059")="\0.5\0"
	s ^TKSOLDES("75058")="\0.5\0"
	s ^TKSOLDES("75057")="\0.5\0"
	s ^TKSOLDES("75055")="\0.5\0"
	s ^TKSOLDES("88545")="\0.5\0"
	s ^TKSOLDES("75054")="\0.5\0"
	s ^TKSOLDES("75053")="\0.5\0"
	s ^TKSOLDES("75052")="\0.5\0"
	s ^TKSOLDES("70618")="\0.5\0"
	s ^TKSOLDES("44116")="\0.5\0"
	s ^TKSOLDES("88543")="\0.5\0"
	s ^TKSOLDES("104737")="\0.5\0"
	s ^TKSOLDES("104738")="\0.5\0"
	s ^TKSOLDES("104739")="\0.5\0"
	s ^TKSOLDES("88002")="\0.5\0"
	s ^TKSOLDES("88003")="\0.5\0"
	s ^TKSOLDES("88004")="\0.5\0"
	s ^TKSOLDES("88005")="\0.5\0"
	s ^TKSOLDES("88007")="\0.5\0"
	s ^TKSOLDES("88008")="\0.5\0"
	s ^TKSOLDES("88009")="\0.5\0"
	s ^TKSOLDES("88010")="\0.5\0"
	s ^TKSOLDES("88021")="\0.5\0"
	s ^TKSOLDES("88020")="\0.5\0"
	s ^TKSOLDES("88019")="\0.5\0"
	s ^TKSOLDES("88015")="\0.5\0"
	s ^TKSOLDES("88014")="\0.5\0"
	s ^TKSOLDES("88012")="\0.5\0"
	s ^TKSOLDES("88544")="\0.5\0"
	s ^TKSOLDES("88546")="\0.5\0"
	s ^TKSOLDES("88579")="\0.5\0"
	s ^TKSOLDES("88571")="\0.5\0"
	s ^TKSOLDES("88566")="\0.5\0"
	s ^TKSOLDES("88567")="\0.5\0"
	s ^TKSOLDES("88568")="\0.5\0"
	s ^TKSOLDES("88569")="\0.5\0"
	s ^TKSOLDES("88570")="\0.5\0"
	s ^TKSOLDES("88572")="\0.5\0"
	s ^TKSOLDES("88564")="\0.5\0"
	s ^TKSOLDES("88573")="\0.5\0"
	s ^TKSOLDES("88574")="\0.5\0"
	s ^TKSOLDES("88575")="\0.5\0"
	s ^TKSOLDES("88576")="\0.5\0"
	s ^TKSOLDES("88577")="\0.5\0"
	s ^TKSOLDES("88578")="\0.5\0"
	s ^TKSOLDES("88565")="\0.5\0"
	s ^TKSOLDES("88563")="\0.5\0"
	s ^TKSOLDES("88547")="\0.5\0"
	s ^TKSOLDES("88562")="\0.5\0"
	s ^TKSOLDES("88548")="\0.5\0"
	s ^TKSOLDES("88549")="\0.5\0"
	s ^TKSOLDES("88550")="\0.5\0"
	s ^TKSOLDES("88551")="\0.5\0"
	s ^TKSOLDES("88552")="\0.5\0"
	s ^TKSOLDES("88553")="\0.5\0"
	s ^TKSOLDES("88554")="\0.5\0"
	s ^TKSOLDES("88555")="\0.5\0"
	s ^TKSOLDES("88561")="\0.5\0"
	s ^TKSOLDES("88560")="\0.5\0"
	s ^TKSOLDES("88559")="\0.5\0"
	s ^TKSOLDES("88558")="\0.5\0"
	s ^TKSOLDES("88557")="\0.5\0"
	s ^TKSOLDES("88556")="\0.5\0"
	s ^TKSOLDES("68255")="\0.5\0"
	s ^TKSOLDES("68254")="\0.5\0"
	s ^TKSOLDES("68192")="\0.5\0"
	s ^TKSOLDES("68194")="\0.5\0"
	s ^TKSOLDES("68195")="\0.5\0"
	s ^TKSOLDES("68196")="\0.5\0"
	s ^TKSOLDES("68197")="\0.5\0"
	s ^TKSOLDES("68198")="\0.5\0"
	s ^TKSOLDES("68199")="\0.5\0"
	s ^TKSOLDES("68200")="\0.5\0"
	s ^TKSOLDES("68201")="\0.5\0"
	s ^TKSOLDES("68202")="\0.5\0"
	s ^TKSOLDES("68203")="\0.5\0"
	s ^TKSOLDES("68204")="\0.5\0"
	s ^TKSOLDES("68205")="\0.5\0"
	s ^TKSOLDES("68193")="\0.5\0"
	s ^TKSOLDES("68191")="\0.5\0"
	s ^TKSOLDES("68207")="\0.5\0"
	s ^TKSOLDES("68182")="\0.5\0"
	s ^TKSOLDES("68177")="\0.5\0"
	s ^TKSOLDES("68178")="\0.5\0"
	s ^TKSOLDES("68179")="\0.5\0"
	s ^TKSOLDES("68180")="\0.5\0"
	s ^TKSOLDES("68181")="\0.5\0"
	s ^TKSOLDES("68183")="\0.5\0"
	s ^TKSOLDES("68190")="\0.5\0"
	s ^TKSOLDES("68184")="\0.5\0"
	s ^TKSOLDES("68185")="\0.5\0"
	s ^TKSOLDES("68186")="\0.5\0"
	s ^TKSOLDES("68187")="\0.5\0"
	s ^TKSOLDES("68188")="\0.5\0"
	s ^TKSOLDES("68189")="\0.5\0"
	s ^TKSOLDES("68206")="\0.5\0"
	s ^TKSOLDES("68208")="\0.5\0"
	s ^TKSOLDES("68175")="\0.5\0"
	s ^TKSOLDES("68220")="\0.5\0"
	s ^TKSOLDES("65863")="\0.5\0"
	s ^TKSOLDES("65862")="\0.5\0"
	s ^TKSOLDES("65861")="\0.5\0"
	s ^TKSOLDES("68218")="\0.5\0"
	s ^TKSOLDES("68219")="\0.5\0"
	s ^TKSOLDES("68221")="\0.5\0"
	s ^TKSOLDES("68209")="\0.5\0"
	s ^TKSOLDES("68222")="\0.5\0"
	s ^TKSOLDES("68223")="\0.5\0"
	s ^TKSOLDES("68224")="\0.5\0"
	s ^TKSOLDES("65860")="\0.5\0"
	s ^TKSOLDES("65856")="\0.5\0"
	s ^TKSOLDES("65855")="\0.5\0"
	s ^TKSOLDES("65864")="\0.5\0"
	s ^TKSOLDES("65865")="\0.5\0"
	s ^TKSOLDES("65866")="\0.5\0"
	s ^TKSOLDES("68210")="\0.5\0"
	s ^TKSOLDES("68211")="\0.5\0"
	s ^TKSOLDES("68212")="\0.5\0"
	s ^TKSOLDES("68213")="\0.5\0"
	s ^TKSOLDES("68214")="\0.5\0"
	s ^TKSOLDES("68215")="\0.5\0"
	s ^TKSOLDES("68216")="\0.5\0"
	s ^TKSOLDES("68217")="\0.5\0"
	s ^TKSOLDES("65867")="\0.5\0"
	s ^TKSOLDES("65868")="\0.5\0"
	s ^TKSOLDES("65869")="\0.5\0"
	s ^TKSOLDES("65870")="\0.5\0"
	s ^TKSOLDES("65871")="\0.5\0"
	s ^TKSOLDES("65872")="\0.5\0"
	s ^TKSOLDES("68176")="\0.5\0"
	s ^TKSOLDES("68174")="\0.5\0"
	s ^TKSOLDES("65853")="\0.5\0"
	s ^TKSOLDES("68071")="\0.5\0"
	s ^TKSOLDES("68095")="\0.5\0"
	s ^TKSOLDES("68075")="\0.5\0"
	s ^TKSOLDES("68074")="\0.5\0"
	s ^TKSOLDES("68073")="\0.5\0"
	s ^TKSOLDES("68072")="\0.5\0"
	s ^TKSOLDES("68070")="\0.5\0"
	s ^TKSOLDES("68173")="\0.5\0"
	s ^TKSOLDES("68069")="\0.5\0"
	s ^TKSOLDES("68068")="\0.5\0"
	s ^TKSOLDES("68096")="\0.5\0"
	s ^TKSOLDES("68168")="\0.5\0"
	s ^TKSOLDES("68169")="\0.5\0"
	s ^TKSOLDES("68067")="\0.5\0"
	s ^TKSOLDES("68094")="\0.5\0"
	s ^TKSOLDES("68093")="\0.5\0"
	s ^TKSOLDES("68092")="\0.5\0"
	s ^TKSOLDES("68088")="\0.5\0"
	s ^TKSOLDES("68087")="\0.5\0"
	s ^TKSOLDES("68086")="\0.5\0"
	s ^TKSOLDES("68085")="\0.5\0"
	s ^TKSOLDES("68084")="\0.5\0"
	s ^TKSOLDES("68083")="\0.5\0"
	s ^TKSOLDES("68082")="\0.5\0"
	s ^TKSOLDES("68081")="\0.5\0"
	s ^TKSOLDES("68091")="\0.5\0"
	s ^TKSOLDES("68076")="\0.5\0"
	s ^TKSOLDES("68077")="\0.5\0"
	s ^TKSOLDES("68078")="\0.5\0"
	s ^TKSOLDES("68079")="\0.5\0"
	s ^TKSOLDES("68080")="\0.5\0"
	s ^TKSOLDES("68066")="\0.5\0"
	s ^TKSOLDES("68065")="\0.5\0"
	s ^TKSOLDES("67648")="\0.5\0"
	s ^TKSOLDES("67653")="\0.5\0"
	s ^TKSOLDES("67652")="\0.5\0"
	s ^TKSOLDES("67651")="\0.5\0"
	s ^TKSOLDES("67650")="\0.5\0"
	s ^TKSOLDES("67649")="\0.5\0"
	s ^TKSOLDES("67647")="\0.5\0"
	s ^TKSOLDES("67655")="\0.5\0"
	s ^TKSOLDES("67646")="\0.5\0"
	s ^TKSOLDES("67645")="\0.5\0"
	s ^TKSOLDES("67644")="\0.5\0"
	s ^TKSOLDES("67643")="\0.5\0"
	s ^TKSOLDES("67642")="\0.5\0"
	s ^TKSOLDES("68172")="\0.5\0"
	s ^TKSOLDES("67654")="\0.5\0"
	s ^TKSOLDES("67656")="\0.5\0"
	s ^TKSOLDES("68064")="\0.5\0"
	s ^TKSOLDES("67657")="\0.5\0"
	s ^TKSOLDES("68170")="\0.5\0"
	s ^TKSOLDES("68171")="\0.5\0"
	s ^TKSOLDES("67669")="\0.5\0"
	s ^TKSOLDES("67668")="\0.5\0"
	s ^TKSOLDES("67667")="\0.5\0"
	s ^TKSOLDES("67666")="\0.5\0"
	s ^TKSOLDES("67665")="\0.5\0"
	s ^TKSOLDES("67664")="\0.5\0"
	s ^TKSOLDES("67658")="\0.5\0"
	s ^TKSOLDES("67659")="\0.5\0"
	s ^TKSOLDES("67660")="\0.5\0"
	s ^TKSOLDES("67661")="\0.5\0"
	s ^TKSOLDES("67662")="\0.5\0"
	s ^TKSOLDES("67663")="\0.5\0"
	s ^TKSOLDES("65854")="\0.5\0"
	s ^TKSOLDES("65852")="\0.5\0"
	s ^TKSOLDES("68253")="\0.5\0"
	s ^TKSOLDES("57143")="\0.5\0"
	s ^TKSOLDES("60651")="\0.5\0"
	s ^TKSOLDES("60650")="\0.5\0"
	s ^TKSOLDES("60649")="\0.5\0"
	s ^TKSOLDES("68239")="\0.5\0"
	s ^TKSOLDES("68240")="\0.5\0"
	s ^TKSOLDES("57142")="\0.5\0"
	s ^TKSOLDES("68225")="\0.5\0"
	s ^TKSOLDES("57128")="\0.5\0"
	s ^TKSOLDES("57127")="\0.5\0"
	s ^TKSOLDES("57126")="\0.5\0"
	s ^TKSOLDES("57125")="\0.5\0"
	s ^TKSOLDES("57124")="\0.5\0"
	s ^TKSOLDES("57123")="\0.5\0"
	s ^TKSOLDES("60654")="\0.5\0"
	s ^TKSOLDES("60655")="\0.5\0"
	s ^TKSOLDES("60656")="\0.5\0"
	s ^TKSOLDES("60674")="\0.5\0"
	s ^TKSOLDES("60673")="\0.5\0"
	s ^TKSOLDES("60672")="\0.5\0"
	s ^TKSOLDES("60671")="\0.5\0"
	s ^TKSOLDES("60670")="\0.5\0"
	s ^TKSOLDES("60669")="\0.5\0"
	s ^TKSOLDES("60668")="\0.5\0"
	s ^TKSOLDES("60667")="\0.5\0"
	s ^TKSOLDES("60658")="\0.5\0"
	s ^TKSOLDES("60662")="\0.5\0"
	s ^TKSOLDES("60663")="\0.5\0"
	s ^TKSOLDES("60664")="\0.5\0"
	s ^TKSOLDES("60665")="\0.5\0"
	s ^TKSOLDES("60666")="\0.5\0"
	s ^TKSOLDES("57122")="\0.5\0"
	s ^TKSOLDES("57121")="\0.5\0"
	s ^TKSOLDES("50416")="\0.5\0"
	s ^TKSOLDES("50421")="\0.5\0"
	s ^TKSOLDES("50420")="\0.5\0"
	s ^TKSOLDES("50419")="\0.5\0"
	s ^TKSOLDES("50418")="\0.5\0"
	s ^TKSOLDES("50417")="\0.5\0"
	s ^TKSOLDES("50415")="\0.5\0"
	s ^TKSOLDES("50423")="\0.5\0"
	s ^TKSOLDES("50414")="\0.5\0"
	s ^TKSOLDES("50413")="\0.5\0"
	s ^TKSOLDES("68249")="\0.5\0"
	s ^TKSOLDES("68250")="\0.5\0"
	s ^TKSOLDES("68251")="\0.5\0"
	s ^TKSOLDES("68252")="\0.5\0"
	s ^TKSOLDES("50422")="\0.5\0"
	s ^TKSOLDES("50424")="\0.5\0"
	s ^TKSOLDES("57119")="\0.5\0"
	s ^TKSOLDES("50425")="\0.5\0"
	s ^TKSOLDES("57118")="\0.5\0"
	s ^TKSOLDES("57117")="\0.5\0"
	s ^TKSOLDES("57116")="\0.5\0"
	s ^TKSOLDES("68241")="\0.5\0"
	s ^TKSOLDES("68242")="\0.5\0"
	s ^TKSOLDES("68243")="\0.5\0"
	s ^TKSOLDES("68244")="\0.5\0"
	s ^TKSOLDES("68245")="\0.5\0"
	s ^TKSOLDES("50426")="\0.5\0"
	s ^TKSOLDES("50427")="\0.5\0"
	s ^TKSOLDES("50428")="\0.5\0"
	s ^TKSOLDES("68248")="\0.5\0"
	s ^TKSOLDES("68247")="\0.5\0"
	s ^TKSOLDES("68246")="\0.5\0"
	s ^TKSOLDES("60675")="\0.5\0"
	s ^TKSOLDES("60676")="\0.5\0"
	s ^TKSOLDES("68237")="\0.5\0"
	s ^TKSOLDES("68232")="\0.5\0"
	s ^TKSOLDES("68233")="\0.5\0"
	s ^TKSOLDES("68234")="\0.5\0"
	s ^TKSOLDES("68235")="\0.5\0"
	s ^TKSOLDES("68236")="\0.5\0"
	s ^TKSOLDES("68238")="\0.5\0"
	s ^TKSOLDES("62274")="\0.5\0"
	s ^TKSOLDES("62284")="\0.5\0"
	s ^TKSOLDES("62283")="\0.5\0"
	s ^TKSOLDES("62282")="\0.5\0"
	s ^TKSOLDES("62280")="\0.5\0"
	s ^TKSOLDES("62278")="\0.5\0"
	s ^TKSOLDES("62277")="\0.5\0"
	s ^TKSOLDES("68231")="\0.5\0"
	s ^TKSOLDES("64051")="\0.5\0"
	s ^TKSOLDES("64052")="\0.5\0"
	s ^TKSOLDES("68226")="\0.5\0"
	s ^TKSOLDES("68227")="\0.5\0"
	s ^TKSOLDES("68228")="\0.5\0"
	s ^TKSOLDES("68229")="\0.5\0"
	s ^TKSOLDES("64062")="\0.5\0"
	s ^TKSOLDES("64060")="\0.5\0"
	s ^TKSOLDES("64059")="\0.5\0"
	s ^TKSOLDES("64058")="\0.5\0"
	s ^TKSOLDES("64053")="\0.5\0"
	s ^TKSOLDES("64054")="\0.5\0"
	s ^TKSOLDES("64055")="\0.5\0"
	s ^TKSOLDES("64056")="\0.5\0"
	s ^TKSOLDES("68230")="\0.5\0"
	s ^TKSOLDES("64057")="\0.5\0"
	s ^TKSOLDES("62276")="\0.5\0"
	s ^TKSOLDES("62266")="\0.5\0"
	s ^TKSOLDES("60677")="\0.5\0"
	s ^TKSOLDES("60691")="\0.5\0"
	s ^TKSOLDES("60699")="\0.5\0"
	s ^TKSOLDES("60698")="\0.5\0"
	s ^TKSOLDES("60696")="\0.5\0"
	s ^TKSOLDES("60694")="\0.5\0"
	s ^TKSOLDES("60693")="\0.5\0"
	s ^TKSOLDES("60689")="\0.5\0"
	s ^TKSOLDES("62235")="\0.5\0"
	s ^TKSOLDES("60684")="\0.5\0"
	s ^TKSOLDES("60683")="\0.5\0"
	s ^TKSOLDES("60682")="\0.5\0"
	s ^TKSOLDES("60680")="\0.5\0"
	s ^TKSOLDES("60679")="\0.5\0"
	s ^TKSOLDES("60678")="\0.5\0"
	s ^TKSOLDES("62232")="\0.5\0"
	s ^TKSOLDES("62239")="\0.5\0"
	s ^TKSOLDES("62263")="\0.5\0"
	s ^TKSOLDES("62240")="\0.5\0"
	s ^TKSOLDES("62262")="\0.5\0"
	s ^TKSOLDES("62261")="\0.5\0"
	s ^TKSOLDES("62258")="\0.5\0"
	s ^TKSOLDES("62257")="\0.5\0"
	s ^TKSOLDES("62256")="\0.5\0"
	s ^TKSOLDES("62254")="\0.5\0"
	s ^TKSOLDES("62253")="\0.5\0"
	s ^TKSOLDES("62252")="\0.5\0"
	s ^TKSOLDES("62245")="\0.5\0"
	s ^TKSOLDES("62247")="\0.5\0"
	s ^TKSOLDES("62248")="\0.5\0"
	s ^TKSOLDES("62249")="\0.5\0"
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 