ROUTINE OPESOLDES50PE13P3
OPESOLDES50PE13P3
 
	s ^TKSOLDES("75117")="\0.5\0"
	s ^TKSOLDES("75118")="\0.5\0"
	s ^TKSOLDES("75119")="\0.5\0"
	s ^TKSOLDES("75129")="\0.5\0"
	s ^TKSOLDES("75130")="\0.5\0"
	s ^TKSOLDES("75158")="\0.5\0"
	s ^TKSOLDES("75159")="\0.5\0"
	s ^TKSOLDES("75161")="\0.5\0"
	s ^TKSOLDES("75164")="\0.5\0"
	s ^TKSOLDES("105099")="\0.5\0"
	s ^TKSOLDES("81913")="\0.5\0"
	s ^TKSOLDES("81614")="\0.5\0"
	s ^TKSOLDES("81862")="\0.5\0"
	s ^TKSOLDES("81660")="\0.5\0"
	s ^TKSOLDES("81659")="\0.5\0"
	s ^TKSOLDES("81658")="\0.5\0"
	s ^TKSOLDES("81632")="\0.5\0"
	s ^TKSOLDES("81630")="\0.5\0"
	s ^TKSOLDES("81629")="\0.5\0"
	s ^TKSOLDES("81628")="\0.5\0"
	s ^TKSOLDES("81619")="\0.5\0"
	s ^TKSOLDES("81618")="\0.5\0"
	s ^TKSOLDES("81617")="\0.5\0"
	s ^TKSOLDES("81616")="\0.5\0"
	s ^TKSOLDES("81615")="\0.5\0"
	s ^TKSOLDES("81661")="\0.5\0"
	s ^TKSOLDES("81662")="\0.5\0"
	s ^TKSOLDES("81839")="\0.5\0"
	s ^TKSOLDES("81853")="\0.5\0"
	s ^TKSOLDES("81851")="\0.5\0"
	s ^TKSOLDES("81848")="\0.5\0"
	s ^TKSOLDES("81846")="\0.5\0"
	s ^TKSOLDES("81840")="\0.5\0"
	s ^TKSOLDES("81820")="\0.5\0"
	s ^TKSOLDES("81719")="\0.5\0"
	s ^TKSOLDES("81815")="\0.5\0"
	s ^TKSOLDES("81812")="\0.5\0"
	s ^TKSOLDES("81786")="\0.5\0"
	s ^TKSOLDES("81743")="\0.5\0"
	s ^TKSOLDES("81732")="\0.5\0"
	s ^TKSOLDES("81720")="\0.5\0"
	s ^TKSOLDES("76247")="\0.5\0"
	s ^TKSOLDES("76270")="\0.5\0"
	s ^TKSOLDES("77949")="\0.5\0"
	s ^TKSOLDES("77749")="\0.5\0"
	s ^TKSOLDES("77629")="\0.5\0"
	s ^TKSOLDES("77635")="\0.5\0"
	s ^TKSOLDES("77701")="\0.5\0"
	s ^TKSOLDES("77748")="\0.5\0"
	s ^TKSOLDES("77752")="\0.5\0"
	s ^TKSOLDES("77599")="\0.5\0"
	s ^TKSOLDES("77756")="\0.5\0"
	s ^TKSOLDES("81112")="\0.5\0"
	s ^TKSOLDES("77781")="\0.5\0"
	s ^TKSOLDES("77799")="\0.5\0"
	s ^TKSOLDES("77800")="\0.5\0"
	s ^TKSOLDES("77600")="\0.5\0"
	s ^TKSOLDES("77592")="\0.5\0"
	s ^TKSOLDES("76883")="\0.5\0"
	s ^TKSOLDES("77510")="\0.5\0"
	s ^TKSOLDES("76889")="\0.5\0"
	s ^TKSOLDES("76896")="\0.5\0"
	s ^TKSOLDES("76899")="\0.5\0"
	s ^TKSOLDES("76939")="\0.5\0"
	s ^TKSOLDES("76941")="\0.5\0"
	s ^TKSOLDES("76942")="\0.5\0"
	s ^TKSOLDES("76950")="\0.5\0"
	s ^TKSOLDES("76951")="\0.5\0"
	s ^TKSOLDES("77159")="\0.5\0"
	s ^TKSOLDES("77160")="\0.5\0"
	s ^TKSOLDES("77161")="\0.5\0"
	s ^TKSOLDES("77424")="\0.5\0"
	s ^TKSOLDES("77801")="\0.5\0"
	s ^TKSOLDES("77802")="\0.5\0"
	s ^TKSOLDES("77803")="\0.5\0"
	s ^TKSOLDES("77927")="\0.5\0"
	s ^TKSOLDES("77932")="\0.5\0"
	s ^TKSOLDES("77933")="\0.5\0"
	s ^TKSOLDES("77938")="\0.5\0"
	s ^TKSOLDES("77939")="\0.5\0"
	s ^TKSOLDES("77940")="\0.5\0"
	s ^TKSOLDES("77941")="\0.5\0"
	s ^TKSOLDES("77943")="\0.5\0"
	s ^TKSOLDES("77945")="\0.5\0"
	s ^TKSOLDES("77946")="\0.5\0"
	s ^TKSOLDES("77947")="\0.5\0"
	s ^TKSOLDES("77948")="\0.5\0"
	s ^TKSOLDES("77926")="\0.5\0"
	s ^TKSOLDES("77890")="\0.5\0"
	s ^TKSOLDES("77866")="\0.5\0"
	s ^TKSOLDES("77804")="\0.5\0"
	s ^TKSOLDES("77805")="\0.5\0"
	s ^TKSOLDES("77806")="\0.5\0"
	s ^TKSOLDES("77807")="\0.5\0"
	s ^TKSOLDES("77809")="\0.5\0"
	s ^TKSOLDES("77880")="\0.5\0"
	s ^TKSOLDES("77889")="\0.5\0"
	s ^TKSOLDES("77881")="\0.5\0"
	s ^TKSOLDES("77883")="\0.5\0"
	s ^TKSOLDES("77884")="\0.5\0"
	s ^TKSOLDES("77886")="\0.5\0"
	s ^TKSOLDES("77887")="\0.5\0"
	s ^TKSOLDES("77888")="\0.5\0"
	s ^TKSOLDES("76888")="\0.5\0"
	s ^TKSOLDES("76882")="\0.5\0"
	s ^TKSOLDES("76272")="\0.5\0"
	s ^TKSOLDES("76371")="\0.5\0"
	s ^TKSOLDES("76356")="\0.5\0"
	s ^TKSOLDES("76357")="\0.5\0"
	s ^TKSOLDES("76369")="\0.5\0"
	s ^TKSOLDES("76370")="\0.5\0"
	s ^TKSOLDES("76372")="\0.5\0"
	s ^TKSOLDES("76354")="\0.5\0"
	s ^TKSOLDES("76375")="\0.5\0"
	s ^TKSOLDES("76377")="\0.5\0"
	s ^TKSOLDES("105077")="\0.5\0"
	s ^TKSOLDES("105074")="\0.5\0"
	s ^TKSOLDES("105073")="\0.5\0"
	s ^TKSOLDES("76355")="\0.5\0"
	s ^TKSOLDES("76353")="\0.5\0"
	s ^TKSOLDES("105068")="\0.5\0"
	s ^TKSOLDES("76351")="\0.5\0"
	s ^TKSOLDES("76279")="\0.5\0"
	s ^TKSOLDES("76280")="\0.5\0"
	s ^TKSOLDES("76282")="\0.5\0"
	s ^TKSOLDES("76300")="\0.5\0"
	s ^TKSOLDES("76305")="\0.5\0"
	s ^TKSOLDES("76307")="\0.5\0"
	s ^TKSOLDES("76317")="\0.5\0"
	s ^TKSOLDES("76321")="\0.5\0"
	s ^TKSOLDES("76322")="\0.5\0"
	s ^TKSOLDES("76323")="\0.5\0"
	s ^TKSOLDES("76336")="\0.5\0"
	s ^TKSOLDES("76348")="\0.5\0"
	s ^TKSOLDES("105069")="\0.5\0"
	s ^TKSOLDES("76457")="\0.5\0"
	s ^TKSOLDES("76881")="\0.5\0"
	s ^TKSOLDES("76492")="\0.5\0"
	s ^TKSOLDES("76632")="\0.5\0"
	s ^TKSOLDES("76633")="\0.5\0"
	s ^TKSOLDES("76634")="\0.5\0"
	s ^TKSOLDES("76635")="\0.5\0"
	s ^TKSOLDES("76638")="\0.5\0"
	s ^TKSOLDES("76640")="\0.5\0"
	s ^TKSOLDES("76642")="\0.5\0"
	s ^TKSOLDES("76643")="\0.5\0"
	s ^TKSOLDES("76868")="\0.5\0"
	s ^TKSOLDES("76870")="\0.5\0"
	s ^TKSOLDES("76879")="\0.5\0"
	s ^TKSOLDES("76880")="\0.5\0"
	s ^TKSOLDES("76631")="\0.5\0"
	s ^TKSOLDES("76630")="\0.5\0"
	s ^TKSOLDES("76509")="\0.5\0"
	s ^TKSOLDES("76493")="\0.5\0"
	s ^TKSOLDES("76496")="\0.5\0"
	s ^TKSOLDES("76506")="\0.5\0"
	s ^TKSOLDES("76507")="\0.5\0"
	s ^TKSOLDES("76508")="\0.5\0"
	s ^TKSOLDES("76511")="\0.5\0"
	s ^TKSOLDES("76629")="\0.5\0"
	s ^TKSOLDES("76618")="\0.5\0"
	s ^TKSOLDES("76621")="\0.5\0"
	s ^TKSOLDES("76625")="\0.5\0"
	s ^TKSOLDES("76626")="\0.5\0"
	s ^TKSOLDES("76627")="\0.5\0"
	s ^TKSOLDES("76628")="\0.5\0"
	s ^TKSOLDES("74588")="\0.5\0"
	s ^TKSOLDES("72395")="\0.5\0"
	s ^TKSOLDES("89944")="\0.5\0"
	s ^TKSOLDES("89903")="\0.5\0"
	s ^TKSOLDES("89902")="\0.5\0"
	s ^TKSOLDES("89901")="\0.5\0"
	s ^TKSOLDES("89899")="\0.5\0"
	s ^TKSOLDES("89898")="\0.5\0"
	s ^TKSOLDES("89897")="\0.5\0"
	s ^TKSOLDES("89896")="\0.5\0"
	s ^TKSOLDES("89894")="\0.5\0"
	s ^TKSOLDES("89904")="\0.5\0"
	s ^TKSOLDES("89923")="\0.5\0"
	s ^TKSOLDES("89936")="\0.5\0"
	s ^TKSOLDES("89941")="\0.5\0"
	s ^TKSOLDES("89940")="\0.5\0"
	s ^TKSOLDES("89938")="\0.5\0"
	s ^TKSOLDES("89935")="\0.5\0"
	s ^TKSOLDES("89925")="\0.5\0"
	s ^TKSOLDES("89934")="\0.5\0"
	s ^TKSOLDES("89932")="\0.5\0"
	s ^TKSOLDES("89931")="\0.5\0"
	s ^TKSOLDES("89926")="\0.5\0"
	s ^TKSOLDES("89891")="\0.5\0"
	s ^TKSOLDES("89889")="\0.5\0"
	s ^TKSOLDES("89867")="\0.5\0"
	s ^TKSOLDES("89864")="\0.5\0"
	s ^TKSOLDES("89854")="\0.5\0"
	s ^TKSOLDES("89851")="\0.5\0"
	s ^TKSOLDES("89848")="\0.5\0"
	s ^TKSOLDES("89847")="\0.5\0"
	s ^TKSOLDES("89846")="\0.5\0"
	s ^TKSOLDES("89844")="\0.5\0"
	s ^TKSOLDES("89839")="\0.5\0"
	s ^TKSOLDES("89865")="\0.5\0"
	s ^TKSOLDES("89870")="\0.5\0"
	s ^TKSOLDES("89886")="\0.5\0"
	s ^TKSOLDES("89882")="\0.5\0"
	s ^TKSOLDES("89885")="\0.5\0"
	s ^TKSOLDES("89884")="\0.5\0"
	s ^TKSOLDES("89883")="\0.5\0"
	s ^TKSOLDES("89880")="\0.5\0"
	s ^TKSOLDES("89871")="\0.5\0"
	s ^TKSOLDES("89878")="\0.5\0"
	s ^TKSOLDES("89877")="\0.5\0"
	s ^TKSOLDES("89876")="\0.5\0"
	s ^TKSOLDES("89872")="\0.5\0"
	s ^TKSOLDES("89943")="\0.5\0"
	s ^TKSOLDES("89945")="\0.5\0"
	s ^TKSOLDES("89836")="\0.5\0"
	s ^TKSOLDES("91851")="\0.5\0"
	s ^TKSOLDES("92067")="\0.5\0"
	s ^TKSOLDES("92058")="\0.5\0"
	s ^TKSOLDES("91992")="\0.5\0"
	s ^TKSOLDES("91903")="\0.5\0"
	s ^TKSOLDES("91896")="\0.5\0"
	s ^TKSOLDES("91893")="\0.5\0"
	s ^TKSOLDES("91882")="\0.5\0"
	s ^TKSOLDES("91858")="\0.5\0"
	s ^TKSOLDES("92068")="\0.5\0"
	s ^TKSOLDES("92676")="\0.5\0"
	s ^TKSOLDES("93115")="\0.5\0"
	s ^TKSOLDES("93120")="\0.5\0"
	s ^TKSOLDES("93117")="\0.5\0"
	s ^TKSOLDES("93116")="\0.5\0"
	s ^TKSOLDES("93103")="\0.5\0"
	s ^TKSOLDES("92986")="\0.5\0"
	s ^TKSOLDES("93095")="\0.5\0"
	s ^TKSOLDES("93083")="\0.5\0"
	s ^TKSOLDES("93080")="\0.5\0"
	s ^TKSOLDES("93079")="\0.5\0"
	s ^TKSOLDES("91854")="\0.5\0"
	s ^TKSOLDES("91841")="\0.5\0"
	s ^TKSOLDES("89947")="\0.5\0"
	s ^TKSOLDES("89989")="\0.5\0"
	s ^TKSOLDES("89979")="\0.5\0"
	s ^TKSOLDES("89978")="\0.5\0"
	s ^TKSOLDES("89977")="\0.5\0"
	s ^TKSOLDES("89976")="\0.5\0"
	s ^TKSOLDES("89975")="\0.5\0"
	s ^TKSOLDES("89960")="\0.5\0"
	s ^TKSOLDES("89959")="\0.5\0"
	s ^TKSOLDES("89951")="\0.5\0"
	s ^TKSOLDES("89988")="\0.5\0"
	s ^TKSOLDES("89996")="\0.5\0"
	s ^TKSOLDES("91793")="\0.5\0"
	s ^TKSOLDES("91617")="\0.5\0"
	s ^TKSOLDES("91754")="\0.5\0"
	s ^TKSOLDES("91708")="\0.5\0"
	s ^TKSOLDES("91706")="\0.5\0"
	s ^TKSOLDES("91313")="\0.5\0"
	s ^TKSOLDES("89997")="\0.5\0"
	s ^TKSOLDES("90657")="\0.5\0"
	s ^TKSOLDES("90381")="\0.5\0"
	s ^TKSOLDES("90084")="\0.5\0"
	s ^TKSOLDES("89998")="\0.5\0"
	s ^TKSOLDES("89837")="\0.5\0"
	s ^TKSOLDES("89828")="\0.5\0"
	s ^TKSOLDES("93122")="\0.5\0"
	s ^TKSOLDES("87557")="\0.5\0"
	s ^TKSOLDES("87612")="\0.5\0"
	s ^TKSOLDES("87609")="\0.5\0"
	s ^TKSOLDES("87608")="\0.5\0"
	s ^TKSOLDES("87607")="\0.5\0"
	s ^TKSOLDES("87597")="\0.5\0"
	s ^TKSOLDES("87567")="\0.5\0"
	s ^TKSOLDES("87566")="\0.5\0"
	s ^TKSOLDES("87560")="\0.5\0"
	s ^TKSOLDES("87613")="\0.5\0"
	s ^TKSOLDES("87614")="\0.5\0"
	s ^TKSOLDES("49727")="\0.5\0"
	s ^TKSOLDES("87738")="\0.5\0"
	s ^TKSOLDES("87737")="\0.5\0"
	s ^TKSOLDES("49578")="\0.5\0"
	s ^TKSOLDES("49797")="\0.5\0"
	s ^TKSOLDES("87615")="\0.5\0"
	s ^TKSOLDES("50198")="\0.5\0"
	s ^TKSOLDES("87623")="\0.5\0"
	s ^TKSOLDES("87622")="\0.5\0"
	s ^TKSOLDES("87621")="\0.5\0"
	s ^TKSOLDES("87558")="\0.5\0"
	s ^TKSOLDES("87556")="\0.5\0"
	s ^TKSOLDES("89822")="\0.5\0"
	s ^TKSOLDES("86378")="\0.5\0"
	s ^TKSOLDES("103338")="\0.5\0"
	s ^TKSOLDES("103339")="\0.5\0"
	s ^TKSOLDES("103340")="\0.5\0"
	s ^TKSOLDES("103342")="\0.5\0"
	s ^TKSOLDES("103343")="\0.5\0"
	s ^TKSOLDES("103344")="\0.5\0"
	s ^TKSOLDES("66502")="\0.5\0"
	s ^TKSOLDES("66505")="\0.5\0"
	s ^TKSOLDES("103337")="\0.5\0"
	s ^TKSOLDES("86394")="\0.5\0"
	s ^TKSOLDES("87554")="\0.5\0"
	s ^TKSOLDES("87546")="\0.5\0"
	s ^TKSOLDES("87552")="\0.5\0"
	s ^TKSOLDES("87551")="\0.5\0"
	s ^TKSOLDES("87550")="\0.5\0"
	s ^TKSOLDES("87537")="\0.5\0"
	s ^TKSOLDES("86474")="\0.5\0"
	s ^TKSOLDES("87525")="\0.5\0"
	s ^TKSOLDES("87521")="\0.5\0"
	s ^TKSOLDES("87519")="\0.5\0"
	s ^TKSOLDES("86591")="\0.5\0"
	s ^TKSOLDES("87739")="\0.5\0"
	s ^TKSOLDES("87747")="\0.5\0"
	s ^TKSOLDES("89802")="\0.5\0"
	s ^TKSOLDES("89800")="\0.5\0"
	s ^TKSOLDES("89798")="\0.5\0"
	s ^TKSOLDES("88488")="\0.5\0"
	s ^TKSOLDES("88480")="\0.5\0"
	s ^TKSOLDES("88477")="\0.5\0"
	s ^TKSOLDES("88464")="\0.5\0"
	s ^TKSOLDES("88462")="\0.5\0"
	s ^TKSOLDES("88459")="\0.5\0"
	s ^TKSOLDES("89801")="\0.5\0"
	s ^TKSOLDES("89803")="\0.5\0"
	s ^TKSOLDES("87748")="\0.5\0"
	s ^TKSOLDES("89813")="\0.5\0"
	s ^TKSOLDES("89819")="\0.5\0"
	s ^TKSOLDES("89818")="\0.5\0"
	s ^TKSOLDES("89816")="\0.5\0"
	s ^TKSOLDES("89812")="\0.5\0"
	s ^TKSOLDES("89804")="\0.5\0"
	s ^TKSOLDES("89809")="\0.5\0"
	s ^TKSOLDES("89808")="\0.5\0"
	s ^TKSOLDES("89806")="\0.5\0"
	s ^TKSOLDES("89805")="\0.5\0"
	s ^TKSOLDES("88452")="\0.5\0"
	s ^TKSOLDES("88450")="\0.5\0"
	s ^TKSOLDES("87754")="\0.5\0"
	s ^TKSOLDES("87758")="\0.5\0"
	s ^TKSOLDES("87757")="\0.5\0"
	s ^TKSOLDES("87756")="\0.5\0"
	s ^TKSOLDES("87753")="\0.5\0"
	s ^TKSOLDES("88449")="\0.5\0"
	s ^TKSOLDES("87752")="\0.5\0"
	s ^TKSOLDES("87751")="\0.5\0"
	s ^TKSOLDES("87750")="\0.5\0"
	s ^TKSOLDES("87749")="\0.5\0"
	s ^TKSOLDES("87759")="\0.5\0"
	s ^TKSOLDES("87760")="\0.5\0"
	s ^TKSOLDES("87871")="\0.5\0"
	s ^TKSOLDES("88448")="\0.5\0"
	s ^TKSOLDES("88446")="\0.5\0"
	s ^TKSOLDES("88445")="\0.5\0"
	s ^TKSOLDES("88400")="\0.5\0"
	s ^TKSOLDES("88399")="\0.5\0"
	s ^TKSOLDES("87927")="\0.5\0"
	s ^TKSOLDES("87926")="\0.5\0"
	s ^TKSOLDES("87920")="\0.5\0"
	s ^TKSOLDES("87895")="\0.5\0"
	s ^TKSOLDES("87881")="\0.5\0"
	s ^TKSOLDES("93121")="\0.5\0"
	s ^TKSOLDES("93123")="\0.5\0"
	s ^TKSOLDES("66528")="\0.5\0"
	s ^TKSOLDES("100930")="\0.5\0"
	s ^TKSOLDES("102263")="\0.5\0"
	s ^TKSOLDES("102260")="\0.5\0"
	s ^TKSOLDES("102258")="\0.5\0"
	s ^TKSOLDES("101083")="\0.5\0"
	s ^TKSOLDES("101081")="\0.5\0"
	s ^TKSOLDES("101062")="\0.5\0"
	s ^TKSOLDES("101061")="\0.5\0"
	s ^TKSOLDES("101060")="\0.5\0"
	s ^TKSOLDES("102265")="\0.5\0"
	s ^TKSOLDES("102266")="\0.5\0"
	s ^TKSOLDES("102278")="\0.5\0"
	s ^TKSOLDES("102301")="\0.5\0"
	s ^TKSOLDES("102295")="\0.5\0"
	s ^TKSOLDES("9172")="\0.5\0"
	s ^TKSOLDES("102272")="\0.5\0"
	s ^TKSOLDES("102267")="\0.5\0"
	s ^TKSOLDES("102271")="\0.5\0"
	s ^TKSOLDES("102270")="\0.5\0"
	s ^TKSOLDES("102269")="\0.5\0"
	s ^TKSOLDES("102268")="\0.5\0"
	s ^TKSOLDES("101050")="\0.5\0"
	s ^TKSOLDES("100929")="\0.5\0"
	s ^TKSOLDES("93141")="\0.5\0"
	s ^TKSOLDES("100812")="\0.5\0"
	s ^TKSOLDES("100810")="\0.5\0"
	s ^TKSOLDES("100809")="\0.5\0"
	s ^TKSOLDES("100808")="\0.5\0"
	s ^TKSOLDES("100796")="\0.5\0"
	s ^TKSOLDES("100795")="\0.5\0"
	s ^TKSOLDES("100794")="\0.5\0"
	s ^TKSOLDES("100793")="\0.5\0"
	s ^TKSOLDES("100792")="\0.5\0"
	s ^TKSOLDES("100811")="\0.5\0"
	s ^TKSOLDES("100820")="\0.5\0"
	s ^TKSOLDES("100928")="\0.5\0"
	s ^TKSOLDES("100923")="\0.5\0"
	s ^TKSOLDES("100927")="\0.5\0"
	s ^TKSOLDES("100926")="\0.5\0"
	s ^TKSOLDES("100925")="\0.5\0"
	s ^TKSOLDES("100838")="\0.5\0"
	s ^TKSOLDES("100821")="\0.5\0"
	s ^TKSOLDES("100837")="\0.5\0"
	s ^TKSOLDES("100836")="\0.5\0"
	s ^TKSOLDES("100835")="\0.5\0"
	s ^TKSOLDES("100834")="\0.5\0"
	s ^TKSOLDES("102304")="\0.5\0"
	s ^TKSOLDES("102306")="\0.5\0"
	s ^TKSOLDES("102409")="\0.5\0"
	s ^TKSOLDES("102404")="\0.5\0"
	s ^TKSOLDES("102399")="\0.5\0"
	s ^TKSOLDES("102397")="\0.5\0"
	s ^TKSOLDES("102396")="\0.5\0"
	s ^TKSOLDES("102394")="\0.5\0"
	s ^TKSOLDES("102393")="\0.5\0"
	s ^TKSOLDES("102391")="\0.5\0"
	s ^TKSOLDES("102390")="\0.5\0"
	s ^TKSOLDES("102407")="\0.5\0"
	s ^TKSOLDES("102419")="\0.5\0"
	s ^TKSOLDES("105393")="\0.5\0"
	s ^TKSOLDES("105614")="\0.5\0"
	s ^TKSOLDES("105692")="\0.5\0"
	s ^TKSOLDES("105616")="\0.5\0"
	s ^TKSOLDES("105615")="\0.5\0"
	s ^TKSOLDES("105613")="\0.5\0"
	s ^TKSOLDES("102435")="\0.5\0"
	s ^TKSOLDES("105612")="\0.5\0"
	s ^TKSOLDES("105605")="\0.5\0"
	s ^TKSOLDES("105604")="\0.5\0"
	s ^TKSOLDES("105603")="\0.5\0"
	s ^TKSOLDES("102389")="\0.5\0"
	s ^TKSOLDES("102385")="\0.5\0"
	s ^TKSOLDES("105399")="\0.5\0"
	s ^TKSOLDES("102324")="\0.5\0"
	s ^TKSOLDES("105405")="\0.5\0"
	s ^TKSOLDES("105404")="\0.5\0"
	s ^TKSOLDES("105398")="\0.5\0"
	s ^TKSOLDES("102384")="\0.5\0"
	s ^TKSOLDES("105397")="\0.5\0"
	s ^TKSOLDES("105396")="\0.5\0"
	s ^TKSOLDES("105395")="\0.5\0"
	s ^TKSOLDES("105394")="\0.5\0"
	s ^TKSOLDES("102329")="\0.5\0"
	s ^TKSOLDES("105597")="\0.5\0"
	s ^TKSOLDES("105599")="\0.5\0"
	s ^TKSOLDES("102383")="\0.5\0"
	s ^TKSOLDES("102382")="\0.5\0"
	s ^TKSOLDES("102381")="\0.5\0"
	s ^TKSOLDES("102380")="\0.5\0"
	s ^TKSOLDES("102365")="\0.5\0"
	s ^TKSOLDES("102359")="\0.5\0"
	s ^TKSOLDES("102356")="\0.5\0"
	s ^TKSOLDES("102354")="\0.5\0"
	s ^TKSOLDES("102342")="\0.5\0"
	s ^TKSOLDES("105600")="\0.5\0"
	s ^TKSOLDES("100791")="\0.5\0"
	s ^TKSOLDES("100778")="\0.5\0"
	s ^TKSOLDES("93302")="\0.5\0"
	s ^TKSOLDES("93524")="\0.5\0"
	s ^TKSOLDES("93523")="\0.5\0"
	s ^TKSOLDES("93464")="\0.5\0"
	s ^TKSOLDES("93462")="\0.5\0"
	s ^TKSOLDES("93383")="\0.5\0"
	s ^TKSOLDES("93381")="\0.5\0"
	s ^TKSOLDES("93380")="\0.5\0"
	s ^TKSOLDES("93378")="\0.5\0"
	s ^TKSOLDES("93525")="\0.5\0"
	s ^TKSOLDES("93527")="\0.5\0"
	s ^TKSOLDES("93849")="\0.5\0"
	s ^TKSOLDES("100086")="\0.5\0"
	s ^TKSOLDES("93870")="\0.5\0"
	s ^TKSOLDES("93852")="\0.5\0"
	s ^TKSOLDES("93846")="\0.5\0"
	s ^TKSOLDES("93554")="\0.5\0"
	s ^TKSOLDES("93845")="\0.5\0"
	s ^TKSOLDES("93814")="\0.5\0"
	s ^TKSOLDES("93780")="\0.5\0"
	s ^TKSOLDES("93779")="\0.5\0"
	s ^TKSOLDES("93342")="\0.5\0"
	s ^TKSOLDES("93295")="\0.5\0"
	s ^TKSOLDES("100090")="\0.5\0"
	s ^TKSOLDES("93238")="\0.5\0"
	s ^TKSOLDES("93233")="\0.5\0"
	s ^TKSOLDES("93232")="\0.5\0"
	s ^TKSOLDES("93231")="\0.5\0"
	s ^TKSOLDES("93176")="\0.5\0"
	s ^TKSOLDES("93173")="\0.5\0"
	s ^TKSOLDES("93166")="\0.5\0"
	s ^TKSOLDES("93159")="\0.5\0"
	s ^TKSOLDES("93144")="\0.5\0"
	s ^TKSOLDES("93236")="\0.5\0"
	s ^TKSOLDES("93239")="\0.5\0"
	s ^TKSOLDES("93294")="\0.5\0"
	s ^TKSOLDES("93290")="\0.5\0"
	s ^TKSOLDES("93293")="\0.5\0"
	s ^TKSOLDES("93292")="\0.5\0"
	s ^TKSOLDES("93291")="\0.5\0"
	s ^TKSOLDES("93283")="\0.5\0"
	s ^TKSOLDES("93240")="\0.5\0"
	s ^TKSOLDES("93261")="\0.5\0"
	s ^TKSOLDES("93254")="\0.5\0"
	s ^TKSOLDES("93250")="\0.5\0"
	s ^TKSOLDES("93249")="\0.5\0"
	s ^TKSOLDES("100088")="\0.5\0"
	s ^TKSOLDES("100091")="\0.5\0"
	s ^TKSOLDES("100621")="\0.5\0"
	s ^TKSOLDES("100602")="\0.5\0"
	s ^TKSOLDES("100244")="\0.5\0"
	s ^TKSOLDES("100241")="\0.5\0"
	s ^TKSOLDES("100239")="\0.5\0"
	s ^TKSOLDES("100238")="\0.5\0"
	s ^TKSOLDES("100232")="\0.5\0"
	s ^TKSOLDES("100194")="\0.5\0"
	s ^TKSOLDES("100193")="\0.5\0"
	s ^TKSOLDES("100187")="\0.5\0"
	s ^TKSOLDES("100601")="\0.5\0"
	s ^TKSOLDES("100604")="\0.5\0"
	s ^TKSOLDES("100094")="\0.5\0"
	s ^TKSOLDES("100615")="\0.5\0"
	s ^TKSOLDES("100619")="\0.5\0"
	s ^TKSOLDES("100618")="\0.5\0"
	s ^TKSOLDES("100616")="\0.5\0"
	s ^TKSOLDES("100612")="\0.5\0"
	s ^TKSOLDES("100605")="\0.5\0"
	s ^TKSOLDES("100611")="\0.5\0"
	s ^TKSOLDES("100610")="\0.5\0"
	s ^TKSOLDES("100608")="\0.5\0"
	s ^TKSOLDES("100607")="\0.5\0"
	s ^TKSOLDES("100186")="\0.5\0"
	s ^TKSOLDES("100185")="\0.5\0"
	s ^TKSOLDES("100101")="\0.5\0"
	s ^TKSOLDES("100105")="\0.5\0"
	s ^TKSOLDES("100104")="\0.5\0"
	s ^TKSOLDES("100102")="\0.5\0"
	s ^TKSOLDES("100099")="\0.5\0"
	s ^TKSOLDES("100182")="\0.5\0"
	s ^TKSOLDES("100098")="\0.5\0"
	s ^TKSOLDES("100097")="\0.5\0"
	s ^TKSOLDES("100096")="\0.5\0"
	s ^TKSOLDES("100095")="\0.5\0"
	s ^TKSOLDES("100132")="\0.5\0"
	s ^TKSOLDES("100135")="\0.5\0"
	s ^TKSOLDES("100136")="\0.5\0"
	s ^TKSOLDES("100181")="\0.5\0"
	s ^TKSOLDES("100174")="\0.5\0"
	s ^TKSOLDES("100170")="\0.5\0"
	s ^TKSOLDES("100168")="\0.5\0"
	s ^TKSOLDES("100167")="\0.5\0"
	s ^TKSOLDES("100166")="\0.5\0"
	s ^TKSOLDES("100148")="\0.5\0"
	s ^TKSOLDES("100147")="\0.5\0"
	s ^TKSOLDES("100140")="\0.5\0"
	s ^TKSOLDES("100137")="\0.5\0"
	s ^TKSOLDES("66510")="\0.5\0"
	s ^TKSOLDES("89817")="\0.5\0"
	s ^TKSOLDES("72405")="\0.5\0"
	s ^TKSOLDES("72408")="\0.5\0"
	s ^TKSOLDES("72409")="\0.5\0"
	s ^TKSOLDES("72411")="\0.5\0"
	s ^TKSOLDES("105109")="\0.5\0"
	s ^TKSOLDES("84328")="\0.5\0"
	s ^TKSOLDES("84327")="\0.5\0"
	s ^TKSOLDES("72407")="\0.5\0"
	s ^TKSOLDES("72369")="\0.5\0"
	s ^TKSOLDES("84324")="\0.5\0"
	s ^TKSOLDES("72305")="\0.5\0"
	s ^TKSOLDES("72290")="\0.5\0"
	s ^TKSOLDES("72291")="\0.5\0"
	s ^TKSOLDES("72318")="\0.5\0"
	s ^TKSOLDES("72356")="\0.5\0"
	s ^TKSOLDES("72325")="\0.5\0"
	s ^TKSOLDES("72332")="\0.5\0"
	s ^TKSOLDES("72355")="\0.5\0"
	s ^TKSOLDES("84325")="\0.5\0"
	s ^TKSOLDES("72973")="\0.5\0"
	s ^TKSOLDES("72285")="\0.5\0"
	s ^TKSOLDES("83745")="\0.5\0"
	s ^TKSOLDES("83740")="\0.5\0"
	s ^TKSOLDES("83744")="\0.5\0"
	s ^TKSOLDES("83746")="\0.5\0"
	s ^TKSOLDES("72978")="\0.5\0"
	s ^TKSOLDES("83749")="\0.5\0"
	s ^TKSOLDES("83750")="\0.5\0"
	s ^TKSOLDES("83751")="\0.5\0"
	s ^TKSOLDES("83739")="\0.5\0"
	s ^TKSOLDES("83738")="\0.5\0"
	s ^TKSOLDES("83736")="\0.5\0"
	s ^TKSOLDES("105108")="\0.5\0"
	s ^TKSOLDES("73191")="\0.5\0"
	s ^TKSOLDES("73193")="\0.5\0"
	s ^TKSOLDES("73194")="\0.5\0"
	s ^TKSOLDES("83691")="\0.5\0"
	s ^TKSOLDES("83692")="\0.5\0"
	s ^TKSOLDES("83694")="\0.5\0"
	s ^TKSOLDES("83735")="\0.5\0"
	s ^TKSOLDES("72286")="\0.5\0"
	s ^TKSOLDES("72282")="\0.5\0"
	s ^TKSOLDES("83758")="\0.5\0"
	s ^TKSOLDES("84890")="\0.5\0"
	s ^TKSOLDES("84893")="\0.5\0"
	s ^TKSOLDES("84891")="\0.5\0"
	s ^TKSOLDES("84887")="\0.5\0"
	s ^TKSOLDES("72278")="\0.5\0"
	s ^TKSOLDES("83594")="\0.5\0"
	s ^TKSOLDES("68322")="\0.5\0"
	s ^TKSOLDES("83595")="\0.5\0"
	s ^TKSOLDES("84894")="\0.5\0"
	s ^TKSOLDES("84895")="\0.5\0"
	s ^TKSOLDES("84908")="\0.5\0"
	s ^TKSOLDES("84933")="\0.5\0"
	s ^TKSOLDES("84932")="\0.5\0"
	s ^TKSOLDES("84928")="\0.5\0"
	s ^TKSOLDES("84924")="\0.5\0"
	s ^TKSOLDES("84922")="\0.5\0"
	s ^TKSOLDES("84917")="\0.5\0"
	s ^TKSOLDES("84915")="\0.5\0"
	s ^TKSOLDES("84909")="\0.5\0"
	s ^TKSOLDES("83596")="\0.5\0"
	s ^TKSOLDES("105111")="\0.5\0"
	s ^TKSOLDES("72271")="\0.5\0"
	s ^TKSOLDES("72269")="\0.5\0"
	s ^TKSOLDES("72270")="\0.5\0"
	s ^TKSOLDES("72274")="\0.5\0"
	s ^TKSOLDES("71915")="\0.5\0"
	s ^TKSOLDES("72275")="\0.5\0"
	s ^TKSOLDES("72276")="\0.5\0"
	s ^TKSOLDES("72277")="\0.5\0"
	s ^TKSOLDES("105110")="\0.5\0"
	s ^TKSOLDES("71668")="\0.5\0"
	s ^TKSOLDES("70471")="\0.5\0"
	s ^TKSOLDES("71667")="\0.5\0"
	s ^TKSOLDES("71245")="\0.5\0"
	s ^TKSOLDES("71397")="\0.5\0"
	s ^TKSOLDES("71463")="\0.5\0"
	s ^TKSOLDES("71526")="\0.5\0"
	s ^TKSOLDES("71529")="\0.5\0"
	s ^TKSOLDES("71569")="\0.5\0"
	s ^TKSOLDES("71589")="\0.5\0"
	s ^TKSOLDES("71666")="\0.5\0"
	s ^TKSOLDES("83757")="\0.5\0"
	s ^TKSOLDES("83762")="\0.5\0"
	s ^TKSOLDES("84936")="\0.5\0"
	s ^TKSOLDES("83837")="\0.5\0"
	s ^TKSOLDES("83835")="\0.5\0"
	s ^TKSOLDES("83836")="\0.5\0"
	s ^TKSOLDES("83858")="\0.5\0"
	s ^TKSOLDES("83765")="\0.5\0"
	s ^TKSOLDES("83860")="\0.5\0"
	s ^TKSOLDES("83861")="\0.5\0"
	s ^TKSOLDES("83955")="\0.5\0"
	s ^TKSOLDES("83833")="\0.5\0"
	s ^TKSOLDES("83832")="\0.5\0"
	s ^TKSOLDES("83831")="\0.5\0"
	s ^TKSOLDES("83972")="\0.5\0"
	s ^TKSOLDES("74262")="\0.5\0"
	s ^TKSOLDES("74263")="\0.5\0"
	s ^TKSOLDES("74264")="\0.5\0"
	s ^TKSOLDES("83824")="\0.5\0"
	s ^TKSOLDES("83825")="\0.5\0"
	s ^TKSOLDES("83827")="\0.5\0"
	s ^TKSOLDES("83829")="\0.5\0"
	s ^TKSOLDES("83954")="\0.5\0"
	s ^TKSOLDES("83945")="\0.5\0"
	s ^TKSOLDES("83895")="\0.5\0"
	s ^TKSOLDES("83893")="\0.5\0"
	s ^TKSOLDES("83894")="\0.5\0"
	s ^TKSOLDES("83896")="\0.5\0"
	s ^TKSOLDES("83873")="\0.5\0"
	s ^TKSOLDES("83898")="\0.5\0"
	s ^TKSOLDES("83903")="\0.5\0"
	s ^TKSOLDES("83909")="\0.5\0"
	s ^TKSOLDES("83874")="\0.5\0"
	s ^TKSOLDES("83872")="\0.5\0"
	s ^TKSOLDES("83944")="\0.5\0"
	s ^TKSOLDES("83869")="\0.5\0"
	s ^TKSOLDES("83943")="\0.5\0"
	s ^TKSOLDES("83862")="\0.5\0"
	s ^TKSOLDES("83931")="\0.5\0"
	s ^TKSOLDES("83911")="\0.5\0"
	s ^TKSOLDES("83863")="\0.5\0"
	s ^TKSOLDES("83910")="\0.5\0"
	s ^TKSOLDES("83867")="\0.5\0"
	s ^TKSOLDES("83868")="\0.5\0"
	s ^TKSOLDES("83823")="\0.5\0"
	s ^TKSOLDES("83822")="\0.5\0"
	s ^TKSOLDES("84021")="\0.5\0"
	s ^TKSOLDES("73708")="\0.5\0"
	s ^TKSOLDES("73727")="\0.5\0"
	s ^TKSOLDES("74141")="\0.5\0"
	s ^TKSOLDES("83775")="\0.5\0"
	s ^TKSOLDES("74143")="\0.5\0"
	s ^TKSOLDES("74148")="\0.5\0"
	s ^TKSOLDES("74150")="\0.5\0"
	s ^TKSOLDES("73707")="\0.5\0"
	s ^TKSOLDES("73706")="\0.5\0"
	s ^TKSOLDES("73704")="\0.5\0"
	s ^TKSOLDES("83767")="\0.5\0"
	s ^TKSOLDES("83769")="\0.5\0"
	s ^TKSOLDES("83771")="\0.5\0"
	s ^TKSOLDES("83772")="\0.5\0"
	s ^TKSOLDES("83773")="\0.5\0"
	s ^TKSOLDES("83774")="\0.5\0"
	s ^TKSOLDES("73701")="\0.5\0"
	s ^TKSOLDES("73703")="\0.5\0"
	s ^TKSOLDES("74260")="\0.5\0"
	s ^TKSOLDES("83776")="\0.5\0"
	s ^TKSOLDES("83821")="\0.5\0"
	s ^TKSOLDES("83813")="\0.5\0"
	s ^TKSOLDES("83801")="\0.5\0"
	s ^TKSOLDES("83806")="\0.5\0"
	s ^TKSOLDES("74261")="\0.5\0"
	s ^TKSOLDES("83788")="\0.5\0"
	s ^TKSOLDES("83815")="\0.5\0"
	s ^TKSOLDES("83818")="\0.5\0"
	s ^TKSOLDES("83820")="\0.5\0"
	s ^TKSOLDES("83799")="\0.5\0"
	s ^TKSOLDES("83786")="\0.5\0"
	s ^TKSOLDES("83777")="\0.5\0"
	s ^TKSOLDES("83785")="\0.5\0"
	s ^TKSOLDES("83778")="\0.5\0"
	s ^TKSOLDES("83779")="\0.5\0"
	s ^TKSOLDES("83780")="\0.5\0"
	s ^TKSOLDES("66854")="\0.5\0"
	s ^TKSOLDES("83781")="\0.5\0"
	s ^TKSOLDES("83782")="\0.5\0"
	s ^TKSOLDES("83783")="\0.5\0"
	s ^TKSOLDES("83784")="\0.5\0"
	s ^TKSOLDES("84935")="\0.5\0"
	s ^TKSOLDES("84888")="\0.5\0"
	s ^TKSOLDES("67198")="\0.5\0"
	s ^TKSOLDES("67121")="\0.5\0"
	s ^TKSOLDES("67111")="\0.5\0"
	s ^TKSOLDES("67073")="\0.5\0"
	s ^TKSOLDES("103345")="\0.5\0"
	s ^TKSOLDES("83244")="\0.5\0"
	s ^TKSOLDES("103346")="\0.5\0"
	s ^TKSOLDES("67220")="\0.5\0"
	s ^TKSOLDES("67222")="\0.5\0"
	s ^TKSOLDES("67482")="\0.5\0"
	s ^TKSOLDES("67195")="\0.5\0"
	s ^TKSOLDES("67126")="\0.5\0"
	s ^TKSOLDES("67127")="\0.5\0"
	s ^TKSOLDES("67454")="\0.5\0"
	s ^TKSOLDES("67504")="\0.5\0"
	s ^TKSOLDES("67506")="\0.5\0"
	s ^TKSOLDES("68007")="\0.5\0"
	s ^TKSOLDES("85577")="\0.5\0"
	s ^TKSOLDES("85576")="\0.5\0"
	s ^TKSOLDES("85575")="\0.5\0"
	s ^TKSOLDES("85561")="\0.5\0"
	s ^TKSOLDES("83156")="\0.5\0"
	s ^TKSOLDES("85560")="\0.5\0"
	s ^TKSOLDES("83243")="\0.5\0"
	s ^TKSOLDES("67236")="\0.5\0"
	s ^TKSOLDES("83261")="\0.5\0"
	s ^TKSOLDES("83361")="\0.5\0"
	s ^TKSOLDES("83317")="\0.5\0"
	s ^TKSOLDES("67065")="\0.5\0"
	s ^TKSOLDES("83360")="\0.5\0"
	s ^TKSOLDES("83509")="\0.5\0"
	s ^TKSOLDES("67010")="\0.5\0"
	s ^TKSOLDES("66987")="\0.5\0"
	s ^TKSOLDES("66892")="\0.5\0"
	s ^TKSOLDES("66882")="\0.5\0"
	s ^TKSOLDES("83510")="\0.5\0"
	s ^TKSOLDES("66989")="\0.5\0"
	s ^TKSOLDES("67457")="\0.5\0"
	s ^TKSOLDES("103355")="\0.5\0"
	s ^TKSOLDES("67063")="\0.5\0"
	s ^TKSOLDES("67061")="\0.5\0"
	s ^TKSOLDES("67058")="\0.5\0"
	s ^TKSOLDES("67011")="\0.5\0"
	s ^TKSOLDES("103347")="\0.5\0"
	s ^TKSOLDES("103356")="\0.5\0"
	s ^TKSOLDES("103384")="\0.5\0"
	s ^TKSOLDES("103380")="\0.5\0"
	s ^TKSOLDES("84937")="\0.5\0"
	s ^TKSOLDES("78535")="\0.5\0"
	s ^TKSOLDES("78533")="\0.5\0"
	s ^TKSOLDES("78534")="\0.5\0"
	s ^TKSOLDES("79068")="\0.5\0"
	s ^TKSOLDES("78532")="\0.5\0"
	s ^TKSOLDES("40161")="\0.5\0"
	s ^TKSOLDES("40163")="\0.5\0"
	s ^TKSOLDES("40159")="\0.5\0"
	s ^TKSOLDES("40164")="\0.5\0"
	s ^TKSOLDES("78531")="\0.5\0"
	s ^TKSOLDES("78530")="\0.5\0"
	s ^TKSOLDES("74576")="\0.5\0"
	s ^TKSOLDES("74585")="\0.5\0"
	s ^TKSOLDES("74580")="\0.5\0"
	s ^TKSOLDES("74583")="\0.5\0"
	s ^TKSOLDES("74586")="\0.5\0"
	s ^TKSOLDES("74577")="\0.5\0"
	s ^TKSOLDES("74598")="\0.5\0"
	s ^TKSOLDES("74599")="\0.5\0"
	s ^TKSOLDES("74514")="\0.5\0"
	s ^TKSOLDES("74578")="\0.5\0"
	s ^TKSOLDES("40174")="\0.5\0"
	s ^TKSOLDES("78536")="\0.5\0"
	s ^TKSOLDES("74575")="\0.5\0"
	s ^TKSOLDES("78537")="\0.5\0"
	s ^TKSOLDES("40142")="\0.5\0"
	s ^TKSOLDES("40141")="\0.5\0"
	s ^TKSOLDES("79066")="\0.5\0"
	s ^TKSOLDES("79064")="\0.5\0"
	s ^TKSOLDES("79051")="\0.5\0"
	s ^TKSOLDES("79050")="\0.5\0"
	s ^TKSOLDES("74574")="\0.5\0"
	s ^TKSOLDES("40167")="\0.5\0"
	s ^TKSOLDES("74522")="\0.5\0"
	s ^TKSOLDES("105213")="\0.5\0"
	s ^TKSOLDES("79111")="\0.5\0"
	s ^TKSOLDES("79117")="\0.5\0"
	s ^TKSOLDES("79116")="\0.5\0"
	s ^TKSOLDES("79109")="\0.5\0"
	s ^TKSOLDES("79069")="\0.5\0"
	s ^TKSOLDES("79091")="\0.5\0"
	s ^TKSOLDES("79086")="\0.5\0"
	s ^TKSOLDES("79085")="\0.5\0"
	s ^TKSOLDES("79118")="\0.5\0"
	s ^TKSOLDES("79119")="\0.5\0"
	s ^TKSOLDES("79121")="\0.5\0"
	s ^TKSOLDES("78406")="\0.5\0"
	s ^TKSOLDES("78410")="\0.5\0"
	s ^TKSOLDES("79125")="\0.5\0"
	s ^TKSOLDES("79124")="\0.5\0"
	s ^TKSOLDES("79123")="\0.5\0"
	s ^TKSOLDES("79122")="\0.5\0"
	s ^TKSOLDES("78413")="\0.5\0"
	s ^TKSOLDES("43965")="\0.5\0"
	s ^TKSOLDES("79084")="\0.5\0"
	s ^TKSOLDES("74516")="\0.5\0"
	s ^TKSOLDES("74559")="\0.5\0"
	s ^TKSOLDES("74556")="\0.5\0"
	s ^TKSOLDES("74558")="\0.5\0"
	s ^TKSOLDES("79079")="\0.5\0"
	s ^TKSOLDES("74528")="\0.5\0"
	s ^TKSOLDES("79078")="\0.5\0"
	s ^TKSOLDES("79077")="\0.5\0"
	s ^TKSOLDES("79076")="\0.5\0"
	s ^TKSOLDES("74529")="\0.5\0"
	s ^TKSOLDES("74527")="\0.5\0"
	s ^TKSOLDES("74517")="\0.5\0"
	s ^TKSOLDES("74526")="\0.5\0"
	s ^TKSOLDES("74519")="\0.5\0"
	s ^TKSOLDES("74520")="\0.5\0"
	s ^TKSOLDES("79083")="\0.5\0"
	s ^TKSOLDES("79082")="\0.5\0"
	s ^TKSOLDES("79081")="\0.5\0"
	s ^TKSOLDES("79080")="\0.5\0"
	s ^TKSOLDES("74521")="\0.5\0"
	s ^TKSOLDES("74511")="\0.5\0"
	s ^TKSOLDES("74512")="\0.5\0"
	s ^TKSOLDES("79036")="\0.5\0"
	s ^TKSOLDES("105215")="\0.5\0"
	s ^TKSOLDES("74389")="\0.5\0"
	s ^TKSOLDES("74390")="\0.5\0"
	s ^TKSOLDES("105214")="\0.5\0"
	s ^TKSOLDES("105216")="\0.5\0"
	s ^TKSOLDES("7197")="\0.5\0"
	s ^TKSOLDES("36096")="\0.5\0"
	s ^TKSOLDES("36095")="\0.5\0"
	s ^TKSOLDES("36087")="\0.5\0"
	s ^TKSOLDES("104500")="\0.5\0"
	s ^TKSOLDES("74497")="\0.5\0"
	s ^TKSOLDES("74388")="\0.5\0"
	s ^TKSOLDES("78990")="\0.5\0"
	s ^TKSOLDES("74386")="\0.5\0"
	s ^TKSOLDES("105426")="\0.5\0"
	s ^TKSOLDES("74508")="\0.5\0"
	s ^TKSOLDES("74506")="\0.5\0"
	s ^TKSOLDES("74504")="\0.5\0"
	s ^TKSOLDES("74503")="\0.5\0"
	s ^TKSOLDES("74501")="\0.5\0"
	s ^TKSOLDES("74500")="\0.5\0"
	s ^TKSOLDES("7196")="\0.5\0"
	s ^TKSOLDES("74382")="\0.5\0"
	s ^TKSOLDES("74383")="\0.5\0"
	s ^TKSOLDES("36075")="\0.5\0"
	s ^TKSOLDES("35476")="\0.5\0"
	s ^TKSOLDES("74451")="\0.5\0"
	s ^TKSOLDES("8755")="\0.5\0"
	s ^TKSOLDES("8757")="\0.5\0"
	s ^TKSOLDES("104498")="\0.5\0"
	s ^TKSOLDES("74610")="\0.5\0"
	s ^TKSOLDES("74609")="\0.5\0"
	s ^TKSOLDES("74608")="\0.5\0"
	s ^TKSOLDES("74607")="\0.5\0"
	s ^TKSOLDES("74606")="\0.5\0"
	s ^TKSOLDES("74605")="\0.5\0"
	s ^TKSOLDES("74604")="\0.5\0"
	s ^TKSOLDES("105217")="\0.5\0"
	s ^TKSOLDES("74603")="\0.5\0"
	s ^TKSOLDES("74600")="\0.5\0"
	s ^TKSOLDES("74450")="\0.5\0"
	s ^TKSOLDES("78401")="\0.5\0"
	s ^TKSOLDES("74449")="\0.5\0"
	s ^TKSOLDES("105218")="\0.5\0"
	s ^TKSOLDES("104499")="\0.5\0"
	s ^TKSOLDES("74602")="\0.5\0"
	s ^TKSOLDES("74391")="\0.5\0"
	s ^TKSOLDES("74613")="\0.5\0"
	s ^TKSOLDES("74612")="\0.5\0"
	s ^TKSOLDES("74611")="\0.5\0"
	s ^TKSOLDES("74601")="\0.5\0"
	s ^TKSOLDES("78987")="\0.5\0"
	s ^TKSOLDES("78991")="\0.5\0"
	s ^TKSOLDES("5802")="\0.5\0"
	s ^TKSOLDES("74371")="\0.5\0"
	s ^TKSOLDES("79030")="\0.5\0"
	s ^TKSOLDES("79028")="\0.5\0"
	s ^TKSOLDES("74370")="\0.5\0"
	s ^TKSOLDES("74372")="\0.5\0"
	s ^TKSOLDES("79032")="\0.5\0"
	s ^TKSOLDES("74373")="\0.5\0"
	s ^TKSOLDES("74374")="\0.5\0"
	s ^TKSOLDES("79026")="\0.5\0"
	s ^TKSOLDES("79024")="\0.5\0"
	s ^TKSOLDES("79031")="\0.5\0"
	s ^TKSOLDES("79033")="\0.5\0"
	s ^TKSOLDES("79016")="\0.5\0"
	s ^TKSOLDES("79034")="\0.5\0"
	s ^TKSOLDES("79048")="\0.5\0"
	s ^TKSOLDES("79045")="\0.5\0"
	s ^TKSOLDES("79044")="\0.5\0"
	s ^TKSOLDES("79042")="\0.5\0"
	s ^TKSOLDES("79041")="\0.5\0"
	s ^TKSOLDES("79040")="\0.5\0"
	s ^TKSOLDES("79039")="\0.5\0"
	s ^TKSOLDES("79037")="\0.5\0"
	s ^TKSOLDES("8758")="\0.5\0"
	s ^TKSOLDES("79035")="\0.5\0"
	s ^TKSOLDES("79017")="\0.5\0"
	s ^TKSOLDES("74378")="\0.5\0"
	s ^TKSOLDES("5806")="\0.5\0"
	s ^TKSOLDES("74379")="\0.5\0"
	s ^TKSOLDES("79004")="\0.5\0"
	s ^TKSOLDES("79003")="\0.5\0"
	s ^TKSOLDES("79002")="\0.5\0"
	s ^TKSOLDES("78999")="\0.5\0"
	s ^TKSOLDES("78997")="\0.5\0"
	s ^TKSOLDES("78996")="\0.5\0"
	s ^TKSOLDES("78995")="\0.5\0"
	s ^TKSOLDES("78994")="\0.5\0"
	s ^TKSOLDES("78993")="\0.5\0"
	s ^TKSOLDES("78992")="\0.5\0"
 
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 