ROUTINE OPESOLDES70PE13P1
OPESOLDES70PE13P1
 
 
 s ^TKSOLDES("81387")="\0.7\0"
 s ^TKSOLDES("81384")="\0.7\0"
 s ^TKSOLDES("81385")="\0.7\0"
 s ^TKSOLDES("81386")="\0.7\0"
 s ^TKSOLDES("81388")="\0.7\0"
 s ^TKSOLDES("87325")="\0.7\0"
 s ^TKSOLDES("81389")="\0.7\0"
 s ^TKSOLDES("81391")="\0.7\0"
 s ^TKSOLDES("81392")="\0.7\0"
 s ^TKSOLDES("81393")="\0.7\0"
 s ^TKSOLDES("81383")="\0.7\0"
 s ^TKSOLDES("81380")="\0.7\0"
 s ^TKSOLDES("81379")="\0.7\0"
 s ^TKSOLDES("9225")="\0.7\0"
 s ^TKSOLDES("54779")="\0.7\0"
 s ^TKSOLDES("54781")="\0.7\0"
 s ^TKSOLDES("54782")="\0.7\0"
 s ^TKSOLDES("54784")="\0.7\0"
 s ^TKSOLDES("55632")="\0.7\0"
 s ^TKSOLDES("55633")="\0.7\0"
 s ^TKSOLDES("62514")="\0.7\0"
 s ^TKSOLDES("80081")="\0.7\0"
 s ^TKSOLDES("81378")="\0.7\0"
 s ^TKSOLDES("81394")="\0.7\0"
 s ^TKSOLDES("81395")="\0.7\0"
 s ^TKSOLDES("81416")="\0.7\0"
 s ^TKSOLDES("81412")="\0.7\0"
 s ^TKSOLDES("81413")="\0.7\0"
 s ^TKSOLDES("81414")="\0.7\0"
 s ^TKSOLDES("81418")="\0.7\0"
 s ^TKSOLDES("81410")="\0.7\0"
 s ^TKSOLDES("81419")="\0.7\0"
 s ^TKSOLDES("81422")="\0.7\0"
 s ^TKSOLDES("87323")="\0.7\0"
 s ^TKSOLDES("87324")="\0.7\0"
 s ^TKSOLDES("81411")="\0.7\0"
 s ^TKSOLDES("81409")="\0.7\0"
 s ^TKSOLDES("81396")="\0.7\0"
 s ^TKSOLDES("81408")="\0.7\0"
 s ^TKSOLDES("81397")="\0.7\0"
 s ^TKSOLDES("81398")="\0.7\0"
 s ^TKSOLDES("81399")="\0.7\0"
 s ^TKSOLDES("81400")="\0.7\0"
 s ^TKSOLDES("81401")="\0.7\0"
 s ^TKSOLDES("81402")="\0.7\0"
 s ^TKSOLDES("81403")="\0.7\0"
 s ^TKSOLDES("81405")="\0.7\0"
 s ^TKSOLDES("81406")="\0.7\0"
 s ^TKSOLDES("81407")="\0.7\0"
 s ^TKSOLDES("8414")="\0.7\0"
 Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 