ROUTINE OPESOLDES50PE13P5
OPESOLDES50PE13P5
 
 s ^TKSOLDES("79749")="\0.5\0"
 s ^TKSOLDES("80810")="\0.5\0"
 s ^TKSOLDES("80809")="\0.5\0"
 s ^TKSOLDES("80803")="\0.5\0"
 s ^TKSOLDES("80800")="\0.5\0"
 s ^TKSOLDES("80314")="\0.5\0"
 s ^TKSOLDES("80641")="\0.5\0"
 s ^TKSOLDES("81041")="\0.5\0"
 s ^TKSOLDES("104184")="\0.5\0"
 s ^TKSOLDES("103056")="\0.5\0"
 s ^TKSOLDES("104483")="\0.5\0"
 s ^TKSOLDES("104474")="\0.5\0"
 s ^TKSOLDES("79876")="\0.5\0"
 s ^TKSOLDES("79879")="\0.5\0"
 s ^TKSOLDES("79880")="\0.5\0"
 s ^TKSOLDES("104159")="\0.5\0"
 s ^TKSOLDES("104475")="\0.5\0"
 s ^TKSOLDES("104484")="\0.5\0"
 s ^TKSOLDES("104183")="\0.5\0"
 s ^TKSOLDES("104485")="\0.5\0"
 s ^TKSOLDES("104491")="\0.5\0"
 s ^TKSOLDES("104490")="\0.5\0"
 s ^TKSOLDES("104489")="\0.5\0"
 s ^TKSOLDES("104488")="\0.5\0"
 s ^TKSOLDES("104487")="\0.5\0"
 s ^TKSOLDES("104486")="\0.5\0"
 s ^TKSOLDES("104473")="\0.5\0"
 s ^TKSOLDES("104472")="\0.5\0"
 s ^TKSOLDES("104470")="\0.5\0"
 s ^TKSOLDES("104161")="\0.5\0"
 s ^TKSOLDES("104162")="\0.5\0"
 s ^TKSOLDES("104179")="\0.5\0"
 s ^TKSOLDES("104180")="\0.5\0"
 s ^TKSOLDES("104181")="\0.5\0"
 s ^TKSOLDES("104182")="\0.5\0"
 s ^TKSOLDES("104160")="\0.5\0"
 s ^TKSOLDES("79872")="\0.5\0"
 s ^TKSOLDES("81066")="\0.5\0"
 s ^TKSOLDES("81071")="\0.5\0"
 s ^TKSOLDES("81067")="\0.5\0"
 s ^TKSOLDES("81047")="\0.5\0"
 s ^TKSOLDES("79873")="\0.5\0"
 s ^TKSOLDES("104469")="\0.5\0"
 s ^TKSOLDES("104468")="\0.5\0"
 s ^TKSOLDES("79875")="\0.5\0"
 s ^TKSOLDES("81175")="\0.5\0"
 s ^TKSOLDES("104471")="\0.5\0"
 s ^TKSOLDES("79144")="\0.5\0"
 s ^TKSOLDES("79140")="\0.5\0"
 s ^TKSOLDES("79141")="\0.5\0"
 s ^TKSOLDES("79142")="\0.5\0"
 s ^TKSOLDES("79143")="\0.5\0"
 s ^TKSOLDES("79145")="\0.5\0"
 s ^TKSOLDES("79138")="\0.5\0"
 s ^TKSOLDES("79146")="\0.5\0"
 s ^TKSOLDES("79147")="\0.5\0"
 s ^TKSOLDES("79148")="\0.5\0"
 s ^TKSOLDES("79199")="\0.5\0"
 s ^TKSOLDES("79201")="\0.5\0"
 s ^TKSOLDES("79139")="\0.5\0"
 s ^TKSOLDES("79137")="\0.5\0"
 s ^TKSOLDES("79204")="\0.5\0"
 s ^TKSOLDES("79136")="\0.5\0"
 s ^TKSOLDES("81240")="\0.5\0"
 s ^TKSOLDES("81208")="\0.5\0"
 s ^TKSOLDES("81207")="\0.5\0"
 s ^TKSOLDES("81238")="\0.5\0"
 s ^TKSOLDES("81237")="\0.5\0"
 s ^TKSOLDES("81236")="\0.5\0"
 s ^TKSOLDES("81235")="\0.5\0"
 s ^TKSOLDES("81234")="\0.5\0"
 s ^TKSOLDES("81233")="\0.5\0"
 s ^TKSOLDES("79132")="\0.5\0"
 s ^TKSOLDES("79134")="\0.5\0"
 s ^TKSOLDES("79135")="\0.5\0"
 s ^TKSOLDES("79203")="\0.5\0"
 s ^TKSOLDES("79205")="\0.5\0"
 s ^TKSOLDES("81242")="\0.5\0"
 s ^TKSOLDES("79206")="\0.5\0"
 s ^TKSOLDES("81200")="\0.5\0"
 s ^TKSOLDES("81201")="\0.5\0"
 s ^TKSOLDES("81260")="\0.5\0"
 s ^TKSOLDES("81261")="\0.5\0"
 s ^TKSOLDES("81225")="\0.5\0"
 s ^TKSOLDES("81226")="\0.5\0"
 s ^TKSOLDES("81227")="\0.5\0"
 s ^TKSOLDES("81228")="\0.5\0"
 s ^TKSOLDES("81229")="\0.5\0"
 s ^TKSOLDES("81230")="\0.5\0"
 s ^TKSOLDES("81231")="\0.5\0"
 s ^TKSOLDES("81232")="\0.5\0"
 s ^TKSOLDES("81199")="\0.5\0"
 s ^TKSOLDES("81198")="\0.5\0"
 s ^TKSOLDES("81206")="\0.5\0"
 s ^TKSOLDES("79208")="\0.5\0"
 s ^TKSOLDES("79209")="\0.5\0"
 s ^TKSOLDES("79212")="\0.5\0"
 s ^TKSOLDES("79215")="\0.5\0"
 s ^TKSOLDES("80313")="\0.5\0"
 s ^TKSOLDES("81205")="\0.5\0"
 s ^TKSOLDES("81197")="\0.5\0"
 s ^TKSOLDES("81202")="\0.5\0"
 s ^TKSOLDES("81256")="\0.5\0"
 s ^TKSOLDES("81224")="\0.5\0"
 s ^TKSOLDES("81258")="\0.5\0"
 s ^TKSOLDES("81196")="\0.5\0"
 s ^TKSOLDES("81259")="\0.5\0"
 s ^TKSOLDES("81241")="\0.5\0"
 s ^TKSOLDES("81239")="\0.5\0"
 s ^TKSOLDES("81253")="\0.5\0"
 s ^TKSOLDES("81219")="\0.5\0"
 s ^TKSOLDES("81218")="\0.5\0"
 s ^TKSOLDES("81187")="\0.5\0"
 s ^TKSOLDES("81188")="\0.5\0"
 s ^TKSOLDES("81243")="\0.5\0"
 s ^TKSOLDES("81190")="\0.5\0"
 s ^TKSOLDES("81191")="\0.5\0"
 s ^TKSOLDES("81192")="\0.5\0"
 s ^TKSOLDES("81193")="\0.5\0"
 s ^TKSOLDES("81194")="\0.5\0"
 s ^TKSOLDES("81186")="\0.5\0"
 s ^TKSOLDES("81185")="\0.5\0"
 s ^TKSOLDES("81220")="\0.5\0"
 s ^TKSOLDES("81257")="\0.5\0"
 s ^TKSOLDES("81223")="\0.5\0"
 s ^TKSOLDES("81222")="\0.5\0"
 s ^TKSOLDES("81221")="\0.5\0"
 s ^TKSOLDES("81250")="\0.5\0"
 s ^TKSOLDES("81184")="\0.5\0"
 s ^TKSOLDES("81177")="\0.5\0"
 s ^TKSOLDES("81178")="\0.5\0"
 s ^TKSOLDES("81181")="\0.5\0"
 s ^TKSOLDES("81182")="\0.5\0"
 s ^TKSOLDES("81183")="\0.5\0"
 s ^TKSOLDES("81195")="\0.5\0"
 s ^TKSOLDES("81189")="\0.5\0"
 s ^TKSOLDES("81248")="\0.5\0"
 s ^TKSOLDES("81214")="\0.5\0"
 s ^TKSOLDES("81213")="\0.5\0"
 s ^TKSOLDES("81254")="\0.5\0"
 s ^TKSOLDES("81247")="\0.5\0"
 s ^TKSOLDES("81212")="\0.5\0"
 s ^TKSOLDES("81211")="\0.5\0"
 s ^TKSOLDES("81210")="\0.5\0"
 s ^TKSOLDES("81215")="\0.5\0"
 s ^TKSOLDES("81217")="\0.5\0"
 s ^TKSOLDES("81245")="\0.5\0"
 s ^TKSOLDES("81244")="\0.5\0"
 s ^TKSOLDES("81249")="\0.5\0"
 s ^TKSOLDES("81255")="\0.5\0"
 s ^TKSOLDES("81209")="\0.5\0"
 s ^TKSOLDES("16322")="\0.5\0"
 s ^TKSOLDES("74135")="\0.5\0"
 s ^TKSOLDES("74137")="\0.5\0"
 s ^TKSOLDES("74138")="\0.5\0"
 s ^TKSOLDES("74140")="\0.5\0"
 s ^TKSOLDES("79278")="\0.5\0"
 s ^TKSOLDES("74358")="\0.5\0"
 s ^TKSOLDES("65578")="\0.5\0"
 s ^TKSOLDES("74359")="\0.5\0"
 s ^TKSOLDES("65588")="\0.5\0"
 s ^TKSOLDES("74360")="\0.5\0"
 s ^TKSOLDES("79263")="\0.5\0"
 s ^TKSOLDES("65586")="\0.5\0"
 s ^TKSOLDES("79280")="\0.5\0"
 s ^TKSOLDES("65582")="\0.5\0"
 s ^TKSOLDES("65580")="\0.5\0"
 s ^TKSOLDES("74357")="\0.5\0"
 s ^TKSOLDES("74352")="\0.5\0"
 s ^TKSOLDES("74316")="\0.5\0"
 s ^TKSOLDES("74318")="\0.5\0"
 s ^TKSOLDES("74351")="\0.5\0"
 s ^TKSOLDES("74314")="\0.5\0"
 s ^TKSOLDES("74350")="\0.5\0"
 s ^TKSOLDES("74349")="\0.5\0"
 s ^TKSOLDES("74348")="\0.5\0"
 s ^TKSOLDES("74353")="\0.5\0"
 s ^TKSOLDES("79286")="\0.5\0"
 s ^TKSOLDES("74132")="\0.5\0"
 s ^TKSOLDES("79282")="\0.5\0"
 s ^TKSOLDES("74356")="\0.5\0"
 s ^TKSOLDES("65575")="\0.5\0"
 s ^TKSOLDES("65574")="\0.5\0"
 s ^TKSOLDES("65573")="\0.5\0"
 s ^TKSOLDES("74355")="\0.5\0"
 s ^TKSOLDES("74354")="\0.5\0"
 s ^TKSOLDES("16289")="\0.5\0"
 s ^TKSOLDES("79281")="\0.5\0"
 s ^TKSOLDES("74134")="\0.5\0"
 s ^TKSOLDES("74101")="\0.5\0"
 s ^TKSOLDES("84459")="\0.5\0"
 s ^TKSOLDES("84461")="\0.5\0"
 s ^TKSOLDES("55956")="\0.5\0"
 s ^TKSOLDES("55930")="\0.5\0"
 s ^TKSOLDES("55919")="\0.5\0"
 s ^TKSOLDES("55901")="\0.5\0"
 s ^TKSOLDES("69240")="\0.5\0"
 s ^TKSOLDES("69239")="\0.5\0"
 s ^TKSOLDES("69238")="\0.5\0"
 s ^TKSOLDES("80750")="\0.5\0"
 s ^TKSOLDES("69231")="\0.5\0"
 s ^TKSOLDES("69232")="\0.5\0"
 s ^TKSOLDES("69234")="\0.5\0"
 s ^TKSOLDES("69236")="\0.5\0"
 s ^TKSOLDES("69237")="\0.5\0"
 s ^TKSOLDES("84460")="\0.5\0"
 s ^TKSOLDES("84458")="\0.5\0"
 s ^TKSOLDES("72953")="\0.5\0"
 s ^TKSOLDES("80643")="\0.5\0"
 s ^TKSOLDES("44625")="\0.5\0"
 s ^TKSOLDES("44534")="\0.5\0"
 s ^TKSOLDES("80680")="\0.5\0"
 s ^TKSOLDES("80653")="\0.5\0"
 s ^TKSOLDES("80649")="\0.5\0"
 s ^TKSOLDES("80648")="\0.5\0"
 s ^TKSOLDES("84449")="\0.5\0"
 s ^TKSOLDES("84457")="\0.5\0"
 s ^TKSOLDES("84450")="\0.5\0"
 s ^TKSOLDES("84456")="\0.5\0"
 s ^TKSOLDES("84455")="\0.5\0"
 s ^TKSOLDES("84454")="\0.5\0"
 s ^TKSOLDES("84453")="\0.5\0"
 s ^TKSOLDES("84452")="\0.5\0"
 s ^TKSOLDES("84451")="\0.5\0"
 s ^TKSOLDES("80751")="\0.5\0"
 s ^TKSOLDES("72959")="\0.5\0"
 s ^TKSOLDES("74131")="\0.5\0"
 s ^TKSOLDES("74122")="\0.5\0"
 s ^TKSOLDES("74116")="\0.5\0"
 s ^TKSOLDES("74117")="\0.5\0"
 s ^TKSOLDES("74118")="\0.5\0"
 s ^TKSOLDES("74119")="\0.5\0"
 s ^TKSOLDES("74120")="\0.5\0"
 s ^TKSOLDES("74121")="\0.5\0"
 s ^TKSOLDES("74123")="\0.5\0"
 s ^TKSOLDES("72964")="\0.5\0"
 s ^TKSOLDES("74124")="\0.5\0"
 s ^TKSOLDES("74130")="\0.5\0"
 s ^TKSOLDES("74129")="\0.5\0"
 s ^TKSOLDES("74128")="\0.5\0"
 s ^TKSOLDES("74127")="\0.5\0"
 s ^TKSOLDES("74126")="\0.5\0"
 s ^TKSOLDES("74125")="\0.5\0"
 s ^TKSOLDES("74115")="\0.5\0"
 s ^TKSOLDES("74114")="\0.5\0"
 s ^TKSOLDES("74113")="\0.5\0"
 s ^TKSOLDES("74100")="\0.5\0"
 s ^TKSOLDES("74099")="\0.5\0"
 s ^TKSOLDES("74098")="\0.5\0"
 s ^TKSOLDES("73237")="\0.5\0"
 s ^TKSOLDES("55324")="\0.5\0"
 s ^TKSOLDES("72969")="\0.5\0"
 s ^TKSOLDES("74362")="\0.5\0"
 s ^TKSOLDES("74103")="\0.5\0"
 s ^TKSOLDES("74109")="\0.5\0"
 s ^TKSOLDES("74111")="\0.5\0"
 s ^TKSOLDES("74110")="\0.5\0"
 s ^TKSOLDES("74108")="\0.5\0"
 s ^TKSOLDES("74104")="\0.5\0"
 s ^TKSOLDES("74107")="\0.5\0"
 s ^TKSOLDES("74106")="\0.5\0"
 s ^TKSOLDES("74105")="\0.5\0"
 s ^TKSOLDES("74361")="\0.5\0"
 s ^TKSOLDES("74317")="\0.5\0"
 s ^TKSOLDES("74363")="\0.5\0"
 s ^TKSOLDES("84821")="\0.5\0"
 s ^TKSOLDES("84814")="\0.5\0"
 s ^TKSOLDES("84815")="\0.5\0"
 s ^TKSOLDES("84816")="\0.5\0"
 s ^TKSOLDES("84817")="\0.5\0"
 s ^TKSOLDES("84818")="\0.5\0"
 s ^TKSOLDES("84820")="\0.5\0"
 s ^TKSOLDES("84822")="\0.5\0"
 s ^TKSOLDES("84812")="\0.5\0"
 s ^TKSOLDES("84823")="\0.5\0"
 s ^TKSOLDES("82504")="\0.5\0"
 s ^TKSOLDES("82505")="\0.5\0"
 s ^TKSOLDES("82506")="\0.5\0"
 s ^TKSOLDES("82507")="\0.5\0"
 s ^TKSOLDES("82508")="\0.5\0"
 s ^TKSOLDES("82509")="\0.5\0"
 s ^TKSOLDES("84813")="\0.5\0"
 s ^TKSOLDES("84811")="\0.5\0"
 s ^TKSOLDES("84787")="\0.5\0"
 s ^TKSOLDES("84803")="\0.5\0"
 s ^TKSOLDES("84794")="\0.5\0"
 s ^TKSOLDES("84793")="\0.5\0"
 s ^TKSOLDES("84792")="\0.5\0"
 s ^TKSOLDES("84791")="\0.5\0"
 s ^TKSOLDES("84790")="\0.5\0"
 s ^TKSOLDES("84789")="\0.5\0"
 s ^TKSOLDES("76967")="\0.5\0"
 s ^TKSOLDES("76971")="\0.5\0"
 s ^TKSOLDES("82106")="\0.5\0"
 s ^TKSOLDES("82109")="\0.5\0"
 s ^TKSOLDES("82108")="\0.5\0"
 s ^TKSOLDES("82105")="\0.5\0"
 s ^TKSOLDES("84795")="\0.5\0"
 s ^TKSOLDES("84801")="\0.5\0"
 s ^TKSOLDES("84796")="\0.5\0"
 s ^TKSOLDES("82097")="\0.5\0"
 s ^TKSOLDES("74364")="\0.5\0"
 s ^TKSOLDES("82503")="\0.5\0"
 s ^TKSOLDES("84824")="\0.5\0"
 s ^TKSOLDES("84845")="\0.5\0"
 s ^TKSOLDES("84844")="\0.5\0"
 s ^TKSOLDES("82188")="\0.5\0"
 s ^TKSOLDES("82186")="\0.5\0"
 s ^TKSOLDES("82159")="\0.5\0"
 s ^TKSOLDES("82158")="\0.5\0"
 s ^TKSOLDES("84846")="\0.5\0"
 s ^TKSOLDES("76975")="\0.5\0"
 s ^TKSOLDES("77247")="\0.5\0"
 s ^TKSOLDES("77245")="\0.5\0"
 s ^TKSOLDES("77246")="\0.5\0"
 s ^TKSOLDES("77248")="\0.5\0"
 s ^TKSOLDES("76984")="\0.5\0"
 s ^TKSOLDES("77250")="\0.5\0"
 s ^TKSOLDES("77251")="\0.5\0"
 s ^TKSOLDES("50644")="\0.5\0"
 s ^TKSOLDES("84843")="\0.5\0"
 s ^TKSOLDES("84842")="\0.5\0"
 s ^TKSOLDES("84830")="\0.5\0"
 s ^TKSOLDES("82116")="\0.5\0"
 s ^TKSOLDES("82115")="\0.5\0"
 s ^TKSOLDES("84828")="\0.5\0"
 s ^TKSOLDES("84827")="\0.5\0"
 s ^TKSOLDES("84826")="\0.5\0"
 s ^TKSOLDES("84825")="\0.5\0"
 s ^TKSOLDES("84829")="\0.5\0"
 s ^TKSOLDES("84831")="\0.5\0"
 s ^TKSOLDES("84841")="\0.5\0"
 s ^TKSOLDES("84836")="\0.5\0"
 s ^TKSOLDES("84840")="\0.5\0"
 s ^TKSOLDES("84839")="\0.5\0"
 s ^TKSOLDES("84835")="\0.5\0"
 s ^TKSOLDES("84832")="\0.5\0"
 s ^TKSOLDES("84834")="\0.5\0"
 s ^TKSOLDES("82117")="\0.5\0"
 s ^TKSOLDES("84833")="\0.5\0"
 s ^TKSOLDES("84788")="\0.5\0"
 s ^TKSOLDES("80709")="\0.5\0"
 s ^TKSOLDES("76965")="\0.5\0"
 s ^TKSOLDES("82946")="\0.5\0"
 s ^TKSOLDES("65564")="\0.5\0"
 s ^TKSOLDES("65563")="\0.5\0"
 s ^TKSOLDES("79300")="\0.5\0"
 s ^TKSOLDES("79302")="\0.5\0"
 s ^TKSOLDES("37374")="\0.5\0"
 s ^TKSOLDES("79303")="\0.5\0"
 s ^TKSOLDES("79304")="\0.5\0"
 s ^TKSOLDES("79305")="\0.5\0"
 s ^TKSOLDES("84779")="\0.5\0"
 s ^TKSOLDES("84778")="\0.5\0"
 s ^TKSOLDES("84777")="\0.5\0"
 s ^TKSOLDES("79308")="\0.5\0"
 s ^TKSOLDES("79307")="\0.5\0"
 s ^TKSOLDES("79306")="\0.5\0"
 s ^TKSOLDES("76956")="\0.5\0"
 s ^TKSOLDES("65565")="\0.5\0"
 s ^TKSOLDES("79290")="\0.5\0"
 s ^TKSOLDES("79299")="\0.5\0"
 s ^TKSOLDES("79298")="\0.5\0"
 s ^TKSOLDES("79295")="\0.5\0"
 s ^TKSOLDES("79294")="\0.5\0"
 s ^TKSOLDES("79293")="\0.5\0"
 s ^TKSOLDES("79292")="\0.5\0"
 s ^TKSOLDES("79289")="\0.5\0"
 s ^TKSOLDES("65566")="\0.5\0"
 s ^TKSOLDES("79288")="\0.5\0"
 s ^TKSOLDES("82013")="\0.5\0"
 s ^TKSOLDES("65569")="\0.5\0"
 s ^TKSOLDES("65570")="\0.5\0"
 s ^TKSOLDES("65571")="\0.5\0"
 s ^TKSOLDES("65572")="\0.5\0"
 s ^TKSOLDES("79287")="\0.5\0"
 s ^TKSOLDES("84781")="\0.5\0"
 s ^TKSOLDES("79301")="\0.5\0"
 s ^TKSOLDES("64989")="\0.5\0"
 s ^TKSOLDES("82920")="\0.5\0"
 s ^TKSOLDES("82929")="\0.5\0"
 s ^TKSOLDES("82927")="\0.5\0"
 s ^TKSOLDES("82914")="\0.5\0"
 s ^TKSOLDES("82916")="\0.5\0"
 s ^TKSOLDES("82919")="\0.5\0"
 s ^TKSOLDES("82921")="\0.5\0"
 s ^TKSOLDES("82934")="\0.5\0"
 s ^TKSOLDES("82922")="\0.5\0"
 s ^TKSOLDES("82923")="\0.5\0"
 s ^TKSOLDES("82924")="\0.5\0"
 s ^TKSOLDES("82925")="\0.5\0"
 s ^TKSOLDES("82926")="\0.5\0"
 s ^TKSOLDES("82945")="\0.5\0"
 s ^TKSOLDES("82931")="\0.5\0"
 s ^TKSOLDES("82913")="\0.5\0"
 s ^TKSOLDES("82935")="\0.5\0"
 s ^TKSOLDES("84785")="\0.5\0"
 s ^TKSOLDES("82938")="\0.5\0"
 s ^TKSOLDES("82939")="\0.5\0"
 s ^TKSOLDES("84786")="\0.5\0"
 s ^TKSOLDES("74365")="\0.5\0"
 s ^TKSOLDES("82941")="\0.5\0"
 s ^TKSOLDES("82944")="\0.5\0"
 s ^TKSOLDES("82937")="\0.5\0"
 s ^TKSOLDES("82928")="\0.5\0"
 s ^TKSOLDES("84782")="\0.5\0"
 s ^TKSOLDES("82912")="\0.5\0"
 s ^TKSOLDES("84784")="\0.5\0"
 s ^TKSOLDES("82936")="\0.5\0"
 s ^TKSOLDES("84783")="\0.5\0"
 s ^TKSOLDES("56193")="\0.5\0"
 s ^TKSOLDES("54902")="\0.5\0"
 s ^TKSOLDES("56182")="\0.5\0"
 s ^TKSOLDES("56181")="\0.5\0"
 s ^TKSOLDES("56183")="\0.5\0"
 s ^TKSOLDES("56176")="\0.5\0"
 s ^TKSOLDES("56180")="\0.5\0"
 s ^TKSOLDES("56179")="\0.5\0"
 s ^TKSOLDES("56174")="\0.5\0"
 s ^TKSOLDES("56162")="\0.5\0"
 s ^TKSOLDES("56171")="\0.5\0"
 s ^TKSOLDES("53499")="\0.5\0"
 s ^TKSOLDES("54903")="\0.5\0"
 s ^TKSOLDES("56163")="\0.5\0"
 s ^TKSOLDES("56209")="\0.5\0"
 s ^TKSOLDES("87350")="\0.5\0"
 s ^TKSOLDES("54860")="\0.5\0"
 s ^TKSOLDES("54849")="\0.5\0"
 s ^TKSOLDES("54848")="\0.5\0"
 s ^TKSOLDES("54846")="\0.5\0"
 s ^TKSOLDES("54845")="\0.5\0"
 s ^TKSOLDES("54284")="\0.5\0"
 s ^TKSOLDES("56197")="\0.5\0"
 s ^TKSOLDES("54275")="\0.5\0"
 s ^TKSOLDES("53872")="\0.5\0"
 s ^TKSOLDES("53870")="\0.5\0"
 s ^TKSOLDES("87351")="\0.5\0"
 s ^TKSOLDES("87353")="\0.5\0"
 s ^TKSOLDES("87352")="\0.5\0"
 s ^TKSOLDES("56535")="\0.5\0"
 s ^TKSOLDES("56534")="\0.5\0"
 s ^TKSOLDES("56533")="\0.5\0"
 s ^TKSOLDES("54861")="\0.5\0"
 s ^TKSOLDES("56206")="\0.5\0"
 s ^TKSOLDES("56207")="\0.5\0"
 s ^TKSOLDES("56210")="\0.5\0"
 s ^TKSOLDES("56211")="\0.5\0"
 s ^TKSOLDES("56286")="\0.5\0"
 s ^TKSOLDES("56287")="\0.5\0"
 s ^TKSOLDES("56288")="\0.5\0"
 s ^TKSOLDES("56532")="\0.5\0"
 s ^TKSOLDES("56531")="\0.5\0"
 s ^TKSOLDES("56530")="\0.5\0"
 s ^TKSOLDES("56529")="\0.5\0"
 s ^TKSOLDES("56528")="\0.5\0"
 s ^TKSOLDES("56289")="\0.5\0"
 s ^TKSOLDES("54847")="\0.5\0"
 s ^TKSOLDES("55756")="\0.5\0"
 s ^TKSOLDES("54936")="\0.5\0"
 s ^TKSOLDES("54934")="\0.5\0"
 s ^TKSOLDES("54935")="\0.5\0"
 s ^TKSOLDES("54910")="\0.5\0"
 s ^TKSOLDES("54905")="\0.5\0"
 s ^TKSOLDES("54937")="\0.5\0"
 s ^TKSOLDES("55773")="\0.5\0"
 s ^TKSOLDES("54939")="\0.5\0"
 s ^TKSOLDES("54906")="\0.5\0"
 s ^TKSOLDES("54907")="\0.5\0"
 s ^TKSOLDES("55400")="\0.5\0"
 s ^TKSOLDES("55407")="\0.5\0"
 s ^TKSOLDES("54931")="\0.5\0"
 s ^TKSOLDES("54930")="\0.5\0"
 s ^TKSOLDES("54929")="\0.5\0"
 s ^TKSOLDES("54912")="\0.5\0"
 s ^TKSOLDES("54913")="\0.5\0"
 s ^TKSOLDES("54914")="\0.5\0"
 s ^TKSOLDES("54915")="\0.5\0"
 s ^TKSOLDES("54911")="\0.5\0"
 s ^TKSOLDES("54917")="\0.5\0"
 s ^TKSOLDES("54918")="\0.5\0"
 s ^TKSOLDES("54920")="\0.5\0"
 s ^TKSOLDES("54921")="\0.5\0"
 s ^TKSOLDES("54923")="\0.5\0"
 s ^TKSOLDES("54925")="\0.5\0"
 s ^TKSOLDES("54904")="\0.5\0"
 s ^TKSOLDES("55431")="\0.5\0"
 s ^TKSOLDES("55436")="\0.5\0"
 s ^TKSOLDES("55759")="\0.5\0"
 s ^TKSOLDES("55754")="\0.5\0"
 s ^TKSOLDES("55755")="\0.5\0"
 s ^TKSOLDES("55757")="\0.5\0"
 s ^TKSOLDES("55758")="\0.5\0"
 s ^TKSOLDES("55760")="\0.5\0"
 s ^TKSOLDES("55752")="\0.5\0"
 s ^TKSOLDES("55761")="\0.5\0"
 s ^TKSOLDES("55767")="\0.5\0"
 s ^TKSOLDES("55768")="\0.5\0"
 s ^TKSOLDES("55769")="\0.5\0"
 s ^TKSOLDES("56536")="\0.5\0"
 s ^TKSOLDES("55753")="\0.5\0"
 s ^TKSOLDES("54909")="\0.5\0"
 s ^TKSOLDES("55455")="\0.5\0"
 s ^TKSOLDES("54908")="\0.5\0"
 s ^TKSOLDES("55475")="\0.5\0"
 s ^TKSOLDES("55483")="\0.5\0"
 s ^TKSOLDES("87349")="\0.5\0"
 s ^TKSOLDES("55723")="\0.5\0"
 s ^TKSOLDES("55724")="\0.5\0"
 s ^TKSOLDES("55725")="\0.5\0"
 s ^TKSOLDES("55726")="\0.5\0"
 s ^TKSOLDES("55727")="\0.5\0"
 s ^TKSOLDES("55728")="\0.5\0"
 s ^TKSOLDES("55749")="\0.5\0"
 s ^TKSOLDES("55750")="\0.5\0"
 s ^TKSOLDES("55751")="\0.5\0"
 s ^TKSOLDES("54927")="\0.5\0"
 s ^TKSOLDES("87330")="\0.5\0"
 s ^TKSOLDES("64604")="\0.5\0"
 s ^TKSOLDES("61962")="\0.5\0"
 s ^TKSOLDES("61961")="\0.5\0"
 s ^TKSOLDES("61960")="\0.5\0"
 s ^TKSOLDES("61955")="\0.5\0"
 s ^TKSOLDES("61954")="\0.5\0"
 s ^TKSOLDES("61949")="\0.5\0"
 s ^TKSOLDES("61947")="\0.5\0"
 s ^TKSOLDES("61945")="\0.5\0"
 s ^TKSOLDES("61964")="\0.5\0"
 s ^TKSOLDES("64602")="\0.5\0"
 s ^TKSOLDES("61943")="\0.5\0"
 s ^TKSOLDES("64245")="\0.5\0"
 s ^TKSOLDES("62346")="\0.5\0"
 s ^TKSOLDES("62345")="\0.5\0"
 s ^TKSOLDES("62344")="\0.5\0"
 s ^TKSOLDES("64246")="\0.5\0"
 s ^TKSOLDES("61968")="\0.5\0"
 s ^TKSOLDES("64578")="\0.5\0"
 s ^TKSOLDES("64579")="\0.5\0"
 s ^TKSOLDES("64589")="\0.5\0"
 s ^TKSOLDES("64599")="\0.5\0"
 s ^TKSOLDES("61944")="\0.5\0"
 s ^TKSOLDES("61942")="\0.5\0"
 s ^TKSOLDES("62348")="\0.5\0"
 s ^TKSOLDES("87332")="\0.5\0"
 s ^TKSOLDES("87329")="\0.5\0"
 s ^TKSOLDES("64240")="\0.5\0"
 s ^TKSOLDES("87331")="\0.5\0"
 s ^TKSOLDES("59901")="\0.5\0"
 s ^TKSOLDES("61940")="\0.5\0"
 s ^TKSOLDES("59900")="\0.5\0"
 s ^TKSOLDES("59899")="\0.5\0"
 s ^TKSOLDES("59898")="\0.5\0"
 s ^TKSOLDES("59897")="\0.5\0"
 s ^TKSOLDES("87328")="\0.5\0"
 s ^TKSOLDES("87327")="\0.5\0"
 s ^TKSOLDES("64669")="\0.5\0"
 s ^TKSOLDES("61935")="\0.5\0"
 s ^TKSOLDES("61928")="\0.5\0"
 s ^TKSOLDES("61927")="\0.5\0"
 s ^TKSOLDES("61926")="\0.5\0"
 s ^TKSOLDES("61923")="\0.5\0"
 s ^TKSOLDES("61922")="\0.5\0"
 s ^TKSOLDES("64605")="\0.5\0"
 s ^TKSOLDES("64619")="\0.5\0"
 s ^TKSOLDES("61920")="\0.5\0"
 s ^TKSOLDES("53497")="\0.5\0"
 s ^TKSOLDES("62347")="\0.5\0"
 s ^TKSOLDES("62349")="\0.5\0"
 s ^TKSOLDES("56537")="\0.5\0"
 s ^TKSOLDES("64140")="\0.5\0"
 s ^TKSOLDES("64143")="\0.5\0"
 s ^TKSOLDES("64142")="\0.5\0"
 s ^TKSOLDES("64141")="\0.5\0"
 s ^TKSOLDES("64139")="\0.5\0"
 s ^TKSOLDES("62350")="\0.5\0"
 s ^TKSOLDES("64138")="\0.5\0"
 s ^TKSOLDES("64137")="\0.5\0"
 s ^TKSOLDES("64136")="\0.5\0"
 s ^TKSOLDES("64135")="\0.5\0"
 s ^TKSOLDES("64144")="\0.5\0"
 s ^TKSOLDES("64145")="\0.5\0"
 s ^TKSOLDES("64146")="\0.5\0"
 s ^TKSOLDES("64155")="\0.5\0"
 s ^TKSOLDES("64154")="\0.5\0"
 s ^TKSOLDES("64241")="\0.5\0"
 s ^TKSOLDES("64153")="\0.5\0"
 s ^TKSOLDES("64152")="\0.5\0"
 s ^TKSOLDES("64151")="\0.5\0"
 s ^TKSOLDES("64150")="\0.5\0"
 s ^TKSOLDES("64149")="\0.5\0"
 s ^TKSOLDES("64148")="\0.5\0"
 s ^TKSOLDES("64147")="\0.5\0"
 s ^TKSOLDES("86757")="\0.5\0"
 s ^TKSOLDES("86765")="\0.5\0"
 s ^TKSOLDES("62943")="\0.5\0"
 s ^TKSOLDES("62967")="\0.5\0"
 s ^TKSOLDES("62958")="\0.5\0"
 s ^TKSOLDES("62957")="\0.5\0"
 s ^TKSOLDES("62927")="\0.5\0"
 s ^TKSOLDES("63018")="\0.5\0"
 s ^TKSOLDES("62924")="\0.5\0"
 s ^TKSOLDES("62922")="\0.5\0"
 s ^TKSOLDES("62914")="\0.5\0"
 s ^TKSOLDES("62351")="\0.5\0"
 s ^TKSOLDES("62971")="\0.5\0"
 s ^TKSOLDES("63026")="\0.5\0"
 s ^TKSOLDES("86766")="\0.5\0"
 s ^TKSOLDES("63032")="\0.5\0"
 s ^TKSOLDES("86824")="\0.5\0"
 s ^TKSOLDES("64242")="\0.5\0"
 s ^TKSOLDES("86825")="\0.5\0"
 s ^TKSOLDES("64243")="\0.5\0"
 s ^TKSOLDES("64244")="\0.5\0"
 s ^TKSOLDES("63629")="\0.5\0"
 s ^TKSOLDES("63628")="\0.5\0"
 s ^TKSOLDES("63627")="\0.5\0"
 s ^TKSOLDES("63626")="\0.5\0"
 s ^TKSOLDES("63625")="\0.5\0"
 s ^TKSOLDES("59896")="\0.5\0"
 s ^TKSOLDES("59895")="\0.5\0"
 s ^TKSOLDES("57197")="\0.5\0"
 s ^TKSOLDES("57200")="\0.5\0"
 s ^TKSOLDES("57199")="\0.5\0"
 s ^TKSOLDES("57198")="\0.5\0"
 s ^TKSOLDES("57196")="\0.5\0"
 s ^TKSOLDES("59894")="\0.5\0"
 s ^TKSOLDES("57195")="\0.5\0"
 s ^TKSOLDES("57194")="\0.5\0"
 s ^TKSOLDES("57193")="\0.5\0"
 s ^TKSOLDES("57192")="\0.5\0"
 s ^TKSOLDES("57201")="\0.5\0"
 s ^TKSOLDES("57202")="\0.5\0"
 s ^TKSOLDES("57203")="\0.5\0"
 s ^TKSOLDES("58302")="\0.5\0"
 s ^TKSOLDES("58301")="\0.5\0"
 s ^TKSOLDES("58299")="\0.5\0"
 s ^TKSOLDES("58298")="\0.5\0"
 s ^TKSOLDES("57209")="\0.5\0"
 s ^TKSOLDES("57208")="\0.5\0"
 s ^TKSOLDES("57207")="\0.5\0"
 s ^TKSOLDES("57206")="\0.5\0"
 s ^TKSOLDES("57205")="\0.5\0"
 s ^TKSOLDES("57204")="\0.5\0"
 s ^TKSOLDES("57191")="\0.5\0"
 s ^TKSOLDES("57190")="\0.5\0"
 s ^TKSOLDES("87344")="\0.5\0"
 s ^TKSOLDES("87341")="\0.5\0"
 s ^TKSOLDES("87342")="\0.5\0"
 s ^TKSOLDES("87343")="\0.5\0"
 s ^TKSOLDES("87345")="\0.5\0"
 s ^TKSOLDES("87339")="\0.5\0"
 s ^TKSOLDES("87346")="\0.5\0"
 s ^TKSOLDES("87347")="\0.5\0"
 s ^TKSOLDES("87348")="\0.5\0"
 s ^TKSOLDES("56538")="\0.5\0"
 s ^TKSOLDES("87340")="\0.5\0"
 s ^TKSOLDES("87338")="\0.5\0"
 s ^TKSOLDES("57189")="\0.5\0"
 s ^TKSOLDES("87336")="\0.5\0"
 s ^TKSOLDES("57188")="\0.5\0"
 s ^TKSOLDES("57187")="\0.5\0"
 s ^TKSOLDES("57186")="\0.5\0"
 s ^TKSOLDES("57185")="\0.5\0"
 s ^TKSOLDES("57184")="\0.5\0"
 s ^TKSOLDES("57183")="\0.5\0"
 s ^TKSOLDES("57182")="\0.5\0"
 s ^TKSOLDES("57181")="\0.5\0"
 s ^TKSOLDES("87334")="\0.5\0"
 s ^TKSOLDES("87335")="\0.5\0"
 s ^TKSOLDES("58304")="\0.5\0"
 s ^TKSOLDES("58791")="\0.5\0"
 s ^TKSOLDES("59299")="\0.5\0"
 s ^TKSOLDES("59309")="\0.5\0"
 s ^TKSOLDES("59307")="\0.5\0"
 s ^TKSOLDES("59300")="\0.5\0"
 s ^TKSOLDES("59285")="\0.5\0"
 s ^TKSOLDES("59270")="\0.5\0"
 s ^TKSOLDES("59284")="\0.5\0"
 s ^TKSOLDES("59283")="\0.5\0"
 s ^TKSOLDES("59282")="\0.5\0"
 s ^TKSOLDES("59281")="\0.5\0"
 s ^TKSOLDES("59313")="\0.5\0"
 s ^TKSOLDES("87333")="\0.5\0"
 s ^TKSOLDES("59879")="\0.5\0"
 s ^TKSOLDES("59893")="\0.5\0"
 s ^TKSOLDES("59892")="\0.5\0"
 s ^TKSOLDES("59890")="\0.5\0"
 s ^TKSOLDES("59889")="\0.5\0"
 s ^TKSOLDES("59888")="\0.5\0"
 s ^TKSOLDES("59887")="\0.5\0"
 s ^TKSOLDES("59886")="\0.5\0"
 s ^TKSOLDES("59885")="\0.5\0"
 s ^TKSOLDES("59884")="\0.5\0"
 s ^TKSOLDES("59882")="\0.5\0"
 s ^TKSOLDES("59280")="\0.5\0"
 s ^TKSOLDES("59258")="\0.5\0"
 s ^TKSOLDES("58793")="\0.5\0"
 s ^TKSOLDES("58804")="\0.5\0"
 s ^TKSOLDES("58807")="\0.5\0"
 s ^TKSOLDES("58806")="\0.5\0"
 s ^TKSOLDES("58805")="\0.5\0"
 s ^TKSOLDES("58803")="\0.5\0"
 s ^TKSOLDES("58809")="\0.5\0"
 s ^TKSOLDES("58802")="\0.5\0"
 s ^TKSOLDES("58801")="\0.5\0"
 s ^TKSOLDES("58800")="\0.5\0"
 s ^TKSOLDES("58799")="\0.5\0"
 s ^TKSOLDES("58808")="\0.5\0"
 s ^TKSOLDES("58810")="\0.5\0"
 s ^TKSOLDES("58833")="\0.5\0"
 s ^TKSOLDES("58811")="\0.5\0"
 s ^TKSOLDES("58831")="\0.5\0"
 s ^TKSOLDES("58823")="\0.5\0"
 s ^TKSOLDES("58822")="\0.5\0"
 s ^TKSOLDES("58818")="\0.5\0"
 s ^TKSOLDES("58817")="\0.5\0"
 s ^TKSOLDES("58816")="\0.5\0"
 s ^TKSOLDES("58815")="\0.5\0"
 s ^TKSOLDES("58814")="\0.5\0"
 s ^TKSOLDES("58813")="\0.5\0"
 s ^TKSOLDES("58812")="\0.5\0"
 s ^TKSOLDES("53498")="\0.5\0"
 s ^TKSOLDES("44364")="\0.5\0"
 s ^TKSOLDES("53496")="\0.5\0"
 s ^TKSOLDES("38674")="\0.5\0"
 s ^TKSOLDES("38684")="\0.5\0"
 s ^TKSOLDES("38675")="\0.5\0"
 s ^TKSOLDES("38673")="\0.5\0"
 s ^TKSOLDES("100017")="\0.5\0"
 s ^TKSOLDES("38660")="\0.5\0"
 s ^TKSOLDES("38659")="\0.5\0"
 s ^TKSOLDES("38658")="\0.5\0"
 s ^TKSOLDES("38685")="\0.5\0"
 s ^TKSOLDES("100016")="\0.5\0"
 s ^TKSOLDES("53494")="\0.5\0"
 s ^TKSOLDES("100015")="\0.5\0"
 s ^TKSOLDES("100007")="\0.5\0"
 s ^TKSOLDES("100008")="\0.5\0"
 s ^TKSOLDES("100009")="\0.5\0"
 s ^TKSOLDES("100010")="\0.5\0"
 s ^TKSOLDES("100011")="\0.5\0"
 s ^TKSOLDES("100012")="\0.5\0"
 s ^TKSOLDES("100013")="\0.5\0"
 s ^TKSOLDES("100014")="\0.5\0"
 s ^TKSOLDES("38622")="\0.5\0"
 s ^TKSOLDES("38479")="\0.5\0"
 s ^TKSOLDES("38478")="\0.5\0"
 s ^TKSOLDES("37534")="\0.5\0"
 s ^TKSOLDES("37533")="\0.5\0"
 s ^TKSOLDES("37532")="\0.5\0"
 s ^TKSOLDES("37524")="\0.5\0"
 s ^TKSOLDES("101665")="\0.5\0"
 s ^TKSOLDES("101672")="\0.5\0"
 s ^TKSOLDES("101674")="\0.5\0"
 s ^TKSOLDES("101675")="\0.5\0"
 s ^TKSOLDES("37538")="\0.5\0"
 s ^TKSOLDES("37540")="\0.5\0"
 s ^TKSOLDES("101663")="\0.5\0"
 s ^TKSOLDES("38475")="\0.5\0"
 s ^TKSOLDES("38474")="\0.5\0"
 s ^TKSOLDES("101662")="\0.5\0"
 s ^TKSOLDES("101664")="\0.5\0"
 s ^TKSOLDES("37542")="\0.5\0"
 s ^TKSOLDES("37552")="\0.5\0"
 s ^TKSOLDES("37551")="\0.5\0"
 s ^TKSOLDES("37549")="\0.5\0"
 s ^TKSOLDES("37546")="\0.5\0"
 s ^TKSOLDES("100006")="\0.5\0"
 s ^TKSOLDES("100005")="\0.5\0"
 s ^TKSOLDES("44218")="\0.5\0"
 s ^TKSOLDES("44224")="\0.5\0"
 s ^TKSOLDES("44223")="\0.5\0"
 s ^TKSOLDES("44217")="\0.5\0"
 s ^TKSOLDES("44226")="\0.5\0"
 s ^TKSOLDES("44215")="\0.5\0"
 s ^TKSOLDES("44212")="\0.5\0"
 s ^TKSOLDES("44209")="\0.5\0"
 s ^TKSOLDES("44225")="\0.5\0"
 s ^TKSOLDES("44227")="\0.5\0"
 s ^TKSOLDES("44203")="\0.5\0"
 s ^TKSOLDES("44228")="\0.5\0"
 s ^TKSOLDES("44239")="\0.5\0"
 s ^TKSOLDES("44237")="\0.5\0"
 s ^TKSOLDES("44236")="\0.5\0"
 s ^TKSOLDES("44235")="\0.5\0"
 s ^TKSOLDES("44233")="\0.5\0"
 s ^TKSOLDES("44232")="\0.5\0"
 s ^TKSOLDES("44231")="\0.5\0"
 s ^TKSOLDES("44230")="\0.5\0"
 s ^TKSOLDES("44204")="\0.5\0"
 s ^TKSOLDES("44202")="\0.5\0"
 s ^TKSOLDES("100004")="\0.5\0"
 s ^TKSOLDES("44201")="\0.5\0"
 s ^TKSOLDES("78678")="\0.5\0"
 s ^TKSOLDES("78679")="\0.5\0"
 s ^TKSOLDES("78681")="\0.5\0"
 s ^TKSOLDES("78687")="\0.5\0"
 s ^TKSOLDES("78694")="\0.5\0"
 s ^TKSOLDES("78699")="\0.5\0"
 s ^TKSOLDES("100002")="\0.5\0"
 s ^TKSOLDES("100003")="\0.5\0"
 s ^TKSOLDES("78677")="\0.5\0"
 s ^TKSOLDES("78676")="\0.5\0"
 s ^TKSOLDES("44191")="\0.5\0"
 s ^TKSOLDES("44199")="\0.5\0"
 s ^TKSOLDES("44198")="\0.5\0"
 s ^TKSOLDES("44192")="\0.5\0"
 s ^TKSOLDES("44190")="\0.5\0"
 s ^TKSOLDES("78675")="\0.5\0"
 s ^TKSOLDES("44189")="\0.5\0"
 s ^TKSOLDES("78670")="\0.5\0"
 s ^TKSOLDES("78673")="\0.5\0"
 s ^TKSOLDES("78674")="\0.5\0"
 s ^TKSOLDES("101679")="\0.5\0"
 s ^TKSOLDES("101685")="\0.5\0"
 s ^TKSOLDES("101699")="\0.5\0"
 s ^TKSOLDES("101694")="\0.5\0"
 s ^TKSOLDES("101696")="\0.5\0"
 s ^TKSOLDES("101700")="\0.5\0"
 s ^TKSOLDES("101692")="\0.5\0"
 s ^TKSOLDES("101701")="\0.5\0"
 s ^TKSOLDES("101702")="\0.5\0"
 s ^TKSOLDES("101703")="\0.5\0"
 s ^TKSOLDES("101693")="\0.5\0"
 s ^TKSOLDES("101691")="\0.5\0"
 s ^TKSOLDES("18541")="\0.5\0"
 s ^TKSOLDES("18460")="\0.5\0"
 s ^TKSOLDES("18538")="\0.5\0"
 s ^TKSOLDES("18537")="\0.5\0"
 s ^TKSOLDES("18517")="\0.5\0"
 s ^TKSOLDES("18514")="\0.5\0"
 s ^TKSOLDES("18512")="\0.5\0"
 s ^TKSOLDES("18509")="\0.5\0"
 s ^TKSOLDES("18508")="\0.5\0"
 s ^TKSOLDES("18492")="\0.5\0"
 s ^TKSOLDES("101704")="\0.5\0"
 s ^TKSOLDES("101705")="\0.5\0"
 s ^TKSOLDES("101706")="\0.5\0"
 s ^TKSOLDES("101743")="\0.5\0"
 s ^TKSOLDES("101746")="\0.5\0"
 s ^TKSOLDES("101748")="\0.5\0"
 s ^TKSOLDES("101751")="\0.5\0"
 s ^TKSOLDES("101752")="\0.5\0"
 s ^TKSOLDES("101753")="\0.5\0"
 s ^TKSOLDES("9949")="\0.5\0"
 s ^TKSOLDES("9948")="\0.5\0"
 s ^TKSOLDES("101742")="\0.5\0"
 s ^TKSOLDES("101735")="\0.5\0"
 s ^TKSOLDES("101723")="\0.5\0"
 s ^TKSOLDES("101719")="\0.5\0"
 s ^TKSOLDES("101720")="\0.5\0"
 s ^TKSOLDES("101722")="\0.5\0"
 s ^TKSOLDES("101724")="\0.5\0"
 s ^TKSOLDES("101731")="\0.5\0"
 s ^TKSOLDES("101725")="\0.5\0"
 s ^TKSOLDES("101726")="\0.5\0"
 s ^TKSOLDES("101727")="\0.5\0"
 s ^TKSOLDES("101730")="\0.5\0"
 s ^TKSOLDES("18540")="\0.5\0"
 s ^TKSOLDES("18546")="\0.5\0"
 s ^TKSOLDES("101689")="\0.5\0"
 s ^TKSOLDES("18747")="\0.5\0"
 s ^TKSOLDES("18749")="\0.5\0"
 s ^TKSOLDES("18748")="\0.5\0"
 s ^TKSOLDES("18746")="\0.5\0"
 s ^TKSOLDES("18753")="\0.5\0"
 s ^TKSOLDES("18745")="\0.5\0"
 s ^TKSOLDES("18744")="\0.5\0"
 s ^TKSOLDES("18737")="\0.5\0"
 s ^TKSOLDES("18752")="\0.5\0"
 s ^TKSOLDES("18756")="\0.5\0"
 s ^TKSOLDES("18734")="\0.5\0"
 s ^TKSOLDES("18757")="\0.5\0"
 s ^TKSOLDES("35972")="\0.5\0"
 s ^TKSOLDES("35970")="\0.5\0"
 s ^TKSOLDES("35968")="\0.5\0"
 s ^TKSOLDES("35967")="\0.5\0"
 s ^TKSOLDES("101690")="\0.5\0"
 s ^TKSOLDES("18800")="\0.5\0"
 s ^TKSOLDES("18775")="\0.5\0"
 s ^TKSOLDES("18770")="\0.5\0"
 s ^TKSOLDES("18736")="\0.5\0"
 s ^TKSOLDES("18733")="\0.5\0"
 s ^TKSOLDES("18548")="\0.5\0"
 s ^TKSOLDES("18732")="\0.5\0"
 s ^TKSOLDES("18664")="\0.5\0"
 s ^TKSOLDES("18661")="\0.5\0"
 s ^TKSOLDES("18660")="\0.5\0"
 s ^TKSOLDES("18659")="\0.5\0"
 s ^TKSOLDES("18651")="\0.5\0"
 s ^TKSOLDES("18650")="\0.5\0"
 s ^TKSOLDES("18575")="\0.5\0"
 s ^TKSOLDES("18558")="\0.5\0"
 s ^TKSOLDES("18680")="\0.5\0"
 s ^TKSOLDES("18681")="\0.5\0"
 s ^TKSOLDES("18718")="\0.5\0"
 s ^TKSOLDES("18731")="\0.5\0"
 s ^TKSOLDES("18730")="\0.5\0"
 s ^TKSOLDES("18719")="\0.5\0"
 s ^TKSOLDES("18717")="\0.5\0"
 s ^TKSOLDES("18684")="\0.5\0"
 s ^TKSOLDES("18714")="\0.5\0"
 s ^TKSOLDES("18698")="\0.5\0"
 s ^TKSOLDES("18693")="\0.5\0"
 s ^TKSOLDES("18686")="\0.5\0"
 s ^TKSOLDES("44242")="\0.5\0"
 s ^TKSOLDES("44243")="\0.5\0"
 s ^TKSOLDES("49957")="\0.5\0"
 s ^TKSOLDES("49959")="\0.5\0"
 s ^TKSOLDES("49958")="\0.5\0"
 s ^TKSOLDES("49956")="\0.5\0"
 s ^TKSOLDES("87703")="\0.5\0"
 s ^TKSOLDES("49955")="\0.5\0"
 s ^TKSOLDES("49954")="\0.5\0"
 s ^TKSOLDES("49953")="\0.5\0"
 s ^TKSOLDES("87704")="\0.5\0"
 s ^TKSOLDES("87702")="\0.5\0"
 s ^TKSOLDES("49927")="\0.5\0"
 s ^TKSOLDES("87701")="\0.5\0"
 s ^TKSOLDES("87688")="\0.5\0"
 s ^TKSOLDES("87689")="\0.5\0"
 s ^TKSOLDES("87690")="\0.5\0"
 s ^TKSOLDES("87691")="\0.5\0"
 s ^TKSOLDES("87692")="\0.5\0"
 s ^TKSOLDES("87697")="\0.5\0"
 s ^TKSOLDES("87699")="\0.5\0"
 s ^TKSOLDES("87700")="\0.5\0"
 s ^TKSOLDES("49951")="\0.5\0"
 s ^TKSOLDES("49950")="\0.5\0"
 s ^TKSOLDES("49949")="\0.5\0"
 s ^TKSOLDES("49936")="\0.5\0"
 s ^TKSOLDES("49935")="\0.5\0"
 s ^TKSOLDES("49934")="\0.5\0"
 s ^TKSOLDES("49933")="\0.5\0"
 s ^TKSOLDES("49932")="\0.5\0"
 s ^TKSOLDES("49931")="\0.5\0"
 s ^TKSOLDES("49930")="\0.5\0"
 s ^TKSOLDES("49929")="\0.5\0"
 s ^TKSOLDES("49937")="\0.5\0"
 s ^TKSOLDES("49938")="\0.5\0"
 s ^TKSOLDES("49945")="\0.5\0"
 s ^TKSOLDES("49948")="\0.5\0"
 s ^TKSOLDES("49947")="\0.5\0"
 s ^TKSOLDES("49946")="\0.5\0"
 s ^TKSOLDES("49944")="\0.5\0"
 s ^TKSOLDES("49939")="\0.5\0"
 s ^TKSOLDES("49943")="\0.5\0"
 s ^TKSOLDES("49942")="\0.5\0"
 s ^TKSOLDES("49941")="\0.5\0"
 s ^TKSOLDES("49940")="\0.5\0"
 s ^TKSOLDES("87687")="\0.5\0"
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 