ROUTINE SOLDES70AH13M391C7
SOLDES70AH13M391C7
 
	s ^TKSOLDES("56125")="\0.7\0"
	s ^TKSOLDES("56130")="\0.7\0"
	s ^TKSOLDES("56144")="\0.7\0"
	s ^TKSOLDES("56679")="\0.7\0"
	s ^TKSOLDES("56682")="\0.7\0"
	s ^TKSOLDES("56685")="\0.7\0"
	s ^TKSOLDES("56698")="\0.7\0"
	s ^TKSOLDES("56709")="\0.7\0"
	s ^TKSOLDES("56716")="\0.7\0"
	s ^TKSOLDES("56725")="\0.7\0"
	s ^TKSOLDES("56774")="\0.7\0"
	s ^TKSOLDES("56985")="\0.7\0"
	s ^TKSOLDES("57005")="\0.7\0"
	s ^TKSOLDES("57116")="\0.7\0"
	s ^TKSOLDES("57291")="\0.7\0"
	s ^TKSOLDES("57308")="\0.7\0"
	s ^TKSOLDES("57369")="\0.7\0"
	s ^TKSOLDES("57884")="\0.7\0"
	s ^TKSOLDES("58007")="\0.7\0"
	s ^TKSOLDES("58012")="\0.7\0"
	s ^TKSOLDES("58042")="\0.7\0"
	s ^TKSOLDES("58043")="\0.7\0"
	s ^TKSOLDES("58044")="\0.7\0"
	s ^TKSOLDES("58048")="\0.7\0"
	s ^TKSOLDES("58051")="\0.7\0"
	s ^TKSOLDES("58062")="\0.7\0"
	s ^TKSOLDES("58064")="\0.7\0"
	s ^TKSOLDES("58067")="\0.7\0"
	s ^TKSOLDES("58391")="\0.7\0"
	s ^TKSOLDES("58548")="\0.7\0"
	s ^TKSOLDES("58727")="\0.7\0"
	s ^TKSOLDES("58730")="\0.7\0"
	s ^TKSOLDES("58986")="\0.7\0"
	s ^TKSOLDES("59016")="\0.7\0"
	s ^TKSOLDES("59021")="\0.7\0"
	s ^TKSOLDES("59093")="\0.7\0"
	s ^TKSOLDES("59097")="\0.7\0"
	s ^TKSOLDES("59150")="\0.7\0"
	s ^TKSOLDES("59151")="\0.7\0"
	s ^TKSOLDES("59155")="\0.7\0"
	s ^TKSOLDES("59754")="\0.7\0"
	s ^TKSOLDES("59873")="\0.7\0"
	s ^TKSOLDES("59934")="\0.7\0"
	s ^TKSOLDES("60571")="\0.7\0"
	s ^TKSOLDES("60667")="\0.7\0"
	s ^TKSOLDES("60693")="\0.7\0"
	s ^TKSOLDES("60698")="\0.7\0"
	s ^TKSOLDES("61510")="\0.7\0"
	s ^TKSOLDES("61842")="\0.7\0"
	s ^TKSOLDES("61872")="\0.7\0"
	s ^TKSOLDES("61873")="\0.7\0"
	s ^TKSOLDES("61874")="\0.7\0"
	s ^TKSOLDES("62235")="\0.7\0"
	s ^TKSOLDES("62238")="\0.7\0"
	s ^TKSOLDES("62278")="\0.7\0"
	s ^TKSOLDES("62506")="\0.7\0"
	s ^TKSOLDES("62522")="\0.7\0"
	s ^TKSOLDES("62532")="\0.7\0"
	s ^TKSOLDES("63035")="\0.7\0"
	s ^TKSOLDES("63036")="\0.7\0"
	s ^TKSOLDES("63070")="\0.7\0"
	s ^TKSOLDES("63346")="\0.7\0"
	s ^TKSOLDES("63364")="\0.7\0"
	s ^TKSOLDES("63365")="\0.7\0"
	s ^TKSOLDES("63366")="\0.7\0"
	s ^TKSOLDES("63381")="\0.7\0"
	s ^TKSOLDES("63386")="\0.7\0"
	s ^TKSOLDES("63393")="\0.7\0"
	s ^TKSOLDES("63402")="\0.7\0"
	s ^TKSOLDES("63419")="\0.7\0"
	s ^TKSOLDES("63440")="\0.7\0"
	s ^TKSOLDES("63441")="\0.7\0"
	s ^TKSOLDES("63620")="\0.7\0"
	s ^TKSOLDES("63696")="\0.7\0"
	s ^TKSOLDES("63827")="\0.7\0"
	s ^TKSOLDES("63830")="\0.7\0"
	s ^TKSOLDES("63840")="\0.7\0"
	s ^TKSOLDES("63841")="\0.7\0"
	s ^TKSOLDES("63847")="\0.7\0"
	s ^TKSOLDES("63852")="\0.7\0"
	s ^TKSOLDES("63869")="\0.7\0"
	s ^TKSOLDES("63875")="\0.7\0"
	s ^TKSOLDES("63982")="\0.7\0"
	s ^TKSOLDES("63985")="\0.7\0"
	s ^TKSOLDES("64006")="\0.7\0"
	s ^TKSOLDES("64022")="\0.7\0"
	s ^TKSOLDES("64025")="\0.7\0"
	s ^TKSOLDES("64055")="\0.7\0"
	s ^TKSOLDES("64116")="\0.7\0"
	s ^TKSOLDES("64204")="\0.7\0"
	s ^TKSOLDES("64219")="\0.7\0"
	s ^TKSOLDES("64222")="\0.7\0"
	s ^TKSOLDES("64280")="\0.7\0"
	s ^TKSOLDES("64288")="\0.7\0"
	s ^TKSOLDES("64290")="\0.7\0"
	s ^TKSOLDES("64296")="\0.7\0"
	s ^TKSOLDES("64307")="\0.7\0"
	s ^TKSOLDES("64384")="\0.7\0"
	s ^TKSOLDES("91884")="\0.7\0"
	s ^TKSOLDES("92060")="\0.7\0"
	s ^TKSOLDES("64739")="\0.7\0"
	s ^TKSOLDES("64745")="\0.7\0"
	s ^TKSOLDES("64765")="\0.7\0"
	s ^TKSOLDES("64769")="\0.7\0"
	s ^TKSOLDES("64771")="\0.7\0"
	s ^TKSOLDES("65219")="\0.7\0"
	s ^TKSOLDES("65474")="\0.7\0"
	s ^TKSOLDES("65565")="\0.7\0"
	s ^TKSOLDES("65583")="\0.7\0"
	s ^TKSOLDES("65586")="\0.7\0"
	s ^TKSOLDES("65619")="\0.7\0"
	s ^TKSOLDES("65651")="\0.7\0"
	s ^TKSOLDES("65662")="\0.7\0"
	s ^TKSOLDES("65663")="\0.7\0"
	s ^TKSOLDES("65689")="\0.7\0"
	s ^TKSOLDES("65886")="\0.7\0"
	s ^TKSOLDES("65891")="\0.7\0"
	s ^TKSOLDES("65898")="\0.7\0"
	s ^TKSOLDES("65904")="\0.7\0"
	s ^TKSOLDES("65942")="\0.7\0"
	s ^TKSOLDES("65948")="\0.7\0"
	s ^TKSOLDES("65963")="\0.7\0"
	s ^TKSOLDES("65967")="\0.7\0"
	s ^TKSOLDES("65971")="\0.7\0"
	s ^TKSOLDES("65983")="\0.7\0"
	s ^TKSOLDES("65985")="\0.7\0"
	s ^TKSOLDES("65993")="\0.7\0"
	s ^TKSOLDES("66007")="\0.7\0"
	s ^TKSOLDES("66020")="\0.7\0"
	s ^TKSOLDES("66041")="\0.7\0"
	s ^TKSOLDES("66049")="\0.7\0"
	s ^TKSOLDES("66103")="\0.7\0"
	s ^TKSOLDES("66114")="\0.7\0"
	s ^TKSOLDES("66369")="\0.7\0"
	s ^TKSOLDES("67269")="\0.7\0"
	s ^TKSOLDES("67400")="\0.7\0"
	s ^TKSOLDES("67411")="\0.7\0"
	s ^TKSOLDES("67477")="\0.7\0"
	s ^TKSOLDES("67489")="\0.7\0"
	s ^TKSOLDES("67496")="\0.7\0"
	s ^TKSOLDES("67497")="\0.7\0"
	s ^TKSOLDES("67646")="\0.7\0"
	s ^TKSOLDES("67652")="\0.7\0"
	s ^TKSOLDES("67656")="\0.7\0"
	s ^TKSOLDES("67660")="\0.7\0"
	s ^TKSOLDES("67665")="\0.7\0"
	s ^TKSOLDES("67671")="\0.7\0"
	s ^TKSOLDES("67703")="\0.7\0"
	s ^TKSOLDES("67705")="\0.7\0"
	s ^TKSOLDES("67948")="\0.7\0"
	s ^TKSOLDES("68059")="\0.7\0"
	s ^TKSOLDES("68075")="\0.7\0"
	s ^TKSOLDES("68108")="\0.7\0"
	s ^TKSOLDES("68174")="\0.7\0"
	s ^TKSOLDES("68230")="\0.7\0"
	s ^TKSOLDES("68618")="\0.7\0"
	s ^TKSOLDES("68657")="\0.7\0"
	s ^TKSOLDES("69194")="\0.7\0"
	s ^TKSOLDES("69205")="\0.7\0"
	s ^TKSOLDES("69742")="\0.7\0"
	s ^TKSOLDES("70127")="\0.7\0"
	s ^TKSOLDES("70369")="\0.7\0"
	s ^TKSOLDES("70370")="\0.7\0"
	s ^TKSOLDES("70372")="\0.7\0"
	s ^TKSOLDES("70376")="\0.7\0"
	s ^TKSOLDES("70386")="\0.7\0"
	s ^TKSOLDES("70395")="\0.7\0"
	s ^TKSOLDES("70440")="\0.7\0"
	s ^TKSOLDES("70448")="\0.7\0"
	s ^TKSOLDES("70484")="\0.7\0"
	s ^TKSOLDES("70527")="\0.7\0"
	s ^TKSOLDES("70639")="\0.7\0"
	s ^TKSOLDES("70642")="\0.7\0"
	s ^TKSOLDES("70650")="\0.7\0"
	s ^TKSOLDES("70651")="\0.7\0"
	s ^TKSOLDES("70708")="\0.7\0"
	s ^TKSOLDES("70843")="\0.7\0"
	s ^TKSOLDES("70854")="\0.7\0"
	s ^TKSOLDES("70862")="\0.7\0"
	s ^TKSOLDES("72407")="\0.7\0"
	s ^TKSOLDES("93759")="\0.7\0"
	s ^TKSOLDES("72860")="\0.7\0"
	s ^TKSOLDES("72874")="\0.7\0"
	s ^TKSOLDES("72915")="\0.7\0"
	s ^TKSOLDES("72948")="\0.7\0"
	s ^TKSOLDES("72949")="\0.7\0"
	s ^TKSOLDES("72950")="\0.7\0"
	s ^TKSOLDES("72951")="\0.7\0"
	s ^TKSOLDES("72952")="\0.7\0"
	s ^TKSOLDES("72953")="\0.7\0"
	s ^TKSOLDES("72954")="\0.7\0"
	s ^TKSOLDES("72956")="\0.7\0"
	s ^TKSOLDES("72957")="\0.7\0"
	s ^TKSOLDES("72958")="\0.7\0"
	s ^TKSOLDES("72959")="\0.7\0"
	s ^TKSOLDES("72960")="\0.7\0"
	s ^TKSOLDES("72961")="\0.7\0"
	s ^TKSOLDES("72963")="\0.7\0"
	s ^TKSOLDES("72964")="\0.7\0"
	s ^TKSOLDES("72965")="\0.7\0"
	s ^TKSOLDES("72966")="\0.7\0"
	s ^TKSOLDES("72967")="\0.7\0"
	s ^TKSOLDES("72970")="\0.7\0"
	s ^TKSOLDES("72971")="\0.7\0"
	s ^TKSOLDES("72986")="\0.7\0"
	s ^TKSOLDES("73028")="\0.7\0"
	s ^TKSOLDES("73568")="\0.7\0"
	s ^TKSOLDES("74128")="\0.7\0"
	s ^TKSOLDES("74316")="\0.7\0"
	s ^TKSOLDES("74350")="\0.7\0"
	s ^TKSOLDES("74483")="\0.7\0"
	s ^TKSOLDES("74540")="\0.7\0"
	s ^TKSOLDES("74597")="\0.7\0"
	s ^TKSOLDES("74613")="\0.7\0"
	s ^TKSOLDES("74630")="\0.7\0"
	s ^TKSOLDES("74784")="\0.7\0"
	s ^TKSOLDES("75453")="\0.7\0"
	s ^TKSOLDES("75454")="\0.7\0"
	s ^TKSOLDES("75458")="\0.7\0"
	s ^TKSOLDES("75492")="\0.7\0"
	s ^TKSOLDES("75509")="\0.7\0"
	s ^TKSOLDES("75960")="\0.7\0"
	s ^TKSOLDES("75974")="\0.7\0"
	s ^TKSOLDES("76031")="\0.7\0"
	s ^TKSOLDES("76080")="\0.7\0"
	s ^TKSOLDES("76221")="\0.7\0"
	s ^TKSOLDES("76290")="\0.7\0"
	s ^TKSOLDES("76482")="\0.7\0"
	s ^TKSOLDES("76872")="\0.7\0"
	s ^TKSOLDES("77026")="\0.7\0"
	s ^TKSOLDES("77061")="\0.7\0"
	s ^TKSOLDES("77068")="\0.7\0"
	s ^TKSOLDES("77069")="\0.7\0"
	s ^TKSOLDES("77508")="\0.7\0"
	s ^TKSOLDES("77798")="\0.7\0"
	s ^TKSOLDES("77996")="\0.7\0"
	s ^TKSOLDES("78177")="\0.7\0"
	s ^TKSOLDES("78182")="\0.7\0"
	s ^TKSOLDES("78185")="\0.7\0"
	s ^TKSOLDES("78186")="\0.7\0"
	s ^TKSOLDES("78191")="\0.7\0"
	s ^TKSOLDES("78215")="\0.7\0"
	s ^TKSOLDES("78286")="\0.7\0"
	s ^TKSOLDES("78416")="\0.7\0"
	s ^TKSOLDES("78471")="\0.7\0"
	s ^TKSOLDES("78533")="\0.7\0"
	s ^TKSOLDES("78534")="\0.7\0"
	s ^TKSOLDES("78539")="\0.7\0"
	s ^TKSOLDES("78736")="\0.7\0"
	s ^TKSOLDES("78745")="\0.7\0"
	s ^TKSOLDES("78802")="\0.7\0"
	s ^TKSOLDES("78913")="\0.7\0"
	s ^TKSOLDES("79056")="\0.7\0"
	s ^TKSOLDES("79083")="\0.7\0"
	s ^TKSOLDES("79102")="\0.7\0"
	s ^TKSOLDES("79129")="\0.7\0"
	s ^TKSOLDES("79260")="\0.7\0"
	s ^TKSOLDES("79283")="\0.7\0"
	s ^TKSOLDES("79288")="\0.7\0"
	s ^TKSOLDES("79302")="\0.7\0"
	s ^TKSOLDES("79459")="\0.7\0"
	s ^TKSOLDES("79546")="\0.7\0"
	s ^TKSOLDES("79553")="\0.7\0"
	s ^TKSOLDES("79969")="\0.7\0"
	s ^TKSOLDES("80222")="\0.7\0"
	s ^TKSOLDES("80660")="\0.7\0"
	s ^TKSOLDES("80667")="\0.7\0"
	s ^TKSOLDES("80692")="\0.7\0"
	s ^TKSOLDES("80693")="\0.7\0"
	s ^TKSOLDES("80706")="\0.7\0"
	s ^TKSOLDES("80708")="\0.7\0"
	s ^TKSOLDES("80710")="\0.7\0"
	s ^TKSOLDES("80711")="\0.7\0"
	s ^TKSOLDES("80819")="\0.7\0"
	s ^TKSOLDES("81044")="\0.7\0"
	s ^TKSOLDES("81046")="\0.7\0"
	s ^TKSOLDES("81155")="\0.7\0"
	s ^TKSOLDES("81209")="\0.7\0"
	s ^TKSOLDES("81243")="\0.7\0"
	s ^TKSOLDES("81265")="\0.7\0"
	s ^TKSOLDES("81384")="\0.7\0"
	s ^TKSOLDES("81385")="\0.7\0"
	s ^TKSOLDES("81391")="\0.7\0"
	s ^TKSOLDES("81432")="\0.7\0"
	s ^TKSOLDES("81693")="\0.7\0"
	s ^TKSOLDES("81696")="\0.7\0"
	s ^TKSOLDES("82014")="\0.7\0"
	s ^TKSOLDES("82019")="\0.7\0"
	s ^TKSOLDES("82075")="\0.7\0"
	s ^TKSOLDES("82101")="\0.7\0"
	s ^TKSOLDES("82174")="\0.7\0"
	s ^TKSOLDES("82257")="\0.7\0"
	s ^TKSOLDES("82309")="\0.7\0"
	s ^TKSOLDES("82443")="\0.7\0"
	s ^TKSOLDES("82461")="\0.7\0"
	s ^TKSOLDES("82577")="\0.7\0"
	s ^TKSOLDES("82595")="\0.7\0"
	s ^TKSOLDES("82631")="\0.7\0"
	s ^TKSOLDES("82640")="\0.7\0"
	s ^TKSOLDES("82650")="\0.7\0"
	s ^TKSOLDES("82672")="\0.7\0"
	s ^TKSOLDES("82673")="\0.7\0"
	s ^TKSOLDES("82704")="\0.7\0"
	s ^TKSOLDES("82927")="\0.7\0"
	s ^TKSOLDES("82937")="\0.7\0"
	s ^TKSOLDES("82938")="\0.7\0"
	s ^TKSOLDES("82946")="\0.7\0"
	s ^TKSOLDES("83367")="\0.7\0"
	s ^TKSOLDES("83421")="\0.7\0"
	s ^TKSOLDES("83520")="\0.7\0"
	s ^TKSOLDES("83568")="\0.7\0"
	s ^TKSOLDES("83854")="\0.7\0"
	s ^TKSOLDES("84029")="\0.7\0"
	s ^TKSOLDES("84079")="\0.7\0"
	s ^TKSOLDES("84846")="\0.7\0"
	s ^TKSOLDES("84893")="\0.7\0"
	s ^TKSOLDES("84992")="\0.7\0"
	s ^TKSOLDES("85096")="\0.7\0"
	s ^TKSOLDES("85099")="\0.7\0"
	s ^TKSOLDES("85128")="\0.7\0"
	s ^TKSOLDES("85137")="\0.7\0"
	s ^TKSOLDES("85861")="\0.7\0"
	s ^TKSOLDES("86155")="\0.7\0"
	s ^TKSOLDES("86400")="\0.7\0"
	s ^TKSOLDES("86478")="\0.7\0"
	s ^TKSOLDES("86621")="\0.7\0"
	s ^TKSOLDES("87728")="\0.7\0"
	s ^TKSOLDES("87769")="\0.7\0"
	s ^TKSOLDES("87980")="\0.7\0"
	s ^TKSOLDES("88000")="\0.7\0"
	s ^TKSOLDES("88002")="\0.7\0"
	s ^TKSOLDES("88005")="\0.7\0"
	s ^TKSOLDES("88032")="\0.7\0"
	s ^TKSOLDES("88567")="\0.7\0"
	s ^TKSOLDES("88595")="\0.7\0"
	s ^TKSOLDES("89927")="\0.7\0"
	s ^TKSOLDES("100148")="\0.7\0"
	s ^TKSOLDES("100255")="\0.7\0"
	s ^TKSOLDES("100286")="\0.7\0"
	s ^TKSOLDES("100332")="\0.7\0"
	s ^TKSOLDES("100385")="\0.7\0"
	s ^TKSOLDES("100500")="\0.7\0"
	s ^TKSOLDES("100633")="\0.7\0"
	s ^TKSOLDES("100646")="\0.7\0"
	s ^TKSOLDES("100729")="\0.7\0"
	s ^TKSOLDES("101118")="\0.7\0"
	s ^TKSOLDES("101185")="\0.7\0"
	s ^TKSOLDES("101186")="\0.7\0"
	s ^TKSOLDES("101195")="\0.7\0"
	s ^TKSOLDES("101207")="\0.7\0"
	s ^TKSOLDES("101209")="\0.7\0"
	s ^TKSOLDES("101443")="\0.7\0"
	s ^TKSOLDES("101444")="\0.7\0"
	s ^TKSOLDES("101448")="\0.7\0"
	s ^TKSOLDES("101449")="\0.7\0"
	s ^TKSOLDES("101454")="\0.7\0"
	s ^TKSOLDES("101461")="\0.7\0"
	s ^TKSOLDES("101516")="\0.7\0"
	s ^TKSOLDES("102945")="\0.7\0"
	s ^TKSOLDES("102953")="\0.7\0"
	s ^TKSOLDES("102954")="\0.7\0"
	s ^TKSOLDES("102966")="\0.7\0"
	s ^TKSOLDES("102967")="\0.7\0"
	s ^TKSOLDES("102968")="\0.7\0"
	s ^TKSOLDES("103087")="\0.7\0"
	s ^TKSOLDES("103270")="\0.7\0"
	s ^TKSOLDES("103663")="\0.7\0"
	s ^TKSOLDES("103675")="\0.7\0"
	s ^TKSOLDES("104183")="\0.7\0"
	s ^TKSOLDES("104735")="\0.7\0"
	s ^TKSOLDES("105151")="\0.7\0"
	s ^TKSOLDES("105491")="\0.7\0"
	s ^TKSOLDES("2442")="\0.7\0"
	s ^TKSOLDES("78931")="\0.7\0"
	s ^TKSOLDES("100634")="\0.7\0"
	s ^TKSOLDES("93409")="\0.7\0"
	s ^TKSOLDES("76227")="\0.7\0"
	s ^TKSOLDES("83373")="\0.7\0"
	s ^TKSOLDES("83773")="\0.7\0"
	s ^TKSOLDES("83785")="\0.7\0"
	s ^TKSOLDES("91636")="\0.7\0"
	s ^TKSOLDES("77430")="\0.7\0"
	s ^TKSOLDES("81551")="\0.7\0"
	s ^TKSOLDES("81908")="\0.7\0"
	s ^TKSOLDES("85922")="\0.7\0"
	s ^TKSOLDES("100653")="\0.7\0"
	s ^TKSOLDES("105594")="\0.7\0"
 
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 