ROUTINE SOLDES70AH13P3
SOLDES70AH13P3	
 
	 s ^TKSOLDES("72761")="\0.7\0"
	s ^TKSOLDES("72762")="\0.7\0"
	s ^TKSOLDES("72785")="\0.7\0"
	s ^TKSOLDES("72783")="\0.7\0"
	s ^TKSOLDES("72776")="\0.7\0"
	s ^TKSOLDES("80850")="\0.7\0"
	s ^TKSOLDES("84859")="\0.7\0"
	s ^TKSOLDES("86086")="\0.7\0"
	s ^TKSOLDES("80369")="\0.7\0"
	s ^TKSOLDES("72760")="\0.7\0"
	s ^TKSOLDES("80345")="\0.7\0"
	s ^TKSOLDES("101700")="\0.7\0"
	s ^TKSOLDES("80424")="\0.7\0"
	s ^TKSOLDES("72641")="\0.7\0"
	s ^TKSOLDES("84854")="\0.7\0"
	s ^TKSOLDES("84853")="\0.7\0"
	s ^TKSOLDES("72644")="\0.7\0"
	s ^TKSOLDES("72715")="\0.7\0"
	s ^TKSOLDES("103548")="\0.7\0"
	s ^TKSOLDES("103549")="\0.7\0"
	s ^TKSOLDES("103551")="\0.7\0"
	s ^TKSOLDES("103550")="\0.7\0"
	s ^TKSOLDES("103554")="\0.7\0"
	s ^TKSOLDES("103555")="\0.7\0"
	s ^TKSOLDES("103553")="\0.7\0"
	s ^TKSOLDES("103567")="\0.7\0"
	s ^TKSOLDES("103564")="\0.7\0"
	s ^TKSOLDES("103572")="\0.7\0"
	s ^TKSOLDES("80851")="\0.7\0"
	s ^TKSOLDES("101736")="\0.7\0"
	s ^TKSOLDES("72727")="\0.7\0"
	s ^TKSOLDES("84135")="\0.7\0"
	s ^TKSOLDES("61950")="\0.7\0"
	s ^TKSOLDES("72723")="\0.7\0"
	s ^TKSOLDES("72650")="\0.7\0"
	s ^TKSOLDES("103623")="\0.7\0"
	s ^TKSOLDES("72731")="\0.7\0"
	s ^TKSOLDES("80856")="\0.7\0"
	s ^TKSOLDES("72652")="\0.7\0"
	s ^TKSOLDES("77269")="\0.7\0"
	s ^TKSOLDES("87706")="\0.7\0"
	s ^TKSOLDES("80384")="\0.7\0"
	s ^TKSOLDES("72734")="\0.7\0"
	s ^TKSOLDES("81368")="\0.7\0"
	s ^TKSOLDES("81369")="\0.7\0"
	s ^TKSOLDES("81370")="\0.7\0"
	s ^TKSOLDES("81371")="\0.7\0"
	s ^TKSOLDES("81366")="\0.7\0"
	s ^TKSOLDES("81367")="\0.7\0"
	s ^TKSOLDES("103624")="\0.7\0"
	s ^TKSOLDES("103625")="\0.7\0"
	s ^TKSOLDES("101690")="\0.7\0"
	s ^TKSOLDES("72732")="\0.7\0"
	s ^TKSOLDES("103626")="\0.7\0"
	s ^TKSOLDES("80431")="\0.7\0"
	s ^TKSOLDES("77260")="\0.7\0"
	s ^TKSOLDES("80427")="\0.7\0"
	s ^TKSOLDES("101738")="\0.7\0"
	s ^TKSOLDES("101737")="\0.7\0"
	s ^TKSOLDES("72703")="\0.7\0"
	s ^TKSOLDES("80852")="\0.7\0"
	s ^TKSOLDES("103614")="\0.7\0"
	s ^TKSOLDES("72772")="\0.7\0"
	s ^TKSOLDES("80841")="\0.7\0"
	s ^TKSOLDES("80842")="\0.7\0"
	s ^TKSOLDES("80374")="\0.7\0"
	s ^TKSOLDES("80376")="\0.7\0"
	s ^TKSOLDES("80375")="\0.7\0"
	s ^TKSOLDES("80377")="\0.7\0"
	s ^TKSOLDES("72707")="\0.7\0"
	s ^TKSOLDES("80846")="\0.7\0"
	s ^TKSOLDES("77262")="\0.7\0"
	s ^TKSOLDES("77261")="\0.7\0"
	s ^TKSOLDES("72639")="\0.7\0"
	s ^TKSOLDES("101752")="\0.7\0"
	s ^TKSOLDES("80420")="\0.7\0"
	s ^TKSOLDES("77266")="\0.7\0"
	s ^TKSOLDES("77265")="\0.7\0"
	s ^TKSOLDES("101697")="\0.7\0"
	s ^TKSOLDES("87710")="\0.7\0"
	s ^TKSOLDES("80353")="\0.7\0"
	s ^TKSOLDES("80419")="\0.7\0"
	s ^TKSOLDES("84136")="\0.7\0"
	s ^TKSOLDES("86080")="\0.7\0"
	s ^TKSOLDES("84885")="\0.7\0"
	s ^TKSOLDES("103582")="\0.7\0"
	s ^TKSOLDES("101712")="\0.7\0"
	s ^TKSOLDES("77259")="\0.7\0"
	s ^TKSOLDES("84884")="\0.7\0"
	s ^TKSOLDES("80408")="\0.7\0"
	s ^TKSOLDES("80407")="\0.7\0"
	s ^TKSOLDES("101698")="\0.7\0"
	s ^TKSOLDES("101721")="\0.7\0"
	s ^TKSOLDES("80406")="\0.7\0"
	s ^TKSOLDES("101692")="\0.7\0"
	s ^TKSOLDES("77270")="\0.7\0"
	s ^TKSOLDES("80383")="\0.7\0"
	s ^TKSOLDES("101691")="\0.7\0"
	s ^TKSOLDES("101693")="\0.7\0"
	s ^TKSOLDES("80425")="\0.7\0"
	s ^TKSOLDES("101713")="\0.7\0"
	s ^TKSOLDES("101753")="\0.7\0"
	s ^TKSOLDES("87697")="\0.7\0"
	s ^TKSOLDES("80429")="\0.7\0"
	s ^TKSOLDES("80432")="\0.7\0"
	s ^TKSOLDES("80426")="\0.7\0"
	s ^TKSOLDES("72775")="\0.7\0"
	s ^TKSOLDES("100010")="\0.7\0"
	s ^TKSOLDES("100016")="\0.7\0"
	s ^TKSOLDES("100008")="\0.7\0"
	s ^TKSOLDES("100011")="\0.7\0"
	s ^TKSOLDES("100002")="\0.7\0"
	s ^TKSOLDES("100017")="\0.7\0"
	s ^TKSOLDES("100015")="\0.7\0"
	s ^TKSOLDES("100014")="\0.7\0"
	s ^TKSOLDES("100012")="\0.7\0"
	s ^TKSOLDES("100004")="\0.7\0"
	s ^TKSOLDES("100005")="\0.7\0"
	s ^TKSOLDES("100009")="\0.7\0"
	s ^TKSOLDES("100007")="\0.7\0"
	s ^TKSOLDES("100006")="\0.7\0"
	s ^TKSOLDES("100013")="\0.7\0"
	s ^TKSOLDES("100003")="\0.7\0"
	s ^TKSOLDES("80831")="\0.7\0"
	s ^TKSOLDES("80836")="\0.7\0"
	s ^TKSOLDES("84875")="\0.7\0"
	s ^TKSOLDES("84874")="\0.7\0"
	s ^TKSOLDES("87705")="\0.7\0"
	s ^TKSOLDES("105530")="\0.7\0"
	s ^TKSOLDES("103590")="\0.7\0"
	s ^TKSOLDES("80398")="\0.7\0"
	s ^TKSOLDES("80405")="\0.7\0"
	s ^TKSOLDES("101678")="\0.7\0"
	s ^TKSOLDES("80397")="\0.7\0"
	s ^TKSOLDES("80399")="\0.7\0"
	s ^TKSOLDES("72753")="\0.7\0"
	s ^TKSOLDES("80351")="\0.7\0"
	s ^TKSOLDES("101685")="\0.7\0"
	s ^TKSOLDES("101695")="\0.7\0"
	s ^TKSOLDES("101704")="\0.7\0"
	s ^TKSOLDES("101705")="\0.7\0"
	s ^TKSOLDES("80826")="\0.7\0"
	s ^TKSOLDES("80334")="\0.7\0"
	s ^TKSOLDES("101706")="\0.7\0"
	s ^TKSOLDES("80825")="\0.7\0"
	s ^TKSOLDES("101703")="\0.7\0"
	s ^TKSOLDES("80346")="\0.7\0"
	s ^TKSOLDES("58831")="\0.7\0"
	s ^TKSOLDES("87702")="\0.7\0"
	s ^TKSOLDES("80347")="\0.7\0"
	s ^TKSOLDES("80855")="\0.7\0"
	s ^TKSOLDES("80834")="\0.7\0"
	s ^TKSOLDES("103621")="\0.7\0"
	s ^TKSOLDES("84881")="\0.7\0"
	s ^TKSOLDES("84880")="\0.7\0"
	s ^TKSOLDES("105516")="\0.7\0"
	s ^TKSOLDES("105537")="\0.7\0"
	s ^TKSOLDES("84867")="\0.7\0"
	s ^TKSOLDES("87679")="\0.7\0"
	s ^TKSOLDES("103571")="\0.7\0"
	s ^TKSOLDES("103584")="\0.7\0"
	s ^TKSOLDES("103560")="\0.7\0"
	s ^TKSOLDES("103573")="\0.7\0"
	s ^TKSOLDES("103596")="\0.7\0"
	s ^TKSOLDES("87696")="\0.7\0"
	s ^TKSOLDES("87695")="\0.7\0"
	s ^TKSOLDES("87694")="\0.7\0"
	s ^TKSOLDES("87693")="\0.7\0"
	s ^TKSOLDES("105550")="\0.7\0"
	s ^TKSOLDES("105548")="\0.7\0"
	s ^TKSOLDES("105524")="\0.7\0"
	s ^TKSOLDES("80338")="\0.7\0"
	s ^TKSOLDES("84852")="\0.7\0"
	s ^TKSOLDES("84850")="\0.7\0"
	s ^TKSOLDES("105540")="\0.7\0"
	s ^TKSOLDES("72682")="\0.7\0"
	s ^TKSOLDES("101675")="\0.7\0"
	s ^TKSOLDES("80344")="\0.7\0"
	s ^TKSOLDES("84848")="\0.7\0"
	s ^TKSOLDES("80339")="\0.7\0"
	s ^TKSOLDES("80335")="\0.7\0"
	s ^TKSOLDES("80342")="\0.7\0"
	s ^TKSOLDES("105551")="\0.7\0"
	s ^TKSOLDES("80845")="\0.7\0"
	s ^TKSOLDES("101679")="\0.7\0"
	s ^TKSOLDES("87711")="\0.7\0"
	s ^TKSOLDES("80409")="\0.7\0"
	s ^TKSOLDES("72712")="\0.7\0"
	s ^TKSOLDES("72759")="\0.7\0"
	s ^TKSOLDES("72758")="\0.7\0"
	s ^TKSOLDES("80837")="\0.7\0"
	s ^TKSOLDES("81354")="\0.7\0"
	s ^TKSOLDES("81355")="\0.7\0"
	s ^TKSOLDES("81356")="\0.7\0"
	s ^TKSOLDES("81357")="\0.7\0"
	s ^TKSOLDES("81358")="\0.7\0"
	s ^TKSOLDES("81359")="\0.7\0"
	s ^TKSOLDES("12533")="\0.7\0"
	s ^TKSOLDES("12535")="\0.7\0"
	s ^TKSOLDES("65831")="\0.7\0"
	s ^TKSOLDES("65832")="\0.7\0"
	s ^TKSOLDES("65824")="\0.7\0"
	s ^TKSOLDES("65825")="\0.7\0"
	s ^TKSOLDES("12502")="\0.7\0"
	s ^TKSOLDES("12506")="\0.7\0"
	s ^TKSOLDES("12508")="\0.7\0"
	s ^TKSOLDES("12509")="\0.7\0"
	s ^TKSOLDES("12518")="\0.7\0"
	s ^TKSOLDES("12513")="\0.7\0"
	s ^TKSOLDES("12515")="\0.7\0"
	s ^TKSOLDES("12519")="\0.7\0"
	s ^TKSOLDES("12524")="\0.7\0"
	s ^TKSOLDES("12525")="\0.7\0"
	s ^TKSOLDES("65827")="\0.7\0"
	s ^TKSOLDES("65818")="\0.7\0"
	s ^TKSOLDES("65821")="\0.7\0"
	s ^TKSOLDES("65820")="\0.7\0"
	s ^TKSOLDES("65819")="\0.7\0"
	s ^TKSOLDES("65822")="\0.7\0"
	s ^TKSOLDES("65823")="\0.7\0"
	s ^TKSOLDES("59234")="\0.7\0"
	s ^TKSOLDES("59236")="\0.7\0"
	s ^TKSOLDES("59235")="\0.7\0"
	s ^TKSOLDES("59227")="\0.7\0"
	s ^TKSOLDES("59228")="\0.7\0"
	s ^TKSOLDES("59232")="\0.7\0"
	s ^TKSOLDES("59233")="\0.7\0"
	s ^TKSOLDES("59225")="\0.7\0"
	s ^TKSOLDES("59226")="\0.7\0"
	s ^TKSOLDES("59229")="\0.7\0"
	s ^TKSOLDES("59231")="\0.7\0"
	s ^TKSOLDES("59238")="\0.7\0"
	s ^TKSOLDES("59237")="\0.7\0"
	s ^TKSOLDES("59239")="\0.7\0"
	s ^TKSOLDES("12529")="\0.7\0"
	s ^TKSOLDES("65850")="\0.7\0"
	s ^TKSOLDES("12538")="\0.7\0"
	s ^TKSOLDES("65836")="\0.7\0"
	s ^TKSOLDES("65835")="\0.7\0"
	s ^TKSOLDES("12540")="\0.7\0"
	s ^TKSOLDES("53498")="\0.7\0"
	s ^TKSOLDES("53499")="\0.7\0"
	s ^TKSOLDES("53497")="\0.7\0"
	s ^TKSOLDES("80403")="\0.7\0"
	s ^TKSOLDES("72740")="\0.7\0"
	s ^TKSOLDES("87707")="\0.7\0"
	s ^TKSOLDES("80411")="\0.7\0"
	s ^TKSOLDES("80412")="\0.7\0"
	s ^TKSOLDES("72716")="\0.7\0"
	s ^TKSOLDES("72745")="\0.7\0"
	s ^TKSOLDES("72743")="\0.7\0"
	s ^TKSOLDES("72742")="\0.7\0"
	s ^TKSOLDES("101688")="\0.7\0"
	s ^TKSOLDES("101686")="\0.7\0"
	s ^TKSOLDES("101687")="\0.7\0"
	s ^TKSOLDES("80433")="\0.7\0"
	s ^TKSOLDES("80414")="\0.7\0"
	s ^TKSOLDES("80413")="\0.7\0"
	s ^TKSOLDES("80415")="\0.7\0"
	s ^TKSOLDES("103598")="\0.7\0"
	s ^TKSOLDES("103597")="\0.7\0"
	s ^TKSOLDES("103593")="\0.7\0"
	s ^TKSOLDES("103594")="\0.7\0"
	s ^TKSOLDES("103595")="\0.7\0"
	s ^TKSOLDES("101745")="\0.7\0"
	s ^TKSOLDES("80356")="\0.7\0"
	s ^TKSOLDES("80354")="\0.7\0"
	s ^TKSOLDES("101694")="\0.7\0"
	s ^TKSOLDES("103600")="\0.7\0"
	s ^TKSOLDES("105536")="\0.7\0"
	s ^TKSOLDES("80853")="\0.7\0"
	s ^TKSOLDES("72672")="\0.7\0"
	s ^TKSOLDES("104504")="\0.7\0"
	s ^TKSOLDES("102058")="\0.7\0"
	s ^TKSOLDES("104505")="\0.7\0"
	s ^TKSOLDES("103620")="\0.7\0"
	s ^TKSOLDES("103619")="\0.7\0"
	s ^TKSOLDES("103615")="\0.7\0"
	s ^TKSOLDES("103616")="\0.7\0"
	s ^TKSOLDES("101746")="\0.7\0"
	s ^TKSOLDES("72647")="\0.7\0"
	s ^TKSOLDES("72646")="\0.7\0"
	s ^TKSOLDES("72648")="\0.7\0"
	s ^TKSOLDES("72645")="\0.7\0"
	s ^TKSOLDES("87359")="\0.7\0"
	s ^TKSOLDES("87351")="\0.7\0"
	s ^TKSOLDES("87361")="\0.7\0"
	s ^TKSOLDES("87343")="\0.7\0"
	s ^TKSOLDES("87340")="\0.7\0"
	s ^TKSOLDES("87338")="\0.7\0"
	s ^TKSOLDES("87339")="\0.7\0"
	s ^TKSOLDES("87357")="\0.7\0"
	s ^TKSOLDES("87352")="\0.7\0"
	s ^TKSOLDES("87349")="\0.7\0"
	s ^TKSOLDES("87360")="\0.7\0"
	s ^TKSOLDES("87362")="\0.7\0"
	s ^TKSOLDES("87350")="\0.7\0"
	s ^TKSOLDES("87332")="\0.7\0"
	s ^TKSOLDES("87358")="\0.7\0"
	s ^TKSOLDES("87327")="\0.7\0"
	s ^TKSOLDES("87331")="\0.7\0"
	s ^TKSOLDES("87334")="\0.7\0"
	s ^TKSOLDES("87328")="\0.7\0"
	s ^TKSOLDES("87329")="\0.7\0"
	s ^TKSOLDES("87330")="\0.7\0"
	s ^TKSOLDES("87333")="\0.7\0"
	s ^TKSOLDES("87345")="\0.7\0"
	s ^TKSOLDES("87337")="\0.7\0"
	s ^TKSOLDES("87347")="\0.7\0"
	s ^TKSOLDES("87348")="\0.7\0"
	s ^TKSOLDES("87341")="\0.7\0"
	s ^TKSOLDES("87342")="\0.7\0"
	s ^TKSOLDES("87355")="\0.7\0"
	s ^TKSOLDES("87346")="\0.7\0"
	s ^TKSOLDES("87353")="\0.7\0"
	s ^TKSOLDES("87336")="\0.7\0"
	s ^TKSOLDES("87356")="\0.7\0"
	s ^TKSOLDES("87344")="\0.7\0"
	s ^TKSOLDES("87335")="\0.7\0"
	s ^TKSOLDES("87354")="\0.7\0"
	s ^TKSOLDES("59894")="\0.7\0"
	s ^TKSOLDES("59899")="\0.7\0"
	s ^TKSOLDES("59900")="\0.7\0"
	s ^TKSOLDES("61942")="\0.7\0"
	s ^TKSOLDES("59895")="\0.7\0"
	s ^TKSOLDES("59893")="\0.7\0"
	s ^TKSOLDES("59892")="\0.7\0"
	s ^TKSOLDES("59897")="\0.7\0"
	s ^TKSOLDES("59901")="\0.7\0"
	s ^TKSOLDES("61961")="\0.7\0"
	s ^TKSOLDES("59886")="\0.7\0"
	s ^TKSOLDES("59896")="\0.7\0"
	s ^TKSOLDES("86769")="\0.7\0"
	s ^TKSOLDES("105542")="\0.7\0"
	s ^TKSOLDES("86754")="\0.7\0"
	s ^TKSOLDES("86757")="\0.7\0"
	s ^TKSOLDES("86764")="\0.7\0"
	s ^TKSOLDES("86758")="\0.7\0"
	s ^TKSOLDES("86761")="\0.7\0"
	s ^TKSOLDES("86760")="\0.7\0"
	s ^TKSOLDES("86768")="\0.7\0"
	s ^TKSOLDES("86765")="\0.7\0"
	s ^TKSOLDES("86766")="\0.7\0"
	s ^TKSOLDES("105543")="\0.7\0"
	s ^TKSOLDES("86767")="\0.7\0"
	s ^TKSOLDES("34810")="\0.7\0"
	s ^TKSOLDES("34811")="\0.7\0"
	s ^TKSOLDES("34812")="\0.7\0"
	s ^TKSOLDES("34813")="\0.7\0"
	s ^TKSOLDES("34814")="\0.7\0"
	s ^TKSOLDES("84442")="\0.7\0"
	s ^TKSOLDES("37662")="\0.7\0"
	s ^TKSOLDES("34815")="\0.7\0"
	s ^TKSOLDES("34816")="\0.7\0"
	s ^TKSOLDES("34817")="\0.7\0"
	s ^TKSOLDES("100709")="\0.7\0"
	s ^TKSOLDES("100710")="\0.7\0"
	s ^TKSOLDES("37147")="\0.7\0"
	s ^TKSOLDES("37148")="\0.7\0"
	s ^TKSOLDES("34818")="\0.7\0"
	s ^TKSOLDES("34819")="\0.7\0"
	s ^TKSOLDES("42328")="\0.7\0"
	s ^TKSOLDES("85554")="\0.7\0"
	s ^TKSOLDES("85555")="\0.7\0"
	s ^TKSOLDES("87844")="\0.7\0"
	s ^TKSOLDES("67993")="\0.7\0"
	s ^TKSOLDES("67989")="\0.7\0"
	s ^TKSOLDES("67991")="\0.7\0"
	s ^TKSOLDES("67987")="\0.7\0"
	s ^TKSOLDES("67976")="\0.7\0"
	s ^TKSOLDES("67992")="\0.7\0"
	s ^TKSOLDES("67990")="\0.7\0"
	s ^TKSOLDES("67977")="\0.7\0"
	s ^TKSOLDES("67986")="\0.7\0"
	s ^TKSOLDES("67981")="\0.7\0"
	s ^TKSOLDES("68001")="\0.7\0"
	s ^TKSOLDES("67979")="\0.7\0"
	s ^TKSOLDES("67999")="\0.7\0"
	s ^TKSOLDES("67974")="\0.7\0"
	s ^TKSOLDES("67975")="\0.7\0"
	s ^TKSOLDES("67988")="\0.7\0"
	s ^TKSOLDES("67994")="\0.7\0"
	s ^TKSOLDES("67995")="\0.7\0"
	s ^TKSOLDES("67973")="\0.7\0"
	s ^TKSOLDES("68000")="\0.7\0"
	s ^TKSOLDES("67972")="\0.7\0"
	s ^TKSOLDES("67984")="\0.7\0"
	s ^TKSOLDES("67983")="\0.7\0"
	s ^TKSOLDES("67996")="\0.7\0"
	s ^TKSOLDES("67997")="\0.7\0"
	s ^TKSOLDES("67985")="\0.7\0"
	s ^TKSOLDES("67978")="\0.7\0"
	s ^TKSOLDES("67998")="\0.7\0"
	s ^TKSOLDES("103293")="\0.7\0"
	s ^TKSOLDES("103294")="\0.7\0"
	s ^TKSOLDES("54780")="\0.7\0"
	s ^TKSOLDES("54779")="\0.7\0"
	s ^TKSOLDES("9271")="\0.7\0"
	s ^TKSOLDES("62514")="\0.7\0"
	s ^TKSOLDES("102335")="\0.7\0"
	s ^TKSOLDES("52848")="\0.7\0"
	s ^TKSOLDES("80077")="\0.7\0"
	s ^TKSOLDES("80080")="\0.7\0"
	s ^TKSOLDES("80079")="\0.7\0"
	s ^TKSOLDES("87317")="\0.7\0"
	s ^TKSOLDES("87849")="\0.7\0"
	s ^TKSOLDES("87848")="\0.7\0"
	s ^TKSOLDES("54783")="\0.7\0"
	s ^TKSOLDES("9272")="\0.7\0"
	s ^TKSOLDES("8441")="\0.7\0"
	s ^TKSOLDES("102337")="\0.7\0"
	s ^TKSOLDES("86998")="\0.7\0"
	s ^TKSOLDES("80065")="\0.7\0"
	s ^TKSOLDES("80232")="\0.7\0"
	s ^TKSOLDES("54791")="\0.7\0"
	s ^TKSOLDES("54790")="\0.7\0"
	s ^TKSOLDES("41085")="\0.7\0"
	s ^TKSOLDES("41082")="\0.7\0"
	s ^TKSOLDES("54787")="\0.7\0"
	s ^TKSOLDES("8415")="\0.7\0"
	s ^TKSOLDES("8414")="\0.7\0"
	s ^TKSOLDES("78543")="\0.7\0"
	s ^TKSOLDES("78542")="\0.7\0"
	s ^TKSOLDES("78541")="\0.7\0"
	s ^TKSOLDES("78540")="\0.7\0"
	s ^TKSOLDES("55584")="\0.7\0"
	s ^TKSOLDES("55585")="\0.7\0"
	s ^TKSOLDES("55582")="\0.7\0"
	s ^TKSOLDES("55583")="\0.7\0"
	s ^TKSOLDES("55580")="\0.7\0"
	s ^TKSOLDES("55579")="\0.7\0"
	s ^TKSOLDES("55578")="\0.7\0"
	s ^TKSOLDES("75978")="\0.7\0"
	s ^TKSOLDES("44302")="\0.7\0"
	s ^TKSOLDES("43881")="\0.7\0"
	s ^TKSOLDES("78585")="\0.7\0"
	s ^TKSOLDES("79162")="\0.7\0"
	s ^TKSOLDES("79163")="\0.7\0"
	s ^TKSOLDES("75951")="\0.7\0"
	s ^TKSOLDES("75952")="\0.7\0"
	s ^TKSOLDES("78720")="\0.7\0"
	s ^TKSOLDES("78718")="\0.7\0"
	s ^TKSOLDES("75968")="\0.7\0"
	s ^TKSOLDES("68040")="\0.7\0"
	s ^TKSOLDES("87144")="\0.7\0"
	s ^TKSOLDES("81045")="\0.7\0"
	s ^TKSOLDES("68046")="\0.7\0"
	s ^TKSOLDES("68044")="\0.7\0"
	s ^TKSOLDES("75993")="\0.7\0"
	s ^TKSOLDES("87156")="\0.7\0"
	s ^TKSOLDES("82302")="\0.7\0"
	s ^TKSOLDES("73127")="\0.7\0"
	s ^TKSOLDES("73128")="\0.7\0"
	s ^TKSOLDES("73130")="\0.7\0"
	s ^TKSOLDES("73129")="\0.7\0"
	s ^TKSOLDES("73124")="\0.7\0"
	s ^TKSOLDES("82301")="\0.7\0"
	s ^TKSOLDES("82311")="\0.7\0"
	s ^TKSOLDES("41310")="\0.7\0"
	s ^TKSOLDES("41309")="\0.7\0"
	s ^TKSOLDES("78735")="\0.7\0"
	s ^TKSOLDES("78738")="\0.7\0"
	s ^TKSOLDES("78737")="\0.7\0"
	s ^TKSOLDES("78733")="\0.7\0"
	s ^TKSOLDES("78732")="\0.7\0"
	s ^TKSOLDES("78731")="\0.7\0"
	s ^TKSOLDES("76167")="\0.7\0"
	s ^TKSOLDES("82307")="\0.7\0"
	s ^TKSOLDES("82300")="\0.7\0"
	s ^TKSOLDES("82268")="\0.7\0"
	s ^TKSOLDES("78794")="\0.7\0"
	s ^TKSOLDES("78795")="\0.7\0"
	s ^TKSOLDES("82457")="\0.7\0"
	s ^TKSOLDES("82453")="\0.7\0"
	s ^TKSOLDES("82456")="\0.7\0"
	s ^TKSOLDES("82460")="\0.7\0"
	s ^TKSOLDES("82459")="\0.7\0"
	s ^TKSOLDES("82448")="\0.7\0"
	s ^TKSOLDES("82438")="\0.7\0"
	s ^TKSOLDES("82510")="\0.7\0"
	s ^TKSOLDES("82511")="\0.7\0"
	s ^TKSOLDES("82287")="\0.7\0"
	s ^TKSOLDES("82289")="\0.7\0"
	s ^TKSOLDES("82288")="\0.7\0"
	s ^TKSOLDES("102405")="\0.7\0"
	s ^TKSOLDES("103079")="\0.7\0"
	s ^TKSOLDES("102551")="\0.7\0"
	s ^TKSOLDES("101452")="\0.7\0"
	s ^TKSOLDES("103225")="\0.7\0"
	s ^TKSOLDES("103228")="\0.7\0"
	s ^TKSOLDES("103252")="\0.7\0"
	s ^TKSOLDES("103080")="\0.7\0"
	s ^TKSOLDES("103250")="\0.7\0"
	s ^TKSOLDES("103251")="\0.7\0"
	s ^TKSOLDES("103085")="\0.7\0"
	s ^TKSOLDES("55586")="\0.7\0"
	s ^TKSOLDES("103095")="\0.7\0"
	s ^TKSOLDES("103084")="\0.7\0"
	s ^TKSOLDES("87383")="\0.7\0"
	s ^TKSOLDES("101458")="\0.7\0"
	s ^TKSOLDES("68045")="\0.7\0"
	s ^TKSOLDES("68043")="\0.7\0"
	s ^TKSOLDES("68041")="\0.7\0"
	s ^TKSOLDES("68042")="\0.7\0"
	s ^TKSOLDES("86512")="\0.7\0"
	s ^TKSOLDES("86515")="\0.7\0"
	s ^TKSOLDES("78806")="\0.7\0"
	s ^TKSOLDES("78430")="\0.7\0"
	s ^TKSOLDES("78429")="\0.7\0"
	s ^TKSOLDES("78421")="\0.7\0"
	s ^TKSOLDES("78432")="\0.7\0"
	s ^TKSOLDES("76182")="\0.7\0"
	s ^TKSOLDES("67417")="\0.7\0"
	s ^TKSOLDES("70101")="\0.7\0"
	s ^TKSOLDES("70100")="\0.7\0"
	s ^TKSOLDES("67418")="\0.7\0"
	s ^TKSOLDES("82458")="\0.7\0"
	s ^TKSOLDES("87377")="\0.7\0"
	s ^TKSOLDES("44303")="\0.7\0"
	s ^TKSOLDES("105186")="\0.7\0"
	s ^TKSOLDES("102332")="\0.7\0"
	s ^TKSOLDES("53511")="\0.7\0"
	s ^TKSOLDES("53524")="\0.7\0"
	s ^TKSOLDES("8653")="\0.7\0"
	s ^TKSOLDES("55282")="\0.7\0"
	s ^TKSOLDES("8650")="\0.7\0"
	s ^TKSOLDES("40961")="\0.7\0"
	s ^TKSOLDES("87142")="\0.7\0"
	s ^TKSOLDES("87143")="\0.7\0"
	s ^TKSOLDES("75946")="\0.7\0"
	s ^TKSOLDES("78586")="\0.7\0"
	s ^TKSOLDES("78552")="\0.7\0"
	s ^TKSOLDES("78937")="\0.7\0"
	s ^TKSOLDES("78940")="\0.7\0"
	s ^TKSOLDES("78938")="\0.7\0"
	s ^TKSOLDES("78547")="\0.7\0"
	s ^TKSOLDES("78730")="\0.7\0"
	s ^TKSOLDES("79161")="\0.7\0"
	s ^TKSOLDES("78549")="\0.7\0"
	s ^TKSOLDES("78550")="\0.7\0"
	s ^TKSOLDES("87151")="\0.7\0"
	s ^TKSOLDES("87150")="\0.7\0"
	s ^TKSOLDES("87157")="\0.7\0"
	s ^TKSOLDES("101184")="\0.7\0"
	s ^TKSOLDES("86996")="\0.7\0"
	s ^TKSOLDES("79159")="\0.7\0"
	s ^TKSOLDES("78936")="\0.7\0"
	s ^TKSOLDES("78934")="\0.7\0"
	s ^TKSOLDES("87152")="\0.7\0"
	s ^TKSOLDES("87153")="\0.7\0"
	s ^TKSOLDES("86990")="\0.7\0"
	s ^TKSOLDES("78740")="\0.7\0"
	s ^TKSOLDES("78728")="\0.7\0"
	s ^TKSOLDES("78799")="\0.7\0"
	s ^TKSOLDES("78803")="\0.7\0"
	s ^TKSOLDES("82308")="\0.7\0"
	s ^TKSOLDES("82306")="\0.7\0"
	s ^TKSOLDES("82313")="\0.7\0"
	s ^TKSOLDES("82315")="\0.7\0"
	s ^TKSOLDES("82294")="\0.7\0"
	s ^TKSOLDES("82293")="\0.7\0"
	s ^TKSOLDES("82290")="\0.7\0"
	s ^TKSOLDES("82292")="\0.7\0"
	s ^TKSOLDES("41078")="\0.7\0"
	s ^TKSOLDES("105287")="\0.7\0"
	s ^TKSOLDES("103088")="\0.7\0"
	s ^TKSOLDES("103090")="\0.7\0"
	s ^TKSOLDES("103089")="\0.7\0"
	s ^TKSOLDES("103091")="\0.7\0"
	s ^TKSOLDES("103086")="\0.7\0"
	s ^TKSOLDES("87380")="\0.7\0"
	s ^TKSOLDES("44012")="\0.7\0"
	s ^TKSOLDES("75947")="\0.7\0"
	s ^TKSOLDES("40953")="\0.7\0"
	s ^TKSOLDES("82297")="\0.7\0"
	s ^TKSOLDES("62509")="\0.7\0"
	s ^TKSOLDES("76187")="\0.7\0"
	s ^TKSOLDES("87382")="\0.7\0"
	s ^TKSOLDES("41081")="\0.7\0"
	s ^TKSOLDES("78722")="\0.7\0"
	s ^TKSOLDES("76185")="\0.7\0"
	s ^TKSOLDES("78741")="\0.7\0"
	s ^TKSOLDES("75988")="\0.7\0"
	s ^TKSOLDES("78721")="\0.7\0"
	s ^TKSOLDES("82266")="\0.7\0"
	s ^TKSOLDES("87376")="\0.7\0"
	s ^TKSOLDES("87141")="\0.7\0"
	s ^TKSOLDES("82304")="\0.7\0"
	s ^TKSOLDES("87381")="\0.7\0"
	s ^TKSOLDES("76000")="\0.7\0"
	s ^TKSOLDES("82310")="\0.7\0"
	s ^TKSOLDES("105462")="\0.7\0"
	s ^TKSOLDES("105457")="\0.7\0"
	s ^TKSOLDES("76173")="\0.7\0"
	s ^TKSOLDES("76174")="\0.7\0"
	s ^TKSOLDES("76005")="\0.7\0"
	s ^TKSOLDES("82267")="\0.7\0"
	s ^TKSOLDES("103452")="\0.7\0"
	s ^TKSOLDES("1592")="\0.7\0"
	s ^TKSOLDES("9110")="\0.7\0"
	s ^TKSOLDES("3529")="\0.7\0"
	s ^TKSOLDES("87600")="\0.7\0"
	s ^TKSOLDES("1600")="\0.7\0"
	s ^TKSOLDES("106040")="\0.7\0"
	s ^TKSOLDES("76576")="\0.7\0"
	s ^TKSOLDES("79589")="\0.7\0"
	s ^TKSOLDES("103453")="\0.7\0"
	s ^TKSOLDES("79789")="\0.7\0"
	s ^TKSOLDES("54982")="\0.7\0"
	s ^TKSOLDES("1396")="\0.7\0"
	s ^TKSOLDES("3326")="\0.7\0"
	s ^TKSOLDES("3325")="\0.7\0"
	s ^TKSOLDES("3321")="\0.7\0"
	s ^TKSOLDES("3318")="\0.7\0"
	s ^TKSOLDES("82059")="\0.7\0"
	s ^TKSOLDES("79529")="\0.7\0"
	s ^TKSOLDES("4025")="\0.7\0"
	s ^TKSOLDES("79525")="\0.7\0"
	s ^TKSOLDES("103450")="\0.7\0"
	s ^TKSOLDES("103451")="\0.7\0"
	s ^TKSOLDES("103379")="\0.7\0"
	s ^TKSOLDES("103377")="\0.7\0"
	s ^TKSOLDES("103444")="\0.7\0"
	s ^TKSOLDES("79478")="\0.7\0"
	s ^TKSOLDES("79472")="\0.7\0"
	s ^TKSOLDES("87595")="\0.7\0"
	s ^TKSOLDES("83107")="\0.7\0"
	s ^TKSOLDES("79476")="\0.7\0"
	s ^TKSOLDES("79475")="\0.7\0"
	s ^TKSOLDES("41743")="\0.7\0"
	s ^TKSOLDES("41742")="\0.7\0"
	s ^TKSOLDES("53564")="\0.7\0"
	s ^TKSOLDES("1727")="\0.7\0"
	s ^TKSOLDES("87596")="\0.7\0"
	s ^TKSOLDES("83108")="\0.7\0"
	s ^TKSOLDES("54506")="\0.7\0"
	s ^TKSOLDES("87594")="\0.7\0"
	s ^TKSOLDES("87599")="\0.7\0"
	s ^TKSOLDES("50778")="\0.7\0"
	s ^TKSOLDES("87598")="\0.7\0"
	s ^TKSOLDES("78022")="\0.7\0"
	s ^TKSOLDES("1745")="\0.7\0"
	s ^TKSOLDES("88542")="\0.7\0"
	s ^TKSOLDES("77468")="\0.7\0"
	s ^TKSOLDES("64433")="\0.7\0"
	s ^TKSOLDES("87590")="\0.7\0"
	s ^TKSOLDES("54511")="\0.7\0"
	s ^TKSOLDES("54206")="\0.7\0"
	s ^TKSOLDES("76577")="\0.7\0"
	s ^TKSOLDES("87592")="\0.7\0"
	s ^TKSOLDES("103446")="\0.7\0"
	s ^TKSOLDES("50749")="\0.7\0"
	s ^TKSOLDES("64424")="\0.7\0"
	s ^TKSOLDES("79467")="\0.7\0"
	s ^TKSOLDES("6815")="\0.7\0"
	s ^TKSOLDES("87589")="\0.7\0"
	s ^TKSOLDES("45866")="\0.7\0"
	s ^TKSOLDES("45867")="\0.7\0"
	s ^TKSOLDES("103374")="\0.7\0"
	s ^TKSOLDES("103375")="\0.7\0"
	s ^TKSOLDES("45241")="\0.7\0"
	s ^TKSOLDES("45238")="\0.7\0"
	s ^TKSOLDES("45237")="\0.7\0"
	s ^TKSOLDES("54977")="\0.7\0"
	s ^TKSOLDES("82051")="\0.7\0"
	s ^TKSOLDES("82054")="\0.7\0"
	s ^TKSOLDES("54839")="\0.7\0"
	s ^TKSOLDES("54841")="\0.7\0"
	s ^TKSOLDES("54837")="\0.7\0"
	s ^TKSOLDES("54842")="\0.7\0"
	s ^TKSOLDES("2890")="\0.7\0"
	s ^TKSOLDES("2872")="\0.7\0"
	s ^TKSOLDES("54979")="\0.7\0"
	s ^TKSOLDES("54981")="\0.7\0"
	s ^TKSOLDES("54978")="\0.7\0"
	s ^TKSOLDES("54980")="\0.7\0"
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 