ROUTINE SOLDES70AH13M391
SOLDES70AH13M391	
 
 s ^TKSOLDES("1154")="\0.7\0"
 s ^TKSOLDES("1592")="\0.7\0"
 s ^TKSOLDES("1600")="\0.7\0"
 s ^TKSOLDES("2872")="\0.7\0"
 s ^TKSOLDES("2877")="\0.7\0"
 s ^TKSOLDES("2886")="\0.7\0"
 s ^TKSOLDES("2890")="\0.7\0"
 s ^TKSOLDES("3318")="\0.7\0"
 s ^TKSOLDES("3321")="\0.7\0"
 s ^TKSOLDES("3326")="\0.7\0"
 s ^TKSOLDES("3370")="\0.7\0"
 s ^TKSOLDES("3529")="\0.7\0"
 s ^TKSOLDES("3606")="\0.7\0"
 s ^TKSOLDES("3938")="\0.7\0"
 s ^TKSOLDES("7383")="\0.7\0"
 s ^TKSOLDES("7790")="\0.7\0"
 s ^TKSOLDES("7792")="\0.7\0"
 s ^TKSOLDES("8007")="\0.7\0"
 s ^TKSOLDES("8360")="\0.7\0"
 s ^TKSOLDES("8608")="\0.7\0"
 s ^TKSOLDES("9110")="\0.7\0"
 s ^TKSOLDES("37569")="\0.7\0"
 s ^TKSOLDES("41662")="\0.7\0"
 s ^TKSOLDES("41666")="\0.7\0"
 s ^TKSOLDES("41669")="\0.7\0"
 s ^TKSOLDES("41742")="\0.7\0"
 s ^TKSOLDES("41743")="\0.7\0"
 s ^TKSOLDES("41917")="\0.7\0"
 s ^TKSOLDES("45237")="\0.7\0"
 s ^TKSOLDES("45238")="\0.7\0"
 s ^TKSOLDES("45241")="\0.7\0"
 s ^TKSOLDES("50749")="\0.7\0"
 s ^TKSOLDES("50778")="\0.7\0"
 s ^TKSOLDES("51505")="\0.7\0"
 s ^TKSOLDES("53564")="\0.7\0"
 s ^TKSOLDES("54206")="\0.7\0"
 s ^TKSOLDES("54484")="\0.7\0"
 s ^TKSOLDES("54485")="\0.7\0"
 s ^TKSOLDES("54511")="\0.7\0"
 s ^TKSOLDES("54837")="\0.7\0"
 s ^TKSOLDES("54841")="\0.7\0"
 s ^TKSOLDES("54977")="\0.7\0"
 s ^TKSOLDES("54981")="\0.7\0"
 s ^TKSOLDES("56647")="\0.7\0"
 s ^TKSOLDES("59644")="\0.7\0"
 s ^TKSOLDES("63945")="\0.7\0"
 s ^TKSOLDES("64377")="\0.7\0"
 s ^TKSOLDES("64424")="\0.7\0"
 s ^TKSOLDES("64433")="\0.7\0"
 s ^TKSOLDES("66519")="\0.7\0"
 s ^TKSOLDES("66864")="\0.7\0"
 s ^TKSOLDES("67353")="\0.7\0"
 s ^TKSOLDES("72173")="\0.7\0"
 s ^TKSOLDES("72290")="\0.7\0"
 s ^TKSOLDES("73002")="\0.7\0"
 s ^TKSOLDES("73005")="\0.7\0"
 s ^TKSOLDES("74141")="\0.7\0"
 s ^TKSOLDES("74588")="\0.7\0"
 s ^TKSOLDES("74594")="\0.7\0"
 s ^TKSOLDES("74812")="\0.7\0"
 s ^TKSOLDES("74816")="\0.7\0"
 s ^TKSOLDES("75080")="\0.7\0"
 s ^TKSOLDES("75159")="\0.7\0"
 s ^TKSOLDES("75244")="\0.7\0"
 s ^TKSOLDES("76044")="\0.7\0"
 s ^TKSOLDES("76336")="\0.7\0"
 s ^TKSOLDES("76354")="\0.7\0"
 s ^TKSOLDES("76355")="\0.7\0"
 s ^TKSOLDES("76357")="\0.7\0"
 s ^TKSOLDES("76618")="\0.7\0"
 s ^TKSOLDES("76621")="\0.7\0"
 s ^TKSOLDES("76625")="\0.7\0"
 s ^TKSOLDES("76628")="\0.7\0"
 s ^TKSOLDES("76634")="\0.7\0"
 s ^TKSOLDES("76638")="\0.7\0"
 s ^TKSOLDES("76642")="\0.7\0"
 s ^TKSOLDES("76883")="\0.7\0"
 s ^TKSOLDES("76896")="\0.7\0"
 s ^TKSOLDES("77801")="\0.7\0"
 s ^TKSOLDES("77806")="\0.7\0"
 s ^TKSOLDES("79342")="\0.7\0"
 s ^TKSOLDES("79467")="\0.7\0"
 s ^TKSOLDES("79472")="\0.7\0"
 s ^TKSOLDES("79478")="\0.7\0"
 s ^TKSOLDES("79589")="\0.7\0"
 s ^TKSOLDES("79721")="\0.7\0"
 s ^TKSOLDES("79722")="\0.7\0"
 s ^TKSOLDES("79723")="\0.7\0"
 s ^TKSOLDES("79735")="\0.7\0"
 s ^TKSOLDES("79766")="\0.7\0"
 s ^TKSOLDES("79852")="\0.7\0"
 s ^TKSOLDES("79967")="\0.7\0"
 s ^TKSOLDES("79984")="\0.7\0"
 s ^TKSOLDES("80026")="\0.7\0"
 s ^TKSOLDES("80027")="\0.7\0"
 s ^TKSOLDES("80028")="\0.7\0"
 s ^TKSOLDES("80036")="\0.7\0"
 s ^TKSOLDES("80039")="\0.7\0"
 s ^TKSOLDES("81917")="\0.7\0"
 s ^TKSOLDES("83993")="\0.7\0"
 s ^TKSOLDES("85871")="\0.7\0"
 s ^TKSOLDES("85899")="\0.7\0"
 s ^TKSOLDES("86126")="\0.7\0"
 s ^TKSOLDES("86127")="\0.7\0"
 s ^TKSOLDES("86128")="\0.7\0"
 s ^TKSOLDES("86129")="\0.7\0"
 s ^TKSOLDES("86130")="\0.7\0"
 s ^TKSOLDES("86131")="\0.7\0"
 s ^TKSOLDES("86133")="\0.7\0"
 s ^TKSOLDES("86135")="\0.7\0"
 s ^TKSOLDES("86137")="\0.7\0"
 s ^TKSOLDES("86138")="\0.7\0"
 s ^TKSOLDES("86139")="\0.7\0"
 s ^TKSOLDES("86140")="\0.7\0"
 s ^TKSOLDES("86141")="\0.7\0"
 s ^TKSOLDES("86142")="\0.7\0"
 s ^TKSOLDES("86143")="\0.7\0"
 s ^TKSOLDES("86144")="\0.7\0"
 s ^TKSOLDES("86145")="\0.7\0"
 s ^TKSOLDES("86146")="\0.7\0"
 s ^TKSOLDES("86147")="\0.7\0"
 s ^TKSOLDES("86148")="\0.7\0"
 s ^TKSOLDES("86314")="\0.7\0"
 s ^TKSOLDES("86318")="\0.7\0"
 s ^TKSOLDES("86332")="\0.7\0"
 s ^TKSOLDES("86336")="\0.7\0"
 s ^TKSOLDES("86337")="\0.7\0"
 s ^TKSOLDES("86339")="\0.7\0"
 s ^TKSOLDES("86340")="\0.7\0"
 s ^TKSOLDES("86341")="\0.7\0"
 s ^TKSOLDES("86342")="\0.7\0"
 s ^TKSOLDES("86343")="\0.7\0"
 s ^TKSOLDES("86462")="\0.7\0"
 s ^TKSOLDES("86464")="\0.7\0"
 s ^TKSOLDES("86473")="\0.7\0"
 s ^TKSOLDES("86489")="\0.7\0"
 s ^TKSOLDES("86490")="\0.7\0"
 s ^TKSOLDES("86491")="\0.7\0"
 s ^TKSOLDES("86493")="\0.7\0"
 s ^TKSOLDES("86505")="\0.7\0"
 s ^TKSOLDES("86541")="\0.7\0"
 s ^TKSOLDES("86561")="\0.7\0"
 s ^TKSOLDES("86562")="\0.7\0"
 s ^TKSOLDES("86563")="\0.7\0"
 s ^TKSOLDES("86565")="\0.7\0"
 s ^TKSOLDES("86913")="\0.7\0"
 s ^TKSOLDES("86915")="\0.7\0"
 s ^TKSOLDES("86927")="\0.7\0"
 s ^TKSOLDES("86929")="\0.7\0"
 s ^TKSOLDES("86930")="\0.7\0"
 s ^TKSOLDES("86961")="\0.7\0"
 s ^TKSOLDES("86964")="\0.7\0"
 s ^TKSOLDES("86965")="\0.7\0"
 s ^TKSOLDES("86982")="\0.7\0"
 s ^TKSOLDES("86986")="\0.7\0"
 s ^TKSOLDES("86987")="\0.7\0"
 s ^TKSOLDES("86988")="\0.7\0"
 s ^TKSOLDES("86989")="\0.7\0"
 s ^TKSOLDES("87264")="\0.7\0"
 s ^TKSOLDES("87265")="\0.7\0"
 s ^TKSOLDES("87274")="\0.7\0"
 s ^TKSOLDES("87483")="\0.7\0"
 s ^TKSOLDES("87484")="\0.7\0"
 s ^TKSOLDES("87485")="\0.7\0"
 s ^TKSOLDES("87486")="\0.7\0"
 s ^TKSOLDES("87487")="\0.7\0"
 s ^TKSOLDES("87586")="\0.7\0"
 s ^TKSOLDES("87634")="\0.7\0"
 s ^TKSOLDES("88192")="\0.7\0"
 s ^TKSOLDES("88355")="\0.7\0"
 s ^TKSOLDES("88356")="\0.7\0"
 s ^TKSOLDES("100786")="\0.7\0"
 s ^TKSOLDES("100815")="\0.7\0"
 s ^TKSOLDES("100937")="\0.7\0"
 s ^TKSOLDES("101051")="\0.7\0"
 s ^TKSOLDES("101062")="\0.7\0"
 s ^TKSOLDES("101072")="\0.7\0"
 s ^TKSOLDES("101791")="\0.7\0"
 s ^TKSOLDES("101792")="\0.7\0"
 s ^TKSOLDES("101799")="\0.7\0"
 s ^TKSOLDES("101800")="\0.7\0"
 s ^TKSOLDES("101801")="\0.7\0"
 s ^TKSOLDES("101822")="\0.7\0"
 s ^TKSOLDES("101824")="\0.7\0"
 s ^TKSOLDES("101840")="\0.7\0"
 s ^TKSOLDES("101842")="\0.7\0"
 s ^TKSOLDES("101865")="\0.7\0"
 s ^TKSOLDES("101868")="\0.7\0"
 s ^TKSOLDES("101875")="\0.7\0"
 s ^TKSOLDES("101878")="\0.7\0"
 s ^TKSOLDES("101890")="\0.7\0"
 s ^TKSOLDES("101891")="\0.7\0"
 s ^TKSOLDES("101914")="\0.7\0"
 s ^TKSOLDES("101916")="\0.7\0"
 s ^TKSOLDES("101938")="\0.7\0"
 s ^TKSOLDES("101953")="\0.7\0"
 s ^TKSOLDES("101954")="\0.7\0"
 s ^TKSOLDES("101955")="\0.7\0"
 s ^TKSOLDES("101956")="\0.7\0"
 s ^TKSOLDES("101957")="\0.7\0"
 s ^TKSOLDES("101958")="\0.7\0"
 s ^TKSOLDES("101962")="\0.7\0"
 s ^TKSOLDES("101964")="\0.7\0"
 s ^TKSOLDES("101980")="\0.7\0"
 s ^TKSOLDES("101981")="\0.7\0"
 s ^TKSOLDES("101991")="\0.7\0"
 s ^TKSOLDES("101994")="\0.7\0"
 s ^TKSOLDES("102120")="\0.7\0"
 s ^TKSOLDES("102121")="\0.7\0"
 s ^TKSOLDES("102124")="\0.7\0"
 s ^TKSOLDES("102125")="\0.7\0"
 s ^TKSOLDES("102126")="\0.7\0"
 s ^TKSOLDES("102127")="\0.7\0"
 s ^TKSOLDES("102130")="\0.7\0"
 s ^TKSOLDES("102131")="\0.7\0"
 s ^TKSOLDES("102138")="\0.7\0"
 s ^TKSOLDES("102139")="\0.7\0"
 s ^TKSOLDES("102140")="\0.7\0"
 s ^TKSOLDES("102141")="\0.7\0"
 s ^TKSOLDES("102145")="\0.7\0"
 s ^TKSOLDES("102146")="\0.7\0"
 s ^TKSOLDES("102147")="\0.7\0"
 s ^TKSOLDES("102148")="\0.7\0"
 s ^TKSOLDES("102151")="\0.7\0"
 s ^TKSOLDES("102154")="\0.7\0"
 s ^TKSOLDES("102156")="\0.7\0"
 s ^TKSOLDES("102157")="\0.7\0"
 s ^TKSOLDES("102161")="\0.7\0"
 s ^TKSOLDES("102162")="\0.7\0"
 s ^TKSOLDES("102163")="\0.7\0"
 s ^TKSOLDES("102164")="\0.7\0"
 s ^TKSOLDES("102165")="\0.7\0"
 s ^TKSOLDES("102166")="\0.7\0"
 s ^TKSOLDES("102167")="\0.7\0"
 s ^TKSOLDES("102168")="\0.7\0"
 s ^TKSOLDES("102169")="\0.7\0"
 s ^TKSOLDES("102170")="\0.7\0"
 s ^TKSOLDES("102426")="\0.7\0"
 s ^TKSOLDES("102442")="\0.7\0"
 s ^TKSOLDES("102443")="\0.7\0"
 s ^TKSOLDES("102445")="\0.7\0"
 s ^TKSOLDES("102529")="\0.7\0"
 s ^TKSOLDES("102531")="\0.7\0"
 s ^TKSOLDES("102532")="\0.7\0"
 s ^TKSOLDES("102535")="\0.7\0"
 s ^TKSOLDES("103486")="\0.7\0"
 s ^TKSOLDES("103686")="\0.7\0"
 s ^TKSOLDES("103687")="\0.7\0"
 s ^TKSOLDES("103688")="\0.7\0"
 s ^TKSOLDES("103689")="\0.7\0"
 s ^TKSOLDES("103690")="\0.7\0"
 s ^TKSOLDES("103691")="\0.7\0"
 s ^TKSOLDES("103692")="\0.7\0"
 s ^TKSOLDES("103694")="\0.7\0"
 s ^TKSOLDES("103695")="\0.7\0"
 s ^TKSOLDES("103696")="\0.7\0"
 s ^TKSOLDES("103697")="\0.7\0"
 s ^TKSOLDES("103698")="\0.7\0"
 s ^TKSOLDES("103699")="\0.7\0"
 s ^TKSOLDES("103700")="\0.7\0"
 s ^TKSOLDES("103701")="\0.7\0"
 s ^TKSOLDES("104020")="\0.7\0"
 s ^TKSOLDES("104021")="\0.7\0"
 s ^TKSOLDES("105555")="\0.7\0"
 s ^TKSOLDES("105557")="\0.7\0"
 s ^TKSOLDES("105558")="\0.7\0"
 s ^TKSOLDES("105560")="\0.7\0"
 s ^TKSOLDES("105561")="\0.7\0"
 s ^TKSOLDES("105562")="\0.7\0"
 s ^TKSOLDES("105563")="\0.7\0"
 s ^TKSOLDES("105564")="\0.7\0"
 s ^TKSOLDES("105565")="\0.7\0"
 s ^TKSOLDES("105566")="\0.7\0"
 s ^TKSOLDES("105567")="\0.7\0"
 s ^TKSOLDES("105568")="\0.7\0"
 s ^TKSOLDES("105569")="\0.7\0"
 s ^TKSOLDES("105570")="\0.7\0"
 s ^TKSOLDES("105571")="\0.7\0"
 s ^TKSOLDES("105572")="\0.7\0"
 s ^TKSOLDES("105573")="\0.7\0"
 s ^TKSOLDES("105753")="\0.7\0"
 s ^TKSOLDES("107731")="\0.7\0"
 s ^TKSOLDES("107943")="\0.7\0"
 s ^TKSOLDES("107944")="\0.7\0"
 s ^TKSOLDES("107945")="\0.7\0"
 s ^TKSOLDES("107946")="\0.7\0"
 s ^TKSOLDES("107947")="\0.7\0"
 s ^TKSOLDES("107948")="\0.7\0"
 s ^TKSOLDES("110511")="\0.7\0"
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 