ROUTINE SOLDES70AH13M391C6
SOLDES70AH13M391C6
 
	s ^TKSOLDES("14552")="\0.7\0"
	s ^TKSOLDES("14553")="\0.7\0"
	s ^TKSOLDES("14562")="\0.7\0"
	s ^TKSOLDES("14673")="\0.7\0"
	s ^TKSOLDES("14674")="\0.7\0"
	s ^TKSOLDES("14763")="\0.7\0"
	s ^TKSOLDES("14765")="\0.7\0"
	s ^TKSOLDES("14778")="\0.7\0"
	s ^TKSOLDES("14780")="\0.7\0"
	s ^TKSOLDES("14784")="\0.7\0"
	s ^TKSOLDES("14790")="\0.7\0"
	s ^TKSOLDES("14795")="\0.7\0"
	s ^TKSOLDES("14796")="\0.7\0"
	s ^TKSOLDES("14802")="\0.7\0"
	s ^TKSOLDES("14808")="\0.7\0"
	s ^TKSOLDES("14820")="\0.7\0"
	s ^TKSOLDES("14827")="\0.7\0"
	s ^TKSOLDES("14901")="\0.7\0"
	s ^TKSOLDES("15014")="\0.7\0"
	s ^TKSOLDES("15032")="\0.7\0"
	s ^TKSOLDES("15057")="\0.7\0"
	s ^TKSOLDES("15093")="\0.7\0"
	s ^TKSOLDES("15094")="\0.7\0"
	s ^TKSOLDES("15188")="\0.7\0"
	s ^TKSOLDES("15192")="\0.7\0"
	s ^TKSOLDES("15203")="\0.7\0"
	s ^TKSOLDES("15284")="\0.7\0"
	s ^TKSOLDES("15286")="\0.7\0"
	s ^TKSOLDES("15293")="\0.7\0"
	s ^TKSOLDES("15302")="\0.7\0"
	s ^TKSOLDES("15326")="\0.7\0"
	s ^TKSOLDES("15331")="\0.7\0"
	s ^TKSOLDES("15341")="\0.7\0"
	s ^TKSOLDES("15439")="\0.7\0"
	s ^TKSOLDES("15456")="\0.7\0"
	s ^TKSOLDES("15485")="\0.7\0"
	s ^TKSOLDES("15494")="\0.7\0"
	s ^TKSOLDES("15500")="\0.7\0"
	s ^TKSOLDES("15505")="\0.7\0"
	s ^TKSOLDES("15510")="\0.7\0"
	s ^TKSOLDES("15525")="\0.7\0"
	s ^TKSOLDES("15539")="\0.7\0"
	s ^TKSOLDES("15543")="\0.7\0"
	s ^TKSOLDES("15574")="\0.7\0"
	s ^TKSOLDES("15634")="\0.7\0"
	s ^TKSOLDES("15715")="\0.7\0"
	s ^TKSOLDES("16059")="\0.7\0"
	s ^TKSOLDES("16113")="\0.7\0"
	s ^TKSOLDES("16117")="\0.7\0"
	s ^TKSOLDES("16131")="\0.7\0"
	s ^TKSOLDES("16289")="\0.7\0"
	s ^TKSOLDES("16406")="\0.7\0"
	s ^TKSOLDES("16627")="\0.7\0"
	s ^TKSOLDES("16672")="\0.7\0"
	s ^TKSOLDES("17721")="\0.7\0"
	s ^TKSOLDES("18210")="\0.7\0"
	s ^TKSOLDES("18225")="\0.7\0"
	s ^TKSOLDES("18261")="\0.7\0"
	s ^TKSOLDES("18266")="\0.7\0"
	s ^TKSOLDES("18329")="\0.7\0"
	s ^TKSOLDES("18341")="\0.7\0"
	s ^TKSOLDES("18400")="\0.7\0"
	s ^TKSOLDES("18402")="\0.7\0"
	s ^TKSOLDES("18408")="\0.7\0"
	s ^TKSOLDES("18416")="\0.7\0"
	s ^TKSOLDES("35082")="\0.7\0"
	s ^TKSOLDES("35232")="\0.7\0"
	s ^TKSOLDES("90780")="\0.7\0"
	s ^TKSOLDES("12598")="\0.7\0"
	s ^TKSOLDES("12605")="\0.7\0"
	s ^TKSOLDES("13356")="\0.7\0"
	s ^TKSOLDES("13636")="\0.7\0"
	s ^TKSOLDES("13655")="\0.7\0"
	s ^TKSOLDES("13662")="\0.7\0"
	s ^TKSOLDES("13678")="\0.7\0"
	s ^TKSOLDES("13711")="\0.7\0"
	s ^TKSOLDES("13726")="\0.7\0"
	s ^TKSOLDES("13748")="\0.7\0"
	s ^TKSOLDES("14156")="\0.7\0"
	s ^TKSOLDES("16661")="\0.7\0"
	s ^TKSOLDES("16741")="\0.7\0"
	s ^TKSOLDES("16745")="\0.7\0"
	s ^TKSOLDES("16750")="\0.7\0"
	s ^TKSOLDES("17187")="\0.7\0"
	s ^TKSOLDES("17188")="\0.7\0"
	s ^TKSOLDES("17480")="\0.7\0"
	s ^TKSOLDES("17509")="\0.7\0"
	s ^TKSOLDES("17510")="\0.7\0"
	s ^TKSOLDES("17523")="\0.7\0"
	s ^TKSOLDES("17584")="\0.7\0"
	s ^TKSOLDES("17591")="\0.7\0"
	s ^TKSOLDES("17660")="\0.7\0"
	s ^TKSOLDES("17690")="\0.7\0"
	s ^TKSOLDES("34910")="\0.7\0"
	s ^TKSOLDES("34914")="\0.7\0"
	s ^TKSOLDES("35111")="\0.7\0"
	s ^TKSOLDES("35120")="\0.7\0"
	s ^TKSOLDES("35122")="\0.7\0"
	s ^TKSOLDES("35536")="\0.7\0"
	s ^TKSOLDES("36009")="\0.7\0"
	s ^TKSOLDES("36011")="\0.7\0"
	s ^TKSOLDES("36015")="\0.7\0"
	s ^TKSOLDES("36016")="\0.7\0"
	s ^TKSOLDES("36036")="\0.7\0"
	s ^TKSOLDES("37232")="\0.7\0"
	s ^TKSOLDES("37356")="\0.7\0"
	s ^TKSOLDES("37357")="\0.7\0"
	s ^TKSOLDES("38325")="\0.7\0"
	s ^TKSOLDES("38338")="\0.7\0"
	s ^TKSOLDES("38348")="\0.7\0"
	s ^TKSOLDES("38362")="\0.7\0"
	s ^TKSOLDES("38384")="\0.7\0"
	s ^TKSOLDES("38390")="\0.7\0"
	s ^TKSOLDES("38409")="\0.7\0"
	s ^TKSOLDES("38417")="\0.7\0"
	s ^TKSOLDES("38429")="\0.7\0"
	s ^TKSOLDES("38451")="\0.7\0"
	s ^TKSOLDES("38457")="\0.7\0"
	s ^TKSOLDES("38470")="\0.7\0"
	s ^TKSOLDES("40418")="\0.7\0"
	s ^TKSOLDES("41173")="\0.7\0"
	s ^TKSOLDES("41276")="\0.7\0"
	s ^TKSOLDES("41307")="\0.7\0"
	s ^TKSOLDES("41655")="\0.7\0"
	s ^TKSOLDES("41661")="\0.7\0"
	s ^TKSOLDES("41784")="\0.7\0"
	s ^TKSOLDES("41787")="\0.7\0"
	s ^TKSOLDES("41808")="\0.7\0"
	s ^TKSOLDES("41809")="\0.7\0"
	s ^TKSOLDES("41812")="\0.7\0"
	s ^TKSOLDES("41817")="\0.7\0"
	s ^TKSOLDES("41831")="\0.7\0"
	s ^TKSOLDES("41834")="\0.7\0"
	s ^TKSOLDES("41835")="\0.7\0"
	s ^TKSOLDES("41836")="\0.7\0"
	s ^TKSOLDES("41845")="\0.7\0"
	s ^TKSOLDES("41847")="\0.7\0"
	s ^TKSOLDES("41868")="\0.7\0"
	s ^TKSOLDES("41873")="\0.7\0"
	s ^TKSOLDES("41877")="\0.7\0"
	s ^TKSOLDES("41890")="\0.7\0"
	s ^TKSOLDES("41897")="\0.7\0"
	s ^TKSOLDES("41900")="\0.7\0"
	s ^TKSOLDES("41909")="\0.7\0"
	s ^TKSOLDES("41935")="\0.7\0"
	s ^TKSOLDES("41948")="\0.7\0"
	s ^TKSOLDES("41953")="\0.7\0"
	s ^TKSOLDES("41972")="\0.7\0"
	s ^TKSOLDES("41974")="\0.7\0"
	s ^TKSOLDES("42050")="\0.7\0"
	s ^TKSOLDES("42129")="\0.7\0"
	s ^TKSOLDES("42134")="\0.7\0"
	s ^TKSOLDES("42142")="\0.7\0"
	s ^TKSOLDES("42150")="\0.7\0"
	s ^TKSOLDES("42151")="\0.7\0"
	s ^TKSOLDES("42152")="\0.7\0"
	s ^TKSOLDES("42164")="\0.7\0"
	s ^TKSOLDES("42171")="\0.7\0"
	s ^TKSOLDES("42187")="\0.7\0"
	s ^TKSOLDES("42192")="\0.7\0"
	s ^TKSOLDES("42212")="\0.7\0"
	s ^TKSOLDES("42225")="\0.7\0"
	s ^TKSOLDES("42255")="\0.7\0"
	s ^TKSOLDES("42261")="\0.7\0"
	s ^TKSOLDES("42266")="\0.7\0"
	s ^TKSOLDES("42271")="\0.7\0"
	s ^TKSOLDES("42280")="\0.7\0"
	s ^TKSOLDES("42307")="\0.7\0"
	s ^TKSOLDES("42351")="\0.7\0"
	s ^TKSOLDES("42408")="\0.7\0"
	s ^TKSOLDES("42427")="\0.7\0"
	s ^TKSOLDES("42610")="\0.7\0"
	s ^TKSOLDES("42616")="\0.7\0"
	s ^TKSOLDES("42834")="\0.7\0"
	s ^TKSOLDES("42862")="\0.7\0"
	s ^TKSOLDES("43106")="\0.7\0"
	s ^TKSOLDES("43119")="\0.7\0"
	s ^TKSOLDES("43146")="\0.7\0"
	s ^TKSOLDES("43233")="\0.7\0"
	s ^TKSOLDES("43243")="\0.7\0"
	s ^TKSOLDES("43255")="\0.7\0"
	s ^TKSOLDES("43256")="\0.7\0"
	s ^TKSOLDES("43257")="\0.7\0"
	s ^TKSOLDES("43276")="\0.7\0"
	s ^TKSOLDES("43285")="\0.7\0"
	s ^TKSOLDES("43837")="\0.7\0"
	s ^TKSOLDES("43841")="\0.7\0"
	s ^TKSOLDES("44075")="\0.7\0"
	s ^TKSOLDES("44091")="\0.7\0"
	s ^TKSOLDES("44144")="\0.7\0"
	s ^TKSOLDES("44261")="\0.7\0"
	s ^TKSOLDES("44271")="\0.7\0"
	s ^TKSOLDES("44273")="\0.7\0"
	s ^TKSOLDES("44276")="\0.7\0"
	s ^TKSOLDES("44293")="\0.7\0"
	s ^TKSOLDES("44296")="\0.7\0"
	s ^TKSOLDES("44301")="\0.7\0"
	s ^TKSOLDES("44680")="\0.7\0"
	s ^TKSOLDES("45699")="\0.7\0"
	s ^TKSOLDES("45711")="\0.7\0"
	s ^TKSOLDES("45717")="\0.7\0"
	s ^TKSOLDES("45784")="\0.7\0"
	s ^TKSOLDES("45787")="\0.7\0"
	s ^TKSOLDES("45789")="\0.7\0"
	s ^TKSOLDES("45792")="\0.7\0"
	s ^TKSOLDES("45796")="\0.7\0"
	s ^TKSOLDES("45815")="\0.7\0"
	s ^TKSOLDES("45818")="\0.7\0"
	s ^TKSOLDES("45829")="\0.7\0"
	s ^TKSOLDES("46033")="\0.7\0"
	s ^TKSOLDES("46034")="\0.7\0"
	s ^TKSOLDES("46036")="\0.7\0"
	s ^TKSOLDES("46037")="\0.7\0"
	s ^TKSOLDES("46043")="\0.7\0"
	s ^TKSOLDES("46110")="\0.7\0"
	s ^TKSOLDES("46127")="\0.7\0"
	s ^TKSOLDES("46132")="\0.7\0"
	s ^TKSOLDES("46156")="\0.7\0"
	s ^TKSOLDES("46179")="\0.7\0"
	s ^TKSOLDES("46183")="\0.7\0"
	s ^TKSOLDES("46184")="\0.7\0"
	s ^TKSOLDES("46186")="\0.7\0"
	s ^TKSOLDES("46189")="\0.7\0"
	s ^TKSOLDES("46197")="\0.7\0"
	s ^TKSOLDES("46206")="\0.7\0"
	s ^TKSOLDES("46208")="\0.7\0"
	s ^TKSOLDES("46213")="\0.7\0"
	s ^TKSOLDES("46299")="\0.7\0"
	s ^TKSOLDES("46317")="\0.7\0"
	s ^TKSOLDES("46318")="\0.7\0"
	s ^TKSOLDES("46321")="\0.7\0"
	s ^TKSOLDES("46344")="\0.7\0"
	s ^TKSOLDES("46352")="\0.7\0"
	s ^TKSOLDES("46381")="\0.7\0"
	s ^TKSOLDES("46420")="\0.7\0"
	s ^TKSOLDES("46465")="\0.7\0"
	s ^TKSOLDES("46480")="\0.7\0"
	s ^TKSOLDES("46483")="\0.7\0"
	s ^TKSOLDES("46486")="\0.7\0"
	s ^TKSOLDES("46564")="\0.7\0"
	s ^TKSOLDES("46836")="\0.7\0"
	s ^TKSOLDES("46838")="\0.7\0"
	s ^TKSOLDES("46850")="\0.7\0"
	s ^TKSOLDES("47038")="\0.7\0"
	s ^TKSOLDES("47100")="\0.7\0"
	s ^TKSOLDES("47129")="\0.7\0"
	s ^TKSOLDES("47130")="\0.7\0"
	s ^TKSOLDES("47133")="\0.7\0"
	s ^TKSOLDES("47306")="\0.7\0"
	s ^TKSOLDES("47723")="\0.7\0"
	s ^TKSOLDES("47728")="\0.7\0"
	s ^TKSOLDES("47734")="\0.7\0"
	s ^TKSOLDES("47745")="\0.7\0"
	s ^TKSOLDES("47930")="\0.7\0"
	s ^TKSOLDES("48744")="\0.7\0"
	s ^TKSOLDES("48819")="\0.7\0"
	s ^TKSOLDES("48892")="\0.7\0"
	s ^TKSOLDES("48896")="\0.7\0"
	s ^TKSOLDES("48906")="\0.7\0"
	s ^TKSOLDES("48948")="\0.7\0"
	s ^TKSOLDES("48957")="\0.7\0"
	s ^TKSOLDES("49036")="\0.7\0"
	s ^TKSOLDES("49074")="\0.7\0"
	s ^TKSOLDES("49144")="\0.7\0"
	s ^TKSOLDES("49151")="\0.7\0"
	s ^TKSOLDES("49158")="\0.7\0"
	s ^TKSOLDES("49168")="\0.7\0"
	s ^TKSOLDES("49194")="\0.7\0"
	s ^TKSOLDES("49199")="\0.7\0"
	s ^TKSOLDES("49366")="\0.7\0"
	s ^TKSOLDES("49367")="\0.7\0"
	s ^TKSOLDES("49372")="\0.7\0"
	s ^TKSOLDES("49373")="\0.7\0"
	s ^TKSOLDES("49398")="\0.7\0"
	s ^TKSOLDES("49411")="\0.7\0"
	s ^TKSOLDES("49417")="\0.7\0"
	s ^TKSOLDES("50676")="\0.7\0"
	s ^TKSOLDES("50679")="\0.7\0"
	s ^TKSOLDES("50682")="\0.7\0"
	s ^TKSOLDES("50753")="\0.7\0"
	s ^TKSOLDES("50806")="\0.7\0"
	s ^TKSOLDES("51261")="\0.7\0"
	s ^TKSOLDES("51268")="\0.7\0"
	s ^TKSOLDES("51316")="\0.7\0"
	s ^TKSOLDES("51323")="\0.7\0"
	s ^TKSOLDES("51334")="\0.7\0"
	s ^TKSOLDES("51813")="\0.7\0"
	s ^TKSOLDES("52156")="\0.7\0"
	s ^TKSOLDES("52170")="\0.7\0"
	s ^TKSOLDES("52176")="\0.7\0"
	s ^TKSOLDES("52361")="\0.7\0"
	s ^TKSOLDES("53161")="\0.7\0"
	s ^TKSOLDES("53163")="\0.7\0"
	s ^TKSOLDES("53275")="\0.7\0"
	s ^TKSOLDES("53277")="\0.7\0"
	s ^TKSOLDES("53502")="\0.7\0"
	s ^TKSOLDES("53712")="\0.7\0"
	s ^TKSOLDES("53746")="\0.7\0"
	s ^TKSOLDES("53773")="\0.7\0"
	s ^TKSOLDES("53778")="\0.7\0"
	s ^TKSOLDES("53831")="\0.7\0"
	s ^TKSOLDES("53855")="\0.7\0"
	s ^TKSOLDES("53996")="\0.7\0"
	s ^TKSOLDES("53997")="\0.7\0"
	s ^TKSOLDES("54114")="\0.7\0"
	s ^TKSOLDES("54156")="\0.7\0"
	s ^TKSOLDES("54167")="\0.7\0"
	s ^TKSOLDES("54190")="\0.7\0"
	s ^TKSOLDES("54216")="\0.7\0"
	s ^TKSOLDES("54782")="\0.7\0"
	s ^TKSOLDES("54873")="\0.7\0"
	s ^TKSOLDES("93006")="\0.7\0"
	s ^TKSOLDES("55606")="\0.7\0"
	s ^TKSOLDES("55647")="\0.7\0"
	s ^TKSOLDES("55654")="\0.7\0"
	s ^TKSOLDES("55669")="\0.7\0"
	s ^TKSOLDES("55676")="\0.7\0"
	s ^TKSOLDES("55680")="\0.7\0"
	s ^TKSOLDES("55698")="\0.7\0"
	s ^TKSOLDES("56110")="\0.7\0"
	s ^TKSOLDES("56128")="\0.7\0"
	s ^TKSOLDES("56680")="\0.7\0"
	s ^TKSOLDES("56689")="\0.7\0"
	s ^TKSOLDES("56704")="\0.7\0"
	s ^TKSOLDES("56728")="\0.7\0"
	s ^TKSOLDES("56768")="\0.7\0"
	s ^TKSOLDES("56972")="\0.7\0"
	s ^TKSOLDES("56986")="\0.7\0"
	s ^TKSOLDES("57021")="\0.7\0"
	s ^TKSOLDES("57052")="\0.7\0"
	s ^TKSOLDES("57073")="\0.7\0"
	s ^TKSOLDES("57075")="\0.7\0"
	s ^TKSOLDES("57126")="\0.7\0"
	s ^TKSOLDES("57297")="\0.7\0"
	s ^TKSOLDES("57310")="\0.7\0"
	s ^TKSOLDES("57997")="\0.7\0"
	s ^TKSOLDES("58009")="\0.7\0"
	s ^TKSOLDES("58052")="\0.7\0"
	s ^TKSOLDES("58053")="\0.7\0"
	s ^TKSOLDES("58055")="\0.7\0"
	s ^TKSOLDES("58066")="\0.7\0"
	s ^TKSOLDES("58068")="\0.7\0"
	s ^TKSOLDES("58071")="\0.7\0"
	s ^TKSOLDES("58073")="\0.7\0"
	s ^TKSOLDES("58390")="\0.7\0"
	s ^TKSOLDES("58393")="\0.7\0"
	s ^TKSOLDES("58610")="\0.7\0"
	s ^TKSOLDES("58699")="\0.7\0"
	s ^TKSOLDES("58704")="\0.7\0"
	s ^TKSOLDES("58706")="\0.7\0"
	s ^TKSOLDES("59000")="\0.7\0"
	s ^TKSOLDES("59144")="\0.7\0"
	s ^TKSOLDES("59167")="\0.7\0"
	s ^TKSOLDES("59335")="\0.7\0"
	s ^TKSOLDES("60564")="\0.7\0"
	s ^TKSOLDES("60566")="\0.7\0"
	s ^TKSOLDES("60676")="\0.7\0"
	s ^TKSOLDES("60870")="\0.7\0"
	s ^TKSOLDES("61542")="\0.7\0"
	s ^TKSOLDES("62230")="\0.7\0"
	s ^TKSOLDES("62252")="\0.7\0"
	s ^TKSOLDES("62515")="\0.7\0"
	s ^TKSOLDES("63341")="\0.7\0"
	s ^TKSOLDES("63344")="\0.7\0"
	s ^TKSOLDES("63382")="\0.7\0"
	s ^TKSOLDES("63415")="\0.7\0"
	s ^TKSOLDES("63683")="\0.7\0"
	s ^TKSOLDES("63712")="\0.7\0"
	s ^TKSOLDES("63713")="\0.7\0"
	s ^TKSOLDES("63714")="\0.7\0"
	s ^TKSOLDES("63716")="\0.7\0"
	s ^TKSOLDES("63717")="\0.7\0"
	s ^TKSOLDES("63734")="\0.7\0"
	s ^TKSOLDES("63868")="\0.7\0"
	s ^TKSOLDES("63999")="\0.7\0"
	s ^TKSOLDES("64024")="\0.7\0"
	s ^TKSOLDES("64034")="\0.7\0"
	s ^TKSOLDES("64043")="\0.7\0"
	s ^TKSOLDES("64213")="\0.7\0"
	s ^TKSOLDES("64315")="\0.7\0"
	s ^TKSOLDES("93072")="\0.7\0"
	s ^TKSOLDES("93388")="\0.7\0"
	s ^TKSOLDES("64750")="\0.7\0"
	s ^TKSOLDES("64942")="\0.7\0"
	s ^TKSOLDES("65216")="\0.7\0"
	s ^TKSOLDES("65224")="\0.7\0"
	s ^TKSOLDES("65231")="\0.7\0"
	s ^TKSOLDES("65296")="\0.7\0"
	s ^TKSOLDES("65569")="\0.7\0"
	s ^TKSOLDES("65582")="\0.7\0"
	s ^TKSOLDES("65608")="\0.7\0"
	s ^TKSOLDES("65610")="\0.7\0"
	s ^TKSOLDES("65730")="\0.7\0"
	s ^TKSOLDES("65750")="\0.7\0"
	s ^TKSOLDES("65762")="\0.7\0"
	s ^TKSOLDES("65866")="\0.7\0"
	s ^TKSOLDES("65906")="\0.7\0"
	s ^TKSOLDES("65909")="\0.7\0"
	s ^TKSOLDES("65924")="\0.7\0"
	s ^TKSOLDES("65933")="\0.7\0"
	s ^TKSOLDES("65944")="\0.7\0"
	s ^TKSOLDES("65964")="\0.7\0"
	s ^TKSOLDES("65972")="\0.7\0"
	s ^TKSOLDES("66026")="\0.7\0"
	s ^TKSOLDES("66028")="\0.7\0"
	s ^TKSOLDES("66029")="\0.7\0"
	s ^TKSOLDES("66036")="\0.7\0"
	s ^TKSOLDES("66050")="\0.7\0"
	s ^TKSOLDES("66128")="\0.7\0"
	s ^TKSOLDES("66154")="\0.7\0"
	s ^TKSOLDES("66156")="\0.7\0"
	s ^TKSOLDES("67494")="\0.7\0"
	s ^TKSOLDES("67654")="\0.7\0"
	s ^TKSOLDES("67661")="\0.7\0"
	s ^TKSOLDES("67944")="\0.7\0"
	s ^TKSOLDES("68062")="\0.7\0"
	s ^TKSOLDES("68087")="\0.7\0"
	s ^TKSOLDES("68097")="\0.7\0"
	s ^TKSOLDES("68102")="\0.7\0"
	s ^TKSOLDES("68103")="\0.7\0"
	s ^TKSOLDES("68121")="\0.7\0"
	s ^TKSOLDES("68164")="\0.7\0"
	s ^TKSOLDES("69217")="\0.7\0"
	s ^TKSOLDES("69218")="\0.7\0"
	s ^TKSOLDES("69219")="\0.7\0"
	s ^TKSOLDES("70338")="\0.7\0"
	s ^TKSOLDES("70345")="\0.7\0"
	s ^TKSOLDES("70355")="\0.7\0"
	s ^TKSOLDES("70381")="\0.7\0"
	s ^TKSOLDES("70385")="\0.7\0"
	s ^TKSOLDES("70412")="\0.7\0"
	s ^TKSOLDES("70414")="\0.7\0"
	s ^TKSOLDES("70418")="\0.7\0"
	s ^TKSOLDES("70426")="\0.7\0"
	s ^TKSOLDES("70447")="\0.7\0"
	s ^TKSOLDES("70655")="\0.7\0"
	s ^TKSOLDES("70665")="\0.7\0"
	s ^TKSOLDES("70706")="\0.7\0"
	s ^TKSOLDES("70717")="\0.7\0"
	s ^TKSOLDES("70848")="\0.7\0"
	s ^TKSOLDES("70968")="\0.7\0"
	s ^TKSOLDES("71726")="\0.7\0"
	s ^TKSOLDES("72159")="\0.7\0"
	s ^TKSOLDES("93425")="\0.7\0"
	s ^TKSOLDES("72851")="\0.7\0"
	s ^TKSOLDES("72913")="\0.7\0"
	s ^TKSOLDES("72994")="\0.7\0"
	s ^TKSOLDES("73034")="\0.7\0"
	s ^TKSOLDES("73046")="\0.7\0"
	s ^TKSOLDES("73049")="\0.7\0"
	s ^TKSOLDES("73537")="\0.7\0"
	s ^TKSOLDES("73586")="\0.7\0"
	s ^TKSOLDES("74124")="\0.7\0"
	s ^TKSOLDES("74365")="\0.7\0"
	s ^TKSOLDES("74619")="\0.7\0"
	s ^TKSOLDES("74634")="\0.7\0"
	s ^TKSOLDES("74649")="\0.7\0"
	s ^TKSOLDES("74814")="\0.7\0"
	s ^TKSOLDES("75154")="\0.7\0"
	s ^TKSOLDES("76020")="\0.7\0"
	s ^TKSOLDES("76183")="\0.7\0"
	s ^TKSOLDES("76472")="\0.7\0"
	s ^TKSOLDES("76480")="\0.7\0"
	s ^TKSOLDES("76908")="\0.7\0"
	s ^TKSOLDES("77058")="\0.7\0"
	s ^TKSOLDES("77059")="\0.7\0"
	s ^TKSOLDES("77429")="\0.7\0"
	s ^TKSOLDES("77502")="\0.7\0"
	s ^TKSOLDES("77505")="\0.7\0"
	s ^TKSOLDES("77526")="\0.7\0"
	s ^TKSOLDES("77781")="\0.7\0"
	s ^TKSOLDES("78187")="\0.7\0"
	s ^TKSOLDES("78196")="\0.7\0"
	s ^TKSOLDES("78213")="\0.7\0"
	s ^TKSOLDES("78817")="\0.7\0"
	s ^TKSOLDES("78925")="\0.7\0"
	s ^TKSOLDES("79125")="\0.7\0"
	s ^TKSOLDES("79166")="\0.7\0"
	s ^TKSOLDES("79239")="\0.7\0"
	s ^TKSOLDES("79263")="\0.7\0"
	s ^TKSOLDES("79269")="\0.7\0"
	s ^TKSOLDES("79282")="\0.7\0"
	s ^TKSOLDES("79304")="\0.7\0"
	s ^TKSOLDES("80224")="\0.7\0"
	s ^TKSOLDES("80686")="\0.7\0"
	s ^TKSOLDES("80689")="\0.7\0"
	s ^TKSOLDES("80691")="\0.7\0"
	s ^TKSOLDES("80723")="\0.7\0"
	s ^TKSOLDES("80817")="\0.7\0"
	s ^TKSOLDES("81042")="\0.7\0"
	s ^TKSOLDES("81156")="\0.7\0"
	s ^TKSOLDES("81160")="\0.7\0"
	s ^TKSOLDES("81188")="\0.7\0"
	s ^TKSOLDES("81206")="\0.7\0"
	s ^TKSOLDES("81212")="\0.7\0"
	s ^TKSOLDES("81232")="\0.7\0"
	s ^TKSOLDES("81249")="\0.7\0"
	s ^TKSOLDES("81472")="\0.7\0"
	s ^TKSOLDES("81641")="\0.7\0"
	s ^TKSOLDES("81670")="\0.7\0"
	s ^TKSOLDES("82011")="\0.7\0"
	s ^TKSOLDES("82078")="\0.7\0"
	s ^TKSOLDES("82095")="\0.7\0"
	s ^TKSOLDES("82099")="\0.7\0"
	s ^TKSOLDES("82107")="\0.7\0"
	s ^TKSOLDES("82128")="\0.7\0"
	s ^TKSOLDES("82172")="\0.7\0"
	s ^TKSOLDES("82173")="\0.7\0"
	s ^TKSOLDES("82283")="\0.7\0"
	s ^TKSOLDES("82305")="\0.7\0"
	s ^TKSOLDES("82593")="\0.7\0"
	s ^TKSOLDES("82632")="\0.7\0"
	s ^TKSOLDES("82651")="\0.7\0"
	s ^TKSOLDES("82687")="\0.7\0"
	s ^TKSOLDES("82689")="\0.7\0"
	s ^TKSOLDES("82691")="\0.7\0"
	s ^TKSOLDES("82920")="\0.7\0"
	s ^TKSOLDES("82923")="\0.7\0"
	s ^TKSOLDES("82926")="\0.7\0"
	s ^TKSOLDES("83345")="\0.7\0"
	s ^TKSOLDES("83358")="\0.7\0"
	s ^TKSOLDES("83666")="\0.7\0"
	s ^TKSOLDES("83764")="\0.7\0"
	s ^TKSOLDES("83799")="\0.7\0"
	s ^TKSOLDES("83904")="\0.7\0"
	s ^TKSOLDES("84461")="\0.7\0"
	s ^TKSOLDES("84776")="\0.7\0"
	s ^TKSOLDES("84823")="\0.7\0"
	s ^TKSOLDES("84829")="\0.7\0"
	s ^TKSOLDES("84936")="\0.7\0"
	s ^TKSOLDES("85027")="\0.7\0"
	s ^TKSOLDES("85579")="\0.7\0"
	s ^TKSOLDES("85798")="\0.7\0"
	s ^TKSOLDES("85850")="\0.7\0"
	s ^TKSOLDES("85905")="\0.7\0"
	s ^TKSOLDES("86301")="\0.7\0"
	s ^TKSOLDES("86388")="\0.7\0"
	s ^TKSOLDES("86619")="\0.7\0"
	s ^TKSOLDES("86647")="\0.7\0"
	s ^TKSOLDES("87620")="\0.7\0"
	s ^TKSOLDES("87648")="\0.7\0"
	s ^TKSOLDES("87810")="\0.7\0"
	s ^TKSOLDES("87813")="\0.7\0"
	s ^TKSOLDES("87984")="\0.7\0"
	s ^TKSOLDES("87987")="\0.7\0"
	s ^TKSOLDES("88012")="\0.7\0"
	s ^TKSOLDES("88030")="\0.7\0"
	s ^TKSOLDES("88036")="\0.7\0"
	s ^TKSOLDES("89953")="\0.7\0"
	s ^TKSOLDES("89984")="\0.7\0"
	s ^TKSOLDES("100192")="\0.7\0"
	s ^TKSOLDES("100287")="\0.7\0"
	s ^TKSOLDES("100324")="\0.7\0"
	s ^TKSOLDES("100326")="\0.7\0"
	s ^TKSOLDES("100331")="\0.7\0"
	s ^TKSOLDES("100494")="\0.7\0"
	s ^TKSOLDES("101120")="\0.7\0"
	s ^TKSOLDES("101208")="\0.7\0"
	s ^TKSOLDES("101447")="\0.7\0"
	s ^TKSOLDES("101459")="\0.7\0"
	s ^TKSOLDES("101894")="\0.7\0"
	s ^TKSOLDES("102950")="\0.7\0"
	s ^TKSOLDES("103199")="\0.7\0"
	s ^TKSOLDES("105150")="\0.7\0"
	s ^TKSOLDES("105152")="\0.7\0"
	s ^TKSOLDES("105155")="\0.7\0"
	s ^TKSOLDES("105475")="\0.7\0"
	s ^TKSOLDES("105490")="\0.7\0"
	s ^TKSOLDES("106113")="\0.7\0"
	s ^TKSOLDES("110865")="\0.7\0"
	s ^TKSOLDES("79655")="\0.7\0"
	s ^TKSOLDES("44183")="\0.7\0"
	s ^TKSOLDES("61461")="\0.7\0"
	s ^TKSOLDES("68349")="\0.7\0"
	s ^TKSOLDES("80719")="\0.7\0"
	s ^TKSOLDES("82037")="\0.7\0"
	s ^TKSOLDES("85045")="\0.7\0"
	s ^TKSOLDES("100693")="\0.7\0"
	s ^TKSOLDES("40052")="\0.7\0"
	s ^TKSOLDES("79545")="\0.7\0"
	s ^TKSOLDES("82367")="\0.7\0"
	s ^TKSOLDES("3934")="\0.7\0"
	s ^TKSOLDES("41737")="\0.7\0"
	s ^TKSOLDES("41738")="\0.7\0"
	s ^TKSOLDES("46906")="\0.7\0"
	s ^TKSOLDES("54467")="\0.7\0"
	s ^TKSOLDES("92006")="\0.7\0"
	s ^TKSOLDES("67278")="\0.7\0"
	s ^TKSOLDES("75536")="\0.7\0"
	s ^TKSOLDES("76015")="\0.7\0"
	s ^TKSOLDES("78455")="\0.7\0"
	s ^TKSOLDES("78558")="\0.7\0"
	s ^TKSOLDES("78789")="\0.7\0"
	s ^TKSOLDES("79237")="\0.7\0"
	s ^TKSOLDES("79997")="\0.7\0"
	s ^TKSOLDES("81516")="\0.7\0"
	s ^TKSOLDES("82476")="\0.7\0"
	s ^TKSOLDES("82778")="\0.7\0"
	s ^TKSOLDES("83827")="\0.7\0"
	s ^TKSOLDES("100197")="\0.7\0"
	s ^TKSOLDES("100613")="\0.7\0"
	s ^TKSOLDES("101514")="\0.7\0"
	s ^TKSOLDES("103502")="\0.7\0"
	s ^TKSOLDES("54501")="\0.7\0"
	s ^TKSOLDES("80322")="\0.7\0"
	s ^TKSOLDES("8505")="\0.7\0"
	s ^TKSOLDES("80205")="\0.7\0"
	s ^TKSOLDES("84063")="\0.7\0"
	s ^TKSOLDES("51491")="\0.7\0"
	s ^TKSOLDES("79583")="\0.7\0"
	s ^TKSOLDES("85558")="\0.7\0"
	s ^TKSOLDES("85694")="\0.7\0"
	s ^TKSOLDES("79153")="\0.7\0"
	s ^TKSOLDES("83505")="\0.7\0"
	s ^TKSOLDES("85858")="\0.7\0"
	s ^TKSOLDES("1394")="\0.7\0"
	s ^TKSOLDES("1461")="\0.7\0"
	s ^TKSOLDES("2776")="\0.7\0"
	s ^TKSOLDES("6352")="\0.7\0"
	s ^TKSOLDES("6699")="\0.7\0"
	s ^TKSOLDES("6701")="\0.7\0"
	s ^TKSOLDES("6715")="\0.7\0"
	s ^TKSOLDES("7467")="\0.7\0"
	s ^TKSOLDES("7470")="\0.7\0"
	s ^TKSOLDES("7471")="\0.7\0"
	s ^TKSOLDES("7626")="\0.7\0"
	s ^TKSOLDES("7678")="\0.7\0"
	s ^TKSOLDES("7687")="\0.7\0"
	s ^TKSOLDES("8169")="\0.7\0"
	s ^TKSOLDES("8396")="\0.7\0"
	s ^TKSOLDES("8438")="\0.7\0"
	s ^TKSOLDES("8442")="\0.7\0"
	s ^TKSOLDES("8456")="\0.7\0"
	s ^TKSOLDES("8473")="\0.7\0"
	s ^TKSOLDES("9029")="\0.7\0"
	s ^TKSOLDES("9275")="\0.7\0"
	s ^TKSOLDES("9305")="\0.7\0"
	s ^TKSOLDES("12664")="\0.7\0"
	s ^TKSOLDES("12684")="\0.7\0"
	s ^TKSOLDES("12699")="\0.7\0"
	s ^TKSOLDES("12711")="\0.7\0"
	s ^TKSOLDES("12713")="\0.7\0"
	s ^TKSOLDES("12719")="\0.7\0"
	s ^TKSOLDES("12736")="\0.7\0"
	s ^TKSOLDES("12753")="\0.7\0"
	s ^TKSOLDES("12781")="\0.7\0"
	s ^TKSOLDES("12842")="\0.7\0"
	s ^TKSOLDES("12851")="\0.7\0"
	s ^TKSOLDES("12913")="\0.7\0"
	s ^TKSOLDES("12922")="\0.7\0"
	s ^TKSOLDES("12930")="\0.7\0"
	s ^TKSOLDES("13017")="\0.7\0"
	s ^TKSOLDES("13023")="\0.7\0"
	s ^TKSOLDES("13091")="\0.7\0"
	s ^TKSOLDES("13116")="\0.7\0"
	s ^TKSOLDES("13128")="\0.7\0"
	s ^TKSOLDES("13136")="\0.7\0"
	s ^TKSOLDES("13139")="\0.7\0"
	s ^TKSOLDES("13141")="\0.7\0"
	s ^TKSOLDES("13146")="\0.7\0"
	s ^TKSOLDES("13148")="\0.7\0"
	s ^TKSOLDES("13290")="\0.7\0"
	s ^TKSOLDES("13400")="\0.7\0"
	s ^TKSOLDES("13423")="\0.7\0"
	s ^TKSOLDES("13544")="\0.7\0"
	s ^TKSOLDES("13584")="\0.7\0"
	s ^TKSOLDES("13586")="\0.7\0"
	s ^TKSOLDES("13588")="\0.7\0"
	s ^TKSOLDES("13615")="\0.7\0"
	s ^TKSOLDES("13650")="\0.7\0"
	s ^TKSOLDES("13814")="\0.7\0"
	s ^TKSOLDES("13844")="\0.7\0"
	s ^TKSOLDES("13885")="\0.7\0"
	s ^TKSOLDES("13897")="\0.7\0"
	s ^TKSOLDES("14199")="\0.7\0"
	s ^TKSOLDES("14229")="\0.7\0"
	s ^TKSOLDES("14244")="\0.7\0"
	s ^TKSOLDES("14495")="\0.7\0"
	s ^TKSOLDES("14501")="\0.7\0"
	s ^TKSOLDES("14511")="\0.7\0"
	s ^TKSOLDES("14516")="\0.7\0"
	s ^TKSOLDES("14518")="\0.7\0"
	s ^TKSOLDES("14519")="\0.7\0"
	s ^TKSOLDES("14537")="\0.7\0"
	s ^TKSOLDES("14541")="\0.7\0"
	s ^TKSOLDES("14547")="\0.7\0"
	s ^TKSOLDES("14577")="\0.7\0"
	s ^TKSOLDES("14672")="\0.7\0"
	s ^TKSOLDES("14681")="\0.7\0"
	s ^TKSOLDES("14769")="\0.7\0"
	s ^TKSOLDES("14777")="\0.7\0"
	s ^TKSOLDES("14787")="\0.7\0"
	s ^TKSOLDES("14798")="\0.7\0"
	s ^TKSOLDES("14803")="\0.7\0"
	s ^TKSOLDES("14809")="\0.7\0"
	s ^TKSOLDES("14818")="\0.7\0"
	s ^TKSOLDES("14823")="\0.7\0"
	s ^TKSOLDES("14831")="\0.7\0"
	s ^TKSOLDES("14853")="\0.7\0"
	s ^TKSOLDES("14909")="\0.7\0"
	s ^TKSOLDES("14910")="\0.7\0"
	s ^TKSOLDES("14911")="\0.7\0"
	s ^TKSOLDES("14998")="\0.7\0"
	s ^TKSOLDES("15006")="\0.7\0"
	s ^TKSOLDES("15054")="\0.7\0"
	s ^TKSOLDES("15096")="\0.7\0"
	s ^TKSOLDES("15102")="\0.7\0"
	s ^TKSOLDES("15105")="\0.7\0"
	s ^TKSOLDES("15129")="\0.7\0"
	s ^TKSOLDES("15134")="\0.7\0"
	s ^TKSOLDES("15247")="\0.7\0"
	s ^TKSOLDES("15256")="\0.7\0"
	s ^TKSOLDES("15311")="\0.7\0"
	s ^TKSOLDES("15312")="\0.7\0"
	s ^TKSOLDES("15314")="\0.7\0"
	s ^TKSOLDES("15319")="\0.7\0"
	s ^TKSOLDES("15334")="\0.7\0"
	s ^TKSOLDES("15360")="\0.7\0"
	s ^TKSOLDES("15362")="\0.7\0"
	s ^TKSOLDES("15376")="\0.7\0"
	s ^TKSOLDES("15398")="\0.7\0"
	s ^TKSOLDES("15477")="\0.7\0"
	s ^TKSOLDES("15489")="\0.7\0"
	s ^TKSOLDES("15497")="\0.7\0"
	s ^TKSOLDES("15506")="\0.7\0"
	s ^TKSOLDES("15530")="\0.7\0"
	s ^TKSOLDES("15534")="\0.7\0"
	s ^TKSOLDES("15564")="\0.7\0"
	s ^TKSOLDES("15570")="\0.7\0"
	s ^TKSOLDES("15575")="\0.7\0"
	s ^TKSOLDES("15593")="\0.7\0"
	s ^TKSOLDES("15602")="\0.7\0"
	s ^TKSOLDES("15609")="\0.7\0"
	s ^TKSOLDES("15636")="\0.7\0"
	s ^TKSOLDES("15638")="\0.7\0"
	s ^TKSOLDES("15642")="\0.7\0"
	s ^TKSOLDES("15651")="\0.7\0"
	s ^TKSOLDES("15653")="\0.7\0"
	s ^TKSOLDES("15669")="\0.7\0"
	s ^TKSOLDES("15685")="\0.7\0"
	s ^TKSOLDES("15699")="\0.7\0"
	s ^TKSOLDES("16055")="\0.7\0"
	s ^TKSOLDES("16073")="\0.7\0"
	s ^TKSOLDES("16086")="\0.7\0"
	s ^TKSOLDES("16118")="\0.7\0"
	s ^TKSOLDES("16129")="\0.7\0"
	s ^TKSOLDES("16132")="\0.7\0"
	s ^TKSOLDES("16166")="\0.7\0"
	s ^TKSOLDES("16173")="\0.7\0"
	s ^TKSOLDES("16177")="\0.7\0"
	s ^TKSOLDES("16182")="\0.7\0"
	s ^TKSOLDES("16205")="\0.7\0"
	s ^TKSOLDES("16285")="\0.7\0"
	s ^TKSOLDES("16350")="\0.7\0"
	s ^TKSOLDES("16358")="\0.7\0"
	s ^TKSOLDES("16390")="\0.7\0"
	s ^TKSOLDES("16395")="\0.7\0"
	s ^TKSOLDES("16410")="\0.7\0"
	s ^TKSOLDES("16499")="\0.7\0"
	s ^TKSOLDES("16512")="\0.7\0"
	s ^TKSOLDES("16631")="\0.7\0"
	s ^TKSOLDES("17111")="\0.7\0"
	s ^TKSOLDES("17113")="\0.7\0"
	s ^TKSOLDES("17114")="\0.7\0"
	s ^TKSOLDES("17121")="\0.7\0"
	s ^TKSOLDES("17713")="\0.7\0"
	s ^TKSOLDES("18198")="\0.7\0"
	s ^TKSOLDES("18217")="\0.7\0"
	s ^TKSOLDES("18238")="\0.7\0"
	s ^TKSOLDES("18240")="\0.7\0"
	s ^TKSOLDES("18247")="\0.7\0"
	s ^TKSOLDES("18272")="\0.7\0"
	s ^TKSOLDES("18314")="\0.7\0"
	s ^TKSOLDES("18326")="\0.7\0"
	s ^TKSOLDES("18342")="\0.7\0"
	s ^TKSOLDES("18399")="\0.7\0"
	s ^TKSOLDES("18401")="\0.7\0"
	s ^TKSOLDES("18405")="\0.7\0"
	s ^TKSOLDES("18407")="\0.7\0"
	s ^TKSOLDES("18409")="\0.7\0"
	s ^TKSOLDES("18427")="\0.7\0"
	s ^TKSOLDES("34827")="\0.7\0"
	s ^TKSOLDES("34938")="\0.7\0"
	s ^TKSOLDES("34943")="\0.7\0"
	s ^TKSOLDES("35114")="\0.7\0"
	s ^TKSOLDES("35215")="\0.7\0"
	s ^TKSOLDES("35221")="\0.7\0"
	s ^TKSOLDES("35225")="\0.7\0"
	s ^TKSOLDES("35323")="\0.7\0"
	s ^TKSOLDES("35337")="\0.7\0"
	s ^TKSOLDES("35351")="\0.7\0"
	s ^TKSOLDES("12597")="\0.7\0"
	s ^TKSOLDES("13435")="\0.7\0"
	s ^TKSOLDES("13627")="\0.7\0"
	s ^TKSOLDES("13631")="\0.7\0"
	s ^TKSOLDES("13686")="\0.7\0"
	s ^TKSOLDES("13693")="\0.7\0"
	s ^TKSOLDES("13694")="\0.7\0"
	s ^TKSOLDES("13736")="\0.7\0"
	s ^TKSOLDES("13744")="\0.7\0"
	s ^TKSOLDES("13746")="\0.7\0"
	s ^TKSOLDES("13749")="\0.7\0"
	s ^TKSOLDES("13759")="\0.7\0"
	s ^TKSOLDES("13784")="\0.7\0"
	s ^TKSOLDES("14217")="\0.7\0"
	s ^TKSOLDES("16658")="\0.7\0"
	s ^TKSOLDES("16684")="\0.7\0"
	s ^TKSOLDES("16704")="\0.7\0"
	s ^TKSOLDES("16737")="\0.7\0"
	s ^TKSOLDES("16739")="\0.7\0"
	s ^TKSOLDES("16770")="\0.7\0"
	s ^TKSOLDES("17189")="\0.7\0"
	s ^TKSOLDES("17497")="\0.7\0"
	s ^TKSOLDES("17499")="\0.7\0"
	s ^TKSOLDES("17658")="\0.7\0"
	s ^TKSOLDES("17662")="\0.7\0"
	s ^TKSOLDES("17671")="\0.7\0"
	s ^TKSOLDES("17679")="\0.7\0"
	s ^TKSOLDES("17688")="\0.7\0"
	s ^TKSOLDES("34907")="\0.7\0"
	s ^TKSOLDES("34908")="\0.7\0"
	s ^TKSOLDES("35106")="\0.7\0"
	s ^TKSOLDES("35129")="\0.7\0"
	s ^TKSOLDES("35133")="\0.7\0"
	s ^TKSOLDES("35556")="\0.7\0"
	s ^TKSOLDES("35561")="\0.7\0"
	s ^TKSOLDES("35827")="\0.7\0"
	s ^TKSOLDES("36035")="\0.7\0"
	s ^TKSOLDES("36040")="\0.7\0"
	s ^TKSOLDES("36046")="\0.7\0"
	s ^TKSOLDES("37174")="\0.7\0"
	s ^TKSOLDES("37181")="\0.7\0"
	s ^TKSOLDES("37204")="\0.7\0"
	s ^TKSOLDES("37255")="\0.7\0"
	s ^TKSOLDES("37256")="\0.7\0"
	s ^TKSOLDES("37262")="\0.7\0"
	s ^TKSOLDES("37269")="\0.7\0"
	s ^TKSOLDES("37332")="\0.7\0"
	s ^TKSOLDES("37352")="\0.7\0"
	s ^TKSOLDES("38327")="\0.7\0"
	s ^TKSOLDES("38342")="\0.7\0"
	s ^TKSOLDES("38343")="\0.7\0"
	s ^TKSOLDES("38346")="\0.7\0"
	s ^TKSOLDES("38355")="\0.7\0"
	s ^TKSOLDES("38394")="\0.7\0"
	s ^TKSOLDES("38401")="\0.7\0"
	s ^TKSOLDES("38410")="\0.7\0"
	s ^TKSOLDES("38411")="\0.7\0"
	s ^TKSOLDES("38413")="\0.7\0"
	s ^TKSOLDES("38426")="\0.7\0"
	s ^TKSOLDES("38444")="\0.7\0"
	s ^TKSOLDES("38452")="\0.7\0"
	s ^TKSOLDES("38454")="\0.7\0"
	s ^TKSOLDES("38456")="\0.7\0"
	s ^TKSOLDES("38458")="\0.7\0"
	s ^TKSOLDES("38463")="\0.7\0"
	s ^TKSOLDES("38464")="\0.7\0"
	s ^TKSOLDES("38469")="\0.7\0"
	s ^TKSOLDES("38513")="\0.7\0"
	s ^TKSOLDES("39393")="\0.7\0"
	s ^TKSOLDES("40776")="\0.7\0"
	s ^TKSOLDES("40777")="\0.7\0"
	s ^TKSOLDES("41216")="\0.7\0"
	s ^TKSOLDES("41232")="\0.7\0"
	s ^TKSOLDES("41550")="\0.7\0"
	s ^TKSOLDES("41650")="\0.7\0"
	s ^TKSOLDES("41654")="\0.7\0"
	s ^TKSOLDES("41659")="\0.7\0"
	s ^TKSOLDES("41781")="\0.7\0"
	s ^TKSOLDES("41783")="\0.7\0"
	s ^TKSOLDES("41786")="\0.7\0"
	s ^TKSOLDES("41788")="\0.7\0"
	s ^TKSOLDES("41800")="\0.7\0"
	s ^TKSOLDES("41804")="\0.7\0"
	s ^TKSOLDES("41828")="\0.7\0"
	s ^TKSOLDES("41848")="\0.7\0"
	s ^TKSOLDES("41851")="\0.7\0"
	s ^TKSOLDES("41869")="\0.7\0"
	s ^TKSOLDES("41871")="\0.7\0"
	s ^TKSOLDES("41882")="\0.7\0"
	s ^TKSOLDES("41888")="\0.7\0"
	s ^TKSOLDES("41892")="\0.7\0"
	s ^TKSOLDES("41894")="\0.7\0"
	s ^TKSOLDES("41895")="\0.7\0"
	s ^TKSOLDES("41902")="\0.7\0"
	s ^TKSOLDES("41908")="\0.7\0"
	s ^TKSOLDES("41912")="\0.7\0"
	s ^TKSOLDES("41936")="\0.7\0"
	s ^TKSOLDES("41937")="\0.7\0"
	s ^TKSOLDES("41939")="\0.7\0"
	s ^TKSOLDES("41945")="\0.7\0"
	s ^TKSOLDES("41947")="\0.7\0"
	s ^TKSOLDES("41949")="\0.7\0"
	s ^TKSOLDES("41952")="\0.7\0"
	s ^TKSOLDES("41955")="\0.7\0"
	s ^TKSOLDES("41956")="\0.7\0"
	s ^TKSOLDES("41958")="\0.7\0"
	s ^TKSOLDES("41961")="\0.7\0"
	s ^TKSOLDES("41963")="\0.7\0"
	s ^TKSOLDES("41975")="\0.7\0"
	s ^TKSOLDES("41979")="\0.7\0"
	s ^TKSOLDES("41982")="\0.7\0"
	s ^TKSOLDES("41986")="\0.7\0"
	s ^TKSOLDES("41992")="\0.7\0"
	s ^TKSOLDES("41996")="\0.7\0"
	s ^TKSOLDES("42000")="\0.7\0"
	s ^TKSOLDES("42011")="\0.7\0"
	s ^TKSOLDES("42016")="\0.7\0"
	s ^TKSOLDES("42022")="\0.7\0"
	s ^TKSOLDES("42023")="\0.7\0"
	s ^TKSOLDES("42028")="\0.7\0"
	s ^TKSOLDES("42031")="\0.7\0"
	s ^TKSOLDES("42032")="\0.7\0"
	s ^TKSOLDES("42033")="\0.7\0"
	s ^TKSOLDES("42068")="\0.7\0"
	s ^TKSOLDES("42072")="\0.7\0"
	s ^TKSOLDES("42073")="\0.7\0"
	s ^TKSOLDES("42093")="\0.7\0"
	s ^TKSOLDES("42096")="\0.7\0"
	s ^TKSOLDES("42127")="\0.7\0"
	s ^TKSOLDES("42130")="\0.7\0"
	s ^TKSOLDES("42132")="\0.7\0"
	s ^TKSOLDES("42135")="\0.7\0"
	s ^TKSOLDES("42136")="\0.7\0"
	s ^TKSOLDES("42139")="\0.7\0"
	s ^TKSOLDES("42140")="\0.7\0"
	s ^TKSOLDES("42145")="\0.7\0"
	s ^TKSOLDES("42149")="\0.7\0"
	s ^TKSOLDES("42165")="\0.7\0"
	s ^TKSOLDES("42172")="\0.7\0"
	s ^TKSOLDES("42176")="\0.7\0"
	s ^TKSOLDES("42182")="\0.7\0"
	s ^TKSOLDES("42201")="\0.7\0"
	s ^TKSOLDES("42205")="\0.7\0"
	s ^TKSOLDES("42211")="\0.7\0"
	s ^TKSOLDES("42216")="\0.7\0"
	s ^TKSOLDES("42221")="\0.7\0"
	s ^TKSOLDES("42223")="\0.7\0"
	s ^TKSOLDES("42230")="\0.7\0"
	s ^TKSOLDES("42240")="\0.7\0"
	s ^TKSOLDES("42252")="\0.7\0"
	s ^TKSOLDES("42254")="\0.7\0"
	s ^TKSOLDES("42256")="\0.7\0"
	s ^TKSOLDES("42258")="\0.7\0"
	s ^TKSOLDES("42260")="\0.7\0"
	s ^TKSOLDES("42281")="\0.7\0"
	s ^TKSOLDES("42314")="\0.7\0"
	s ^TKSOLDES("42318")="\0.7\0"
	s ^TKSOLDES("42352")="\0.7\0"
	s ^TKSOLDES("42392")="\0.7\0"
	s ^TKSOLDES("42402")="\0.7\0"
	s ^TKSOLDES("42407")="\0.7\0"
	s ^TKSOLDES("42409")="\0.7\0"
	s ^TKSOLDES("42410")="\0.7\0"
	s ^TKSOLDES("42418")="\0.7\0"
	s ^TKSOLDES("42420")="\0.7\0"
	s ^TKSOLDES("42422")="\0.7\0"
	s ^TKSOLDES("42423")="\0.7\0"
	s ^TKSOLDES("42591")="\0.7\0"
	s ^TKSOLDES("42615")="\0.7\0"
	s ^TKSOLDES("42637")="\0.7\0"
	s ^TKSOLDES("42684")="\0.7\0"
	s ^TKSOLDES("42687")="\0.7\0"
	s ^TKSOLDES("42689")="\0.7\0"
	s ^TKSOLDES("42691")="\0.7\0"
	s ^TKSOLDES("42694")="\0.7\0"
	s ^TKSOLDES("42832")="\0.7\0"
	s ^TKSOLDES("42863")="\0.7\0"
	s ^TKSOLDES("43023")="\0.7\0"
	s ^TKSOLDES("43032")="\0.7\0"
	s ^TKSOLDES("43033")="\0.7\0"
	s ^TKSOLDES("43066")="\0.7\0"
	s ^TKSOLDES("43086")="\0.7\0"
	s ^TKSOLDES("43090")="\0.7\0"
	s ^TKSOLDES("43095")="\0.7\0"
	s ^TKSOLDES("43102")="\0.7\0"
	s ^TKSOLDES("43107")="\0.7\0"
	s ^TKSOLDES("43114")="\0.7\0"
	s ^TKSOLDES("43117")="\0.7\0"
	s ^TKSOLDES("43131")="\0.7\0"
	s ^TKSOLDES("43134")="\0.7\0"
	s ^TKSOLDES("43139")="\0.7\0"
	s ^TKSOLDES("43144")="\0.7\0"
	s ^TKSOLDES("43160")="\0.7\0"
	s ^TKSOLDES("43163")="\0.7\0"
	s ^TKSOLDES("43174")="\0.7\0"
	s ^TKSOLDES("43178")="\0.7\0"
	s ^TKSOLDES("43198")="\0.7\0"
	s ^TKSOLDES("43202")="\0.7\0"
	s ^TKSOLDES("43220")="\0.7\0"
	s ^TKSOLDES("43225")="\0.7\0"
	s ^TKSOLDES("43229")="\0.7\0"
	s ^TKSOLDES("43230")="\0.7\0"
	s ^TKSOLDES("43236")="\0.7\0"
	s ^TKSOLDES("43238")="\0.7\0"
	s ^TKSOLDES("43239")="\0.7\0"
	s ^TKSOLDES("43242")="\0.7\0"
	s ^TKSOLDES("43259")="\0.7\0"
	s ^TKSOLDES("43261")="\0.7\0"
	s ^TKSOLDES("43262")="\0.7\0"
	s ^TKSOLDES("43290")="\0.7\0"
	s ^TKSOLDES("43746")="\0.7\0"
	s ^TKSOLDES("43842")="\0.7\0"
	s ^TKSOLDES("43889")="\0.7\0"
	s ^TKSOLDES("44011")="\0.7\0"
	s ^TKSOLDES("44014")="\0.7\0"
	s ^TKSOLDES("44063")="\0.7\0"
	s ^TKSOLDES("44065")="\0.7\0"
	s ^TKSOLDES("44077")="\0.7\0"
	s ^TKSOLDES("44113")="\0.7\0"
	s ^TKSOLDES("44139")="\0.7\0"
	s ^TKSOLDES("44256")="\0.7\0"
	s ^TKSOLDES("44286")="\0.7\0"
	s ^TKSOLDES("44294")="\0.7\0"
	s ^TKSOLDES("44305")="\0.7\0"
	s ^TKSOLDES("44473")="\0.7\0"
	s ^TKSOLDES("44628")="\0.7\0"
	s ^TKSOLDES("45423")="\0.7\0"
	s ^TKSOLDES("45734")="\0.7\0"
	s ^TKSOLDES("45762")="\0.7\0"
	s ^TKSOLDES("45768")="\0.7\0"
	s ^TKSOLDES("45778")="\0.7\0"
	s ^TKSOLDES("45788")="\0.7\0"
	s ^TKSOLDES("45802")="\0.7\0"
	s ^TKSOLDES("45812")="\0.7\0"
	s ^TKSOLDES("45819")="\0.7\0"
	s ^TKSOLDES("45886")="\0.7\0"
	s ^TKSOLDES("45892")="\0.7\0"
	s ^TKSOLDES("45933")="\0.7\0"
	s ^TKSOLDES("46006")="\0.7\0"
	s ^TKSOLDES("46106")="\0.7\0"
	s ^TKSOLDES("46111")="\0.7\0"
	s ^TKSOLDES("46129")="\0.7\0"
	s ^TKSOLDES("46136")="\0.7\0"
	s ^TKSOLDES("46140")="\0.7\0"
	s ^TKSOLDES("46146")="\0.7\0"
	s ^TKSOLDES("46157")="\0.7\0"
	s ^TKSOLDES("46181")="\0.7\0"
	s ^TKSOLDES("46196")="\0.7\0"
	s ^TKSOLDES("46199")="\0.7\0"
	s ^TKSOLDES("46200")="\0.7\0"
	s ^TKSOLDES("46205")="\0.7\0"
	s ^TKSOLDES("46210")="\0.7\0"
	s ^TKSOLDES("46223")="\0.7\0"
	s ^TKSOLDES("46247")="\0.7\0"
	s ^TKSOLDES("46279")="\0.7\0"
	s ^TKSOLDES("46320")="\0.7\0"
	s ^TKSOLDES("46323")="\0.7\0"
	s ^TKSOLDES("46328")="\0.7\0"
	s ^TKSOLDES("46339")="\0.7\0"
	s ^TKSOLDES("46343")="\0.7\0"
	s ^TKSOLDES("46347")="\0.7\0"
	s ^TKSOLDES("46351")="\0.7\0"
	s ^TKSOLDES("46355")="\0.7\0"
	s ^TKSOLDES("46368")="\0.7\0"
	s ^TKSOLDES("46375")="\0.7\0"
	s ^TKSOLDES("46379")="\0.7\0"
	s ^TKSOLDES("46386")="\0.7\0"
	s ^TKSOLDES("46470")="\0.7\0"
	s ^TKSOLDES("46475")="\0.7\0"
	s ^TKSOLDES("46477")="\0.7\0"
	s ^TKSOLDES("46481")="\0.7\0"
	s ^TKSOLDES("46484")="\0.7\0"
	s ^TKSOLDES("46885")="\0.7\0"
	s ^TKSOLDES("46901")="\0.7\0"
	s ^TKSOLDES("46964")="\0.7\0"
	s ^TKSOLDES("47050")="\0.7\0"
	s ^TKSOLDES("47094")="\0.7\0"
	s ^TKSOLDES("47096")="\0.7\0"
	s ^TKSOLDES("47101")="\0.7\0"
	s ^TKSOLDES("47102")="\0.7\0"
	s ^TKSOLDES("47107")="\0.7\0"
	s ^TKSOLDES("47108")="\0.7\0"
	s ^TKSOLDES("47113")="\0.7\0"
	s ^TKSOLDES("47116")="\0.7\0"
	s ^TKSOLDES("47117")="\0.7\0"
	s ^TKSOLDES("47168")="\0.7\0"
	s ^TKSOLDES("47284")="\0.7\0"
	s ^TKSOLDES("47291")="\0.7\0"
	s ^TKSOLDES("47724")="\0.7\0"
	s ^TKSOLDES("47731")="\0.7\0"
	s ^TKSOLDES("47736")="\0.7\0"
	s ^TKSOLDES("47738")="\0.7\0"
	s ^TKSOLDES("48572")="\0.7\0"
	s ^TKSOLDES("48581")="\0.7\0"
	s ^TKSOLDES("48599")="\0.7\0"
	s ^TKSOLDES("48601")="\0.7\0"
	s ^TKSOLDES("48604")="\0.7\0"
	s ^TKSOLDES("48605")="\0.7\0"
	s ^TKSOLDES("48608")="\0.7\0"
	s ^TKSOLDES("48705")="\0.7\0"
	s ^TKSOLDES("48708")="\0.7\0"
	s ^TKSOLDES("48719")="\0.7\0"
	s ^TKSOLDES("48722")="\0.7\0"
	s ^TKSOLDES("48740")="\0.7\0"
	s ^TKSOLDES("48741")="\0.7\0"
	s ^TKSOLDES("48742")="\0.7\0"
	s ^TKSOLDES("48755")="\0.7\0"
	s ^TKSOLDES("48840")="\0.7\0"
	s ^TKSOLDES("48857")="\0.7\0"
	s ^TKSOLDES("48858")="\0.7\0"
	s ^TKSOLDES("48860")="\0.7\0"
	s ^TKSOLDES("48867")="\0.7\0"
	s ^TKSOLDES("48875")="\0.7\0"
	s ^TKSOLDES("48891")="\0.7\0"
	s ^TKSOLDES("48955")="\0.7\0"
	s ^TKSOLDES("48974")="\0.7\0"
	s ^TKSOLDES("49066")="\0.7\0"
	s ^TKSOLDES("49072")="\0.7\0"
	s ^TKSOLDES("49075")="\0.7\0"
	s ^TKSOLDES("49104")="\0.7\0"
	s ^TKSOLDES("49140")="\0.7\0"
	s ^TKSOLDES("49146")="\0.7\0"
	s ^TKSOLDES("49173")="\0.7\0"
	s ^TKSOLDES("49192")="\0.7\0"
	s ^TKSOLDES("49207")="\0.7\0"
	s ^TKSOLDES("49364")="\0.7\0"
	s ^TKSOLDES("49368")="\0.7\0"
	s ^TKSOLDES("49376")="\0.7\0"
	s ^TKSOLDES("49378")="\0.7\0"
	s ^TKSOLDES("49386")="\0.7\0"
	s ^TKSOLDES("49387")="\0.7\0"
	s ^TKSOLDES("49397")="\0.7\0"
	s ^TKSOLDES("49401")="\0.7\0"
	s ^TKSOLDES("49406")="\0.7\0"
	s ^TKSOLDES("49419")="\0.7\0"
	s ^TKSOLDES("50678")="\0.7\0"
	s ^TKSOLDES("50680")="\0.7\0"
	s ^TKSOLDES("50744")="\0.7\0"
	s ^TKSOLDES("51269")="\0.7\0"
	s ^TKSOLDES("51313")="\0.7\0"
	s ^TKSOLDES("51319")="\0.7\0"
	s ^TKSOLDES("51321")="\0.7\0"
	s ^TKSOLDES("51336")="\0.7\0"
	s ^TKSOLDES("51337")="\0.7\0"
	s ^TKSOLDES("51344")="\0.7\0"
	s ^TKSOLDES("51345")="\0.7\0"
	s ^TKSOLDES("51859")="\0.7\0"
	s ^TKSOLDES("51879")="\0.7\0"
	s ^TKSOLDES("52174")="\0.7\0"
	s ^TKSOLDES("52360")="\0.7\0"
	s ^TKSOLDES("52362")="\0.7\0"
	s ^TKSOLDES("52776")="\0.7\0"
	s ^TKSOLDES("52788")="\0.7\0"
	s ^TKSOLDES("52791")="\0.7\0"
	s ^TKSOLDES("52792")="\0.7\0"
	s ^TKSOLDES("52885")="\0.7\0"
	s ^TKSOLDES("53168")="\0.7\0"
	s ^TKSOLDES("53278")="\0.7\0"
	s ^TKSOLDES("53743")="\0.7\0"
	s ^TKSOLDES("53752")="\0.7\0"
	s ^TKSOLDES("53775")="\0.7\0"
	s ^TKSOLDES("53780")="\0.7\0"
	s ^TKSOLDES("53793")="\0.7\0"
	s ^TKSOLDES("53796")="\0.7\0"
	s ^TKSOLDES("53810")="\0.7\0"
	s ^TKSOLDES("53819")="\0.7\0"
	s ^TKSOLDES("53821")="\0.7\0"
	s ^TKSOLDES("53822")="\0.7\0"
	s ^TKSOLDES("53842")="\0.7\0"
	s ^TKSOLDES("53845")="\0.7\0"
	s ^TKSOLDES("53847")="\0.7\0"
	s ^TKSOLDES("53859")="\0.7\0"
	s ^TKSOLDES("53864")="\0.7\0"
	s ^TKSOLDES("53998")="\0.7\0"
	s ^TKSOLDES("54119")="\0.7\0"
	s ^TKSOLDES("54131")="\0.7\0"
	s ^TKSOLDES("54138")="\0.7\0"
	s ^TKSOLDES("54168")="\0.7\0"
	s ^TKSOLDES("54180")="\0.7\0"
	s ^TKSOLDES("54181")="\0.7\0"
	s ^TKSOLDES("54193")="\0.7\0"
	s ^TKSOLDES("54211")="\0.7\0"
	s ^TKSOLDES("54340")="\0.7\0"
	s ^TKSOLDES("54371")="\0.7\0"
	s ^TKSOLDES("54537")="\0.7\0"
	s ^TKSOLDES("54548")="\0.7\0"
	s ^TKSOLDES("54778")="\0.7\0"
	s ^TKSOLDES("54784")="\0.7\0"
	s ^TKSOLDES("54948")="\0.7\0"
	s ^TKSOLDES("54953")="\0.7\0"
	s ^TKSOLDES("55307")="\0.7\0"
	s ^TKSOLDES("55309")="\0.7\0"
	s ^TKSOLDES("55311")="\0.7\0"
	s ^TKSOLDES("55313")="\0.7\0"
	s ^TKSOLDES("55314")="\0.7\0"
	s ^TKSOLDES("55315")="\0.7\0"
	s ^TKSOLDES("55347")="\0.7\0"
	s ^TKSOLDES("50624")="\0.7\0"
	s ^TKSOLDES("55649")="\0.7\0"
	s ^TKSOLDES("55677")="\0.7\0"
	s ^TKSOLDES("55689")="\0.7\0"
	s ^TKSOLDES("55713")="\0.7\0"
	s ^TKSOLDES("55714")="\0.7\0"
	s ^TKSOLDES("55922")="\0.7\0"
	s ^TKSOLDES("55966")="\0.7\0"
	s ^TKSOLDES("56103")="\0.7\0"
	s ^TKSOLDES("56111")="\0.7\0"
	s ^TKSOLDES("56120")="\0.7\0"
	s ^TKSOLDES("56124")="\0.7\0"
 
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 