ROUTINE SOLDES70AH13M391C5
SOLDES70AH13M391C5
 
	s ^TKSOLDES("15120")="\0.7\0"
	s ^TKSOLDES("15184")="\0.7\0"
	s ^TKSOLDES("15211")="\0.7\0"
	s ^TKSOLDES("15227")="\0.7\0"
	s ^TKSOLDES("15246")="\0.7\0"
	s ^TKSOLDES("15347")="\0.7\0"
	s ^TKSOLDES("15355")="\0.7\0"
	s ^TKSOLDES("15416")="\0.7\0"
	s ^TKSOLDES("15487")="\0.7\0"
	s ^TKSOLDES("15526")="\0.7\0"
	s ^TKSOLDES("15580")="\0.7\0"
	s ^TKSOLDES("15595")="\0.7\0"
	s ^TKSOLDES("15683")="\0.7\0"
	s ^TKSOLDES("16057")="\0.7\0"
	s ^TKSOLDES("16111")="\0.7\0"
	s ^TKSOLDES("16116")="\0.7\0"
	s ^TKSOLDES("16396")="\0.7\0"
	s ^TKSOLDES("16397")="\0.7\0"
	s ^TKSOLDES("16400")="\0.7\0"
	s ^TKSOLDES("16404")="\0.7\0"
	s ^TKSOLDES("16407")="\0.7\0"
	s ^TKSOLDES("16637")="\0.7\0"
	s ^TKSOLDES("17710")="\0.7\0"
	s ^TKSOLDES("17877")="\0.7\0"
	s ^TKSOLDES("18188")="\0.7\0"
	s ^TKSOLDES("18201")="\0.7\0"
	s ^TKSOLDES("18271")="\0.7\0"
	s ^TKSOLDES("18311")="\0.7\0"
	s ^TKSOLDES("18346")="\0.7\0"
	s ^TKSOLDES("18398")="\0.7\0"
	s ^TKSOLDES("18413")="\0.7\0"
	s ^TKSOLDES("34993")="\0.7\0"
	s ^TKSOLDES("35081")="\0.7\0"
	s ^TKSOLDES("35216")="\0.7\0"
	s ^TKSOLDES("35218")="\0.7\0"
	s ^TKSOLDES("12602")="\0.7\0"
	s ^TKSOLDES("13439")="\0.7\0"
	s ^TKSOLDES("13591")="\0.7\0"
	s ^TKSOLDES("13595")="\0.7\0"
	s ^TKSOLDES("13600")="\0.7\0"
	s ^TKSOLDES("13710")="\0.7\0"
	s ^TKSOLDES("13751")="\0.7\0"
	s ^TKSOLDES("14155")="\0.7\0"
	s ^TKSOLDES("16322")="\0.7\0"
	s ^TKSOLDES("16323")="\0.7\0"
	s ^TKSOLDES("16683")="\0.7\0"
	s ^TKSOLDES("17664")="\0.7\0"
	s ^TKSOLDES("34909")="\0.7\0"
	s ^TKSOLDES("34911")="\0.7\0"
	s ^TKSOLDES("34926")="\0.7\0"
	s ^TKSOLDES("35096")="\0.7\0"
	s ^TKSOLDES("35102")="\0.7\0"
	s ^TKSOLDES("35267")="\0.7\0"
	s ^TKSOLDES("35545")="\0.7\0"
	s ^TKSOLDES("36023")="\0.7\0"
	s ^TKSOLDES("36048")="\0.7\0"
	s ^TKSOLDES("37242")="\0.7\0"
	s ^TKSOLDES("37246")="\0.7\0"
	s ^TKSOLDES("37254")="\0.7\0"
	s ^TKSOLDES("37260")="\0.7\0"
	s ^TKSOLDES("37336")="\0.7\0"
	s ^TKSOLDES("37379")="\0.7\0"
	s ^TKSOLDES("38319")="\0.7\0"
	s ^TKSOLDES("38321")="\0.7\0"
	s ^TKSOLDES("38345")="\0.7\0"
	s ^TKSOLDES("38350")="\0.7\0"
	s ^TKSOLDES("38365")="\0.7\0"
	s ^TKSOLDES("38368")="\0.7\0"
	s ^TKSOLDES("38380")="\0.7\0"
	s ^TKSOLDES("38402")="\0.7\0"
	s ^TKSOLDES("38408")="\0.7\0"
	s ^TKSOLDES("38430")="\0.7\0"
	s ^TKSOLDES("38432")="\0.7\0"
	s ^TKSOLDES("38460")="\0.7\0"
	s ^TKSOLDES("38516")="\0.7\0"
	s ^TKSOLDES("40101")="\0.7\0"
	s ^TKSOLDES("40132")="\0.7\0"
	s ^TKSOLDES("40176")="\0.7\0"
	s ^TKSOLDES("40778")="\0.7\0"
	s ^TKSOLDES("41110")="\0.7\0"
	s ^TKSOLDES("41129")="\0.7\0"
	s ^TKSOLDES("41637")="\0.7\0"
	s ^TKSOLDES("41643")="\0.7\0"
	s ^TKSOLDES("41651")="\0.7\0"
	s ^TKSOLDES("41653")="\0.7\0"
	s ^TKSOLDES("41782")="\0.7\0"
	s ^TKSOLDES("41830")="\0.7\0"
	s ^TKSOLDES("41844")="\0.7\0"
	s ^TKSOLDES("41846")="\0.7\0"
	s ^TKSOLDES("41856")="\0.7\0"
	s ^TKSOLDES("41870")="\0.7\0"
	s ^TKSOLDES("41872")="\0.7\0"
	s ^TKSOLDES("41874")="\0.7\0"
	s ^TKSOLDES("41899")="\0.7\0"
	s ^TKSOLDES("41911")="\0.7\0"
	s ^TKSOLDES("41921")="\0.7\0"
	s ^TKSOLDES("41928")="\0.7\0"
	s ^TKSOLDES("41930")="\0.7\0"
	s ^TKSOLDES("41931")="\0.7\0"
	s ^TKSOLDES("41950")="\0.7\0"
	s ^TKSOLDES("41966")="\0.7\0"
	s ^TKSOLDES("41980")="\0.7\0"
	s ^TKSOLDES("42039")="\0.7\0"
	s ^TKSOLDES("42043")="\0.7\0"
	s ^TKSOLDES("42044")="\0.7\0"
	s ^TKSOLDES("42047")="\0.7\0"
	s ^TKSOLDES("42048")="\0.7\0"
	s ^TKSOLDES("42051")="\0.7\0"
	s ^TKSOLDES("42052")="\0.7\0"
	s ^TKSOLDES("42053")="\0.7\0"
	s ^TKSOLDES("42054")="\0.7\0"
	s ^TKSOLDES("42056")="\0.7\0"
	s ^TKSOLDES("42081")="\0.7\0"
	s ^TKSOLDES("42087")="\0.7\0"
	s ^TKSOLDES("42126")="\0.7\0"
	s ^TKSOLDES("42131")="\0.7\0"
	s ^TKSOLDES("42137")="\0.7\0"
	s ^TKSOLDES("42202")="\0.7\0"
	s ^TKSOLDES("42206")="\0.7\0"
	s ^TKSOLDES("42242")="\0.7\0"
	s ^TKSOLDES("42243")="\0.7\0"
	s ^TKSOLDES("42244")="\0.7\0"
	s ^TKSOLDES("42263")="\0.7\0"
	s ^TKSOLDES("42274")="\0.7\0"
	s ^TKSOLDES("42275")="\0.7\0"
	s ^TKSOLDES("42277")="\0.7\0"
	s ^TKSOLDES("42278")="\0.7\0"
	s ^TKSOLDES("42279")="\0.7\0"
	s ^TKSOLDES("42626")="\0.7\0"
	s ^TKSOLDES("42697")="\0.7\0"
	s ^TKSOLDES("42817")="\0.7\0"
	s ^TKSOLDES("42819")="\0.7\0"
	s ^TKSOLDES("42864")="\0.7\0"
	s ^TKSOLDES("42988")="\0.7\0"
	s ^TKSOLDES("42989")="\0.7\0"
	s ^TKSOLDES("43001")="\0.7\0"
	s ^TKSOLDES("43036")="\0.7\0"
	s ^TKSOLDES("43044")="\0.7\0"
	s ^TKSOLDES("43067")="\0.7\0"
	s ^TKSOLDES("43082")="\0.7\0"
	s ^TKSOLDES("43088")="\0.7\0"
	s ^TKSOLDES("43098")="\0.7\0"
	s ^TKSOLDES("43103")="\0.7\0"
	s ^TKSOLDES("43201")="\0.7\0"
	s ^TKSOLDES("43222")="\0.7\0"
	s ^TKSOLDES("43308")="\0.7\0"
	s ^TKSOLDES("43843")="\0.7\0"
	s ^TKSOLDES("44080")="\0.7\0"
	s ^TKSOLDES("44092")="\0.7\0"
	s ^TKSOLDES("44102")="\0.7\0"
	s ^TKSOLDES("44111")="\0.7\0"
	s ^TKSOLDES("44117")="\0.7\0"
	s ^TKSOLDES("44255")="\0.7\0"
	s ^TKSOLDES("44263")="\0.7\0"
	s ^TKSOLDES("45715")="\0.7\0"
	s ^TKSOLDES("45716")="\0.7\0"
	s ^TKSOLDES("45723")="\0.7\0"
	s ^TKSOLDES("45731")="\0.7\0"
	s ^TKSOLDES("45732")="\0.7\0"
	s ^TKSOLDES("45736")="\0.7\0"
	s ^TKSOLDES("45742")="\0.7\0"
	s ^TKSOLDES("45745")="\0.7\0"
	s ^TKSOLDES("45748")="\0.7\0"
	s ^TKSOLDES("45755")="\0.7\0"
	s ^TKSOLDES("45760")="\0.7\0"
	s ^TKSOLDES("45761")="\0.7\0"
	s ^TKSOLDES("45765")="\0.7\0"
	s ^TKSOLDES("45770")="\0.7\0"
	s ^TKSOLDES("45772")="\0.7\0"
	s ^TKSOLDES("45776")="\0.7\0"
	s ^TKSOLDES("45790")="\0.7\0"
	s ^TKSOLDES("45791")="\0.7\0"
	s ^TKSOLDES("45824")="\0.7\0"
	s ^TKSOLDES("45979")="\0.7\0"
	s ^TKSOLDES("45982")="\0.7\0"
	s ^TKSOLDES("46025")="\0.7\0"
	s ^TKSOLDES("46039")="\0.7\0"
	s ^TKSOLDES("46044")="\0.7\0"
	s ^TKSOLDES("46091")="\0.7\0"
	s ^TKSOLDES("46101")="\0.7\0"
	s ^TKSOLDES("46107")="\0.7\0"
	s ^TKSOLDES("46130")="\0.7\0"
	s ^TKSOLDES("46133")="\0.7\0"
	s ^TKSOLDES("46178")="\0.7\0"
	s ^TKSOLDES("46190")="\0.7\0"
	s ^TKSOLDES("46202")="\0.7\0"
	s ^TKSOLDES("46215")="\0.7\0"
	s ^TKSOLDES("46217")="\0.7\0"
	s ^TKSOLDES("46228")="\0.7\0"
	s ^TKSOLDES("46260")="\0.7\0"
	s ^TKSOLDES("46294")="\0.7\0"
	s ^TKSOLDES("46298")="\0.7\0"
	s ^TKSOLDES("46304")="\0.7\0"
	s ^TKSOLDES("46311")="\0.7\0"
	s ^TKSOLDES("46345")="\0.7\0"
	s ^TKSOLDES("46391")="\0.7\0"
	s ^TKSOLDES("46396")="\0.7\0"
	s ^TKSOLDES("46398")="\0.7\0"
	s ^TKSOLDES("46478")="\0.7\0"
	s ^TKSOLDES("46479")="\0.7\0"
	s ^TKSOLDES("46821")="\0.7\0"
	s ^TKSOLDES("46824")="\0.7\0"
	s ^TKSOLDES("46837")="\0.7\0"
	s ^TKSOLDES("46842")="\0.7\0"
	s ^TKSOLDES("46854")="\0.7\0"
	s ^TKSOLDES("46861")="\0.7\0"
	s ^TKSOLDES("46862")="\0.7\0"
	s ^TKSOLDES("47045")="\0.7\0"
	s ^TKSOLDES("47742")="\0.7\0"
	s ^TKSOLDES("48586")="\0.7\0"
	s ^TKSOLDES("48587")="\0.7\0"
	s ^TKSOLDES("48603")="\0.7\0"
	s ^TKSOLDES("48745")="\0.7\0"
	s ^TKSOLDES("48752")="\0.7\0"
	s ^TKSOLDES("48863")="\0.7\0"
	s ^TKSOLDES("48959")="\0.7\0"
	s ^TKSOLDES("49169")="\0.7\0"
	s ^TKSOLDES("49374")="\0.7\0"
	s ^TKSOLDES("49389")="\0.7\0"
	s ^TKSOLDES("49392")="\0.7\0"
	s ^TKSOLDES("49413")="\0.7\0"
	s ^TKSOLDES("50668")="\0.7\0"
	s ^TKSOLDES("51282")="\0.7\0"
	s ^TKSOLDES("51283")="\0.7\0"
	s ^TKSOLDES("51293")="\0.7\0"
	s ^TKSOLDES("51333")="\0.7\0"
	s ^TKSOLDES("51882")="\0.7\0"
	s ^TKSOLDES("52158")="\0.7\0"
	s ^TKSOLDES("52177")="\0.7\0"
	s ^TKSOLDES("52357")="\0.7\0"
	s ^TKSOLDES("52359")="\0.7\0"
	s ^TKSOLDES("52401")="\0.7\0"
	s ^TKSOLDES("53164")="\0.7\0"
	s ^TKSOLDES("53745")="\0.7\0"
	s ^TKSOLDES("53747")="\0.7\0"
	s ^TKSOLDES("53755")="\0.7\0"
	s ^TKSOLDES("53760")="\0.7\0"
	s ^TKSOLDES("53761")="\0.7\0"
	s ^TKSOLDES("53776")="\0.7\0"
	s ^TKSOLDES("53782")="\0.7\0"
	s ^TKSOLDES("53807")="\0.7\0"
	s ^TKSOLDES("53827")="\0.7\0"
	s ^TKSOLDES("53828")="\0.7\0"
	s ^TKSOLDES("53854")="\0.7\0"
	s ^TKSOLDES("54134")="\0.7\0"
	s ^TKSOLDES("54375")="\0.7\0"
	s ^TKSOLDES("54536")="\0.7\0"
	s ^TKSOLDES("54781")="\0.7\0"
	s ^TKSOLDES("54949")="\0.7\0"
	s ^TKSOLDES("55308")="\0.7\0"
	s ^TKSOLDES("55652")="\0.7\0"
	s ^TKSOLDES("55659")="\0.7\0"
	s ^TKSOLDES("55663")="\0.7\0"
	s ^TKSOLDES("55666")="\0.7\0"
	s ^TKSOLDES("55682")="\0.7\0"
	s ^TKSOLDES("55685")="\0.7\0"
	s ^TKSOLDES("55686")="\0.7\0"
	s ^TKSOLDES("55687")="\0.7\0"
	s ^TKSOLDES("55690")="\0.7\0"
	s ^TKSOLDES("55703")="\0.7\0"
	s ^TKSOLDES("55704")="\0.7\0"
	s ^TKSOLDES("55717")="\0.7\0"
	s ^TKSOLDES("56094")="\0.7\0"
	s ^TKSOLDES("56714")="\0.7\0"
	s ^TKSOLDES("56722")="\0.7\0"
	s ^TKSOLDES("56747")="\0.7\0"
	s ^TKSOLDES("56749")="\0.7\0"
	s ^TKSOLDES("56984")="\0.7\0"
	s ^TKSOLDES("57119")="\0.7\0"
	s ^TKSOLDES("57147")="\0.7\0"
	s ^TKSOLDES("57292")="\0.7\0"
	s ^TKSOLDES("57314")="\0.7\0"
	s ^TKSOLDES("57335")="\0.7\0"
	s ^TKSOLDES("58008")="\0.7\0"
	s ^TKSOLDES("58041")="\0.7\0"
	s ^TKSOLDES("58076")="\0.7\0"
	s ^TKSOLDES("58105")="\0.7\0"
	s ^TKSOLDES("59019")="\0.7\0"
	s ^TKSOLDES("59029")="\0.7\0"
	s ^TKSOLDES("59098")="\0.7\0"
	s ^TKSOLDES("59105")="\0.7\0"
	s ^TKSOLDES("59755")="\0.7\0"
	s ^TKSOLDES("60651")="\0.7\0"
	s ^TKSOLDES("60662")="\0.7\0"
	s ^TKSOLDES("60665")="\0.7\0"
	s ^TKSOLDES("60666")="\0.7\0"
	s ^TKSOLDES("60696")="\0.7\0"
	s ^TKSOLDES("61042")="\0.7\0"
	s ^TKSOLDES("61431")="\0.7\0"
	s ^TKSOLDES("62247")="\0.7\0"
	s ^TKSOLDES("62280")="\0.7\0"
	s ^TKSOLDES("63404")="\0.7\0"
	s ^TKSOLDES("63417")="\0.7\0"
	s ^TKSOLDES("63423")="\0.7\0"
	s ^TKSOLDES("63680")="\0.7\0"
	s ^TKSOLDES("63688")="\0.7\0"
	s ^TKSOLDES("63690")="\0.7\0"
	s ^TKSOLDES("63691")="\0.7\0"
	s ^TKSOLDES("63838")="\0.7\0"
	s ^TKSOLDES("63882")="\0.7\0"
	s ^TKSOLDES("64037")="\0.7\0"
	s ^TKSOLDES("64042")="\0.7\0"
	s ^TKSOLDES("64053")="\0.7\0"
	s ^TKSOLDES("64059")="\0.7\0"
	s ^TKSOLDES("64112")="\0.7\0"
	s ^TKSOLDES("64163")="\0.7\0"
	s ^TKSOLDES("64215")="\0.7\0"
	s ^TKSOLDES("64224")="\0.7\0"
	s ^TKSOLDES("64273")="\0.7\0"
	s ^TKSOLDES("64286")="\0.7\0"
	s ^TKSOLDES("64291")="\0.7\0"
	s ^TKSOLDES("64302")="\0.7\0"
	s ^TKSOLDES("64306")="\0.7\0"
	s ^TKSOLDES("64385")="\0.7\0"
	s ^TKSOLDES("92080")="\0.7\0"
	s ^TKSOLDES("64746")="\0.7\0"
	s ^TKSOLDES("64749")="\0.7\0"
	s ^TKSOLDES("64752")="\0.7\0"
	s ^TKSOLDES("64758")="\0.7\0"
	s ^TKSOLDES("65563")="\0.7\0"
	s ^TKSOLDES("65588")="\0.7\0"
	s ^TKSOLDES("65625")="\0.7\0"
	s ^TKSOLDES("65694")="\0.7\0"
	s ^TKSOLDES("65710")="\0.7\0"
	s ^TKSOLDES("65759")="\0.7\0"
	s ^TKSOLDES("65765")="\0.7\0"
	s ^TKSOLDES("65778")="\0.7\0"
	s ^TKSOLDES("65854")="\0.7\0"
	s ^TKSOLDES("65878")="\0.7\0"
	s ^TKSOLDES("65916")="\0.7\0"
	s ^TKSOLDES("65925")="\0.7\0"
	s ^TKSOLDES("65937")="\0.7\0"
	s ^TKSOLDES("65947")="\0.7\0"
	s ^TKSOLDES("66002")="\0.7\0"
	s ^TKSOLDES("66003")="\0.7\0"
	s ^TKSOLDES("66032")="\0.7\0"
	s ^TKSOLDES("66039")="\0.7\0"
	s ^TKSOLDES("66053")="\0.7\0"
	s ^TKSOLDES("66072")="\0.7\0"
	s ^TKSOLDES("66098")="\0.7\0"
	s ^TKSOLDES("66158")="\0.7\0"
	s ^TKSOLDES("67004")="\0.7\0"
	s ^TKSOLDES("67389")="\0.7\0"
	s ^TKSOLDES("67643")="\0.7\0"
	s ^TKSOLDES("67651")="\0.7\0"
	s ^TKSOLDES("67664")="\0.7\0"
	s ^TKSOLDES("67667")="\0.7\0"
	s ^TKSOLDES("67943")="\0.7\0"
	s ^TKSOLDES("67950")="\0.7\0"
	s ^TKSOLDES("67966")="\0.7\0"
	s ^TKSOLDES("68182")="\0.7\0"
	s ^TKSOLDES("68216")="\0.7\0"
	s ^TKSOLDES("68222")="\0.7\0"
	s ^TKSOLDES("68224")="\0.7\0"
	s ^TKSOLDES("68238")="\0.7\0"
	s ^TKSOLDES("68293")="\0.7\0"
	s ^TKSOLDES("69203")="\0.7\0"
	s ^TKSOLDES("70259")="\0.7\0"
	s ^TKSOLDES("70336")="\0.7\0"
	s ^TKSOLDES("70340")="\0.7\0"
	s ^TKSOLDES("70347")="\0.7\0"
	s ^TKSOLDES("70351")="\0.7\0"
	s ^TKSOLDES("70354")="\0.7\0"
	s ^TKSOLDES("70361")="\0.7\0"
	s ^TKSOLDES("70368")="\0.7\0"
	s ^TKSOLDES("70379")="\0.7\0"
	s ^TKSOLDES("70380")="\0.7\0"
	s ^TKSOLDES("70383")="\0.7\0"
	s ^TKSOLDES("70389")="\0.7\0"
	s ^TKSOLDES("70390")="\0.7\0"
	s ^TKSOLDES("70391")="\0.7\0"
	s ^TKSOLDES("70393")="\0.7\0"
	s ^TKSOLDES("70402")="\0.7\0"
	s ^TKSOLDES("70403")="\0.7\0"
	s ^TKSOLDES("70405")="\0.7\0"
	s ^TKSOLDES("70409")="\0.7\0"
	s ^TKSOLDES("70411")="\0.7\0"
	s ^TKSOLDES("70419")="\0.7\0"
	s ^TKSOLDES("70423")="\0.7\0"
	s ^TKSOLDES("70425")="\0.7\0"
	s ^TKSOLDES("70444")="\0.7\0"
	s ^TKSOLDES("70450")="\0.7\0"
	s ^TKSOLDES("70526")="\0.7\0"
	s ^TKSOLDES("70533")="\0.7\0"
	s ^TKSOLDES("70545")="\0.7\0"
	s ^TKSOLDES("70643")="\0.7\0"
	s ^TKSOLDES("70648")="\0.7\0"
	s ^TKSOLDES("70671")="\0.7\0"
	s ^TKSOLDES("70707")="\0.7\0"
	s ^TKSOLDES("70817")="\0.7\0"
	s ^TKSOLDES("70859")="\0.7\0"
	s ^TKSOLDES("71718")="\0.7\0"
	s ^TKSOLDES("72876")="\0.7\0"
	s ^TKSOLDES("72911")="\0.7\0"
	s ^TKSOLDES("73032")="\0.7\0"
	s ^TKSOLDES("73538")="\0.7\0"
	s ^TKSOLDES("73592")="\0.7\0"
	s ^TKSOLDES("73737")="\0.7\0"
	s ^TKSOLDES("74115")="\0.7\0"
	s ^TKSOLDES("74653")="\0.7\0"
	s ^TKSOLDES("75038")="\0.7\0"
	s ^TKSOLDES("76470")="\0.7\0"
	s ^TKSOLDES("76636")="\0.7\0"
	s ^TKSOLDES("77027")="\0.7\0"
	s ^TKSOLDES("77051")="\0.7\0"
	s ^TKSOLDES("77066")="\0.7\0"
	s ^TKSOLDES("77070")="\0.7\0"
	s ^TKSOLDES("77148")="\0.7\0"
	s ^TKSOLDES("77851")="\0.7\0"
	s ^TKSOLDES("78181")="\0.7\0"
	s ^TKSOLDES("78216")="\0.7\0"
	s ^TKSOLDES("78344")="\0.7\0"
	s ^TKSOLDES("78791")="\0.7\0"
	s ^TKSOLDES("78834")="\0.7\0"
	s ^TKSOLDES("79143")="\0.7\0"
	s ^TKSOLDES("79179")="\0.7\0"
	s ^TKSOLDES("79273")="\0.7\0"
	s ^TKSOLDES("79291")="\0.7\0"
	s ^TKSOLDES("79298")="\0.7\0"
	s ^TKSOLDES("79574")="\0.7\0"
	s ^TKSOLDES("80203")="\0.7\0"
	s ^TKSOLDES("80209")="\0.7\0"
	s ^TKSOLDES("81207")="\0.7\0"
	s ^TKSOLDES("81231")="\0.7\0"
	s ^TKSOLDES("81233")="\0.7\0"
	s ^TKSOLDES("81235")="\0.7\0"
	s ^TKSOLDES("81271")="\0.7\0"
	s ^TKSOLDES("81403")="\0.7\0"
	s ^TKSOLDES("81649")="\0.7\0"
	s ^TKSOLDES("81652")="\0.7\0"
	s ^TKSOLDES("81657")="\0.7\0"
	s ^TKSOLDES("81705")="\0.7\0"
	s ^TKSOLDES("82096")="\0.7\0"
	s ^TKSOLDES("82097")="\0.7\0"
	s ^TKSOLDES("82104")="\0.7\0"
	s ^TKSOLDES("82134")="\0.7\0"
	s ^TKSOLDES("82589")="\0.7\0"
	s ^TKSOLDES("82609")="\0.7\0"
	s ^TKSOLDES("82658")="\0.7\0"
	s ^TKSOLDES("82660")="\0.7\0"
	s ^TKSOLDES("82668")="\0.7\0"
	s ^TKSOLDES("82690")="\0.7\0"
	s ^TKSOLDES("82917")="\0.7\0"
	s ^TKSOLDES("83085")="\0.7\0"
	s ^TKSOLDES("83123")="\0.7\0"
	s ^TKSOLDES("83362")="\0.7\0"
	s ^TKSOLDES("83392")="\0.7\0"
	s ^TKSOLDES("83401")="\0.7\0"
	s ^TKSOLDES("83414")="\0.7\0"
	s ^TKSOLDES("83419")="\0.7\0"
	s ^TKSOLDES("83440")="\0.7\0"
	s ^TKSOLDES("83454")="\0.7\0"
	s ^TKSOLDES("83487")="\0.7\0"
	s ^TKSOLDES("83884")="\0.7\0"
	s ^TKSOLDES("83894")="\0.7\0"
	s ^TKSOLDES("83901")="\0.7\0"
	s ^TKSOLDES("84818")="\0.7\0"
	s ^TKSOLDES("85008")="\0.7\0"
	s ^TKSOLDES("85774")="\0.7\0"
	s ^TKSOLDES("85821")="\0.7\0"
	s ^TKSOLDES("87364")="\0.7\0"
	s ^TKSOLDES("87637")="\0.7\0"
	s ^TKSOLDES("87721")="\0.7\0"
	s ^TKSOLDES("87723")="\0.7\0"
	s ^TKSOLDES("87726")="\0.7\0"
	s ^TKSOLDES("87732")="\0.7\0"
	s ^TKSOLDES("87745")="\0.7\0"
	s ^TKSOLDES("87825")="\0.7\0"
	s ^TKSOLDES("88109")="\0.7\0"
	s ^TKSOLDES("88510")="\0.7\0"
	s ^TKSOLDES("88547")="\0.7\0"
	s ^TKSOLDES("88577")="\0.7\0"
	s ^TKSOLDES("88578")="\0.7\0"
	s ^TKSOLDES("88584")="\0.7\0"
	s ^TKSOLDES("100158")="\0.7\0"
	s ^TKSOLDES("100321")="\0.7\0"
	s ^TKSOLDES("100386")="\0.7\0"
	s ^TKSOLDES("100462")="\0.7\0"
	s ^TKSOLDES("100487")="\0.7\0"
	s ^TKSOLDES("100495")="\0.7\0"
	s ^TKSOLDES("100530")="\0.7\0"
	s ^TKSOLDES("100549")="\0.7\0"
	s ^TKSOLDES("101772")="\0.7\0"
	s ^TKSOLDES("102499")="\0.7\0"
	s ^TKSOLDES("102509")="\0.7\0"
	s ^TKSOLDES("102938")="\0.7\0"
	s ^TKSOLDES("102959")="\0.7\0"
	s ^TKSOLDES("102969")="\0.7\0"
	s ^TKSOLDES("102972")="\0.7\0"
	s ^TKSOLDES("104733")="\0.7\0"
	s ^TKSOLDES("105153")="\0.7\0"
	s ^TKSOLDES("105161")="\0.7\0"
	s ^TKSOLDES("105257")="\0.7\0"
	s ^TKSOLDES("105468")="\0.7\0"
	s ^TKSOLDES("105484")="\0.7\0"
	s ^TKSOLDES("106112")="\0.7\0"
	s ^TKSOLDES("82757")="\0.7\0"
	s ^TKSOLDES("87843")="\0.7\0"
	s ^TKSOLDES("76630")="\0.7\0"
	s ^TKSOLDES("81916")="\0.7\0"
	s ^TKSOLDES("83998")="\0.7\0"
	s ^TKSOLDES("107658")="\0.7\0"
	s ^TKSOLDES("46908")="\0.7\0"
	s ^TKSOLDES("82775")="\0.7\0"
	s ^TKSOLDES("59681")="\0.7\0"
	s ^TKSOLDES("78978")="\0.7\0"
	s ^TKSOLDES("79526")="\0.7\0"
	s ^TKSOLDES("8335")="\0.7\0"
	s ^TKSOLDES("41723")="\0.7\0"
	s ^TKSOLDES("90919")="\0.7\0"
	s ^TKSOLDES("77421")="\0.7\0"
	s ^TKSOLDES("77425")="\0.7\0"
	s ^TKSOLDES("77683")="\0.7\0"
	s ^TKSOLDES("79645")="\0.7\0"
	s ^TKSOLDES("81426")="\0.7\0"
	s ^TKSOLDES("82766")="\0.7\0"
	s ^TKSOLDES("84003")="\0.7\0"
	s ^TKSOLDES("85778")="\0.7\0"
	s ^TKSOLDES("104910")="\0.7\0"
	s ^TKSOLDES("73700")="\0.7\0"
	s ^TKSOLDES("77912")="\0.7\0"
	s ^TKSOLDES("78815")="\0.7\0"
	s ^TKSOLDES("100105")="\0.7\0"
	s ^TKSOLDES("83968")="\0.7\0"
	s ^TKSOLDES("85052")="\0.7\0"
	s ^TKSOLDES("101555")="\0.7\0"
	s ^TKSOLDES("59686")="\0.7\0"
	s ^TKSOLDES("82759")="\0.7\0"
	s ^TKSOLDES("91273")="\0.7\0"
	s ^TKSOLDES("2741")="\0.7\0"
	s ^TKSOLDES("3684")="\0.7\0"
	s ^TKSOLDES("6704")="\0.7\0"
	s ^TKSOLDES("9306")="\0.7\0"
	s ^TKSOLDES("12670")="\0.7\0"
	s ^TKSOLDES("12682")="\0.7\0"
	s ^TKSOLDES("12687")="\0.7\0"
	s ^TKSOLDES("12689")="\0.7\0"
	s ^TKSOLDES("12692")="\0.7\0"
	s ^TKSOLDES("12728")="\0.7\0"
	s ^TKSOLDES("12732")="\0.7\0"
	s ^TKSOLDES("12743")="\0.7\0"
	s ^TKSOLDES("12745")="\0.7\0"
	s ^TKSOLDES("12747")="\0.7\0"
	s ^TKSOLDES("12893")="\0.7\0"
	s ^TKSOLDES("13018")="\0.7\0"
	s ^TKSOLDES("13027")="\0.7\0"
	s ^TKSOLDES("13057")="\0.7\0"
	s ^TKSOLDES("13092")="\0.7\0"
	s ^TKSOLDES("13106")="\0.7\0"
	s ^TKSOLDES("13123")="\0.7\0"
	s ^TKSOLDES("13125")="\0.7\0"
	s ^TKSOLDES("13135")="\0.7\0"
	s ^TKSOLDES("13159")="\0.7\0"
	s ^TKSOLDES("13175")="\0.7\0"
	s ^TKSOLDES("13177")="\0.7\0"
	s ^TKSOLDES("13293")="\0.7\0"
	s ^TKSOLDES("13373")="\0.7\0"
	s ^TKSOLDES("13389")="\0.7\0"
	s ^TKSOLDES("13840")="\0.7\0"
	s ^TKSOLDES("13847")="\0.7\0"
	s ^TKSOLDES("13848")="\0.7\0"
	s ^TKSOLDES("13857")="\0.7\0"
	s ^TKSOLDES("13859")="\0.7\0"
	s ^TKSOLDES("13866")="\0.7\0"
	s ^TKSOLDES("13867")="\0.7\0"
	s ^TKSOLDES("13879")="\0.7\0"
	s ^TKSOLDES("13883")="\0.7\0"
	s ^TKSOLDES("13888")="\0.7\0"
	s ^TKSOLDES("14121")="\0.7\0"
	s ^TKSOLDES("14125")="\0.7\0"
	s ^TKSOLDES("14133")="\0.7\0"
	s ^TKSOLDES("14261")="\0.7\0"
	s ^TKSOLDES("14376")="\0.7\0"
	s ^TKSOLDES("14477")="\0.7\0"
	s ^TKSOLDES("14578")="\0.7\0"
	s ^TKSOLDES("14590")="\0.7\0"
	s ^TKSOLDES("14788")="\0.7\0"
	s ^TKSOLDES("14794")="\0.7\0"
	s ^TKSOLDES("14812")="\0.7\0"
	s ^TKSOLDES("14814")="\0.7\0"
	s ^TKSOLDES("15021")="\0.7\0"
	s ^TKSOLDES("15058")="\0.7\0"
	s ^TKSOLDES("15098")="\0.7\0"
	s ^TKSOLDES("15101")="\0.7\0"
	s ^TKSOLDES("15112")="\0.7\0"
	s ^TKSOLDES("15117")="\0.7\0"
	s ^TKSOLDES("15125")="\0.7\0"
	s ^TKSOLDES("15130")="\0.7\0"
	s ^TKSOLDES("15133")="\0.7\0"
	s ^TKSOLDES("15179")="\0.7\0"
	s ^TKSOLDES("15196")="\0.7\0"
	s ^TKSOLDES("15215")="\0.7\0"
	s ^TKSOLDES("15337")="\0.7\0"
	s ^TKSOLDES("15350")="\0.7\0"
	s ^TKSOLDES("15357")="\0.7\0"
	s ^TKSOLDES("15379")="\0.7\0"
	s ^TKSOLDES("15380")="\0.7\0"
	s ^TKSOLDES("15396")="\0.7\0"
	s ^TKSOLDES("15463")="\0.7\0"
	s ^TKSOLDES("15471")="\0.7\0"
	s ^TKSOLDES("15538")="\0.7\0"
	s ^TKSOLDES("15545")="\0.7\0"
	s ^TKSOLDES("15594")="\0.7\0"
	s ^TKSOLDES("15597")="\0.7\0"
	s ^TKSOLDES("15600")="\0.7\0"
	s ^TKSOLDES("15698")="\0.7\0"
	s ^TKSOLDES("16125")="\0.7\0"
	s ^TKSOLDES("16133")="\0.7\0"
	s ^TKSOLDES("16147")="\0.7\0"
	s ^TKSOLDES("16391")="\0.7\0"
	s ^TKSOLDES("16394")="\0.7\0"
	s ^TKSOLDES("16398")="\0.7\0"
	s ^TKSOLDES("16409")="\0.7\0"
	s ^TKSOLDES("16460")="\0.7\0"
	s ^TKSOLDES("17262")="\0.7\0"
	s ^TKSOLDES("17711")="\0.7\0"
	s ^TKSOLDES("17718")="\0.7\0"
	s ^TKSOLDES("18264")="\0.7\0"
	s ^TKSOLDES("18276")="\0.7\0"
	s ^TKSOLDES("18309")="\0.7\0"
	s ^TKSOLDES("18345")="\0.7\0"
	s ^TKSOLDES("18393")="\0.7\0"
	s ^TKSOLDES("18394")="\0.7\0"
	s ^TKSOLDES("34945")="\0.7\0"
	s ^TKSOLDES("12611")="\0.7\0"
	s ^TKSOLDES("13620")="\0.7\0"
	s ^TKSOLDES("13639")="\0.7\0"
	s ^TKSOLDES("13665")="\0.7\0"
	s ^TKSOLDES("13703")="\0.7\0"
	s ^TKSOLDES("13705")="\0.7\0"
	s ^TKSOLDES("13715")="\0.7\0"
	s ^TKSOLDES("13721")="\0.7\0"
	s ^TKSOLDES("13722")="\0.7\0"
	s ^TKSOLDES("13734")="\0.7\0"
	s ^TKSOLDES("14162")="\0.7\0"
	s ^TKSOLDES("14211")="\0.7\0"
	s ^TKSOLDES("16273")="\0.7\0"
	s ^TKSOLDES("16691")="\0.7\0"
	s ^TKSOLDES("16749")="\0.7\0"
	s ^TKSOLDES("16752")="\0.7\0"
	s ^TKSOLDES("16753")="\0.7\0"
	s ^TKSOLDES("17508")="\0.7\0"
	s ^TKSOLDES("17518")="\0.7\0"
	s ^TKSOLDES("17551")="\0.7\0"
	s ^TKSOLDES("17609")="\0.7\0"
	s ^TKSOLDES("17613")="\0.7\0"
	s ^TKSOLDES("34923")="\0.7\0"
	s ^TKSOLDES("35127")="\0.7\0"
	s ^TKSOLDES("35274")="\0.7\0"
	s ^TKSOLDES("35555")="\0.7\0"
	s ^TKSOLDES("35563")="\0.7\0"
	s ^TKSOLDES("35564")="\0.7\0"
	s ^TKSOLDES("36010")="\0.7\0"
	s ^TKSOLDES("36013")="\0.7\0"
	s ^TKSOLDES("36032")="\0.7\0"
	s ^TKSOLDES("37227")="\0.7\0"
	s ^TKSOLDES("37230")="\0.7\0"
	s ^TKSOLDES("37250")="\0.7\0"
	s ^TKSOLDES("38353")="\0.7\0"
	s ^TKSOLDES("38363")="\0.7\0"
	s ^TKSOLDES("38415")="\0.7\0"
	s ^TKSOLDES("38416")="\0.7\0"
	s ^TKSOLDES("38420")="\0.7\0"
	s ^TKSOLDES("38447")="\0.7\0"
	s ^TKSOLDES("39997")="\0.7\0"
	s ^TKSOLDES("40100")="\0.7\0"
	s ^TKSOLDES("40779")="\0.7\0"
	s ^TKSOLDES("41127")="\0.7\0"
	s ^TKSOLDES("41283")="\0.7\0"
	s ^TKSOLDES("41306")="\0.7\0"
	s ^TKSOLDES("41502")="\0.7\0"
	s ^TKSOLDES("41503")="\0.7\0"
	s ^TKSOLDES("41509")="\0.7\0"
	s ^TKSOLDES("41640")="\0.7\0"
	s ^TKSOLDES("41646")="\0.7\0"
	s ^TKSOLDES("41660")="\0.7\0"
	s ^TKSOLDES("41765")="\0.7\0"
	s ^TKSOLDES("41775")="\0.7\0"
	s ^TKSOLDES("41777")="\0.7\0"
	s ^TKSOLDES("41790")="\0.7\0"
	s ^TKSOLDES("41792")="\0.7\0"
	s ^TKSOLDES("41795")="\0.7\0"
	s ^TKSOLDES("41853")="\0.7\0"
	s ^TKSOLDES("41861")="\0.7\0"
	s ^TKSOLDES("41863")="\0.7\0"
	s ^TKSOLDES("41883")="\0.7\0"
	s ^TKSOLDES("41889")="\0.7\0"
	s ^TKSOLDES("41891")="\0.7\0"
	s ^TKSOLDES("41896")="\0.7\0"
	s ^TKSOLDES("41925")="\0.7\0"
	s ^TKSOLDES("41940")="\0.7\0"
	s ^TKSOLDES("41962")="\0.7\0"
	s ^TKSOLDES("41970")="\0.7\0"
	s ^TKSOLDES("41976")="\0.7\0"
	s ^TKSOLDES("41983")="\0.7\0"
	s ^TKSOLDES("42017")="\0.7\0"
	s ^TKSOLDES("42038")="\0.7\0"
	s ^TKSOLDES("42046")="\0.7\0"
	s ^TKSOLDES("42138")="\0.7\0"
	s ^TKSOLDES("42156")="\0.7\0"
	s ^TKSOLDES("42194")="\0.7\0"
	s ^TKSOLDES("42200")="\0.7\0"
	s ^TKSOLDES("42208")="\0.7\0"
	s ^TKSOLDES("42209")="\0.7\0"
	s ^TKSOLDES("42222")="\0.7\0"
	s ^TKSOLDES("42236")="\0.7\0"
	s ^TKSOLDES("42245")="\0.7\0"
	s ^TKSOLDES("42246")="\0.7\0"
	s ^TKSOLDES("42257")="\0.7\0"
	s ^TKSOLDES("42269")="\0.7\0"
	s ^TKSOLDES("42428")="\0.7\0"
	s ^TKSOLDES("42434")="\0.7\0"
	s ^TKSOLDES("42666")="\0.7\0"
	s ^TKSOLDES("42855")="\0.7\0"
	s ^TKSOLDES("42985")="\0.7\0"
	s ^TKSOLDES("42998")="\0.7\0"
	s ^TKSOLDES("43008")="\0.7\0"
	s ^TKSOLDES("43026")="\0.7\0"
	s ^TKSOLDES("43035")="\0.7\0"
	s ^TKSOLDES("43041")="\0.7\0"
	s ^TKSOLDES("43045")="\0.7\0"
	s ^TKSOLDES("43054")="\0.7\0"
	s ^TKSOLDES("43075")="\0.7\0"
	s ^TKSOLDES("43076")="\0.7\0"
	s ^TKSOLDES("43101")="\0.7\0"
	s ^TKSOLDES("43150")="\0.7\0"
	s ^TKSOLDES("43196")="\0.7\0"
	s ^TKSOLDES("43207")="\0.7\0"
	s ^TKSOLDES("43215")="\0.7\0"
	s ^TKSOLDES("43240")="\0.7\0"
	s ^TKSOLDES("43253")="\0.7\0"
	s ^TKSOLDES("43263")="\0.7\0"
	s ^TKSOLDES("43266")="\0.7\0"
	s ^TKSOLDES("43267")="\0.7\0"
	s ^TKSOLDES("43287")="\0.7\0"
	s ^TKSOLDES("43297")="\0.7\0"
	s ^TKSOLDES("44068")="\0.7\0"
	s ^TKSOLDES("44078")="\0.7\0"
	s ^TKSOLDES("44116")="\0.7\0"
	s ^TKSOLDES("44142")="\0.7\0"
	s ^TKSOLDES("44145")="\0.7\0"
	s ^TKSOLDES("44254")="\0.7\0"
	s ^TKSOLDES("44260")="\0.7\0"
	s ^TKSOLDES("44282")="\0.7\0"
	s ^TKSOLDES("45415")="\0.7\0"
	s ^TKSOLDES("45424")="\0.7\0"
	s ^TKSOLDES("45710")="\0.7\0"
	s ^TKSOLDES("45718")="\0.7\0"
	s ^TKSOLDES("45722")="\0.7\0"
	s ^TKSOLDES("45728")="\0.7\0"
	s ^TKSOLDES("45739")="\0.7\0"
	s ^TKSOLDES("45750")="\0.7\0"
	s ^TKSOLDES("45757")="\0.7\0"
	s ^TKSOLDES("45764")="\0.7\0"
	s ^TKSOLDES("45769")="\0.7\0"
	s ^TKSOLDES("45779")="\0.7\0"
	s ^TKSOLDES("45783")="\0.7\0"
	s ^TKSOLDES("45786")="\0.7\0"
	s ^TKSOLDES("45804")="\0.7\0"
	s ^TKSOLDES("45826")="\0.7\0"
	s ^TKSOLDES("45827")="\0.7\0"
	s ^TKSOLDES("45890")="\0.7\0"
	s ^TKSOLDES("45907")="\0.7\0"
	s ^TKSOLDES("46004")="\0.7\0"
	s ^TKSOLDES("46019")="\0.7\0"
	s ^TKSOLDES("46035")="\0.7\0"
	s ^TKSOLDES("46042")="\0.7\0"
	s ^TKSOLDES("46048")="\0.7\0"
	s ^TKSOLDES("46098")="\0.7\0"
	s ^TKSOLDES("46108")="\0.7\0"
	s ^TKSOLDES("46124")="\0.7\0"
	s ^TKSOLDES("46134")="\0.7\0"
	s ^TKSOLDES("46149")="\0.7\0"
	s ^TKSOLDES("46170")="\0.7\0"
	s ^TKSOLDES("46176")="\0.7\0"
	s ^TKSOLDES("46188")="\0.7\0"
	s ^TKSOLDES("46195")="\0.7\0"
	s ^TKSOLDES("46198")="\0.7\0"
	s ^TKSOLDES("46263")="\0.7\0"
	s ^TKSOLDES("46287")="\0.7\0"
	s ^TKSOLDES("46289")="\0.7\0"
	s ^TKSOLDES("46292")="\0.7\0"
	s ^TKSOLDES("46293")="\0.7\0"
	s ^TKSOLDES("46297")="\0.7\0"
	s ^TKSOLDES("46340")="\0.7\0"
	s ^TKSOLDES("46357")="\0.7\0"
	s ^TKSOLDES("46365")="\0.7\0"
	s ^TKSOLDES("46374")="\0.7\0"
	s ^TKSOLDES("46387")="\0.7\0"
	s ^TKSOLDES("46388")="\0.7\0"
	s ^TKSOLDES("46397")="\0.7\0"
	s ^TKSOLDES("46406")="\0.7\0"
	s ^TKSOLDES("46416")="\0.7\0"
	s ^TKSOLDES("46471")="\0.7\0"
	s ^TKSOLDES("46839")="\0.7\0"
	s ^TKSOLDES("46846")="\0.7\0"
	s ^TKSOLDES("46855")="\0.7\0"
	s ^TKSOLDES("47099")="\0.7\0"
	s ^TKSOLDES("47103")="\0.7\0"
	s ^TKSOLDES("47105")="\0.7\0"
	s ^TKSOLDES("47120")="\0.7\0"
	s ^TKSOLDES("47127")="\0.7\0"
	s ^TKSOLDES("47290")="\0.7\0"
	s ^TKSOLDES("47740")="\0.7\0"
	s ^TKSOLDES("47910")="\0.7\0"
	s ^TKSOLDES("48580")="\0.7\0"
	s ^TKSOLDES("48583")="\0.7\0"
	s ^TKSOLDES("48606")="\0.7\0"
	s ^TKSOLDES("48622")="\0.7\0"
	s ^TKSOLDES("48624")="\0.7\0"
	s ^TKSOLDES("48674")="\0.7\0"
	s ^TKSOLDES("48686")="\0.7\0"
	s ^TKSOLDES("48690")="\0.7\0"
	s ^TKSOLDES("48695")="\0.7\0"
	s ^TKSOLDES("48712")="\0.7\0"
	s ^TKSOLDES("48739")="\0.7\0"
	s ^TKSOLDES("48829")="\0.7\0"
	s ^TKSOLDES("48915")="\0.7\0"
	s ^TKSOLDES("48933")="\0.7\0"
	s ^TKSOLDES("49044")="\0.7\0"
	s ^TKSOLDES("49149")="\0.7\0"
	s ^TKSOLDES("49150")="\0.7\0"
	s ^TKSOLDES("49161")="\0.7\0"
	s ^TKSOLDES("49203")="\0.7\0"
	s ^TKSOLDES("49208")="\0.7\0"
	s ^TKSOLDES("49209")="\0.7\0"
	s ^TKSOLDES("49210")="\0.7\0"
	s ^TKSOLDES("49211")="\0.7\0"
	s ^TKSOLDES("49264")="\0.7\0"
	s ^TKSOLDES("49267")="\0.7\0"
	s ^TKSOLDES("49385")="\0.7\0"
	s ^TKSOLDES("49399")="\0.7\0"
	s ^TKSOLDES("50385")="\0.7\0"
	s ^TKSOLDES("51257")="\0.7\0"
	s ^TKSOLDES("51284")="\0.7\0"
	s ^TKSOLDES("51312")="\0.7\0"
	s ^TKSOLDES("51322")="\0.7\0"
	s ^TKSOLDES("51883")="\0.7\0"
	s ^TKSOLDES("52117")="\0.7\0"
	s ^TKSOLDES("52371")="\0.7\0"
	s ^TKSOLDES("52383")="\0.7\0"
	s ^TKSOLDES("52405")="\0.7\0"
	s ^TKSOLDES("52499")="\0.7\0"
	s ^TKSOLDES("52523")="\0.7\0"
	s ^TKSOLDES("53753")="\0.7\0"
	s ^TKSOLDES("53815")="\0.7\0"
	s ^TKSOLDES("53843")="\0.7\0"
	s ^TKSOLDES("53853")="\0.7\0"
	s ^TKSOLDES("53863")="\0.7\0"
	s ^TKSOLDES("53866")="\0.7\0"
	s ^TKSOLDES("54118")="\0.7\0"
	s ^TKSOLDES("54164")="\0.7\0"
	s ^TKSOLDES("54179")="\0.7\0"
	s ^TKSOLDES("54182")="\0.7\0"
	s ^TKSOLDES("54191")="\0.7\0"
	s ^TKSOLDES("54217")="\0.7\0"
	s ^TKSOLDES("54833")="\0.7\0"
	s ^TKSOLDES("54868")="\0.7\0"
	s ^TKSOLDES("54874")="\0.7\0"
	s ^TKSOLDES("91772")="\0.7\0"
	s ^TKSOLDES("55664")="\0.7\0"
	s ^TKSOLDES("55665")="\0.7\0"
	s ^TKSOLDES("55668")="\0.7\0"
	s ^TKSOLDES("55672")="\0.7\0"
	s ^TKSOLDES("55681")="\0.7\0"
	s ^TKSOLDES("55683")="\0.7\0"
	s ^TKSOLDES("55718")="\0.7\0"
	s ^TKSOLDES("56108")="\0.7\0"
	s ^TKSOLDES("56119")="\0.7\0"
	s ^TKSOLDES("56133")="\0.7\0"
	s ^TKSOLDES("56981")="\0.7\0"
	s ^TKSOLDES("56987")="\0.7\0"
	s ^TKSOLDES("57017")="\0.7\0"
	s ^TKSOLDES("57018")="\0.7\0"
	s ^TKSOLDES("57053")="\0.7\0"
	s ^TKSOLDES("57054")="\0.7\0"
	s ^TKSOLDES("57056")="\0.7\0"
	s ^TKSOLDES("57074")="\0.7\0"
	s ^TKSOLDES("57077")="\0.7\0"
	s ^TKSOLDES("57117")="\0.7\0"
	s ^TKSOLDES("57276")="\0.7\0"
	s ^TKSOLDES("57295")="\0.7\0"
	s ^TKSOLDES("57320")="\0.7\0"
	s ^TKSOLDES("57321")="\0.7\0"
	s ^TKSOLDES("58021")="\0.7\0"
	s ^TKSOLDES("58027")="\0.7\0"
	s ^TKSOLDES("58040")="\0.7\0"
	s ^TKSOLDES("58723")="\0.7\0"
	s ^TKSOLDES("59100")="\0.7\0"
	s ^TKSOLDES("59334")="\0.7\0"
	s ^TKSOLDES("59877")="\0.7\0"
	s ^TKSOLDES("60670")="\0.7\0"
	s ^TKSOLDES("61425")="\0.7\0"
	s ^TKSOLDES("61840")="\0.7\0"
	s ^TKSOLDES("62256")="\0.7\0"
	s ^TKSOLDES("62261")="\0.7\0"
	s ^TKSOLDES("62505")="\0.7\0"
	s ^TKSOLDES("63333")="\0.7\0"
	s ^TKSOLDES("63384")="\0.7\0"
	s ^TKSOLDES("63385")="\0.7\0"
	s ^TKSOLDES("63387")="\0.7\0"
	s ^TKSOLDES("63394")="\0.7\0"
	s ^TKSOLDES("63437")="\0.7\0"
	s ^TKSOLDES("63487")="\0.7\0"
	s ^TKSOLDES("63687")="\0.7\0"
	s ^TKSOLDES("63692")="\0.7\0"
	s ^TKSOLDES("63837")="\0.7\0"
	s ^TKSOLDES("63850")="\0.7\0"
	s ^TKSOLDES("63870")="\0.7\0"
	s ^TKSOLDES("63873")="\0.7\0"
	s ^TKSOLDES("64001")="\0.7\0"
	s ^TKSOLDES("64040")="\0.7\0"
	s ^TKSOLDES("64060")="\0.7\0"
	s ^TKSOLDES("64117")="\0.7\0"
	s ^TKSOLDES("64211")="\0.7\0"
	s ^TKSOLDES("64231")="\0.7\0"
	s ^TKSOLDES("64313")="\0.7\0"
	s ^TKSOLDES("64742")="\0.7\0"
	s ^TKSOLDES("64744")="\0.7\0"
	s ^TKSOLDES("64754")="\0.7\0"
	s ^TKSOLDES("65257")="\0.7\0"
	s ^TKSOLDES("65577")="\0.7\0"
	s ^TKSOLDES("65614")="\0.7\0"
	s ^TKSOLDES("65727")="\0.7\0"
	s ^TKSOLDES("65905")="\0.7\0"
	s ^TKSOLDES("65965")="\0.7\0"
	s ^TKSOLDES("65995")="\0.7\0"
	s ^TKSOLDES("66009")="\0.7\0"
	s ^TKSOLDES("66015")="\0.7\0"
	s ^TKSOLDES("66017")="\0.7\0"
	s ^TKSOLDES("66043")="\0.7\0"
	s ^TKSOLDES("66048")="\0.7\0"
	s ^TKSOLDES("66073")="\0.7\0"
	s ^TKSOLDES("66081")="\0.7\0"
	s ^TKSOLDES("66124")="\0.7\0"
	s ^TKSOLDES("66753")="\0.7\0"
	s ^TKSOLDES("67499")="\0.7\0"
	s ^TKSOLDES("67642")="\0.7\0"
	s ^TKSOLDES("67658")="\0.7\0"
	s ^TKSOLDES("67666")="\0.7\0"
	s ^TKSOLDES("67923")="\0.7\0"
	s ^TKSOLDES("67940")="\0.7\0"
	s ^TKSOLDES("68244")="\0.7\0"
	s ^TKSOLDES("68249")="\0.7\0"
	s ^TKSOLDES("68252")="\0.7\0"
	s ^TKSOLDES("68297")="\0.7\0"
	s ^TKSOLDES("69238")="\0.7\0"
	s ^TKSOLDES("69239")="\0.7\0"
	s ^TKSOLDES("70331")="\0.7\0"
	s ^TKSOLDES("70346")="\0.7\0"
	s ^TKSOLDES("70359")="\0.7\0"
	s ^TKSOLDES("70371")="\0.7\0"
	s ^TKSOLDES("70378")="\0.7\0"
	s ^TKSOLDES("70382")="\0.7\0"
	s ^TKSOLDES("70384")="\0.7\0"
	s ^TKSOLDES("70392")="\0.7\0"
	s ^TKSOLDES("70394")="\0.7\0"
	s ^TKSOLDES("70396")="\0.7\0"
	s ^TKSOLDES("70399")="\0.7\0"
	s ^TKSOLDES("70408")="\0.7\0"
	s ^TKSOLDES("70410")="\0.7\0"
	s ^TKSOLDES("70413")="\0.7\0"
	s ^TKSOLDES("70420")="\0.7\0"
	s ^TKSOLDES("70421")="\0.7\0"
	s ^TKSOLDES("70422")="\0.7\0"
	s ^TKSOLDES("70424")="\0.7\0"
	s ^TKSOLDES("70431")="\0.7\0"
	s ^TKSOLDES("70436")="\0.7\0"
	s ^TKSOLDES("70446")="\0.7\0"
	s ^TKSOLDES("70452")="\0.7\0"
	s ^TKSOLDES("70483")="\0.7\0"
	s ^TKSOLDES("70535")="\0.7\0"
	s ^TKSOLDES("70537")="\0.7\0"
	s ^TKSOLDES("70662")="\0.7\0"
	s ^TKSOLDES("70690")="\0.7\0"
	s ^TKSOLDES("70823")="\0.7\0"
	s ^TKSOLDES("70849")="\0.7\0"
	s ^TKSOLDES("93161")="\0.7\0"
	s ^TKSOLDES("72862")="\0.7\0"
	s ^TKSOLDES("72907")="\0.7\0"
	s ^TKSOLDES("73539")="\0.7\0"
	s ^TKSOLDES("73544")="\0.7\0"
	s ^TKSOLDES("73569")="\0.7\0"
	s ^TKSOLDES("75034")="\0.7\0"
	s ^TKSOLDES("75047")="\0.7\0"
	s ^TKSOLDES("75107")="\0.7\0"
	s ^TKSOLDES("75399")="\0.7\0"
	s ^TKSOLDES("75493")="\0.7\0"
	s ^TKSOLDES("75514")="\0.7\0"
	s ^TKSOLDES("76326")="\0.7\0"
	s ^TKSOLDES("76460")="\0.7\0"
	s ^TKSOLDES("77017")="\0.7\0"
	s ^TKSOLDES("77050")="\0.7\0"
	s ^TKSOLDES("77057")="\0.7\0"
	s ^TKSOLDES("77122")="\0.7\0"
	s ^TKSOLDES("77140")="\0.7\0"
	s ^TKSOLDES("77503")="\0.7\0"
	s ^TKSOLDES("77504")="\0.7\0"
	s ^TKSOLDES("77512")="\0.7\0"
	s ^TKSOLDES("77850")="\0.7\0"
	s ^TKSOLDES("77854")="\0.7\0"
	s ^TKSOLDES("78184")="\0.7\0"
	s ^TKSOLDES("78214")="\0.7\0"
	s ^TKSOLDES("78345")="\0.7\0"
	s ^TKSOLDES("78538")="\0.7\0"
	s ^TKSOLDES("78641")="\0.7\0"
	s ^TKSOLDES("78919")="\0.7\0"
	s ^TKSOLDES("79061")="\0.7\0"
	s ^TKSOLDES("79100")="\0.7\0"
	s ^TKSOLDES("79130")="\0.7\0"
	s ^TKSOLDES("79261")="\0.7\0"
	s ^TKSOLDES("79265")="\0.7\0"
	s ^TKSOLDES("79292")="\0.7\0"
	s ^TKSOLDES("79296")="\0.7\0"
	s ^TKSOLDES("79454")="\0.7\0"
	s ^TKSOLDES("80672")="\0.7\0"
	s ^TKSOLDES("80683")="\0.7\0"
	s ^TKSOLDES("80709")="\0.7\0"
	s ^TKSOLDES("81191")="\0.7\0"
	s ^TKSOLDES("81208")="\0.7\0"
	s ^TKSOLDES("81228")="\0.7\0"
	s ^TKSOLDES("81229")="\0.7\0"
	s ^TKSOLDES("81236")="\0.7\0"
	s ^TKSOLDES("81554")="\0.7\0"
	s ^TKSOLDES("82138")="\0.7\0"
	s ^TKSOLDES("82146")="\0.7\0"
	s ^TKSOLDES("82423")="\0.7\0"
	s ^TKSOLDES("82464")="\0.7\0"
	s ^TKSOLDES("82647")="\0.7\0"
	s ^TKSOLDES("82655")="\0.7\0"
	s ^TKSOLDES("82665")="\0.7\0"
	s ^TKSOLDES("82669")="\0.7\0"
	s ^TKSOLDES("82697")="\0.7\0"
	s ^TKSOLDES("82914")="\0.7\0"
	s ^TKSOLDES("83297")="\0.7\0"
	s ^TKSOLDES("83301")="\0.7\0"
	s ^TKSOLDES("83316")="\0.7\0"
	s ^TKSOLDES("83374")="\0.7\0"
	s ^TKSOLDES("83403")="\0.7\0"
	s ^TKSOLDES("83410")="\0.7\0"
	s ^TKSOLDES("83416")="\0.7\0"
	s ^TKSOLDES("83452")="\0.7\0"
	s ^TKSOLDES("83506")="\0.7\0"
	s ^TKSOLDES("83507")="\0.7\0"
	s ^TKSOLDES("83706")="\0.7\0"
	s ^TKSOLDES("83729")="\0.7\0"
	s ^TKSOLDES("83740")="\0.7\0"
	s ^TKSOLDES("83784")="\0.7\0"
	s ^TKSOLDES("83824")="\0.7\0"
	s ^TKSOLDES("83984")="\0.7\0"
	s ^TKSOLDES("84284")="\0.7\0"
	s ^TKSOLDES("84286")="\0.7\0"
	s ^TKSOLDES("84460")="\0.7\0"
	s ^TKSOLDES("84824")="\0.7\0"
	s ^TKSOLDES("84826")="\0.7\0"
	s ^TKSOLDES("84831")="\0.7\0"
	s ^TKSOLDES("85076")="\0.7\0"
	s ^TKSOLDES("85117")="\0.7\0"
	s ^TKSOLDES("85130")="\0.7\0"
	s ^TKSOLDES("85131")="\0.7\0"
	s ^TKSOLDES("85846")="\0.7\0"
	s ^TKSOLDES("85921")="\0.7\0"
	s ^TKSOLDES("86385")="\0.7\0"
	s ^TKSOLDES("86622")="\0.7\0"
	s ^TKSOLDES("86997")="\0.7\0"
	s ^TKSOLDES("87643")="\0.7\0"
	s ^TKSOLDES("87731")="\0.7\0"
	s ^TKSOLDES("87982")="\0.7\0"
	s ^TKSOLDES("88009")="\0.7\0"
	s ^TKSOLDES("88110")="\0.7\0"
	s ^TKSOLDES("88557")="\0.7\0"
	s ^TKSOLDES("88588")="\0.7\0"
	s ^TKSOLDES("88594")="\0.7\0"
	s ^TKSOLDES("88596")="\0.7\0"
	s ^TKSOLDES("89879")="\0.7\0"
	s ^TKSOLDES("89881")="\0.7\0"
	s ^TKSOLDES("89961")="\0.7\0"
	s ^TKSOLDES("100090")="\0.7\0"
	s ^TKSOLDES("100097")="\0.7\0"
	s ^TKSOLDES("100179")="\0.7\0"
	s ^TKSOLDES("100387")="\0.7\0"
	s ^TKSOLDES("100485")="\0.7\0"
	s ^TKSOLDES("100503")="\0.7\0"
	s ^TKSOLDES("100513")="\0.7\0"
	s ^TKSOLDES("101165")="\0.7\0"
	s ^TKSOLDES("101183")="\0.7\0"
	s ^TKSOLDES("101190")="\0.7\0"
	s ^TKSOLDES("101200")="\0.7\0"
	s ^TKSOLDES("102940")="\0.7\0"
	s ^TKSOLDES("102944")="\0.7\0"
	s ^TKSOLDES("102948")="\0.7\0"
	s ^TKSOLDES("102958")="\0.7\0"
	s ^TKSOLDES("102973")="\0.7\0"
	s ^TKSOLDES("102976")="\0.7\0"
	s ^TKSOLDES("103044")="\0.7\0"
	s ^TKSOLDES("103081")="\0.7\0"
	s ^TKSOLDES("103082")="\0.7\0"
	s ^TKSOLDES("103524")="\0.7\0"
	s ^TKSOLDES("103671")="\0.7\0"
	s ^TKSOLDES("104729")="\0.7\0"
	s ^TKSOLDES("105144")="\0.7\0"
	s ^TKSOLDES("105145")="\0.7\0"
	s ^TKSOLDES("105149")="\0.7\0"
	s ^TKSOLDES("105157")="\0.7\0"
	s ^TKSOLDES("105216")="\0.7\0"
	s ^TKSOLDES("105492")="\0.7\0"
	s ^TKSOLDES("105508")="\0.7\0"
	s ^TKSOLDES("106116")="\0.7\0"
	s ^TKSOLDES("106843")="\0.7\0"
	s ^TKSOLDES("106844")="\0.7\0"
	s ^TKSOLDES("107781")="\0.7\0"
	s ^TKSOLDES("44165")="\0.7\0"
	s ^TKSOLDES("78790")="\0.7\0"
	s ^TKSOLDES("83356")="\0.7\0"
	s ^TKSOLDES("37443")="\0.7\0"
	s ^TKSOLDES("77805")="\0.7\0"
	s ^TKSOLDES("79175")="\0.7\0"
	s ^TKSOLDES("80724")="\0.7\0"
	s ^TKSOLDES("100239")="\0.7\0"
	s ^TKSOLDES("76333")="\0.7\0"
	s ^TKSOLDES("77794")="\0.7\0"
	s ^TKSOLDES("78637")="\0.7\0"
	s ^TKSOLDES("6817")="\0.7\0"
	s ^TKSOLDES("9208")="\0.7\0"
	s ^TKSOLDES("47758")="\0.7\0"
	s ^TKSOLDES("63037")="\0.7\0"
	s ^TKSOLDES("67318")="\0.7\0"
	s ^TKSOLDES("68307")="\0.7\0"
	s ^TKSOLDES("77947")="\0.7\0"
	s ^TKSOLDES("82535")="\0.7\0"
	s ^TKSOLDES("83337")="\0.7\0"
	s ^TKSOLDES("83979")="\0.7\0"
	s ^TKSOLDES("84020")="\0.7\0"
	s ^TKSOLDES("89929")="\0.7\0"
	s ^TKSOLDES("100106")="\0.7\0"
	s ^TKSOLDES("101513")="\0.7\0"
	s ^TKSOLDES("104913")="\0.7\0"
	s ^TKSOLDES("64438")="\0.7\0"
	s ^TKSOLDES("79666")="\0.7\0"
	s ^TKSOLDES("85927")="\0.7\0"
	s ^TKSOLDES("78885")="\0.7\0"
	s ^TKSOLDES("83701")="\0.7\0"
	s ^TKSOLDES("89959")="\0.7\0"
	s ^TKSOLDES("79817")="\0.7\0"
	s ^TKSOLDES("85857")="\0.7\0"
	s ^TKSOLDES("75620")="\0.7\0"
	s ^TKSOLDES("78888")="\0.7\0"
	s ^TKSOLDES("2284")="\0.7\0"
	s ^TKSOLDES("3592")="\0.7\0"
	s ^TKSOLDES("4012")="\0.7\0"
	s ^TKSOLDES("91313")="\0.7\0"
	s ^TKSOLDES("6703")="\0.7\0"
	s ^TKSOLDES("6732")="\0.7\0"
	s ^TKSOLDES("7468")="\0.7\0"
	s ^TKSOLDES("7684")="\0.7\0"
	s ^TKSOLDES("7706")="\0.7\0"
	s ^TKSOLDES("8398")="\0.7\0"
	s ^TKSOLDES("8451")="\0.7\0"
	s ^TKSOLDES("8470")="\0.7\0"
	s ^TKSOLDES("9228")="\0.7\0"
	s ^TKSOLDES("9252")="\0.7\0"
	s ^TKSOLDES("9256")="\0.7\0"
	s ^TKSOLDES("12660")="\0.7\0"
	s ^TKSOLDES("12673")="\0.7\0"
	s ^TKSOLDES("12678")="\0.7\0"
	s ^TKSOLDES("12680")="\0.7\0"
	s ^TKSOLDES("12681")="\0.7\0"
	s ^TKSOLDES("12714")="\0.7\0"
	s ^TKSOLDES("12749")="\0.7\0"
	s ^TKSOLDES("12760")="\0.7\0"
	s ^TKSOLDES("12771")="\0.7\0"
	s ^TKSOLDES("12852")="\0.7\0"
	s ^TKSOLDES("12854")="\0.7\0"
	s ^TKSOLDES("12885")="\0.7\0"
	s ^TKSOLDES("12980")="\0.7\0"
	s ^TKSOLDES("13013")="\0.7\0"
	s ^TKSOLDES("13036")="\0.7\0"
	s ^TKSOLDES("13055")="\0.7\0"
	s ^TKSOLDES("13059")="\0.7\0"
	s ^TKSOLDES("13113")="\0.7\0"
	s ^TKSOLDES("13127")="\0.7\0"
	s ^TKSOLDES("13131")="\0.7\0"
	s ^TKSOLDES("13143")="\0.7\0"
	s ^TKSOLDES("13144")="\0.7\0"
	s ^TKSOLDES("13171")="\0.7\0"
	s ^TKSOLDES("13264")="\0.7\0"
	s ^TKSOLDES("13278")="\0.7\0"
	s ^TKSOLDES("13351")="\0.7\0"
	s ^TKSOLDES("13387")="\0.7\0"
	s ^TKSOLDES("13391")="\0.7\0"
	s ^TKSOLDES("13401")="\0.7\0"
	s ^TKSOLDES("13797")="\0.7\0"
	s ^TKSOLDES("13887")="\0.7\0"
	s ^TKSOLDES("14114")="\0.7\0"
	s ^TKSOLDES("14127")="\0.7\0"
	s ^TKSOLDES("14224")="\0.7\0"
	s ^TKSOLDES("14297")="\0.7\0"
	s ^TKSOLDES("14355")="\0.7\0"
	s ^TKSOLDES("14377")="\0.7\0"
	s ^TKSOLDES("14500")="\0.7\0"
 
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 