ROUTINE SOLDES70AH13M215C1
SOLDES70AH13M215C1
 
	s ^TKSOLDES("105212")="\0.7\0"
	s ^TKSOLDES("109844")="\0.7\0"
	s ^TKSOLDES("107734")="\0.7\0"
	s ^TKSOLDES("105555")="\0.7\0"
	s ^TKSOLDES("107066")="\0.7\0"
	s ^TKSOLDES("107068")="\0.7\0"
	s ^TKSOLDES("105207")="\0.7\0"
	s ^TKSOLDES("109843")="\0.7\0"
	s ^TKSOLDES("107071")="\0.7\0"
	s ^TKSOLDES("107074")="\0.7\0"
	s ^TKSOLDES("106060")="\0.7\0"
	s ^TKSOLDES("106059")="\0.7\0"
	s ^TKSOLDES("105219")="\0.7\0"
	s ^TKSOLDES("107945")="\0.7\0"
	s ^TKSOLDES("107943")="\0.7\0"
	s ^TKSOLDES("107948")="\0.7\0"
	s ^TKSOLDES("107944")="\0.7\0"
	s ^TKSOLDES("107946")="\0.7\0"
	s ^TKSOLDES("105570")="\0.7\0"
	s ^TKSOLDES("105572")="\0.7\0"
	s ^TKSOLDES("105568")="\0.7\0"
	s ^TKSOLDES("105564")="\0.7\0"
	s ^TKSOLDES("105562")="\0.7\0"
	s ^TKSOLDES("105561")="\0.7\0"
	s ^TKSOLDES("105560")="\0.7\0"
	s ^TKSOLDES("105558")="\0.7\0"
	s ^TKSOLDES("105566")="\0.7\0"
	s ^TKSOLDES("105569")="\0.7\0"
	s ^TKSOLDES("105571")="\0.7\0"
	s ^TKSOLDES("105563")="\0.7\0"
	s ^TKSOLDES("105557")="\0.7\0"
	s ^TKSOLDES("105565")="\0.7\0"
	s ^TKSOLDES("105573")="\0.7\0"
	s ^TKSOLDES("109842")="\0.7\0"
	s ^TKSOLDES("109840")="\0.7\0"
	s ^TKSOLDES("109837")="\0.7\0"
	s ^TKSOLDES("109839")="\0.7\0"
	s ^TKSOLDES("107731")="\0.7\0"
	s ^TKSOLDES("109836")="\0.7\0"
	s ^TKSOLDES("109838")="\0.7\0"
	s ^TKSOLDES("110740")="\0.7\0"
	s ^TKSOLDES("105202")="\0.7\0"
	s ^TKSOLDES("110841")="\0.7\0"
	s ^TKSOLDES("103502")="\0.7\0"
	s ^TKSOLDES("103500")="\0.7\0"
	s ^TKSOLDES("104909")="\0.7\0"
	s ^TKSOLDES("104906")="\0.7\0"
	s ^TKSOLDES("104907")="\0.7\0"
	s ^TKSOLDES("104901")="\0.7\0"
	s ^TKSOLDES("104902")="\0.7\0"
	s ^TKSOLDES("104911")="\0.7\0"
	s ^TKSOLDES("104912")="\0.7\0"
	s ^TKSOLDES("104905")="\0.7\0"
	s ^TKSOLDES("104903")="\0.7\0"
	s ^TKSOLDES("101536")="\0.7\0"
	s ^TKSOLDES("104916")="\0.7\0"
	s ^TKSOLDES("102166")="\0.7\0"
	s ^TKSOLDES("102161")="\0.7\0"
	s ^TKSOLDES("102160")="\0.7\0"
	s ^TKSOLDES("102165")="\0.7\0"
	s ^TKSOLDES("102162")="\0.7\0"
	s ^TKSOLDES("102163")="\0.7\0"
	s ^TKSOLDES("102168")="\0.7\0"
	s ^TKSOLDES("102151")="\0.7\0"
	s ^TKSOLDES("102154")="\0.7\0"
	s ^TKSOLDES("102157")="\0.7\0"
	s ^TKSOLDES("102532")="\0.7\0"
	s ^TKSOLDES("104494")="\0.7\0"
	s ^TKSOLDES("104492")="\0.7\0"
	s ^TKSOLDES("102537")="\0.7\0"
	s ^TKSOLDES("102531")="\0.7\0"
	s ^TKSOLDES("102443")="\0.7\0"
	s ^TKSOLDES("102444")="\0.7\0"
	s ^TKSOLDES("102442")="\0.7\0"
	s ^TKSOLDES("100761")="\0.7\0"
	s ^TKSOLDES("100630")="\0.7\0"
	s ^TKSOLDES("100631")="\0.7\0"
	s ^TKSOLDES("100637")="\0.7\0"
	s ^TKSOLDES("103507")="\0.7\0"
	s ^TKSOLDES("86156")="\0.7\0"
	s ^TKSOLDES("86155")="\0.7\0"
	s ^TKSOLDES("86154")="\0.7\0"
	s ^TKSOLDES("88356")="\0.7\0"
	s ^TKSOLDES("88355")="\0.7\0"
	s ^TKSOLDES("86141")="\0.7\0"
	s ^TKSOLDES("86147")="\0.7\0"
	s ^TKSOLDES("86145")="\0.7\0"
	s ^TKSOLDES("100213")="\0.7\0"
	s ^TKSOLDES("100212")="\0.7\0"
	s ^TKSOLDES("100200")="\0.7\0"
	s ^TKSOLDES("86130")="\0.7\0"
	s ^TKSOLDES("86128")="\0.7\0"
	s ^TKSOLDES("86143")="\0.7\0"
	s ^TKSOLDES("88501")="\0.7\0"
	s ^TKSOLDES("88505")="\0.7\0"
	s ^TKSOLDES("86985")="\0.7\0"
	s ^TKSOLDES("87275")="\0.7\0"
	s ^TKSOLDES("86989")="\0.7\0"
	s ^TKSOLDES("79718")="\0.7\0"
	s ^TKSOLDES("80220")="\0.7\0"
	s ^TKSOLDES("82526")="\0.7\0"
	s ^TKSOLDES("79424")="\0.7\0"
	s ^TKSOLDES("84273")="\0.7\0"
	s ^TKSOLDES("80299")="\0.7\0"
	s ^TKSOLDES("80302")="\0.7\0"
	s ^TKSOLDES("80303")="\0.7\0"
	s ^TKSOLDES("79864")="\0.7\0"
	s ^TKSOLDES("82771")="\0.7\0"
	s ^TKSOLDES("80002")="\0.7\0"
	s ^TKSOLDES("79628")="\0.7\0"
	s ^TKSOLDES("79630")="\0.7\0"
	s ^TKSOLDES("79857")="\0.7\0"
	s ^TKSOLDES("79767")="\0.7\0"
	s ^TKSOLDES("82904")="\0.7\0"
	s ^TKSOLDES("81532")="\0.7\0"
	s ^TKSOLDES("81531")="\0.7\0"
	s ^TKSOLDES("81527")="\0.7\0"
	s ^TKSOLDES("81038")="\0.7\0"
	s ^TKSOLDES("81026")="\0.7\0"
	s ^TKSOLDES("81030")="\0.7\0"
	s ^TKSOLDES("79352")="\0.7\0"
	s ^TKSOLDES("79353")="\0.7\0"
	s ^TKSOLDES("79816")="\0.7\0"
	s ^TKSOLDES("79813")="\0.7\0"
	s ^TKSOLDES("82907")="\0.7\0"
	s ^TKSOLDES("83886")="\0.7\0"
	s ^TKSOLDES("83887")="\0.7\0"
	s ^TKSOLDES("80027")="\0.7\0"
	s ^TKSOLDES("84078")="\0.7\0"
	s ^TKSOLDES("84076")="\0.7\0"
	s ^TKSOLDES("84080")="\0.7\0"
	s ^TKSOLDES("84068")="\0.7\0"
	s ^TKSOLDES("84060")="\0.7\0"
	s ^TKSOLDES("84320")="\0.7\0"
	s ^TKSOLDES("84322")="\0.7\0"
	s ^TKSOLDES("84308")="\0.7\0"
	s ^TKSOLDES("79446")="\0.7\0"
	s ^TKSOLDES("75361")="\0.7\0"
	s ^TKSOLDES("76395")="\0.7\0"
	s ^TKSOLDES("76053")="\0.7\0"
	s ^TKSOLDES("76200")="\0.7\0"
	s ^TKSOLDES("75621")="\0.7\0"
	s ^TKSOLDES("78724")="\0.7\0"
	s ^TKSOLDES("78727")="\0.7\0"
	s ^TKSOLDES("76462")="\0.7\0"
	s ^TKSOLDES("75599")="\0.7\0"
	s ^TKSOLDES("67924")="\0.7\0"
	s ^TKSOLDES("68020")="\0.7\0"
	s ^TKSOLDES("63080")="\0.7\0"
	s ^TKSOLDES("1154")="\0.7\0"
	s ^TKSOLDES("100549")="\0.7\0"
	s ^TKSOLDES("100523")="\0.7\0"
	s ^TKSOLDES("100524")="\0.7\0"
	s ^TKSOLDES("100513")="\0.7\0"
	s ^TKSOLDES("100514")="\0.7\0"
	s ^TKSOLDES("100515")="\0.7\0"
	s ^TKSOLDES("100520")="\0.7\0"
	s ^TKSOLDES("102499")="\0.7\0"
	s ^TKSOLDES("102502")="\0.7\0"
	s ^TKSOLDES("102511")="\0.7\0"
	s ^TKSOLDES("102514")="\0.7\0"
	s ^TKSOLDES("102510")="\0.7\0"
	s ^TKSOLDES("100487")="\0.7\0"
	s ^TKSOLDES("104729")="\0.7\0"
	s ^TKSOLDES("100497")="\0.7\0"
	s ^TKSOLDES("100498")="\0.7\0"
	s ^TKSOLDES("100500")="\0.7\0"
	s ^TKSOLDES("100501")="\0.7\0"
	s ^TKSOLDES("100503")="\0.7\0"
	s ^TKSOLDES("100504")="\0.7\0"
	s ^TKSOLDES("100510")="\0.7\0"
	s ^TKSOLDES("104730")="\0.7\0"
	s ^TKSOLDES("104738")="\0.7\0"
	s ^TKSOLDES("104734")="\0.7\0"
	s ^TKSOLDES("100495")="\0.7\0"
	s ^TKSOLDES("101107")="\0.7\0"
	s ^TKSOLDES("101110")="\0.7\0"
	s ^TKSOLDES("86617")="\0.7\0"
	s ^TKSOLDES("88552")="\0.7\0"
	s ^TKSOLDES("86622")="\0.7\0"
	s ^TKSOLDES("86623")="\0.7\0"
	s ^TKSOLDES("86625")="\0.7\0"
	s ^TKSOLDES("86626")="\0.7\0"
	s ^TKSOLDES("86627")="\0.7\0"
	s ^TKSOLDES("80286")="\0.7\0"
	s ^TKSOLDES("80288")="\0.7\0"
	s ^TKSOLDES("82591")="\0.7\0"
	s ^TKSOLDES("82593")="\0.7\0"
	s ^TKSOLDES("83417")="\0.7\0"
	s ^TKSOLDES("83397")="\0.7\0"
	s ^TKSOLDES("82615")="\0.7\0"
	s ^TKSOLDES("82616")="\0.7\0"
	s ^TKSOLDES("82617")="\0.7\0"
	s ^TKSOLDES("82620")="\0.7\0"
	s ^TKSOLDES("82693")="\0.7\0"
	s ^TKSOLDES("82694")="\0.7\0"
	s ^TKSOLDES("82690")="\0.7\0"
	s ^TKSOLDES("83406")="\0.7\0"
	s ^TKSOLDES("83405")="\0.7\0"
	s ^TKSOLDES("83404")="\0.7\0"
	s ^TKSOLDES("82632")="\0.7\0"
	s ^TKSOLDES("82633")="\0.7\0"
	s ^TKSOLDES("82661")="\0.7\0"
	s ^TKSOLDES("82664")="\0.7\0"
	s ^TKSOLDES("82669")="\0.7\0"
	s ^TKSOLDES("82673")="\0.7\0"
	s ^TKSOLDES("81470")="\0.7\0"
	s ^TKSOLDES("77017")="\0.7\0"
	s ^TKSOLDES("78212")="\0.7\0"
	s ^TKSOLDES("78211")="\0.7\0"
	s ^TKSOLDES("78215")="\0.7\0"
	s ^TKSOLDES("73549")="\0.7\0"
	s ^TKSOLDES("73548")="\0.7\0"
	s ^TKSOLDES("72911")="\0.7\0"
	s ^TKSOLDES("73560")="\0.7\0"
	s ^TKSOLDES("72869")="\0.7\0"
	s ^TKSOLDES("72853")="\0.7\0"
	s ^TKSOLDES("72871")="\0.7\0"
	s ^TKSOLDES("72852")="\0.7\0"
	s ^TKSOLDES("75971")="\0.7\0"
	s ^TKSOLDES("72877")="\0.7\0"
	s ^TKSOLDES("75035")="\0.7\0"
	s ^TKSOLDES("74988")="\0.7\0"
	s ^TKSOLDES("74990")="\0.7\0"
	s ^TKSOLDES("75005")="\0.7\0"
	s ^TKSOLDES("75007")="\0.7\0"
	s ^TKSOLDES("75018")="\0.7\0"
	s ^TKSOLDES("75020")="\0.7\0"
	s ^TKSOLDES("77019")="\0.7\0"
	s ^TKSOLDES("65958")="\0.7\0"
	s ^TKSOLDES("65967")="\0.7\0"
	s ^TKSOLDES("67140")="\0.7\0"
	s ^TKSOLDES("68297")="\0.7\0"
	s ^TKSOLDES("68298")="\0.7\0"
	s ^TKSOLDES("68289")="\0.7\0"
	s ^TKSOLDES("68291")="\0.7\0"
	s ^TKSOLDES("68294")="\0.7\0"
	s ^TKSOLDES("64749")="\0.7\0"
	s ^TKSOLDES("68146")="\0.7\0"
	s ^TKSOLDES("68134")="\0.7\0"
	s ^TKSOLDES("68139")="\0.7\0"
	s ^TKSOLDES("68168")="\0.7\0"
	s ^TKSOLDES("68170")="\0.7\0"
	s ^TKSOLDES("68169")="\0.7\0"
	s ^TKSOLDES("68115")="\0.7\0"
	s ^TKSOLDES("68177")="\0.7\0"
	s ^TKSOLDES("68179")="\0.7\0"
	s ^TKSOLDES("68178")="\0.7\0"
	s ^TKSOLDES("68171")="\0.7\0"
	s ^TKSOLDES("68173")="\0.7\0"
	s ^TKSOLDES("68172")="\0.7\0"
	s ^TKSOLDES("68123")="\0.7\0"
	s ^TKSOLDES("68122")="\0.7\0"
	s ^TKSOLDES("68127")="\0.7\0"
	s ^TKSOLDES("68114")="\0.7\0"
	s ^TKSOLDES("68109")="\0.7\0"
	s ^TKSOLDES("68180")="\0.7\0"
	s ^TKSOLDES("68182")="\0.7\0"
	s ^TKSOLDES("68181")="\0.7\0"
	s ^TKSOLDES("68156")="\0.7\0"
	s ^TKSOLDES("68160")="\0.7\0"
	s ^TKSOLDES("68153")="\0.7\0"
	s ^TKSOLDES("68155")="\0.7\0"
	s ^TKSOLDES("68149")="\0.7\0"
	s ^TKSOLDES("68148")="\0.7\0"
	s ^TKSOLDES("68161")="\0.7\0"
	s ^TKSOLDES("68165")="\0.7\0"
	s ^TKSOLDES("67643")="\0.7\0"
	s ^TKSOLDES("68283")="\0.7\0"
	s ^TKSOLDES("68266")="\0.7\0"
	s ^TKSOLDES("70618")="\0.7\0"
	s ^TKSOLDES("68263")="\0.7\0"
	s ^TKSOLDES("68264")="\0.7\0"
	s ^TKSOLDES("68247")="\0.7\0"
	s ^TKSOLDES("64739")="\0.7\0"
	s ^TKSOLDES("64742")="\0.7\0"
	s ^TKSOLDES("64743")="\0.7\0"
	s ^TKSOLDES("64744")="\0.7\0"
	s ^TKSOLDES("64720")="\0.7\0"
	s ^TKSOLDES("67492")="\0.7\0"
	s ^TKSOLDES("68225")="\0.7\0"
	s ^TKSOLDES("68240")="\0.7\0"
	s ^TKSOLDES("68245")="\0.7\0"
	s ^TKSOLDES("68214")="\0.7\0"
	s ^TKSOLDES("68261")="\0.7\0"
	s ^TKSOLDES("68226")="\0.7\0"
	s ^TKSOLDES("68254")="\0.7\0"
	s ^TKSOLDES("68255")="\0.7\0"
	s ^TKSOLDES("68257")="\0.7\0"
	s ^TKSOLDES("68258")="\0.7\0"
	s ^TKSOLDES("65748")="\0.7\0"
	s ^TKSOLDES("68071")="\0.7\0"
	s ^TKSOLDES("68076")="\0.7\0"
	s ^TKSOLDES("68078")="\0.7\0"
	s ^TKSOLDES("68083")="\0.7\0"
	s ^TKSOLDES("68093")="\0.7\0"
	s ^TKSOLDES("68095")="\0.7\0"
	s ^TKSOLDES("68096")="\0.7\0"
	s ^TKSOLDES("68098")="\0.7\0"
	s ^TKSOLDES("68099")="\0.7\0"
	s ^TKSOLDES("68085")="\0.7\0"
	s ^TKSOLDES("56084")="\0.7\0"
	s ^TKSOLDES("56083")="\0.7\0"
	s ^TKSOLDES("56079")="\0.7\0"
	s ^TKSOLDES("56078")="\0.7\0"
	s ^TKSOLDES("56080")="\0.7\0"
	s ^TKSOLDES("62232")="\0.7\0"
	s ^TKSOLDES("62537")="\0.7\0"
	s ^TKSOLDES("61427")="\0.7\0"
	s ^TKSOLDES("61426")="\0.7\0"
	s ^TKSOLDES("64057")="\0.7\0"
	s ^TKSOLDES("64058")="\0.7\0"
	s ^TKSOLDES("57287")="\0.7\0"
	s ^TKSOLDES("50407")="\0.7\0"
	s ^TKSOLDES("50414")="\0.7\0"
	s ^TKSOLDES("50382")="\0.7\0"
	s ^TKSOLDES("50391")="\0.7\0"
	s ^TKSOLDES("50399")="\0.7\0"
	s ^TKSOLDES("47743")="\0.7\0"
	s ^TKSOLDES("17614")="\0.7\0"
	s ^TKSOLDES("17610")="\0.7\0"
	s ^TKSOLDES("38391")="\0.7\0"
	s ^TKSOLDES("38395")="\0.7\0"
	s ^TKSOLDES("38440")="\0.7\0"
	s ^TKSOLDES("17557")="\0.7\0"
	s ^TKSOLDES("41198")="\0.7\0"
	s ^TKSOLDES("17680")="\0.7\0"
	s ^TKSOLDES("17675")="\0.7\0"
	s ^TKSOLDES("35558")="\0.7\0"
	s ^TKSOLDES("43064")="\0.7\0"
	s ^TKSOLDES("43075")="\0.7\0"
	s ^TKSOLDES("17501")="\0.7\0"
	s ^TKSOLDES("17504")="\0.7\0"
	s ^TKSOLDES("40134")="\0.7\0"
	s ^TKSOLDES("17532")="\0.7\0"
	s ^TKSOLDES("17538")="\0.7\0"
	s ^TKSOLDES("35578")="\0.7\0"
	s ^TKSOLDES("17527")="\0.7\0"
	s ^TKSOLDES("17647")="\0.7\0"
	s ^TKSOLDES("86392")="\0.7\0"
	s ^TKSOLDES("89910")="\0.7\0"
	s ^TKSOLDES("84894")="\0.7\0"
	s ^TKSOLDES("84893")="\0.7\0"
	s ^TKSOLDES("89926")="\0.7\0"
	s ^TKSOLDES("85768")="\0.7\0"
	s ^TKSOLDES("85766")="\0.7\0"
	s ^TKSOLDES("89962")="\0.7\0"
	s ^TKSOLDES("89890")="\0.7\0"
	s ^TKSOLDES("89887")="\0.7\0"
	s ^TKSOLDES("89883")="\0.7\0"
	s ^TKSOLDES("89848")="\0.7\0"
	s ^TKSOLDES("89844")="\0.7\0"
	s ^TKSOLDES("89839")="\0.7\0"
	s ^TKSOLDES("89847")="\0.7\0"
	s ^TKSOLDES("89836")="\0.7\0"
	s ^TKSOLDES("89837")="\0.7\0"
	s ^TKSOLDES("85778")="\0.7\0"
	s ^TKSOLDES("85771")="\0.7\0"
	s ^TKSOLDES("87622")="\0.7\0"
	s ^TKSOLDES("86458")="\0.7\0"
	s ^TKSOLDES("86459")="\0.7\0"
	s ^TKSOLDES("86588")="\0.7\0"
	s ^TKSOLDES("86587")="\0.7\0"
	s ^TKSOLDES("87732")="\0.7\0"
	s ^TKSOLDES("87729")="\0.7\0"
	s ^TKSOLDES("89923")="\0.7\0"
	s ^TKSOLDES("86563")="\0.7\0"
	s ^TKSOLDES("89878")="\0.7\0"
	s ^TKSOLDES("89945")="\0.7\0"
	s ^TKSOLDES("89954")="\0.7\0"
	s ^TKSOLDES("86493")="\0.7\0"
	s ^TKSOLDES("86488")="\0.7\0"
	s ^TKSOLDES("100185")="\0.7\0"
	s ^TKSOLDES("100186")="\0.7\0"
	s ^TKSOLDES("84890")="\0.7\0"
	s ^TKSOLDES("86521")="\0.7\0"
	s ^TKSOLDES("87827")="\0.7\0"
	s ^TKSOLDES("87870")="\0.7\0"
	s ^TKSOLDES("87483")="\0.7\0"
	s ^TKSOLDES("87486")="\0.7\0"
	s ^TKSOLDES("87487")="\0.7\0"
	s ^TKSOLDES("86394")="\0.7\0"
	s ^TKSOLDES("87736")="\0.7\0"
	s ^TKSOLDES("100091")="\0.7\0"
	s ^TKSOLDES("85796")="\0.7\0"
	s ^TKSOLDES("100244")="\0.7\0"
	s ^TKSOLDES("100241")="\0.7\0"
	s ^TKSOLDES("100240")="\0.7\0"
	s ^TKSOLDES("86964")="\0.7\0"
	s ^TKSOLDES("100137")="\0.7\0"
	s ^TKSOLDES("100140")="\0.7\0"
	s ^TKSOLDES("100132")="\0.7\0"
	s ^TKSOLDES("89875")="\0.7\0"
	s ^TKSOLDES("89896")="\0.7\0"
	s ^TKSOLDES("86379")="\0.7\0"
	s ^TKSOLDES("86380")="\0.7\0"
	s ^TKSOLDES("89884")="\0.7\0"
	s ^TKSOLDES("86505")="\0.7\0"
	s ^TKSOLDES("89931")="\0.7\0"
	s ^TKSOLDES("86318")="\0.7\0"
	s ^TKSOLDES("87738")="\0.7\0"
	s ^TKSOLDES("87737")="\0.7\0"
	s ^TKSOLDES("86573")="\0.7\0"
	s ^TKSOLDES("87740")="\0.7\0"
	s ^TKSOLDES("86151")="\0.7\0"
	s ^TKSOLDES("86149")="\0.7\0"
	s ^TKSOLDES("89975")="\0.7\0"
	s ^TKSOLDES("89978")="\0.7\0"
	s ^TKSOLDES("89977")="\0.7\0"
	s ^TKSOLDES("89976")="\0.7\0"
	s ^TKSOLDES("89988")="\0.7\0"
	s ^TKSOLDES("89904")="\0.7\0"
	s ^TKSOLDES("89902")="\0.7\0"
	s ^TKSOLDES("87646")="\0.7\0"
	s ^TKSOLDES("87645")="\0.7\0"
	s ^TKSOLDES("87639")="\0.7\0"
	s ^TKSOLDES("87638")="\0.7\0"
	s ^TKSOLDES("85853")="\0.7\0"
	s ^TKSOLDES("85855")="\0.7\0"
	s ^TKSOLDES("87754")="\0.7\0"
	s ^TKSOLDES("86386")="\0.7\0"
	s ^TKSOLDES("87752")="\0.7\0"
	s ^TKSOLDES("87895")="\0.7\0"
	s ^TKSOLDES("87749")="\0.7\0"
	s ^TKSOLDES("86474")="\0.7\0"
	s ^TKSOLDES("87759")="\0.7\0"
	s ^TKSOLDES("87758")="\0.7\0"
	s ^TKSOLDES("87757")="\0.7\0"
	s ^TKSOLDES("87756")="\0.7\0"
	s ^TKSOLDES("87748")="\0.7\0"
	s ^TKSOLDES("87747")="\0.7\0"
	s ^TKSOLDES("86383")="\0.7\0"
	s ^TKSOLDES("86385")="\0.7\0"
	s ^TKSOLDES("86473")="\0.7\0"
	s ^TKSOLDES("87764")="\0.7\0"
	s ^TKSOLDES("85801")="\0.7\0"
	s ^TKSOLDES("85800")="\0.7\0"
	s ^TKSOLDES("87763")="\0.7\0"
	s ^TKSOLDES("89870")="\0.7\0"
	s ^TKSOLDES("85783")="\0.7\0"
	s ^TKSOLDES("85782")="\0.7\0"
	s ^TKSOLDES("86323")="\0.7\0"
	s ^TKSOLDES("85906")="\0.7\0"
	s ^TKSOLDES("89960")="\0.7\0"
	s ^TKSOLDES("89929")="\0.7\0"
	s ^TKSOLDES("86410")="\0.7\0"
	s ^TKSOLDES("86413")="\0.7\0"
	s ^TKSOLDES("86414")="\0.7\0"
	s ^TKSOLDES("100170")="\0.7\0"
	s ^TKSOLDES("100172")="\0.7\0"
	s ^TKSOLDES("89927")="\0.7\0"
	s ^TKSOLDES("89924")="\0.7\0"
	s ^TKSOLDES("89997")="\0.7\0"
	s ^TKSOLDES("87368")="\0.7\0"
	s ^TKSOLDES("87366")="\0.7\0"
	s ^TKSOLDES("89854")="\0.7\0"
	s ^TKSOLDES("89889")="\0.7\0"
	s ^TKSOLDES("86308")="\0.7\0"
	s ^TKSOLDES("86309")="\0.7\0"
	s ^TKSOLDES("85833")="\0.7\0"
	s ^TKSOLDES("85832")="\0.7\0"
	s ^TKSOLDES("84887")="\0.7\0"
	s ^TKSOLDES("89813")="\0.7\0"
	s ^TKSOLDES("89816")="\0.7\0"
	s ^TKSOLDES("85904")="\0.7\0"
	s ^TKSOLDES("87793")="\0.7\0"
	s ^TKSOLDES("87790")="\0.7\0"
	s ^TKSOLDES("87926")="\0.7\0"
	s ^TKSOLDES("100182")="\0.7\0"
	s ^TKSOLDES("100181")="\0.7\0"
	s ^TKSOLDES("86296")="\0.7\0"
	s ^TKSOLDES("86290")="\0.7\0"
	s ^TKSOLDES("87841")="\0.7\0"
	s ^TKSOLDES("86375")="\0.7\0"
	s ^TKSOLDES("100160")="\0.7\0"
	s ^TKSOLDES("100194")="\0.7\0"
	s ^TKSOLDES("87836")="\0.7\0"
	s ^TKSOLDES("87835")="\0.7\0"
	s ^TKSOLDES("87834")="\0.7\0"
	s ^TKSOLDES("87832")="\0.7\0"
	s ^TKSOLDES("87577")="\0.7\0"
	s ^TKSOLDES("84891")="\0.7\0"
	s ^TKSOLDES("86321")="\0.7\0"
	s ^TKSOLDES("85856")="\0.7\0"
	s ^TKSOLDES("85857")="\0.7\0"
	s ^TKSOLDES("85858")="\0.7\0"
	s ^TKSOLDES("85830")="\0.7\0"
	s ^TKSOLDES("87726")="\0.7\0"
	s ^TKSOLDES("87725")="\0.7\0"
	s ^TKSOLDES("87722")="\0.7\0"
	s ^TKSOLDES("89809")="\0.7\0"
	s ^TKSOLDES("89808")="\0.7\0"
	s ^TKSOLDES("86387")="\0.7\0"
	s ^TKSOLDES("86389")="\0.7\0"
	s ^TKSOLDES("86332")="\0.7\0"
	s ^TKSOLDES("85871")="\0.7\0"
	s ^TKSOLDES("86478")="\0.7\0"
	s ^TKSOLDES("86479")="\0.7\0"
	s ^TKSOLDES("87798")="\0.7\0"
	s ^TKSOLDES("87797")="\0.7\0"
	s ^TKSOLDES("84928")="\0.7\0"
	s ^TKSOLDES("84937")="\0.7\0"
	s ^TKSOLDES("89901")="\0.7\0"
	s ^TKSOLDES("89871")="\0.7\0"
	s ^TKSOLDES("100086")="\0.7\0"
	s ^TKSOLDES("100088")="\0.7\0"
	s ^TKSOLDES("100176")="\0.7\0"
	s ^TKSOLDES("100105")="\0.7\0"
	s ^TKSOLDES("100104")="\0.7\0"
	s ^TKSOLDES("100098")="\0.7\0"
	s ^TKSOLDES("100101")="\0.7\0"
	s ^TKSOLDES("87365")="\0.7\0"
	s ^TKSOLDES("85577")="\0.7\0"
	s ^TKSOLDES("85575")="\0.7\0"
	s ^TKSOLDES("84913")="\0.7\0"
	s ^TKSOLDES("84917")="\0.7\0"
	s ^TKSOLDES("84934")="\0.7\0"
	s ^TKSOLDES("84920")="\0.7\0"
	s ^TKSOLDES("84922")="\0.7\0"
	s ^TKSOLDES("84921")="\0.7\0"
	s ^TKSOLDES("85580")="\0.7\0"
	s ^TKSOLDES("84924")="\0.7\0"
	s ^TKSOLDES("84936")="\0.7\0"
	s ^TKSOLDES("84932")="\0.7\0"
	s ^TKSOLDES("87811")="\0.7\0"
	s ^TKSOLDES("100102")="\0.7\0"
	s ^TKSOLDES("100087")="\0.7\0"
	s ^TKSOLDES("89893")="\0.7\0"
	s ^TKSOLDES("89885")="\0.7\0"
	s ^TKSOLDES("89877")="\0.7\0"
	s ^TKSOLDES("89802")="\0.7\0"
	s ^TKSOLDES("89801")="\0.7\0"
	s ^TKSOLDES("89798")="\0.7\0"
	s ^TKSOLDES("89800")="\0.7\0"
	s ^TKSOLDES("89805")="\0.7\0"
	s ^TKSOLDES("89806")="\0.7\0"
	s ^TKSOLDES("89804")="\0.7\0"
	s ^TKSOLDES("89803")="\0.7\0"
	s ^TKSOLDES("100097")="\0.7\0"
	s ^TKSOLDES("100095")="\0.7\0"
	s ^TKSOLDES("100099")="\0.7\0"
	s ^TKSOLDES("100167")="\0.7\0"
	s ^TKSOLDES("100168")="\0.7\0"
	s ^TKSOLDES("89880")="\0.7\0"
	s ^TKSOLDES("83778")="\0.7\0"
	s ^TKSOLDES("83042")="\0.7\0"
	s ^TKSOLDES("83859")="\0.7\0"
	s ^TKSOLDES("82357")="\0.7\0"
	s ^TKSOLDES("82358")="\0.7\0"
	s ^TKSOLDES("82359")="\0.7\0"
	s ^TKSOLDES("83749")="\0.7\0"
	s ^TKSOLDES("83750")="\0.7\0"
	s ^TKSOLDES("82355")="\0.7\0"
	s ^TKSOLDES("83907")="\0.7\0"
	s ^TKSOLDES("83906")="\0.7\0"
	s ^TKSOLDES("83741")="\0.7\0"
	s ^TKSOLDES("83785")="\0.7\0"
	s ^TKSOLDES("83786")="\0.7\0"
	s ^TKSOLDES("81665")="\0.7\0"
	s ^TKSOLDES("81666")="\0.7\0"
	s ^TKSOLDES("81667")="\0.7\0"
	s ^TKSOLDES("84002")="\0.7\0"
	s ^TKSOLDES("83292")="\0.7\0"
	s ^TKSOLDES("83296")="\0.7\0"
	s ^TKSOLDES("83993")="\0.7\0"
	s ^TKSOLDES("83797")="\0.7\0"
	s ^TKSOLDES("83771")="\0.7\0"
	s ^TKSOLDES("83598")="\0.7\0"
	s ^TKSOLDES("82404")="\0.7\0"
	s ^TKSOLDES("83601")="\0.7\0"
	s ^TKSOLDES("84001")="\0.7\0"
	s ^TKSOLDES("83780")="\0.7\0"
	s ^TKSOLDES("82978")="\0.7\0"
	s ^TKSOLDES("82977")="\0.7\0"
	s ^TKSOLDES("83836")="\0.7\0"
	s ^TKSOLDES("82371")="\0.7\0"
	s ^TKSOLDES("82370")="\0.7\0"
	s ^TKSOLDES("83511")="\0.7\0"
	s ^TKSOLDES("83518")="\0.7\0"
	s ^TKSOLDES("83512")="\0.7\0"
	s ^TKSOLDES("83888")="\0.7\0"
	s ^TKSOLDES("83302")="\0.7\0"
	s ^TKSOLDES("83307")="\0.7\0"
	s ^TKSOLDES("84328")="\0.7\0"
	s ^TKSOLDES("81449")="\0.7\0"
	s ^TKSOLDES("81453")="\0.7\0"
	s ^TKSOLDES("81671")="\0.7\0"
	s ^TKSOLDES("83376")="\0.7\0"
	s ^TKSOLDES("81672")="\0.7\0"
	s ^TKSOLDES("81673")="\0.7\0"
	s ^TKSOLDES("83378")="\0.7\0"
	s ^TKSOLDES("81675")="\0.7\0"
	s ^TKSOLDES("81674")="\0.7\0"
	s ^TKSOLDES("83375")="\0.7\0"
	s ^TKSOLDES("82417")="\0.7\0"
	s ^TKSOLDES("82419")="\0.7\0"
	s ^TKSOLDES("82418")="\0.7\0"
	s ^TKSOLDES("82351")="\0.7\0"
	s ^TKSOLDES("81704")="\0.7\0"
	s ^TKSOLDES("81709")="\0.7\0"
	s ^TKSOLDES("81706")="\0.7\0"
	s ^TKSOLDES("81708")="\0.7\0"
	s ^TKSOLDES("81703")="\0.7\0"
	s ^TKSOLDES("81707")="\0.7\0"
	s ^TKSOLDES("83815")="\0.7\0"
	s ^TKSOLDES("83336")="\0.7\0"
	s ^TKSOLDES("83877")="\0.7\0"
	s ^TKSOLDES("83875")="\0.7\0"
	s ^TKSOLDES("83861")="\0.7\0"
	s ^TKSOLDES("81839")="\0.7\0"
	s ^TKSOLDES("83327")="\0.7\0"
	s ^TKSOLDES("82432")="\0.7\0"
	s ^TKSOLDES("83477")="\0.7\0"
	s ^TKSOLDES("83603")="\0.7\0"
	s ^TKSOLDES("82131")="\0.7\0"
	s ^TKSOLDES("83604")="\0.7\0"
	s ^TKSOLDES("83740")="\0.7\0"
	s ^TKSOLDES("83479")="\0.7\0"
	s ^TKSOLDES("82402")="\0.7\0"
	s ^TKSOLDES("83954")="\0.7\0"
	s ^TKSOLDES("82750")="\0.7\0"
	s ^TKSOLDES("83744")="\0.7\0"
	s ^TKSOLDES("83745")="\0.7\0"
	s ^TKSOLDES("83746")="\0.7\0"
	s ^TKSOLDES("83077")="\0.7\0"
	s ^TKSOLDES("83779")="\0.7\0"
	s ^TKSOLDES("83074")="\0.7\0"
	s ^TKSOLDES("83075")="\0.7\0"
	s ^TKSOLDES("82950")="\0.7\0"
	s ^TKSOLDES("82949")="\0.7\0"
	s ^TKSOLDES("82951")="\0.7\0"
	s ^TKSOLDES("83478")="\0.7\0"
	s ^TKSOLDES("81695")="\0.7\0"
	s ^TKSOLDES("83529")="\0.7\0"
	s ^TKSOLDES("83530")="\0.7\0"
	s ^TKSOLDES("83528")="\0.7\0"
	s ^TKSOLDES("83531")="\0.7\0"
	s ^TKSOLDES("82216")="\0.7\0"
	s ^TKSOLDES("83894")="\0.7\0"
	s ^TKSOLDES("83893")="\0.7\0"
	s ^TKSOLDES("84011")="\0.7\0"
	s ^TKSOLDES("81871")="\0.7\0"
	s ^TKSOLDES("83735")="\0.7\0"
	s ^TKSOLDES("83738")="\0.7\0"
	s ^TKSOLDES("83769")="\0.7\0"
	s ^TKSOLDES("83764")="\0.7\0"
	s ^TKSOLDES("83897")="\0.7\0"
	s ^TKSOLDES("83705")="\0.7\0"
	s ^TKSOLDES("83706")="\0.7\0"
	s ^TKSOLDES("83697")="\0.7\0"
	s ^TKSOLDES("83707")="\0.7\0"
	s ^TKSOLDES("83700")="\0.7\0"
	s ^TKSOLDES("83360")="\0.7\0"
	s ^TKSOLDES("82400")="\0.7\0"
	s ^TKSOLDES("83259")="\0.7\0"
	s ^TKSOLDES("82476")="\0.7\0"
	s ^TKSOLDES("82479")="\0.7\0"
	s ^TKSOLDES("81911")="\0.7\0"
	s ^TKSOLDES("83357")="\0.7\0"
	s ^TKSOLDES("83355")="\0.7\0"
	s ^TKSOLDES("82470")="\0.7\0"
	s ^TKSOLDES("82468")="\0.7\0"
	s ^TKSOLDES("83351")="\0.7\0"
	s ^TKSOLDES("83349")="\0.7\0"
	s ^TKSOLDES("82463")="\0.7\0"
	s ^TKSOLDES("82467")="\0.7\0"
	s ^TKSOLDES("83347")="\0.7\0"
	s ^TKSOLDES("82471")="\0.7\0"
	s ^TKSOLDES("83346")="\0.7\0"
	s ^TKSOLDES("82410")="\0.7\0"
	s ^TKSOLDES("82415")="\0.7\0"
	s ^TKSOLDES("82416")="\0.7\0"
	s ^TKSOLDES("82414")="\0.7\0"
	s ^TKSOLDES("83694")="\0.7\0"
	s ^TKSOLDES("84090")="\0.7\0"
	s ^TKSOLDES("83923")="\0.7\0"
	s ^TKSOLDES("83924")="\0.7\0"
	s ^TKSOLDES("83925")="\0.7\0"
	s ^TKSOLDES("83927")="\0.7\0"
	s ^TKSOLDES("82500")="\0.7\0"
	s ^TKSOLDES("82499")="\0.7\0"
	s ^TKSOLDES("82497")="\0.7\0"
	s ^TKSOLDES("82498")="\0.7\0"
	s ^TKSOLDES("81778")="\0.7\0"
	s ^TKSOLDES("80748")="\0.7\0"
	s ^TKSOLDES("83485")="\0.7\0"
	s ^TKSOLDES("83490")="\0.7\0"
	s ^TKSOLDES("83487")="\0.7\0"
	s ^TKSOLDES("83503")="\0.7\0"
	s ^TKSOLDES("83501")="\0.7\0"
	s ^TKSOLDES("83827")="\0.7\0"
	s ^TKSOLDES("83823")="\0.7\0"
	s ^TKSOLDES("83755")="\0.7\0"
	s ^TKSOLDES("83757")="\0.7\0"
	s ^TKSOLDES("82979")="\0.7\0"
	s ^TKSOLDES("82910")="\0.7\0"
	s ^TKSOLDES("83773")="\0.7\0"
	s ^TKSOLDES("83833")="\0.7\0"
	s ^TKSOLDES("82980")="\0.7\0"
	s ^TKSOLDES("79155")="\0.7\0"
	s ^TKSOLDES("83830")="\0.7\0"
	s ^TKSOLDES("83831")="\0.7\0"
	s ^TKSOLDES("83829")="\0.7\0"
	s ^TKSOLDES("83762")="\0.7\0"
	s ^TKSOLDES("82962")="\0.7\0"
	s ^TKSOLDES("83909")="\0.7\0"
	s ^TKSOLDES("83774")="\0.7\0"
	s ^TKSOLDES("83776")="\0.7\0"
	s ^TKSOLDES("83770")="\0.7\0"
	s ^TKSOLDES("83080")="\0.7\0"
	s ^TKSOLDES("83079")="\0.7\0"
	s ^TKSOLDES("73003")="\0.7\0"
	s ^TKSOLDES("73002")="\0.7\0"
	s ^TKSOLDES("73005")="\0.7\0"
	s ^TKSOLDES("74146")="\0.7\0"
	s ^TKSOLDES("76222")="\0.7\0"
	s ^TKSOLDES("76325")="\0.7\0"
	s ^TKSOLDES("78349")="\0.7\0"
	s ^TKSOLDES("77642")="\0.7\0"
	s ^TKSOLDES("77421")="\0.7\0"
	s ^TKSOLDES("77418")="\0.7\0"
	s ^TKSOLDES("77416")="\0.7\0"
	s ^TKSOLDES("77415")="\0.7\0"
	s ^TKSOLDES("77414")="\0.7\0"
	s ^TKSOLDES("77778")="\0.7\0"
	s ^TKSOLDES("77763")="\0.7\0"
	s ^TKSOLDES("78058")="\0.7\0"
	s ^TKSOLDES("77516")="\0.7\0"
	s ^TKSOLDES("77517")="\0.7\0"
	s ^TKSOLDES("77430")="\0.7\0"
	s ^TKSOLDES("75184")="\0.7\0"
	s ^TKSOLDES("75677")="\0.7\0"
	s ^TKSOLDES("75672")="\0.7\0"
	s ^TKSOLDES("75673")="\0.7\0"
	s ^TKSOLDES("75674")="\0.7\0"
	s ^TKSOLDES("75675")="\0.7\0"
	s ^TKSOLDES("76338")="\0.7\0"
	s ^TKSOLDES("73700")="\0.7\0"
	s ^TKSOLDES("73702")="\0.7\0"
	s ^TKSOLDES("73705")="\0.7\0"
	s ^TKSOLDES("76623")="\0.7\0"
	s ^TKSOLDES("77803")="\0.7\0"
	s ^TKSOLDES("76260")="\0.7\0"
	s ^TKSOLDES("77858")="\0.7\0"
	s ^TKSOLDES("77853")="\0.7\0"
	s ^TKSOLDES("77852")="\0.7\0"
	s ^TKSOLDES("77851")="\0.7\0"
	s ^TKSOLDES("77793")="\0.7\0"
	s ^TKSOLDES("77791")="\0.7\0"
	s ^TKSOLDES("77796")="\0.7\0"
	s ^TKSOLDES("77798")="\0.7\0"
	s ^TKSOLDES("74255")="\0.7\0"
	s ^TKSOLDES("77957")="\0.7\0"
	s ^TKSOLDES("76359")="\0.7\0"
	s ^TKSOLDES("76334")="\0.7\0"
	s ^TKSOLDES("76335")="\0.7\0"
	s ^TKSOLDES("77965")="\0.7\0"
	s ^TKSOLDES("77510")="\0.7\0"
	s ^TKSOLDES("77512")="\0.7\0"
	s ^TKSOLDES("78483")="\0.7\0"
	s ^TKSOLDES("78245")="\0.7\0"
	s ^TKSOLDES("78246")="\0.7\0"
	s ^TKSOLDES("78248")="\0.7\0"
	s ^TKSOLDES("78659")="\0.7\0"
	s ^TKSOLDES("78569")="\0.7\0"
	s ^TKSOLDES("78643")="\0.7\0"
	s ^TKSOLDES("78644")="\0.7\0"
	s ^TKSOLDES("78340")="\0.7\0"
	s ^TKSOLDES("78767")="\0.7\0"
	s ^TKSOLDES("93848")="\0.7\0"
	s ^TKSOLDES("68454")="\0.7\0"
	s ^TKSOLDES("72330")="\0.7\0"
	s ^TKSOLDES("71715")="\0.7\0"
	s ^TKSOLDES("93160")="\0.7\0"
	s ^TKSOLDES("93270")="\0.7\0"
	s ^TKSOLDES("93276")="\0.7\0"
	s ^TKSOLDES("66955")="\0.7\0"
	s ^TKSOLDES("71661")="\0.7\0"
	s ^TKSOLDES("66521")="\0.7\0"
	s ^TKSOLDES("93372")="\0.7\0"
	s ^TKSOLDES("93373")="\0.7\0"
	s ^TKSOLDES("93361")="\0.7\0"
	s ^TKSOLDES("91932")="\0.7\0"
	s ^TKSOLDES("93074")="\0.7\0"
	s ^TKSOLDES("91792")="\0.7\0"
	s ^TKSOLDES("91890")="\0.7\0"
	s ^TKSOLDES("91871")="\0.7\0"
	s ^TKSOLDES("91908")="\0.7\0"
	s ^TKSOLDES("93075")="\0.7\0"
	s ^TKSOLDES("91934")="\0.7\0"
	s ^TKSOLDES("91973")="\0.7\0"
	s ^TKSOLDES("93340")="\0.7\0"
	s ^TKSOLDES("91888")="\0.7\0"
	s ^TKSOLDES("93076")="\0.7\0"
	s ^TKSOLDES("50744")="\0.7\0"
	s ^TKSOLDES("91767")="\0.7\0"
	s ^TKSOLDES("91769")="\0.7\0"
	s ^TKSOLDES("91844")="\0.7\0"
	s ^TKSOLDES("8497")="\0.7\0"
	s ^TKSOLDES("8498")="\0.7\0"
	s ^TKSOLDES("8499")="\0.7\0"
	s ^TKSOLDES("8501")="\0.7\0"
	s ^TKSOLDES("8503")="\0.7\0"
	s ^TKSOLDES("8506")="\0.7\0"
	s ^TKSOLDES("105194")="\0.7\0"
	s ^TKSOLDES("105500")="\0.7\0"
	s ^TKSOLDES("105494")="\0.7\0"
	s ^TKSOLDES("105507")="\0.7\0"
	s ^TKSOLDES("105497")="\0.7\0"
	s ^TKSOLDES("105498")="\0.7\0"
	s ^TKSOLDES("111809")="\0.7\0"
	s ^TKSOLDES("105490")="\0.7\0"
	s ^TKSOLDES("105487")="\0.7\0"
	s ^TKSOLDES("105486")="\0.7\0"
	s ^TKSOLDES("105488")="\0.7\0"
	s ^TKSOLDES("105216")="\0.7\0"
	s ^TKSOLDES("105215")="\0.7\0"
	s ^TKSOLDES("107781")="\0.7\0"
	s ^TKSOLDES("110865")="\0.7\0"
	s ^TKSOLDES("105491")="\0.7\0"
	s ^TKSOLDES("105492")="\0.7\0"
	s ^TKSOLDES("105501")="\0.7\0"
	s ^TKSOLDES("105257")="\0.7\0"
	s ^TKSOLDES("106845")="\0.7\0"
	s ^TKSOLDES("105504")="\0.7\0"
	s ^TKSOLDES("105421")="\0.7\0"
	s ^TKSOLDES("105197")="\0.7\0"
	s ^TKSOLDES("105508")="\0.7\0"
	s ^TKSOLDES("105485")="\0.7\0"
	s ^TKSOLDES("105509")="\0.7\0"
	s ^TKSOLDES("109845")="\0.7\0"
	s ^TKSOLDES("106843")="\0.7\0"
	s ^TKSOLDES("106844")="\0.7\0"
	s ^TKSOLDES("105499")="\0.7\0"
	s ^TKSOLDES("105493")="\0.7\0"
	s ^TKSOLDES("105468")="\0.7\0"
	s ^TKSOLDES("105469")="\0.7\0"
	s ^TKSOLDES("105475")="\0.7\0"
	s ^TKSOLDES("111808")="\0.7\0"
	s ^TKSOLDES("105495")="\0.7\0"
	s ^TKSOLDES("105503")="\0.7\0"
	s ^TKSOLDES("105506")="\0.7\0"
	s ^TKSOLDES("105441")="\0.7\0"
	s ^TKSOLDES("105505")="\0.7\0"
	s ^TKSOLDES("100386")="\0.7\0"
	s ^TKSOLDES("105150")="\0.7\0"
	s ^TKSOLDES("105149")="\0.7\0"
	s ^TKSOLDES("100327")="\0.7\0"
	s ^TKSOLDES("105152")="\0.7\0"
	s ^TKSOLDES("100735")="\0.7\0"
	s ^TKSOLDES("103201")="\0.7\0"
	s ^TKSOLDES("105144")="\0.7\0"
	s ^TKSOLDES("105153")="\0.7\0"
	s ^TKSOLDES("103061")="\0.7\0"
	s ^TKSOLDES("103060")="\0.7\0"
	s ^TKSOLDES("103072")="\0.7\0"
	s ^TKSOLDES("105147")="\0.7\0"
	s ^TKSOLDES("105148")="\0.7\0"
	s ^TKSOLDES("102235")="\0.7\0"
	s ^TKSOLDES("102232")="\0.7\0"
	s ^TKSOLDES("102231")="\0.7\0"
	s ^TKSOLDES("100421")="\0.7\0"
	s ^TKSOLDES("100321")="\0.7\0"
	s ^TKSOLDES("100324")="\0.7\0"
	s ^TKSOLDES("104461")="\0.7\0"
	s ^TKSOLDES("104463")="\0.7\0"
	s ^TKSOLDES("104464")="\0.7\0"
	s ^TKSOLDES("104465")="\0.7\0"
	s ^TKSOLDES("104466")="\0.7\0"
	s ^TKSOLDES("102230")="\0.7\0"
	s ^TKSOLDES("102228")="\0.7\0"
	s ^TKSOLDES("102227")="\0.7\0"
	s ^TKSOLDES("101169")="\0.7\0"
	s ^TKSOLDES("101754")="\0.7\0"
	s ^TKSOLDES("101166")="\0.7\0"
	s ^TKSOLDES("103525")="\0.7\0"
	s ^TKSOLDES("103270")="\0.7\0"
	s ^TKSOLDES("105154")="\0.7\0"
	s ^TKSOLDES("105145")="\0.7\0"
	s ^TKSOLDES("104483")="\0.7\0"
	s ^TKSOLDES("100331")="\0.7\0"
	s ^TKSOLDES("103113")="\0.7\0"
	s ^TKSOLDES("87384")="\0.7\0"
	s ^TKSOLDES("85108")="\0.7\0"
	s ^TKSOLDES("85131")="\0.7\0"
	s ^TKSOLDES("87372")="\0.7\0"
	s ^TKSOLDES("87373")="\0.7\0"
	s ^TKSOLDES("87374")="\0.7\0"
	s ^TKSOLDES("85101")="\0.7\0"
	s ^TKSOLDES("81160")="\0.7\0"
	s ^TKSOLDES("81193")="\0.7\0"
	s ^TKSOLDES("81191")="\0.7\0"
	s ^TKSOLDES("81208")="\0.7\0"
	s ^TKSOLDES("81216")="\0.7\0"
	s ^TKSOLDES("81226")="\0.7\0"
	s ^TKSOLDES("82780")="\0.7\0"
	s ^TKSOLDES("83092")="\0.7\0"
	s ^TKSOLDES("79082")="\0.7\0"
	s ^TKSOLDES("79083")="\0.7\0"
	s ^TKSOLDES("81279")="\0.7\0"
	s ^TKSOLDES("74621")="\0.7\0"
	s ^TKSOLDES("74620")="\0.7\0"
	s ^TKSOLDES("74624")="\0.7\0"
	s ^TKSOLDES("74540")="\0.7\0"
	s ^TKSOLDES("74537")="\0.7\0"
	s ^TKSOLDES("66366")="\0.7\0"
	s ^TKSOLDES("67424")="\0.7\0"
	s ^TKSOLDES("66357")="\0.7\0"
	s ^TKSOLDES("110747")="\0.7\0"
	s ^TKSOLDES("110748")="\0.7\0"
	s ^TKSOLDES("110751")="\0.7\0"
	s ^TKSOLDES("107949")="\0.7\0"
	s ^TKSOLDES("110755")="\0.7\0"
	s ^TKSOLDES("110745")="\0.7\0"
	s ^TKSOLDES("110746")="\0.7\0"
	s ^TKSOLDES("110749")="\0.7\0"
	s ^TKSOLDES("110752")="\0.7\0"
	s ^TKSOLDES("103679")="\0.7\0"
	s ^TKSOLDES("103669")="\0.7\0"
	s ^TKSOLDES("103668")="\0.7\0"
	s ^TKSOLDES("84783")="\0.7\0"
	s ^TKSOLDES("84784")="\0.7\0"
	s ^TKSOLDES("84792")="\0.7\0"
	s ^TKSOLDES("84785")="\0.7\0"
	s ^TKSOLDES("84460")="\0.7\0"
	s ^TKSOLDES("84455")="\0.7\0"
	s ^TKSOLDES("84461")="\0.7\0"
	s ^TKSOLDES("84457")="\0.7\0"
	s ^TKSOLDES("84456")="\0.7\0"
	s ^TKSOLDES("84458")="\0.7\0"
	s ^TKSOLDES("84459")="\0.7\0"
	s ^TKSOLDES("88041")="\0.7\0"
	s ^TKSOLDES("88037")="\0.7\0"
	s ^TKSOLDES("88038")="\0.7\0"
	s ^TKSOLDES("88040")="\0.7\0"
	s ^TKSOLDES("88039")="\0.7\0"
	s ^TKSOLDES("84796")="\0.7\0"
	s ^TKSOLDES("84451")="\0.7\0"
	s ^TKSOLDES("84453")="\0.7\0"
	s ^TKSOLDES("84452")="\0.7\0"
	s ^TKSOLDES("84454")="\0.7\0"
	s ^TKSOLDES("84450")="\0.7\0"
	s ^TKSOLDES("84786")="\0.7\0"
	s ^TKSOLDES("82095")="\0.7\0"
	s ^TKSOLDES("79260")="\0.7\0"
	s ^TKSOLDES("82108")="\0.7\0"
	s ^TKSOLDES("82109")="\0.7\0"
	s ^TKSOLDES("79262")="\0.7\0"
	s ^TKSOLDES("82105")="\0.7\0"
	s ^TKSOLDES("79301")="\0.7\0"
	s ^TKSOLDES("79298")="\0.7\0"
	s ^TKSOLDES("79297")="\0.7\0"
	s ^TKSOLDES("79300")="\0.7\0"
	s ^TKSOLDES("79302")="\0.7\0"
	s ^TKSOLDES("79299")="\0.7\0"
	s ^TKSOLDES("82944")="\0.7\0"
	s ^TKSOLDES("83163")="\0.7\0"
	s ^TKSOLDES("83162")="\0.7\0"
	s ^TKSOLDES("82945")="\0.7\0"
	s ^TKSOLDES("82919")="\0.7\0"
	s ^TKSOLDES("82925")="\0.7\0"
	s ^TKSOLDES("82118")="\0.7\0"
	s ^TKSOLDES("79268")="\0.7\0"
	s ^TKSOLDES("82509")="\0.7\0"
	s ^TKSOLDES("82508")="\0.7\0"
	s ^TKSOLDES("79307")="\0.7\0"
	s ^TKSOLDES("79304")="\0.7\0"
	s ^TKSOLDES("79303")="\0.7\0"
	s ^TKSOLDES("79306")="\0.7\0"
	s ^TKSOLDES("79308")="\0.7\0"
	s ^TKSOLDES("79305")="\0.7\0"
	s ^TKSOLDES("79289")="\0.7\0"
	s ^TKSOLDES("79290")="\0.7\0"
	s ^TKSOLDES("79288")="\0.7\0"
	s ^TKSOLDES("79278")="\0.7\0"
	s ^TKSOLDES("82098")="\0.7\0"
	s ^TKSOLDES("79280")="\0.7\0"
	s ^TKSOLDES("79281")="\0.7\0"
	s ^TKSOLDES("82096")="\0.7\0"
	s ^TKSOLDES("79295")="\0.7\0"
	s ^TKSOLDES("79292")="\0.7\0"
	s ^TKSOLDES("79294")="\0.7\0"
	s ^TKSOLDES("79296")="\0.7\0"
	s ^TKSOLDES("79293")="\0.7\0"
	s ^TKSOLDES("82913")="\0.7\0"
	s ^TKSOLDES("80627")="\0.7\0"
	s ^TKSOLDES("82507")="\0.7\0"
	s ^TKSOLDES("82503")="\0.7\0"
	s ^TKSOLDES("82506")="\0.7\0"
	s ^TKSOLDES("82504")="\0.7\0"
	s ^TKSOLDES("82505")="\0.7\0"
	s ^TKSOLDES("82115")="\0.7\0"
	s ^TKSOLDES("82117")="\0.7\0"
	s ^TKSOLDES("77527")="\0.7\0"
	s ^TKSOLDES("77528")="\0.7\0"
	s ^TKSOLDES("77526")="\0.7\0"
	s ^TKSOLDES("73032")="\0.7\0"
	s ^TKSOLDES("77531")="\0.7\0"
	s ^TKSOLDES("63431")="\0.7\0"
	s ^TKSOLDES("64000")="\0.7\0"
	s ^TKSOLDES("58045")="\0.7\0"
	s ^TKSOLDES("47608")="\0.7\0"
	s ^TKSOLDES("107683")="\0.7\0"
	s ^TKSOLDES("105259")="\0.7\0"
	s ^TKSOLDES("105184")="\0.7\0"
	s ^TKSOLDES("105187")="\0.7\0"
	s ^TKSOLDES("106112")="\0.7\0"
	s ^TKSOLDES("106118")="\0.7\0"
	s ^TKSOLDES("106110")="\0.7\0"
	s ^TKSOLDES("106115")="\0.7\0"
	s ^TKSOLDES("106114")="\0.7\0"
	s ^TKSOLDES("106111")="\0.7\0"
	s ^TKSOLDES("106116")="\0.7\0"
	s ^TKSOLDES("106109")="\0.7\0"
	s ^TKSOLDES("106106")="\0.7\0"
	s ^TKSOLDES("101183")="\0.7\0"
	s ^TKSOLDES("101181")="\0.7\0"
	s ^TKSOLDES("101182")="\0.7\0"
	s ^TKSOLDES("101185")="\0.7\0"
	s ^TKSOLDES("101188")="\0.7\0"
	s ^TKSOLDES("102398")="\0.7\0"
	s ^TKSOLDES("102406")="\0.7\0"
	s ^TKSOLDES("102402")="\0.7\0"
	s ^TKSOLDES("102403")="\0.7\0"
	s ^TKSOLDES("102401")="\0.7\0"
	s ^TKSOLDES("101447")="\0.7\0"
	s ^TKSOLDES("103097")="\0.7\0"
	s ^TKSOLDES("103087")="\0.7\0"
	s ^TKSOLDES("101443")="\0.7\0"
	s ^TKSOLDES("102550")="\0.7\0"
	s ^TKSOLDES("103083")="\0.7\0"
	s ^TKSOLDES("100463")="\0.7\0"
	s ^TKSOLDES("100467")="\0.7\0"
	s ^TKSOLDES("100465")="\0.7\0"
	s ^TKSOLDES("103199")="\0.7\0"
	s ^TKSOLDES("103198")="\0.7\0"
	s ^TKSOLDES("105155")="\0.7\0"
	s ^TKSOLDES("101207")="\0.7\0"
	s ^TKSOLDES("101208")="\0.7\0"
	s ^TKSOLDES("85030")="\0.7\0"
	s ^TKSOLDES("86993")="\0.7\0"
	s ^TKSOLDES("86994")="\0.7\0"
	s ^TKSOLDES("86995")="\0.7\0"
	s ^TKSOLDES("85122")="\0.7\0"
	s ^TKSOLDES("86991")="\0.7\0"
	s ^TKSOLDES("86992")="\0.7\0"
	s ^TKSOLDES("87378")="\0.7\0"
	s ^TKSOLDES("81043")="\0.7\0"
	s ^TKSOLDES("83665")="\0.7\0"
	s ^TKSOLDES("83666")="\0.7\0"
	s ^TKSOLDES("81396")="\0.7\0"
	s ^TKSOLDES("83568")="\0.7\0"
	s ^TKSOLDES("75949")="\0.7\0"
	s ^TKSOLDES("78742")="\0.7\0"
	s ^TKSOLDES("44016")="\0.7\0"
	s ^TKSOLDES("44010")="\0.7\0"
	s ^TKSOLDES("44009")="\0.7\0"
	s ^TKSOLDES("8475")="\0.7\0"
	s ^TKSOLDES("107710")="\0.7\0"
	s ^TKSOLDES("107711")="\0.7\0"
	s ^TKSOLDES("105753")="\0.7\0"
	s ^TKSOLDES("110511")="\0.7\0"
	s ^TKSOLDES("107661")="\0.7\0"
	s ^TKSOLDES("107657")="\0.7\0"
	s ^TKSOLDES("107658")="\0.7\0"
	s ^TKSOLDES("107659")="\0.7\0"
	s ^TKSOLDES("107662")="\0.7\0"
	s ^TKSOLDES("100306")="\0.7\0"
	s ^TKSOLDES("100479")="\0.7\0"
	s ^TKSOLDES("100304")="\0.7\0"
	s ^TKSOLDES("100594")="\0.7\0"
	s ^TKSOLDES("100690")="\0.7\0"
	s ^TKSOLDES("100693")="\0.7\0"
	s ^TKSOLDES("100285")="\0.7\0"
	s ^TKSOLDES("100277")="\0.7\0"
	s ^TKSOLDES("84105")="\0.7\0"
	s ^TKSOLDES("84015")="\0.7\0"
	s ^TKSOLDES("83957")="\0.7\0"
	s ^TKSOLDES("84104")="\0.7\0"
	s ^TKSOLDES("83614")="\0.7\0"
	s ^TKSOLDES("83616")="\0.7\0"
	s ^TKSOLDES("83661")="\0.7\0"
	s ^TKSOLDES("83662")="\0.7\0"
	s ^TKSOLDES("83655")="\0.7\0"
	s ^TKSOLDES("83558")="\0.7\0"
	s ^TKSOLDES("83562")="\0.7\0"
	s ^TKSOLDES("77479")="\0.7\0"
	s ^TKSOLDES("64503")="\0.7\0"
	s ^TKSOLDES("58776")="\0.7\0"
	s ^TKSOLDES("58782")="\0.7\0"
	s ^TKSOLDES("64377")="\0.7\0"
	s ^TKSOLDES("64485")="\0.7\0"
	s ^TKSOLDES("64500")="\0.7\0"
	s ^TKSOLDES("54835")="\0.7\0"
	s ^TKSOLDES("54836")="\0.7\0"
	s ^TKSOLDES("54975")="\0.7\0"
	s ^TKSOLDES("54838")="\0.7\0"
	s ^TKSOLDES("54843")="\0.7\0"
	s ^TKSOLDES("37569")="\0.7\0"
	s ^TKSOLDES("44159")="\0.7\0"
	s ^TKSOLDES("44161")="\0.7\0"
	s ^TKSOLDES("44165")="\0.7\0"
	s ^TKSOLDES("37568")="\0.7\0"
	s ^TKSOLDES("41917")="\0.7\0"
	s ^TKSOLDES("37455")="\0.7\0"
	s ^TKSOLDES("8898")="\0.7\0"
	s ^TKSOLDES("7278")="\0.7\0"
	s ^TKSOLDES("2762")="\0.7\0"
	s ^TKSOLDES("2877")="\0.7\0"
	s ^TKSOLDES("2886")="\0.7\0"
	s ^TKSOLDES("3606")="\0.7\0"
	s ^TKSOLDES("2878")="\0.7\0"
	s ^TKSOLDES("110485")="\0.7\0"
	s ^TKSOLDES("76084")="\0.7\0"
	s ^TKSOLDES("76385")="\0.7\0"
	s ^TKSOLDES("76433")="\0.7\0"
	s ^TKSOLDES("76434")="\0.7\0"
	s ^TKSOLDES("77540")="\0.7\0"
	s ^TKSOLDES("70740")="\0.7\0"
	s ^TKSOLDES("70901")="\0.7\0"
	s ^TKSOLDES("65787")="\0.7\0"
	s ^TKSOLDES("70739")="\0.7\0"
	s ^TKSOLDES("92056")="\0.7\0"
	s ^TKSOLDES("63058")="\0.7\0"
	s ^TKSOLDES("6153")="\0.7\0"
	s ^TKSOLDES("7462")="\0.7\0"
	s ^TKSOLDES("8069")="\0.7\0"
	s ^TKSOLDES("2435")="\0.7\0"
	s ^TKSOLDES("4963")="\0.7\0"
	s ^TKSOLDES("100534")="\0.7\0"
	s ^TKSOLDES("100535")="\0.7\0"
	s ^TKSOLDES("100536")="\0.7\0"
	s ^TKSOLDES("100499")="\0.7\0"
	s ^TKSOLDES("100527")="\0.7\0"
	s ^TKSOLDES("100530")="\0.7\0"
	s ^TKSOLDES("100491")="\0.7\0"
	s ^TKSOLDES("100493")="\0.7\0"
	s ^TKSOLDES("100494")="\0.7\0"
	s ^TKSOLDES("86618")="\0.7\0"
	s ^TKSOLDES("88544")="\0.7\0"
	s ^TKSOLDES("88546")="\0.7\0"
	s ^TKSOLDES("88576")="\0.7\0"
	s ^TKSOLDES("83395")="\0.7\0"
	s ^TKSOLDES("82589")="\0.7\0"
	s ^TKSOLDES("83392")="\0.7\0"
	s ^TKSOLDES("80263")="\0.7\0"
	s ^TKSOLDES("82626")="\0.7\0"
	s ^TKSOLDES("77049")="\0.7\0"
	s ^TKSOLDES("77060")="\0.7\0"
	s ^TKSOLDES("77051")="\0.7\0"
	s ^TKSOLDES("77052")="\0.7\0"
	s ^TKSOLDES("77056")="\0.7\0"
	s ^TKSOLDES("77065")="\0.7\0"
	s ^TKSOLDES("77064")="\0.7\0"
	s ^TKSOLDES("77063")="\0.7\0"
	s ^TKSOLDES("77062")="\0.7\0"
	s ^TKSOLDES("77154")="\0.7\0"
	s ^TKSOLDES("77130")="\0.7\0"
	s ^TKSOLDES("77145")="\0.7\0"
	s ^TKSOLDES("77153")="\0.7\0"
	s ^TKSOLDES("77147")="\0.7\0"
	s ^TKSOLDES("77143")="\0.7\0"
	s ^TKSOLDES("77150")="\0.7\0"
	s ^TKSOLDES("77123")="\0.7\0"
	s ^TKSOLDES("77090")="\0.7\0"
	s ^TKSOLDES("77115")="\0.7\0"
	s ^TKSOLDES("77114")="\0.7\0"
	s ^TKSOLDES("77121")="\0.7\0"
	s ^TKSOLDES("77120")="\0.7\0"
	s ^TKSOLDES("77112")="\0.7\0"
	s ^TKSOLDES("77135")="\0.7\0"
	s ^TKSOLDES("73539")="\0.7\0"
	s ^TKSOLDES("72988")="\0.7\0"
	s ^TKSOLDES("73559")="\0.7\0"
	s ^TKSOLDES("73077")="\0.7\0"
	s ^TKSOLDES("72878")="\0.7\0"
	s ^TKSOLDES("77057")="\0.7\0"
	s ^TKSOLDES("77058")="\0.7\0"
	s ^TKSOLDES("77059")="\0.7\0"
	s ^TKSOLDES("77044")="\0.7\0"
	s ^TKSOLDES("77045")="\0.7\0"
	s ^TKSOLDES("77046")="\0.7\0"
	s ^TKSOLDES("73583")="\0.7\0"
	s ^TKSOLDES("75058")="\0.7\0"
	s ^TKSOLDES("74980")="\0.7\0"
	s ^TKSOLDES("74998")="\0.7\0"
	s ^TKSOLDES("75022")="\0.7\0"
	s ^TKSOLDES("74982")="\0.7\0"
	s ^TKSOLDES("75024")="\0.7\0"
	s ^TKSOLDES("77139")="\0.7\0"
	s ^TKSOLDES("65957")="\0.7\0"
	s ^TKSOLDES("65959")="\0.7\0"
	s ^TKSOLDES("65960")="\0.7\0"
	s ^TKSOLDES("65980")="\0.7\0"
	s ^TKSOLDES("67133")="\0.7\0"
	s ^TKSOLDES("65697")="\0.7\0"
	s ^TKSOLDES("65692")="\0.7\0"
	s ^TKSOLDES("65694")="\0.7\0"
	s ^TKSOLDES("65690")="\0.7\0"
	s ^TKSOLDES("65693")="\0.7\0"
 
 
	Q
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 